# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classification", "0001_initial"),
        ("odoo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodelassignment",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classifier_assignments",
                to="odoo.odooproduct",
            ),
        ),
        migrations.AddField(
            model_name="trainingrun",
            name="classifier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training_runs",
                to="classification.imageclassifiermodel",
            ),
        ),
    ]
