# Generated by Django 5.2.11 on 2026-03-07 19:31

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classification", "0001_initial"),
        ("media", "0001_initial"),
        ("odoo", "0008_odooemployee_avatar_null"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentclassification",
            options={"ordering": ["-queued_at"]},
        ),
        migrations.AddField(
            model_name="contentclassification",
            name="queued_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="contentclassification",
            name="classified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contentclassification",
            name="confidence",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="productmodelassignment",
            name="min_confidence",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.5000"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="classificationtag",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("auto_dispatch", False),
                    ("dispatch_route__gt", ""),
                    _connector="OR",
                ),
                name="classification_dispatch_route_required_when_auto_dispatch",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentclassification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("confidence__gte", Decimal("0")), ("confidence__lte", Decimal("1"))
                ),
                name="classification_content_confidence_between_zero_and_one",
            ),
        ),
        migrations.AddConstraint(
            model_name="imageclassifiermodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False), ("is_selected", True)),
                fields=("model_type",),
                name="classification_unique_selected_model_per_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="imageclassifiermodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_selected", False),
                    ("status", "ready"),
                    ("is_deleted", True),
                    _connector="OR",
                ),
                name="classification_selected_model_must_be_ready",
            ),
        ),
        migrations.AddConstraint(
            model_name="productmodelassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True), ("is_deleted", False)),
                fields=("product",),
                name="classification_unique_default_classifier_per_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="productmodelassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("min_confidence__gte", Decimal("0")),
                    ("min_confidence__lte", Decimal("1")),
                ),
                name="classification_product_assignment_min_confidence_between_zero_and_one",
            ),
        ),
    ]
