# Generated by Django 5.2.8 on 2026-03-07

from django.db import migrations

from apps.extensions.defaults import github_resolve_comments_extension_defaults


def seed_github_resolve_comments_extension(apps, schema_editor):
    """Seed the GitHub bulk resolve-comments helper extension."""
    JsExtension = apps.get_model("extensions", "JsExtension")

    defaults = github_resolve_comments_extension_defaults()
    slug = str(defaults.pop("slug"))

    JsExtension.objects.get_or_create(slug=slug, defaults=defaults)


def remove_github_resolve_comments_extension(apps, schema_editor):
    """Remove seeded GitHub helper extension only when it matches seeded defaults."""
    JsExtension = apps.get_model("extensions", "JsExtension")

    defaults = github_resolve_comments_extension_defaults()
    slug = str(defaults.pop("slug"))

    extension = JsExtension.objects.filter(slug=slug).first()
    if extension is None:
        return

    seeded_keys = (
        "name",
        "description",
        "version",
        "manifest_version",
        "matches",
        "permissions",
        "host_permissions",
        "content_script",
        "options_page",
    )
    if all(getattr(extension, key) == defaults[key] for key in seeded_keys):
        extension.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("extensions", "0002_js_extension_manifest_version_constraint"),
    ]

    operations = [
        migrations.RunPython(
            seed_github_resolve_comments_extension,
            remove_github_resolve_comments_extension,
        ),
    ]
