# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nodes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("label", models.CharField(max_length=120)),
                ("url", models.URLField()),
                ("priority", models.PositiveIntegerField(default=100)),
            ],
            options={
                "verbose_name": "Operation Link",
                "verbose_name_plural": "Operation Links",
                "ordering": ("priority", "id"),
            },
        ),
        migrations.CreateModel(
            name="OperationScreen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "start_url",
                    models.CharField(
                        help_text="Internal admin or public URL where this operation starts.",
                        max_length=500,
                    ),
                ),
                (
                    "validation_sql",
                    models.TextField(
                        blank=True,
                        help_text="Optional SQL query returning a truthy scalar when validation passes.",
                    ),
                ),
                ("priority", models.PositiveIntegerField(default=100)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("per_user", "Once per user"),
                            ("per_node", "Once per node"),
                        ],
                        default="per_user",
                        max_length=20,
                    ),
                ),
                (
                    "recurrence_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of days after completion when this operation becomes pending again.",
                        null=True,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Operation Screen",
                "verbose_name_plural": "Operation Screens",
                "ordering": ("priority", "title"),
            },
        ),
        migrations.CreateModel(
            name="SecurityAlertEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("key", models.CharField(max_length=255, unique=True)),
                ("severity", models.CharField(default="error", max_length=20)),
                ("message", models.CharField(max_length=255)),
                ("detail", models.TextField(blank=True)),
                ("occurrence_count", models.PositiveIntegerField(default=1)),
                (
                    "last_occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "remediation_url",
                    models.CharField(default="/admin/", max_length=500),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Security Alert Event",
                "verbose_name_plural": "Security Alert Events",
                "ordering": ("-last_occurred_at", "-updated_at"),
            },
        ),
        migrations.CreateModel(
            name="OperationExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "performed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
                ("validation_passed", models.BooleanField(blank=True, null=True)),
                ("validation_output", models.TextField(blank=True)),
                ("expiration_notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_executions",
                        to="nodes.node",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operation Execution",
                "verbose_name_plural": "Operation Executions",
                "ordering": ("-performed_at",),
            },
        ),
    ]
