# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="operationexecution",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operation_executions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="operationscreen",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_operations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="operationlink",
            name="operation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="ops.operationscreen",
            ),
        ),
        migrations.AddField(
            model_name="operationexecution",
            name="operation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="ops.operationscreen",
            ),
        ),
        migrations.AddIndex(
            model_name="securityalertevent",
            index=models.Index(
                fields=["is_active", "-last_occurred_at"],
                name="ops_secalert_active_last",
            ),
        ),
        migrations.AddIndex(
            model_name="operationexecution",
            index=models.Index(
                fields=["operation", "user", "-performed_at"],
                name="ops_exec_op_user_date",
            ),
        ),
    ]
