# Generated by Django 5.2.6 on 2026-02-23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationexecution",
            name="completed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
