# Generated by Django 5.2.12 on 2026-04-02 17:55

import apps.ops.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationscreen",
            name="start_url",
            field=models.CharField(
                help_text="Local absolute path where this operation starts, without scheme or host.",
                max_length=500,
                validators=[apps.ops.models.validate_local_absolute_path_url],
            ),
        ),
    ]
