# Generated by Django 5.2.11 on 2026-02-23 03:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0027_update_ap_router_roles"),
        ("ops", "0002_dashboard_rule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="operationexecution",
            index=models.Index(
                fields=["operation", "user", "-performed_at"],
                name="ops_exec_op_user_date",
            ),
        ),
    ]
