# Generated by Django 5.2.12 on 2026-03-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0004_securityalertevent"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="securityalertevent",
            index=models.Index(
                fields=["is_active", "-last_occurred_at"],
                name="ops_secalert_active_last",
            ),
        ),
    ]
