# Generated by Django 5.2.11 on 2026-03-10 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0005_alter_securityalertevent_key"),
        ("ops", "0005_securityalertevent_ops_secalert_active_last"),
    ]

    operations = []
