# Generated by Django 5.2.11 on 2026-03-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0006_merge_20260310_1406"),
        ("ops", "0006_merge_20260310_1506"),
    ]

    operations = []
