# Generated by Django 5.2.12 on 2026-03-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0007_merge_20260310_2213"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="securityalertevent",
            name="ops_secalert_active_last",
        ),
    ]
