# Generated by Django 5.2.11 on 2026-03-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0007_merge_20260311_0000"),
        ("ops", "0007_merge_20260311_0648"),
    ]

    operations = []
