# Generated by Django 5.2.12 on 2026-03-15 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0008_merge_20260311_1100"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="securityalertevent",
            name="ops_secalert_active_last",
        ),
    ]
