# Generated by Django 5.2.4 on 2025-08-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("from_address", models.CharField(blank=True, max_length=200)),
                ("to_address", models.CharField(blank=True, max_length=200)),
                ("cc", models.CharField(blank=True, max_length=200)),
                ("bcc", models.CharField(blank=True, max_length=200)),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField(blank=True)),
            ],
        ),
    ]
