# Generated by Django 5.2.4 on 2025-08-10 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailpattern",
            options={
                "verbose_name": "Email Pattern",
                "verbose_name_plural": "Email Patterns",
            },
        ),
    ]
