# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Thermometer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("unit", models.CharField(blank=True, max_length=16)),
                (
                    "report_regex",
                    models.CharField(
                        blank=True,
                        help_text="Regex used to parse sensor readings from reports. Use a named group 'value' or the first capture group.",
                        max_length=255,
                    ),
                ),
                (
                    "report_scale",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1"),
                        help_text="Multiplier applied to parsed readings.",
                        max_digits=10,
                    ),
                ),
                (
                    "display_precision",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Number of decimal places to display for readings.",
                    ),
                ),
                (
                    "sampling_interval_seconds",
                    models.PositiveIntegerField(
                        default=300,
                        help_text="Sampling interval in seconds.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "last_reading",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Thermometer",
                "verbose_name_plural": "Thermometers",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UsbTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "required_file_path",
                    models.CharField(
                        help_text="Relative path that must exist on the USB device.",
                        max_length=255,
                    ),
                ),
                (
                    "required_file_regex",
                    models.TextField(
                        blank=True,
                        help_text="Optional regex used to validate file contents before marking a match.",
                    ),
                ),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_matched_at", models.DateTimeField(blank=True, null=True)),
                ("last_match_path", models.CharField(blank=True, max_length=512)),
                ("last_error", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "USB Tracker",
                "verbose_name_plural": "USB Trackers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ThermometerReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reading", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "read_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "thermometer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="sensors.thermometer",
                    ),
                ),
            ],
            options={
                "ordering": ["-read_at"],
                "indexes": [
                    models.Index(
                        fields=["thermometer", "read_at"],
                        name="sensors_the_thermom_615c9d_idx",
                    )
                ],
            },
        ),
    ]
