# Generated by Django 5.2.15 on 2026-07-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thermometer',
            name='alarm_audio_enabled',
        ),
        migrations.RemoveField(
            model_name='thermometeralarmevent',
            name='audio_status',
        ),
        migrations.AlterField(
            model_name='usbportmapping',
            name='source_identifier',
            field=models.CharField(help_text='USB tracker slug used to decide whether the port is connected.', max_length=255),
        ),
        migrations.AlterField(
            model_name='usbportmapping',
            name='source_type',
            field=models.CharField(choices=[('usb-tracker', 'USB tracker')], help_text='Local device inventory used to decide whether the port is connected.', max_length=32),
        ),
    ]
