# Generated by Django 5.2 on 2026-09-01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("sensors", "0002_remove_thermometer_alarm_audio_enabled_and_more")]

    operations = [
        migrations.RemoveField(model_name="thermometer", name="alarm_lcd_enabled"),
        migrations.RemoveField(model_name="thermometeralarmevent", name="lcd_notified"),
        migrations.DeleteModel(name="UsbPortMapping"),
    ]
