# Generated by Django 5.2.12 on 2026-04-10 00:31

import apps.souls.models.soul
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cards", "0004_offeringsoul"),
        ("shop", "0001_initial"),
        ("survey", "0002_alter_surveyresponse_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Soul",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("soul_id", models.CharField(max_length=64, unique=True)),
                ("survey_digest", models.CharField(max_length=64)),
                ("package_version", models.CharField(default="1.0", max_length=16)),
                ("sig_alg", models.CharField(default="none", max_length=32)),
                ("kid", models.CharField(blank=True, default="", max_length=64)),
                ("signature", models.TextField(blank=True, default="")),
                ("package", models.JSONField(blank=True, default=dict)),
                ("package_bytes", models.BinaryField(blank=True, null=True)),
                ("email_hash", models.CharField(blank=True, default="", max_length=64)),
                (
                    "email_verified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "offering_soul",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="souls",
                        to="cards.offeringsoul",
                    ),
                ),
                (
                    "survey_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="souls",
                        to="survey.surveyresponse",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soul",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="ShopOrderSoulAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("written", "Written"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "order_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soul_attachment",
                        to="shop.shoporderitem",
                    ),
                ),
                (
                    "soul",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_attachments",
                        to="souls.soul",
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="SoulRegistrationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("email", models.EmailField(max_length=254)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("offering_done", "Offering Completed"),
                            ("survey_done", "Survey Completed"),
                            ("email_sent", "Email Sent"),
                            ("verified", "Verified"),
                            ("completed", "Completed"),
                        ],
                        default="started",
                        max_length=32,
                    ),
                ),
                (
                    "verification_token_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("verification_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=apps.souls.models.soul.default_session_expiry
                    ),
                ),
                ("ip_hash", models.CharField(blank=True, default="", max_length=64)),
                ("ua_hash", models.CharField(blank=True, default="", max_length=64)),
                (
                    "offering_soul",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registration_sessions",
                        to="cards.offeringsoul",
                    ),
                ),
                (
                    "survey_response",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registration_sessions",
                        to="survey.surveyresponse",
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
            },
        ),
    ]
