# Generated by Django 5.2.12 on 2026-05-01 21:55

import apps.souls.models.seed
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_offeringsoul_options'),
        ('skills', '0003_agentskillfile'),
        ('souls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seed_data', models.BooleanField(default=False, editable=False)),
                ('is_user_data', models.BooleanField(default=False, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('match_strategy', models.CharField(choices=[('exact', 'Exact'), ('composed', 'Composed'), ('manual', 'Manual')], default='composed', max_length=16)),
                ('match_score', models.FloatField(default=0.0)),
                ('summary', models.TextField(blank=True, default='')),
                ('tool_allowlist', models.JSONField(blank=True, default=list)),
                ('compatibility_notes', models.JSONField(blank=True, default=list)),
                ('fallback_guidance', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_soul_seed_bundles', to='skills.agentskill')),
                ('skills', models.ManyToManyField(blank=True, related_name='soul_seed_bundles', to='skills.agentskill')),
            ],
            options={
                'verbose_name': 'Skill Bundle',
                'verbose_name_plural': 'Skill Bundles',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='AgentInterfaceSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seed_data', models.BooleanField(default=False, editable=False)),
                ('is_user_data', models.BooleanField(default=False, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('mode', models.CharField(choices=[('auto', 'Auto'), ('cli', 'CLI'), ('web', 'Web')], default='auto', max_length=16)),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('commands', models.JSONField(blank=True, default=list)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('visible_fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_specs', to='souls.skillbundle')),
            ],
            options={
                'verbose_name': 'Agent Interface Spec',
                'verbose_name_plural': 'Agent Interface Specs',
                'ordering': ('bundle__slug', 'mode', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SoulIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seed_data', models.BooleanField(default=False, editable=False)),
                ('is_user_data', models.BooleanField(default=False, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('problem_statement', models.TextField()),
                ('normalized_intent', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('role', models.CharField(blank=True, default='', max_length=64)),
                ('constraints', models.JSONField(blank=True, default=dict)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('desired_interface', models.CharField(choices=[('auto', 'Auto'), ('cli', 'CLI'), ('web', 'Web')], default='auto', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soul_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Soul Intent',
                'verbose_name_plural': 'Soul Intents',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='skillbundle',
            name='intent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_bundles', to='souls.soulintent'),
        ),
        migrations.CreateModel(
            name='SoulSeedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seed_data', models.BooleanField(default=False, editable=False)),
                ('is_user_data', models.BooleanField(default=False, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('card_uid', models.CharField(db_index=True, max_length=255)),
                ('manifest_fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('preview_only', 'Preview only'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('card_payload', models.JSONField(blank=True, default=dict)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soul_seed_cards', to='souls.soulintent')),
                ('interface_spec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soul_seed_cards', to='souls.agentinterfacespec')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soul_seed_cards', to=settings.AUTH_USER_MODEL)),
                ('rfid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soul_seed_cards', to='cards.rfid')),
                ('skill_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soul_seed_cards', to='souls.skillbundle')),
            ],
            options={
                'verbose_name': 'Soul Seed Card',
                'verbose_name_plural': 'Soul Seed Cards',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CardSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seed_data', models.BooleanField(default=False, editable=False)),
                ('is_user_data', models.BooleanField(default=False, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('session_id', models.CharField(default=apps.souls.models.seed.default_card_session_id, max_length=64, unique=True)),
                ('reader_id', models.CharField(blank=True, default='', max_length=128)),
                ('node_id', models.CharField(blank=True, default='', max_length=128)),
                ('trust_tier', models.CharField(choices=[('unknown', 'Unknown'), ('local_authenticated', 'Local authenticated'), ('trusted_operator_console', 'Trusted operator console'), ('trusted_gway', 'Trusted GWAY'), ('provisioner', 'Provisioner')], default='unknown', max_length=32)),
                ('state', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('closed', 'Closed'), ('evicted', 'Evicted'), ('rejected', 'Rejected')], default='planned', max_length=16)),
                ('activation_plan', models.JSONField(blank=True, default=dict)),
                ('runtime_namespace', models.CharField(blank=True, default='', max_length=128)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('eviction_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rfid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soul_seed_sessions', to='cards.rfid')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='souls.soulseedcard')),
            ],
            options={
                'verbose_name': 'Card Session',
                'verbose_name_plural': 'Card Sessions',
                'ordering': ('-id',),
            },
        ),
    ]
