# Generated by Django 5.2.4 on 2025-09-14 04:45

import core.entity
import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("awg", "0002_user_data_field"),
        ("core", "0014_delete_businesspowerlead"),
        ("nodes", "0003_user_data_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatProfile",
            fields=[],
            options={
                "verbose_name": "Chat Profile",
                "verbose_name_plural": "Chat Profiles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.chatprofile",),
        ),
        migrations.CreateModel(
            name="EmailCollector",
            fields=[],
            options={
                "verbose_name": "Email Collector",
                "verbose_name_plural": "Email Collectors",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.emailcollector",),
        ),
        migrations.CreateModel(
            name="EmailInbox",
            fields=[],
            options={
                "verbose_name": "Email Inbox",
                "verbose_name_plural": "Email Inboxes",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.emailinbox",),
        ),
        migrations.CreateModel(
            name="EmailOutbox",
            fields=[],
            options={
                "verbose_name": "Email Outbox",
                "verbose_name_plural": "Email Outboxes",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("nodes.emailoutbox",),
        ),
        migrations.CreateModel(
            name="InviteLead",
            fields=[],
            options={
                "verbose_name": "Invite Lead",
                "verbose_name_plural": "Invite Leads",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.invitelead",),
        ),
        migrations.CreateModel(
            name="OdooProfile",
            fields=[],
            options={
                "verbose_name": "Odoo Profile",
                "verbose_name_plural": "Odoo Profiles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.odooprofile",),
        ),
        migrations.CreateModel(
            name="PowerLead",
            fields=[],
            options={
                "verbose_name": "Power Lead",
                "verbose_name_plural": "Power Leads",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("awg.powerlead",),
        ),
        migrations.CreateModel(
            name="ReleaseManager",
            fields=[],
            options={
                "verbose_name": "Release Manager",
                "verbose_name_plural": "Release Managers",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.releasemanager",),
        ),
        migrations.CreateModel(
            name="SecurityGroup",
            fields=[],
            options={
                "verbose_name": "Security Group",
                "verbose_name_plural": "Security Groups",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.securitygroup",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.user",),
            managers=[
                ("objects", core.entity.EntityUserManager()),
                ("all_objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
