# Generated by Django 5.2.4 on 2025-09-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_aplead"),
        ("teams", "0002_alter_odooprofile_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="APLead",
            fields=[],
            options={
                "verbose_name": "AP Lead",
                "verbose_name_plural": "AP Leads",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.aplead",),
        ),
    ]
