# Generated by Django 5.2.4 on 2025-09-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0005_assistantprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="APLead",
        ),
    ]
