# Generated by Django 5.2.7 on 2025-11-06 02:35

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0086_remove_user_birthday"),
        ("nodes", "0028_terminal_clipboard_poll_default"),
        ("teams", "0012_manualtask"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackBotProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "team_id",
                    models.CharField(
                        help_text="Slack workspace team identifier (starts with T).",
                        max_length=32,
                    ),
                ),
                (
                    "bot_user_id",
                    models.CharField(
                        blank=True,
                        help_text="Slack bot user identifier (starts with U or B).",
                        max_length=32,
                    ),
                ),
                (
                    "bot_token",
                    core.fields.SigilShortAutoField(
                        help_text="Slack bot token used for authenticated API calls.",
                        max_length=255,
                    ),
                ),
                (
                    "signing_secret",
                    core.fields.SigilShortAutoField(
                        help_text="Slack signing secret used to verify incoming requests.",
                        max_length=255,
                    ),
                ),
                (
                    "default_channels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Channel identifiers where Net Messages should be posted. Provide a JSON array of channel IDs (for example ["C01ABCDE"]).',
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Disable to stop the bot from posting to Slack.",
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.securitygroup",
                    ),
                ),
                (
                    "node",
                    models.OneToOneField(
                        blank=True,
                        help_text="Node that owns this Slack chatbot.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slack_bot",
                        to="nodes.node",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Slack Chatbot",
                "verbose_name_plural": "Slack Chatbots",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("team_id",), name="slackbotprofile_team_id_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("user__isnull", False), ("group__isnull", True)),
                            models.Q(("user__isnull", True), ("group__isnull", False)),
                            models.Q(
                                ("user__isnull", True),
                                ("group__isnull", True),
                                ("node__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="slackbotprofile_requires_owner",
                    ),
                ],
            },
        ),
    ]
