# Generated by Django 5.2.7 on 2025-11-06 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0088_openpayprofile_default_processor_and_more"),
        ("teams", "0013_slackbotprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="manualtask",
            name="assigned_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional security group responsible for the task.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_manual_tasks",
                to="core.securitygroup",
                verbose_name="Assigned group",
            ),
        ),
        migrations.AddField(
            model_name="manualtask",
            name="assigned_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional user responsible for the task.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_manual_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned user",
            ),
        ),
        migrations.AddField(
            model_name="manualtask",
            name="enable_notifications",
            field=models.BooleanField(
                default=False,
                help_text="Send reminder emails to the assigned contacts when Celery notifications are available.",
                verbose_name="Enable notifications",
            ),
        ),
    ]
