# Generated by Django 5.2.7 on 2025-11-06 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0013_slackbotprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="totpdevice",
            options={
                "verbose_name": "TOTP Device",
                "verbose_name_plural": "TOTP Devices",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
