# Generated by Django 5.2.4 on 2025-11-07 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_alter_totpdevice_options_alter_user_options'),
        ('teams', '0014_manualtask_assigned_group_manualtask_assigned_user_and_more'),
    ]

    operations = [
    ]
