# Generated by Django 5.2.8 on 2025-11-11 22:13

from decimal import Decimal
import core.entity
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0096_move_email_profiles"),
        ("teams", "0016_move_email_profiles"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional details supporting Markdown formatting.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="workgroup/task_categories/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated fulfillment cost in local currency.",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Cost",
                    ),
                ),
                (
                    "odoo_product",
                    models.JSONField(
                        blank=True,
                        help_text="Selected product from Odoo (id and name).",
                        null=True,
                        verbose_name="Odoo product",
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("immediate", "Immediate"),
                            ("2_3_business_days", "2-3 business days"),
                            ("2_3_weeks", "2-3 weeks"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="none",
                        help_text="Typical lead time for scheduling this work.",
                        max_length=32,
                        verbose_name="Availability",
                    ),
                ),
                (
                    "assigned_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Security group typically assigned to this work.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_categories_as_assignee",
                        to="core.securitygroup",
                        verbose_name="Assigned to group",
                    ),
                ),
                (
                    "requestor_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Security group authorized to request this work.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_categories_as_requestor",
                        to="core.securitygroup",
                        verbose_name="Requestor group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Category",
                "verbose_name_plural": "Task Categories",
                "db_table": "core_taskcategory",
                "ordering": ("name",),
            },
            bases=(core.entity.Entity,),
        ),
        migrations.AddField(
            model_name="manualtask",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional workgroup category for this task.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manual_tasks",
                to="teams.taskcategory",
                verbose_name="Category",
            ),
        ),
    ]
