# Generated by Django 5.2.7 on 2025-03-01 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0017_taskcategory_manualtask_category"),
        ("core", "0098_location_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manualtask",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Location associated with this manual task.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manual_tasks",
                to="core.location",
                verbose_name="Location",
            ),
        ),
    ]
