# Generated by Django 5.2.8 on 2025-11-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0018_manualtask_location_to_core"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailinbox",
            options={
                "ordering": ["-priority", "id"],
                "verbose_name": "Email Inbox",
                "verbose_name_plural": "Email Inboxes",
            },
        ),
        migrations.AlterModelOptions(
            name="emailoutbox",
            options={
                "ordering": ["-priority", "id"],
                "verbose_name": "Email Outbox",
                "verbose_name_plural": "Email Outboxes",
            },
        ),
        migrations.AddField(
            model_name="emailinbox",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="Higher values are selected first when multiple inboxes are available.",
            ),
        ),
        migrations.AddField(
            model_name="emailoutbox",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="Higher values are selected first when multiple outboxes are available.",
            ),
        ),
    ]
