# Generated by Django 5.2.8 on 2025-11-25 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0116_admincommandresult"),
        ("teams", "0019_alter_emailinbox_options_alter_emailoutbox_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manualtask",
            options={
                "ordering": ("scheduled_start", "category__name"),
                "verbose_name": "Manual Task",
                "verbose_name_plural": "Manual Tasks",
            },
        ),
        migrations.RemoveField(
            model_name="manualtask",
            name="title",
        ),
        migrations.RemoveField(
            model_name="taskcategory",
            name="odoo_product",
        ),
        migrations.AddField(
            model_name="manualtask",
            name="duration",
            field=models.DurationField(
                blank=True,
                help_text="Estimated time to complete the task.",
                null=True,
                verbose_name="Expected duration",
            ),
        ),
        migrations.AddField(
            model_name="manualtask",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="User overseeing the task.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_manual_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Manager",
            ),
        ),
        migrations.AddField(
            model_name="manualtask",
            name="odoo_products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Products associated with the requested work.",
                related_name="manual_tasks",
                to="core.product",
                verbose_name="Odoo products",
            ),
        ),
        migrations.AddField(
            model_name="taskcategory",
            name="default_duration",
            field=models.DurationField(
                blank=True,
                help_text="Typical time expected to complete tasks in this category.",
                null=True,
                verbose_name="Default duration",
            ),
        ),
        migrations.AddField(
            model_name="taskcategory",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="User responsible for overseeing this category.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_task_categories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Manager",
            ),
        ),
        migrations.AddField(
            model_name="taskcategory",
            name="odoo_products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Relevant Odoo products for this category.",
                related_name="task_categories",
                to="core.product",
                verbose_name="Odoo products",
            ),
        ),
        migrations.AlterField(
            model_name="manualtask",
            name="assigned_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Security group containing users who can fulfill the task.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_manual_tasks",
                to="core.securitygroup",
                verbose_name="Potential assignees",
            ),
        ),
        migrations.AlterField(
            model_name="manualtask",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the standardized category for this work.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manual_tasks",
                to="teams.taskcategory",
                verbose_name="Category",
            ),
        ),
    ]
