# Generated by Django 5.2.8 on 2025-11-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0020_alter_manualtask_options_remove_manualtask_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailinbox",
            name="is_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Disable to remove this inbox from automatic selection.",
            ),
        ),
    ]
