# Generated by Django 5.2.8 on 2025-11-28 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0023_alter_manualtask_description_verbose_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
