# Generated by Django 5.2.8 on 2025-11-29 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0024_delete_user"),
        ("teams", "0024_seed_charge_point_maintenance_category"),
    ]

    operations = []
