# Generated by Django 5.2.8 on 2025-11-29 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0026_alter_manualtask_location"),
        ("teams", "0026_socialprofile"),
    ]

    operations = []
