# Generated by Django 5.2.4 on 2025-09-10 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_manuals", "0002_rpi_control_manual"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usermanual",
            options={
                "verbose_name": "User Manual",
                "verbose_name_plural": "User Manuals",
            },
        ),
    ]
