# Generated by Django 5.2.9 on 2026-01-04 20:35

import apps.mcp.models
import apps.sigils.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MCPServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Human friendly label for this MCP server.",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default=apps.mcp.models._generate_slug,
                        help_text="Unique path component used to address this MCP server.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Controls whether the MCP server is reachable.",
                    ),
                ),
                (
                    "api_secret",
                    apps.sigils.fields.SigilShortAutoField(
                        default=apps.mcp.models._generate_secret,
                        help_text="Secret required by agents to retrieve MCP configuration and invoke endpoints.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acting_user",
                    models.ForeignKey(
                        help_text="User account the MCP service should act as when invoked.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mcp_servers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MCP server",
                "verbose_name_plural": "MCP servers",
                "ordering": ("name",),
            },
        ),
    ]
