# Generated by Django 5.2.12 on 2026-03-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chats", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppWebhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "route_key",
                    models.SlugField(
                        default="",
                        help_text="Unique key used in the webhook URL path for routing.",
                        max_length=48,
                        unique=True,
                    ),
                ),
                (
                    "verify_token",
                    models.CharField(
                        default="",
                        help_text="Verification token copied into the Meta webhook setup page.",
                        max_length=96,
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Webhook",
                "verbose_name_plural": "WhatsApp Webhooks",
                "ordering": ["bridge__site__domain", "pk"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppWebhookMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("message_id", models.CharField(db_index=True, max_length=96)),
                ("messaging_product", models.CharField(blank=True, max_length=32)),
                ("from_phone", models.CharField(blank=True, max_length=32)),
                ("wa_id", models.CharField(blank=True, max_length=32)),
                ("profile_name", models.CharField(blank=True, max_length=255)),
                ("timestamp", models.BigIntegerField(blank=True, null=True)),
                ("message_type", models.CharField(blank=True, max_length=32)),
                ("text_body", models.TextField(blank=True)),
                ("context_message_id", models.CharField(blank=True, max_length=96)),
                (
                    "metadata_phone_number_id",
                    models.CharField(blank=True, max_length=96),
                ),
                (
                    "metadata_display_phone_number",
                    models.CharField(blank=True, max_length=64),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "WhatsApp Webhook Message",
                "verbose_name_plural": "WhatsApp Webhook Messages",
                "ordering": ["-pk"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppChatBridge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Disable to stop forwarding chat messages to this bridge.",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Use as the fallback bridge when no site-specific configuration is defined.",
                    ),
                ),
                (
                    "api_base_url",
                    models.URLField(
                        default="https://graph.facebook.com/v18.0",
                        help_text="Base URL for the Meta Graph API.",
                    ),
                ),
                (
                    "phone_number_id",
                    models.CharField(
                        help_text="Identifier of the WhatsApp phone number used for delivery.",
                        max_length=64,
                        verbose_name="Phone Number ID",
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        help_text="Meta access token used to authenticate Graph API requests."
                    ),
                ),
                (
                    "avatars",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Avatars allowed to use this bridge.",
                        related_name="%(app_label)s_%(class)s_bridges",
                        to="chats.chatavatar",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Chat Bridge",
                "verbose_name_plural": "WhatsApp Chat Bridges",
                "db_table": "pages_whatsappchatbridge",
                "ordering": ["site__domain", "pk"],
            },
        ),
    ]
