# Generated by Django 5.2.8 on 2025-11-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0001_initial"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="whatsappchatbridge",
            name="unique_whatsapp_chat_bridge_site",
        ),
        migrations.RemoveConstraint(
            model_name="whatsappchatbridge",
            name="single_default_whatsapp_chat_bridge",
        ),
        migrations.AddConstraint(
            model_name="whatsappchatbridge",
            constraint=models.UniqueConstraint(
                condition=models.Q(("site__isnull", False)),
                fields=("site",),
                name="unique_whatsapp_chat_bridge_site",
            ),
        ),
        migrations.AddConstraint(
            model_name="whatsappchatbridge",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="single_default_whatsapp_chat_bridge",
            ),
        ),
    ]
