# Generated by Django 5.2.12 on 2026-04-23 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whatsappwebhook",
            name="bridge",
        ),
        migrations.RemoveField(
            model_name="whatsappwebhookmessage",
            name="webhook",
        ),
        migrations.DeleteModel(
            name="WhatsAppChatBridge",
        ),
        migrations.DeleteModel(
            name="WhatsAppWebhook",
        ),
        migrations.DeleteModel(
            name="WhatsAppWebhookMessage",
        ),
    ]
