# Generated by Django 5.2.11 on 2026-02-20 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppWebhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "route_key",
                    models.SlugField(
                        default="",
                        help_text="Unique key used in the webhook URL path for routing.",
                        max_length=48,
                        unique=True,
                    ),
                ),
                (
                    "verify_token",
                    models.CharField(
                        default="",
                        help_text="Verification token copied into the Meta webhook setup page.",
                        max_length=96,
                    ),
                ),
                (
                    "bridge",
                    models.OneToOneField(
                        help_text="Bridge that owns this inbound webhook endpoint.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook",
                        to="meta.whatsappchatbridge",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Webhook",
                "verbose_name_plural": "WhatsApp Webhooks",
                "ordering": ["bridge__site__domain", "pk"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppWebhookMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("message_id", models.CharField(db_index=True, max_length=96)),
                ("messaging_product", models.CharField(blank=True, max_length=32)),
                ("from_phone", models.CharField(blank=True, max_length=32)),
                ("wa_id", models.CharField(blank=True, max_length=32)),
                ("profile_name", models.CharField(blank=True, max_length=255)),
                ("timestamp", models.BigIntegerField(blank=True, null=True)),
                ("message_type", models.CharField(blank=True, max_length=32)),
                ("text_body", models.TextField(blank=True)),
                ("context_message_id", models.CharField(blank=True, max_length=96)),
                (
                    "metadata_phone_number_id",
                    models.CharField(blank=True, max_length=96),
                ),
                (
                    "metadata_display_phone_number",
                    models.CharField(blank=True, max_length=64),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="meta.whatsappwebhook",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Webhook Message",
                "verbose_name_plural": "WhatsApp Webhook Messages",
                "ordering": ["-pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("webhook", "message_id"),
                        name="meta_unique_webhook_message_id",
                    )
                ],
            },
        ),
    ]
