# Generated by Django 5.2.12 on 2026-04-25 04:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seed_data', models.BooleanField(default=False, editable=False)),
                ('is_user_data', models.BooleanField(default=False, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('key', models.CharField(db_index=True, editable=False, max_length=16, unique=True)),
                ('recipient', models.CharField(blank=True, help_text='WhatsApp recipient phone number for the Attention request.', max_length=64)),
                ('agent', models.CharField(blank=True, max_length=128)),
                ('severity', models.CharField(default='urgent', max_length=32)),
                ('title', models.CharField(default='Attention', max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('responded', 'Responded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_from_phone', models.CharField(blank=True, max_length=64)),
                ('response_text', models.TextField(blank=True)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bridge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attentions', to='meta.whatsappchatbridge')),
                ('response_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attentions', to='meta.whatsappwebhookmessage')),
            ],
            options={
                'verbose_name': 'Attention',
                'verbose_name_plural': 'Attention',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
