# Generated by Django 5.2.4 on 2025-08-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("refs", "0003_reference_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="image",
            field=models.ImageField(blank=True, upload_to="refs/"),
        ),
    ]
