# Generated by Django 5.2.4 on 2025-08-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("refs", "0004_alter_reference_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="content_type",
            field=models.CharField(
                choices=[("text", "Text"), ("image", "Image")],
                default="text",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="file",
            field=models.FileField(blank=True, upload_to="refs/"),
        ),
        migrations.AlterField(
            model_name="reference",
            name="alt_text",
            field=models.CharField(max_length=500, verbose_name="Title / Alt Text"),
        ),
        migrations.AlterField(
            model_name="reference",
            name="image",
            field=models.ImageField(blank=True, upload_to="refs/qr/"),
        ),
        migrations.AlterField(
            model_name="reference",
            name="value",
            field=models.TextField(blank=True),
        ),
    ]
