# Generated by Django 5.2.4 on 2025-08-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("refs", "0005_reference_content_type_reference_file_and_more"),
        ("refs", "0005_tag_taggeditem"),
    ]

    operations = []
