# Generated by Django 5.2.4 on 2025-08-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("refs", "0006_merge_20250820_1451"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="reference",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="tag",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="tag",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="taggeditem",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="taggeditem",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
