# Generated by Django 5.2.12 on 2026-09-17 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("nodes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.SlugField(max_length=80, unique=True)),
                ("display_name", models.CharField(max_length=120)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("terminal", "Terminal"),
                            ("satellite", "Satellite"),
                            ("control", "Control"),
                            ("watchtower", "Watchtower"),
                        ],
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("identifier",),
            },
        ),
        migrations.CreateModel(
            name="NodeLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relation", models.CharField(default="peer", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="nodes.node",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_links",
                        to="nodes.node",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "target"), name="unique_node_link"
                    )
                ],
            },
        ),
    ]
