# Generated by Django 5.2 on 2026-09-01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("nodes", "0002_initial")]

    operations = [
        migrations.RemoveField(
            model_name="netmessage",
            name="lcd_channel_num",
        ),
        migrations.RemoveField(
            model_name="netmessage",
            name="lcd_channel_type",
        ),
    ]
