# Generated by Django 5.2.12 on 2026-04-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="last_mesh_heartbeat",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="node",
            name="mesh_capability_flags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="node",
            name="mesh_enrollment_state",
            field=models.CharField(
                choices=[
                    ("UNENROLLED", "Unenrolled"),
                    ("PENDING", "Pending"),
                    ("ENROLLED", "Enrolled"),
                    ("FAILED", "Failed"),
                ],
                default="UNENROLLED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="mesh_key_fingerprint_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
