# Generated by Django 5.2.8 on 2025-12-04 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0003_nodemanager_avatar"),
        ("nodes", "0003_remove_node_profile"),
    ]

    operations = []
