# Generated by Django 5.2.8 on 2025-12-05 00:42

from django.db import migrations
from django.db.migrations.operations.base import Operation


def drop_profile_column(apps, schema_editor):
    try:
        Node = apps.get_model("nodes", "Node")
    except LookupError:
        return

    connection = schema_editor.connection
    table = Node._meta.db_table
    existing_columns = {
        column.name
        for column in connection.introspection.get_table_description(
            connection.cursor(), table
        )
    }
    if "profile_id" not in existing_columns:
        return

    field = Node._meta.get_field("profile")
    schema_editor.remove_field(Node, field)


def drop_nodeprofile_table(apps, schema_editor):
    try:
        NodeProfile = apps.get_model("nodes", "NodeProfile")
    except LookupError:
        return

    connection = schema_editor.connection
    table = NodeProfile._meta.db_table
    if table not in connection.introspection.table_names():
        return

    schema_editor.delete_model(NodeProfile)


class PruneNodeProfileState(Operation):
    reduces_to_sql = False
    reversible = True

    def state_forwards(self, app_label, state):
        state.models.pop((app_label, "nodeprofile"), None)
        try:
            model_state = state.models[(app_label, "node")]
        except KeyError:
            return
        model_state.fields.pop("profile", None)

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        return

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        return

    def describe(self):
        return "Prune legacy NodeProfile state"


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0004_ensure_node_profile_column"),
    ]

    operations = [
        migrations.RunPython(drop_profile_column, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(drop_nodeprofile_table, reverse_code=migrations.RunPython.noop),
        PruneNodeProfileState(),
    ]
