# Generated by Django 5.2.12 on 2026-04-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0004_nodeenrollment_nodeenrollmentevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodeenrollment",
            name="last_auth_error_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="nodeenrollment",
            name="last_authenticated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nodeenrollment",
            name="scope",
            field=models.CharField(default="mesh:read", max_length=64),
        ),
    ]
