# Generated by Django 5.2.8 on 2025-12-05 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0004_ensure_node_profile_column"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="profile",
        ),
        migrations.DeleteModel(
            name="NodeProfile",
        ),
    ]
