# Generated by Django 5.2.12 on 2026-04-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0005_nodeenrollment_last_auth_error_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="netmessage",
            name="filter_current_relation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UPSTREAM", "Upstream"),
                    ("DOWNSTREAM", "Downstream"),
                    ("PEER", "Peer"),
                    ("SIBLING", "Sibling"),
                    ("SELF", "Self"),
                ],
                max_length=10,
                verbose_name="Current relation",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="current_relation",
            field=models.CharField(
                choices=[
                    ("UPSTREAM", "Upstream"),
                    ("DOWNSTREAM", "Downstream"),
                    ("PEER", "Peer"),
                    ("SIBLING", "Sibling"),
                    ("SELF", "Self"),
                ],
                default="PEER",
                max_length=10,
            ),
        ),
    ]
