# Generated by Django 5.2.8 on 2025-12-05 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0004_merge_20251204_1646"),
        ("nodes", "0005_remove_node_profile_delete_nodeprofile"),
    ]

    operations = []
