# Generated by Django 5.2.12 on 2026-04-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0006_alter_netmessage_filter_current_relation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="ipc_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional sibling IPC socket path override.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="ipc_scheme",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional sibling IPC transport scheme (for example unix_socket).",
                max_length=20,
            ),
        ),
    ]
