# Generated by Django 5.2.12 on 2026-04-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0007_node_host_instance_id_and_more_pr20260402"),
        ("nodes", "0007_node_ipc_scheme_node_ipc_path_pr20260402"),
    ]

    operations = []
