# Generated by Django 5.2.12 on 2026-04-02 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0008_merge_20260402_1451"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="upgrade_canaries",
        ),
        migrations.RemoveField(
            model_name="upgradepolicy",
            name="requires_canaries",
        ),
    ]
