# Generated by Django 5.2.9 on 2026-01-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0010_noderole_acronym"),
    ]

    operations = [
        migrations.AddField(
            model_name="netmessage",
            name="lcd_channel",
            field=models.CharField(
                blank=True,
                choices=[("low", "Low"), ("high", "High"), ("all", "All")],
                help_text="Optional LCD channel to write when the feature is enabled.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="netmessage",
            name="lcd_channel_number",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Optional LCD channel number (0 for the default channel).",
            ),
        ),
    ]
