# Generated by Django 5.2.9 on 2026-01-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0010_noderole_acronym"),
    ]

    operations = [
        migrations.AddField(
            model_name="netmessage",
            name="lcd_channel",
            field=models.CharField(
                choices=[("low", "Low"), ("high", "High"), ("event", "Event")],
                default="low",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="netmessage",
            name="lcd_duration_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
