# Generated by Django 5.2.9 on 2026-01-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0010_noderole_acronym"),
    ]

    operations = [
        migrations.AddField(
            model_name="netmessage",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Stop propagating and displaying this message after this time.",
                null=True,
            ),
        ),
    ]
