# Generated by Django 5.2.11 on 2026-02-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0027_update_ap_router_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="upgradepolicy",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Enable this policy for upgrade scheduling and execution.",
            ),
        ),
    ]
