# Generated by Django 5.2.11 on 2026-02-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0028_nodemigrationcheckpoint"),
        ("nodes", "0029_update_policy_requirements"),
    ]

    operations = []
