# Generated by Django 5.2.11 on 2026-02-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0032_remove_ftp_server_node_feature"),
        ("nodes", "0032_retire_charge_points_node_feature"),
    ]

    operations = []
