# Generated by Django 5.2.11 on 2026-03-01 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0033_merge_20260228_1251"),
        ("nodes", "0033_merge_20260228_1333"),
    ]

    operations = []
