# Generated by Django 5.2.11 on 2026-03-01 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0033_cleanup_screenshot_poll_manual_assignments"),
        ("nodes", "0036_merge_20260228_2001"),
    ]

    operations = []
