# Generated by Django 5.2.11 on 2026-03-08 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0039_add_playwright_browser_features"),
        ("nodes", "0039_add_systemd_manager_feature"),
    ]

    operations = []
