# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dns", "0002_initial"),
        ("nmcli", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dnsprovidercredential",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User that owns this object.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dnsproxyconfig",
            name="nmcli_connection",
            field=models.ForeignKey(
                blank=True,
                help_text="NMCLI connection used as an upstream DNS source.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dns_proxy_configs",
                to="nmcli.networkconnection",
            ),
        ),
        migrations.AddField(
            model_name="godaddydnsrecord",
            name="credentials",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dns_records",
                to="dns.dnsprovidercredential",
            ),
        ),
    ]
