"""Default configuration for the pages application."""

from __future__ import annotations

DEFAULT_APPLICATION_DESCRIPTIONS: dict[str, str] = {
    "app": "Application registry and metadata.",
    "actions": "Remote actions API, bearer token management, and OpenAPI export.",
    "base": "Core configurations and shared utilities.",
    "cards": "Reusable UI cards and layout helpers.",
    "celery": "Celery integration and scheduled task tooling.",
    "certs": "Certificate management and lifecycle automation.",
    "clocks": "Timekeeping utilities, schedules, and reminders.",
    "content": "Static content blocks and editorial assets.",
    "counters": "Counting helpers and numeric trackers.",
    "core": "Support for Business Processes and monetization.",
    "credentials": "Credential storage and secrets management helpers.",
    "dns": "Domain name utilities and DNS helpers.",
    "docs": "Documentation and reference pages.",
    "emails": "Email delivery and templating.",
    "ocpp": "Compatibility with Standards and Good Practices.",
    "energy": "Support for Energy processes and monetization.",
    "groups": "Shared group definitions and permissions.",
    "nodes": "System and Node-level operations.",
    "links": "Link management and redirects.",
    "locale": "Localization helpers and translations.",
    "locals": "Local environment helpers and overrides.",
    "maps": "Geospatial utilities and map views.",
    "media": "Media storage and asset management.",
    "mermaid": "Diagram rendering and Mermaid integration.",
    "nmcli": "Network manager CLI integrations.",
    "modules": "Module discovery and registry helpers.",
    "nginx": "Nginx configuration and reverse proxy helpers.",
    "odoo": "Odoo integrations and ERP data sync helpers.",
    "pages": "User QA, Continuity Design and Chaos Testing.",
    "protocols": "Protocol helpers and shared interfaces.",
    "release": "Release management and deployment helpers.",
    "reports": "Reporting pipelines and analytics summaries.",
    "rfid": "RFID tag scanning and notifications.",
    "repos": "Repository management and release helpers.",
    "screens": "UI screen definitions and templates.",
    "sensors": "Sensor data ingestion and monitoring utilities.",
    "sigils": "Sigil handling and certificate helpers.",
    "sites": "Site management, domains, and tenancy helpers.",
    "summary": "Aggregated dashboards and executive summaries.",
    "tasks": "Task execution and job tracking.",
    "tests": "Test fixtures, utilities, and QA helpers.",
    "totp": "Time-based OTP and MFA utilities.",
    "users": "User profiles and authentication helpers.",
    "widgets": "Reusable UI widgets and embed components.",
}
