# Generated by Django 5.2.11 on 2026-03-01 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recipes", "0002_recipe_body_type_alter_recipe_script"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskbarMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("left_click_enabled", models.BooleanField(default=True)),
                ("right_click_default_enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Taskbar Menu",
                "verbose_name_plural": "Taskbar Menus",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="TaskbarIcon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "icon_b64",
                    models.TextField(
                        help_text="Base64 PNG payload without data URI prefix."
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("name",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("is_default",),
                        name="taskbar_single_default_icon",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskbarMenuAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("label", models.CharField(max_length=120)),
                (
                    "action_type",
                    models.CharField(
                        choices=[("command", "Command"), ("recipe", "Recipe")],
                        default="command",
                        max_length=16,
                    ),
                ),
                ("command", models.CharField(blank=True, max_length=200)),
                (
                    "is_left_click",
                    models.BooleanField(
                        default=True,
                        help_text="When true this entry appears in the left-click menu payload.",
                    ),
                ),
                (
                    "is_default_right_click",
                    models.BooleanField(
                        default=False,
                        help_text="When true this action is used as the right-click default action.",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="taskbar.taskbarmenu",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="taskbar_actions",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ("menu", "label"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default_right_click", True)),
                        fields=("menu",),
                        name="taskbar_one_default_right_click_per_menu",
                    )
                ],
            },
        ),
    ]
