# Generated by Django 5.2.8 on 2025-12-03 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manualtask",
            name="assigned_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Security group containing users who can fulfill the task.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_manual_tasks",
                to="groups.securitygroup",
                verbose_name="Potential assignees",
            ),
        ),
        migrations.AlterField(
            model_name="taskcategory",
            name="assigned_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Security group typically assigned to this work.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_categories_as_assignee",
                to="groups.securitygroup",
                verbose_name="Assigned to group",
            ),
        ),
        migrations.AlterField(
            model_name="taskcategory",
            name="requestor_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Security group authorized to request this work.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_categories_as_requestor",
                to="groups.securitygroup",
                verbose_name="Requestor group",
            ),
        ),
    ]
