# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0002_initial"),
        ("maps", "0002_initial"),
        ("media", "0001_initial"),
        ("nodes", "0002_initial"),
        ("odoo", "0003_initial"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chargervendorsubmission",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who completed the latest review step.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_vendor_submissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reviewed by",
            ),
        ),
        migrations.AddField(
            model_name="manualtaskreport",
            name="executor",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed the work. Can differ from the assignee.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="executed_manual_task_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Executor",
            ),
        ),
        migrations.AddField(
            model_name="manualtaskrequest",
            name="assigned_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Security group containing users who can fulfill the task.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_manual_task_requests",
                to="groups.securitygroup",
                verbose_name="Potential assignees",
            ),
        ),
        migrations.AddField(
            model_name="manualtaskrequest",
            name="assigned_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional user responsible for coordinating the task.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_manual_task_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned user",
            ),
        ),
        migrations.AddField(
            model_name="manualtaskrequest",
            name="github_issue_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template used when creating GitHub issues for this task.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manual_task_requests",
                to="tasks.githubissuetemplate",
                verbose_name="GitHub issue template",
            ),
        ),
        migrations.AddField(
            model_name="manualtaskrequest",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Location associated with this manual task.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manual_task_requests",
                to="maps.location",
                verbose_name="Location",
            ),
        ),
        migrations.AddField(
            model_name="manualtaskrequest",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="User overseeing the task.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_manual_task_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Manager",
            ),
        ),
        migrations.AddField(
            model_name="manualtaskrequest",
            name="node",
            field=models.ForeignKey(
                blank=True,
                help_text="Node where this manual task should be completed.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manual_task_requests",
                to="nodes.node",
                verbose_name="Node",
            ),
        ),
        migrations.AddField(
            model_name="manualtaskrequest",
            name="odoo_products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Products associated with the requested work.",
                related_name="manual_task_requests",
                to="odoo.odooproduct",
                verbose_name="Odoo products",
            ),
        ),
        migrations.AddField(
            model_name="manualtaskrequest",
            name="requestor",
            field=models.ForeignKey(
                blank=True,
                help_text="User creating the manual task request.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_manual_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Requestor",
            ),
        ),
        migrations.AddField(
            model_name="manualtaskrequest",
            name="required_skills",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional skills that should cover this request.",
                related_name="manual_task_requests",
                to="tasks.manualskill",
                verbose_name="Required skills",
            ),
        ),
        migrations.AddField(
            model_name="manualtaskreport",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="tasks.manualtaskrequest",
                verbose_name="Task request",
            ),
        ),
        migrations.AddField(
            model_name="taskcategory",
            name="assigned_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Security group typically assigned to this work.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_categories_as_assignee",
                to="groups.securitygroup",
                verbose_name="Assigned to group",
            ),
        ),
        migrations.AddField(
            model_name="taskcategory",
            name="image_media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_category_images",
                to="media.mediafile",
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="taskcategory",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="User responsible for overseeing this category.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_task_categories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Manager",
            ),
        ),
        migrations.AddField(
            model_name="taskcategory",
            name="odoo_products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Relevant Odoo products for this category.",
                related_name="task_categories",
                to="odoo.odooproduct",
                verbose_name="Odoo products",
            ),
        ),
        migrations.AddField(
            model_name="taskcategory",
            name="requestor_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Security group authorized to request this work.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_categories_as_requestor",
                to="groups.securitygroup",
                verbose_name="Requestor group",
            ),
        ),
        migrations.AddField(
            model_name="manualtaskrequest",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the standardized category for this work.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manual_task_requests",
                to="tasks.taskcategory",
                verbose_name="Category",
            ),
        ),
        migrations.AddConstraint(
            model_name="manualtaskrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("node__isnull", False),
                    ("location__isnull", False),
                    _connector="OR",
                ),
                name="manualtaskrequest_requires_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="manualtaskrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("scheduled_end__gte", models.F("scheduled_start"))),
                name="manualtaskrequest_schedule_order",
            ),
        ),
    ]
