# Generated by Django 5.2.11 on 2026-03-08 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_taskcategory_media_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubIssueTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name shown when selecting a template.",
                        max_length=200,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "title_template",
                    models.CharField(
                        help_text="Issue title supporting sigils such as [TASK.DESCRIPTION].",
                        max_length=240,
                        verbose_name="Title template",
                    ),
                ),
                (
                    "body_template",
                    models.TextField(
                        help_text="Issue body supporting sigils and multiline content.",
                        verbose_name="Body template",
                    ),
                ),
                (
                    "labels",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated GitHub labels to apply to created issues.",
                        max_length=500,
                        verbose_name="Labels",
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub Issue Template",
                "verbose_name_plural": "GitHub Issue Templates",
                "db_table": "core_githubissuetemplate",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="manualtaskrequest",
            name="github_issue_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of the GitHub issue created for this task request.",
                null=True,
                verbose_name="GitHub issue number",
            ),
        ),
        migrations.AddField(
            model_name="manualtaskrequest",
            name="github_issue_opened_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when a GitHub issue was created for this request.",
                null=True,
                verbose_name="GitHub issue opened at",
            ),
        ),
        migrations.AddField(
            model_name="manualtaskrequest",
            name="github_issue_overdue_after",
            field=models.DurationField(
                blank=True,
                help_text="Delay after scheduled start before opening overdue issues.",
                null=True,
                verbose_name="GitHub overdue threshold",
            ),
        ),
        migrations.AddField(
            model_name="manualtaskrequest",
            name="github_issue_trigger",
            field=models.CharField(
                blank=True,
                choices=[
                    ("scheduled_start", "Scheduled start"),
                    ("completed", "Completed"),
                    ("overdue", "Overdue"),
                ],
                help_text="When the linked GitHub issue should be created for this task request.",
                max_length=32,
                verbose_name="GitHub issue trigger",
            ),
        ),
        migrations.AddField(
            model_name="manualtaskrequest",
            name="github_issue_url",
            field=models.URLField(
                blank=True,
                help_text="URL of the GitHub issue created for this task request.",
                verbose_name="GitHub issue URL",
            ),
        ),
        migrations.AddField(
            model_name="manualtaskrequest",
            name="github_issue_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template used when creating GitHub issues for this task.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manual_task_requests",
                to="tasks.githubissuetemplate",
                verbose_name="GitHub issue template",
            ),
        ),
    ]
