# Generated by Django 5.2.12 on 2026-03-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_githubissuetemplate_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manualtaskrequest",
            options={
                "ordering": ("scheduled_start", "category__name"),
                "verbose_name": "Manual Request",
                "verbose_name_plural": "Manual Requests",
            },
        ),
    ]
