# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("totp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="totpdevice",
            name="user",
            field=models.ForeignKey(
                help_text="The user that this device belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="totpdevice",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="totp_device_unique_name_per_user"
            ),
        ),
    ]
