# Generated by Django 5.2.12 on 2026-04-13 00:00

from django.db import migrations


def copy_totp_devices_to_plugin(apps, schema_editor):
    source_model = apps.get_model("totp", "TOTPDevice")
    target_model = apps.get_model("otp_totp", "TOTPDevice")

    for source in source_model.objects.all().iterator():
        target_model.objects.update_or_create(
            id=source.id,
            defaults={
                "name": source.name,
                "confirmed": source.confirmed,
                "throttling_failure_timestamp": source.throttling_failure_timestamp,
                "throttling_failure_count": source.throttling_failure_count,
                "created_at": source.created_at,
                "last_used_at": source.last_used_at,
                "key": source.key,
                "step": source.step,
                "t0": source.t0,
                "digits": source.digits,
                "tolerance": source.tolerance,
                "drift": source.drift,
                "last_t": source.last_t,
                "user_id": source.user_id,
            },
        )

    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT setval(
                    pg_get_serial_sequence('otp_totp_totpdevice', 'id'),
                    COALESCE((SELECT MAX(id) FROM otp_totp_totpdevice), 1),
                    (SELECT COUNT(*) > 0 FROM otp_totp_totpdevice)
                )
                """
            )


def copy_totp_devices_to_local(apps, schema_editor):
    source_model = apps.get_model("otp_totp", "TOTPDevice")
    target_model = apps.get_model("totp", "TOTPDevice")

    for source in source_model.objects.all().iterator():
        target_model.objects.update_or_create(
            id=source.id,
            defaults={
                "name": source.name,
                "confirmed": source.confirmed,
                "throttling_failure_timestamp": source.throttling_failure_timestamp,
                "throttling_failure_count": source.throttling_failure_count,
                "created_at": source.created_at,
                "last_used_at": source.last_used_at,
                "key": source.key,
                "step": source.step,
                "t0": source.t0,
                "digits": source.digits,
                "tolerance": source.tolerance,
                "drift": source.drift,
                "last_t": source.last_t,
                "user_id": source.user_id,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("otp_totp", "0003_add_timestamps"),
        ("totp", "0002_initial"),
    ]

    operations = [
        migrations.RunPython(
            copy_totp_devices_to_plugin,
            reverse_code=copy_totp_devices_to_local,
        ),
    ]
