# Generated by Django 5.2.12 on 2026-04-13 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("totp", "0003_migrate_devices_to_otp_totp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TOTPDevice",
        ),
    ]
