# Generated by Django 5.2.10 on 2026-02-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0006_charge_points_module_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="agent_notes",
            field=models.TextField(
                blank=True,
                help_text="Hidden, agent-facing guidance about what this module is best used for.",
            ),
        ),
    ]
