# Generated by Django 5.2.8 on 2025-12-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Allow this location to be visible to unauthenticated visitors.",
                verbose_name="Public",
            ),
        ),
    ]
