"""Default configuration for the pages application."""
from __future__ import annotations

from typing import Dict

DEFAULT_APPLICATION_DESCRIPTIONS: Dict[str, str] = {
    "app": "Application registry and metadata.",
    "base": "Core configurations and shared utilities.",
    "cards": "Reusable UI cards and layout helpers.",
    "celery_app": "Celery integration and scheduled task tooling.",
    "chats": "Chat messaging and conversational flows.",
    "awg": "Power, Energy and Cost calculations.",
    "content": "Static content blocks and editorial assets.",
    "counters": "Counting helpers and numeric trackers.",
    "core": "Support for Business Processes and monetization.",
    "dns": "Domain name utilities and DNS helpers.",
    "docs": "Documentation and reference pages.",
    "emails": "Email delivery and templating.",
    "ocpp": "Compatibility with Standards and Good Practices.",
    "ocpp_forwarder": "Forward OCPP payloads to downstream systems.",
    "ocpp_simulator": "Simulate OCPP devices and interactions.",
    "embeds": "Embeddable widgets and integrations.",
    "energy": "Support for Energy processes and monetization.",
    "flows": "Workflow orchestration and pipelines.",
    "groups": "Shared group definitions and permissions.",
    "nodes": "System and Node-level operations.",
    "links": "Link management and redirects.",
    "locale": "Localization helpers and translations.",
    "locals": "Local environment helpers and overrides.",
    "maps": "Geospatial utilities and map views.",
    "media": "Media storage and asset management.",
    "meta": "Metadata helpers and system insights.",
    "nmcli": "Network manager CLI integrations.",
    "payments": "Payment gateways and billing helpers.",
    "pages": "User QA, Continuity Design and Chaos Testing.",
    "protocols": "Protocol helpers and shared interfaces.",
    "rates": "Rates, pricing and tariff helpers.",
    "rfid": "RFID tag scanning and notifications.",
    "repos": "Repository management and release helpers.",
    "screens": "UI screen definitions and templates.",
    "sigils": "Sigil handling and certificate helpers.",
    "teams": "Identity, Entitlements and Access Controls.",
    "tasks": "Task execution and job tracking.",
    "users": "User profiles and authentication helpers.",
    "vehicle": "Vehicle management and telemetry.",
}
