# Generated by Django 5.2.8 on 2025-12-02 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("awg", "0001_initial"),
        ("energy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnergyTariff",
            fields=[],
            options={
                "verbose_name": "Energy Tariff",
                "verbose_name_plural": "Energy Tariffs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("energy.energytariff",),
        ),
        migrations.AddField(
            model_name="powerlead",
            name="assign_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="powerlead",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
