# Generated by Django 5.2.8 on 2025-12-06 15:03

from django.db import migrations


OLD_DESCRIPTION = "EV Charger - Residential charging for a single Electric Vehicle."
NEW_DESCRIPTION = "Single vehicle residential charging"
TEMPLATE_NAME = "EV Charger"


def update_description(apps, schema_editor):
    CalculatorTemplate = apps.get_model("awg", "CalculatorTemplate")
    CalculatorTemplate.objects.filter(name=TEMPLATE_NAME).update(
        description=NEW_DESCRIPTION
    )


def revert_description(apps, schema_editor):
    CalculatorTemplate = apps.get_model("awg", "CalculatorTemplate")
    CalculatorTemplate.objects.filter(name=TEMPLATE_NAME).update(
        description=OLD_DESCRIPTION
    )


class Migration(migrations.Migration):

    dependencies = [
        ("awg", "0002_initial"),
    ]

    operations = [
        migrations.RunPython(update_description, revert_description),
    ]
