# Generated by Django 5.2.12 on 2026-04-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awg", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HypergeometricTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("deck_size", models.PositiveIntegerField(default=60)),
                ("success_states", models.PositiveIntegerField(default=4)),
                ("draws", models.PositiveIntegerField(default=7)),
                ("min_successes", models.PositiveIntegerField(default=1)),
                ("exact_successes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "show_in_pages",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="Show in public site"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hypergeometric Template",
                "verbose_name_plural": "Hypergeometric Templates",
            },
        ),
    ]
