# Generated by Codex on 2026-04-25

from django.db import migrations


PRESETS = [
    {
        "name": "40-card Draft",
        "description": "Limited baseline: 40-card deck, 17 lands, and a four-of-style key card check.",
        "deck_size": 40,
        "success_states": 4,
        "draws": 7,
        "min_successes": 1,
        "exact_successes": None,
        "show_in_pages": True,
        "is_seed_data": True,
    },
    {
        "name": "60-card Standard",
        "description": "Constructed baseline: 60-card deck and four copies of a key card in the opening hand.",
        "deck_size": 60,
        "success_states": 4,
        "draws": 7,
        "min_successes": 1,
        "exact_successes": None,
        "show_in_pages": True,
        "is_seed_data": True,
    },
    {
        "name": "100-card Commander",
        "description": "Commander baseline: 99-card library plus commander; check one singleton card by turn three.",
        "deck_size": 99,
        "success_states": 1,
        "draws": 10,
        "min_successes": 1,
        "exact_successes": None,
        "show_in_pages": True,
        "is_seed_data": True,
    },
    {
        "name": "360-card Realm",
        "description": "Realm baseline: long 20+ turn game with at least 20 creatures, 20 lands, and a split utility package.",
        "deck_size": 360,
        "success_states": 20,
        "draws": 27,
        "min_successes": 1,
        "exact_successes": None,
        "show_in_pages": True,
        "is_seed_data": True,
    },
]


def create_presets(apps, schema_editor):
    HypergeometricTemplate = apps.get_model("awg", "HypergeometricTemplate")
    for preset in PRESETS:
        values = preset.copy()
        name = values.pop("name")
        HypergeometricTemplate.objects.update_or_create(
            name=name,
            defaults=values,
        )


def remove_presets(apps, schema_editor):
    HypergeometricTemplate = apps.get_model("awg", "HypergeometricTemplate")
    HypergeometricTemplate.objects.filter(
        name__in=[preset["name"] for preset in PRESETS],
        is_seed_data=True,
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("awg", "0003_hypergeometrictemplate"),
    ]

    operations = [
        migrations.RunPython(create_presets, remove_presets),
    ]
