# Generated by Django 5.2.10 on 2026-02-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awg", "0004_update_ev_charger_phases"),
    ]

    operations = [
        migrations.AlterField(
            model_name="powerlead",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("assigned", "Assigned"),
                    ("closed", "Closed"),
                    ("spam", "Spam"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
