# Generated by Django 5.2.4 on 2026-03-01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ManagedDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(max_length=64, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=120)),
                ("engine", models.CharField(max_length=255)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("host", models.CharField(blank=True, max_length=255)),
                ("port", models.CharField(blank=True, max_length=32)),
                ("username", models.CharField(blank=True, max_length=255)),
                ("is_current", models.BooleanField(default=False)),
                ("is_django_connection", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Managed Database",
                "verbose_name_plural": "Managed Databases",
                "ordering": ["-is_current", "alias"],
            },
        ),
    ]
