# Generated by Django 5.2.4 on 2025-08-26 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rfid_last_seen_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfid",
            name="data",
            field=models.JSONField(
                blank=True, default=list, help_text="Sector and block data"
            ),
        ),
        migrations.AddField(
            model_name="rfid",
            name="key_a_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rfid",
            name="key_b_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="FediverseProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "service",
                    models.CharField(
                        choices=[("mastodon", "Mastodon"), ("bluesky", "Bluesky")],
                        max_length=20,
                    ),
                ),
                ("host", models.CharField(max_length=255)),
                ("handle", models.CharField(max_length=255)),
                ("access_token", models.CharField(blank=True, max_length=255)),
                ("verified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fediverse_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
