# Generated by Django 5.2.4 on 2025-09-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_chatprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitelead",
            name="sent_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invitelead",
            name="error",
            field=models.TextField(blank=True),
        ),
    ]
