# Generated by Django 5.2.4 on 2025-09-09 15:28

from django.db import migrations, models
import django.utils.timezone
from core.models import validate_relative_url


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_businesspowerlead"),
    ]

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("description", models.CharField(max_length=255)),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        validators=[validate_relative_url],
                    ),
                ),
            ],
            options={
                "verbose_name": "TODO",
                "verbose_name_plural": "TODOs",
            },
        ),
        migrations.AddField(
            model_name="invitelead",
            name="error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="invitelead",
            name="sent_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("content", models.TextField()),
                (
                    "published",
                    models.DateField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-published"],
                "verbose_name": "News Article",
                "verbose_name_plural": "News Articles",
            },
        ),
    ]
