# Generated by Django 5.2.4 on 2025-09-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_businesspowerlead"),
    ]

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "TODO",
                "verbose_name_plural": "TODOs",
            },
        ),
        migrations.AddField(
            model_name="invitelead",
            name="error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="invitelead",
            name="sent_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
