# Generated by Django 5.2.4 on 2025-09-11 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_invitelead_error_invitelead_sent_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rfid",
            name="reference",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional reference for this RFID.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rfids",
                to="core.reference",
            ),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="version",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
