# Generated by Django 5.2.4 on 2025-09-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_emailcollector_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminhistory",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="brand",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="chatprofile",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="electricvehicle",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="emailartifact",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="emailcollector",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="emailinbox",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="energyaccount",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="energycredit",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="energyreport",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="evmodel",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="invitelead",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="odooprofile",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="package",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="packagerelease",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="reference",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="releasemanager",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="rfid",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="sigilroot",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="livesubscription",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="todo",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="user",
            name="data_path",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="wmicode",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.DeleteModel(
            name="UserDatum",
        ),
    ]
