# Generated by Django 5.2.4 on 2025-09-14 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_user_data_field"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BusinessPowerLead",
        ),
    ]
