# Generated by Django 5.2.4 on 2025-09-14 07:21

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_delete_businesspowerlead"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="request_details",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddConstraint(
            model_name="todo",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("description"),
                condition=models.Q(("is_deleted", False)),
                name="unique_active_todo_description",
            ),
        ),
    ]
