# Generated by Django 5.2.4 on 2025-09-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_todo_request_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="done_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
