# Generated by Django 5.2.4 on 2025-09-15 00:00

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_todo_done_on"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="todo",
            name="unique_active_todo_description",
        ),
        migrations.RenameField(
            model_name="todo",
            old_name="description",
            new_name="request",
        ),
        migrations.AddConstraint(
            model_name="todo",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("request"),
                condition=models.Q(("is_deleted", False)),
                name="unique_active_todo_request",
            ),
        ),
    ]
