# Generated by Django 5.2.4 on 2025-09-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_todo_request_rename"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EnergyReport",
            new_name="ClientReport",
        ),
        migrations.AlterModelOptions(
            name="clientreport",
            options={
                "ordering": ["-created_on"],
                "verbose_name": "Client Report",
                "verbose_name_plural": "Client Reports",
            },
        ),
        migrations.AlterModelTable(
            name="clientreport",
            table="core_client_report",
        ),
    ]
