# Generated by Django 5.2.4 on 2025-09-16 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_remove_cmd_sigil_root"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="operate_as",
            field=models.ForeignKey(
                blank=True,
                help_text="Operate using another user's permissions when additional authority is required.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operated_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
