# Generated by Django 5.2.4 on 2025-09-17 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_chatprofile_group_odooprofile_group_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="odooprofile",
            options={
                "verbose_name": "Odoo Employee",
                "verbose_name_plural": "Odoo Employees",
            },
        ),
    ]
