# Generated by Django 5.2.4 on 2025-09-17 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_odooprofile_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="APLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("path", models.TextField(blank=True)),
                ("referer", models.TextField(blank=True)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("ssid", models.CharField(max_length=32)),
                (
                    "mode",
                    models.CharField(
                        choices=[("secure", "Secure"), ("public", "Public")],
                        default="secure",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AP Lead",
                "verbose_name_plural": "AP Leads",
            },
        ),
    ]
