# Generated by Django 5.2.4 on 2025-09-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_remove_user_phone_number_userphonenumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="userphonenumber",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="userphonenumber",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="userphonenumber",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
