# Generated by Django 5.2.4 on 2025-09-17 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_userphonenumber_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailinbox",
            name="group",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.securitygroup",
            ),
        ),
        migrations.AlterField(
            model_name="emailinbox",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
