# Generated by Django 5.2.4 on 2025-09-19 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_reference_features_reference_roles_reference_sites_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitelead",
            name="mac_address",
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.CreateModel(
            name="PublicWifiAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("mac_address", models.CharField(max_length=17)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("revoked_on", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_wifi_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Public Wi-Fi Access",
                "verbose_name_plural": "Public Wi-Fi Access",
                "unique_together": {("user", "mac_address")},
            },
        ),
    ]
