# Generated by Django 5.2.4 on 2025-09-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_invitelead_mac_address_publicwifiaccess"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="license",
            field=models.CharField(default="GPL-3.0-only", max_length=100),
        ),
    ]
