# Generated by Django 5.2.4 on 2025-09-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_clientreport_disable_emails_clientreport_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_visit_ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
