# Generated by Django 5.2.4 on 2025-09-20 23:37

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_energytariff"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="on_done_condition",
            field=core.fields.ConditionTextField(blank=True, default=""),
        ),
    ]
