# Generated by Django 5.2.4 on 2025-09-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_energytariff"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="energytariff",
            name="uniq_energy_tariff_schedule",
        ),
        migrations.RemoveIndex(
            model_name="energytariff",
            name="energy_tariff_schedule_idx",
        ),
        migrations.RenameField(
            model_name="energytariff",
            old_name="time_of_day",
            new_name="period",
        ),
        migrations.RemoveField(
            model_name="energytariff",
            name="month",
        ),
        migrations.AddField(
            model_name="energytariff",
            name="season",
            field=models.CharField(
                choices=[
                    ("annual", "All year"),
                    ("summer", "Summer season"),
                    ("non_summer", "Non-summer season"),
                ],
                default="annual",
                help_text="Season or applicability window defined by CFE.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="energytariff",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kwh", "Kilowatt-hour"),
                    ("kw", "Kilowatt"),
                    ("month", "Monthly charge"),
                ],
                default="kwh",
                help_text="Measurement unit for the tariff charge.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="energytariff",
            name="notes",
            field=models.TextField(
                default="",
                help_text="Context or special billing conditions published by CFE.",
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name="energytariff",
            name="contract_type",
            field=models.CharField(
                choices=[
                    ("domestic", "Domestic service (Tarifa 1)"),
                    ("dac", "High consumption domestic (DAC)"),
                    ("pdbt", "General service low demand (PDBT)"),
                    ("gdbt", "General service high demand (GDBT)"),
                    ("gdmto", "General distribution medium tension (GDMTO)"),
                    (
                        "gdmth",
                        "General distribution medium tension hourly (GDMTH)",
                    ),
                ],
                help_text="Type of service contract regulated by CFE.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="energytariff",
            name="period",
            field=models.CharField(
                choices=[
                    ("flat", "Flat rate"),
                    ("basic", "Basic block"),
                    ("intermediate_1", "Intermediate block 1"),
                    ("intermediate_2", "Intermediate block 2"),
                    ("excess", "Excess consumption"),
                    ("base", "Base"),
                    ("intermediate", "Intermediate"),
                    ("peak", "Peak"),
                    ("critical_peak", "Critical peak"),
                    ("demand", "Demand charge"),
                    ("capacity", "Capacity charge"),
                    ("distribution", "Distribution charge"),
                    ("fixed", "Fixed charge"),
                ],
                help_text="Tariff block, demand component, or time-of-use period.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="energytariff",
            name="price_mxn",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Customer price per unit in MXN.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="energytariff",
            name="cost_mxn",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Provider cost per unit in MXN.",
                max_digits=10,
            ),
        ),
        migrations.AddIndex(
            model_name="energytariff",
            index=models.Index(
                fields=["year", "season", "zone", "contract_type"],
                name="energy_tariff_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="energytariff",
            constraint=models.UniqueConstraint(
                fields=[
                    "year",
                    "season",
                    "zone",
                    "contract_type",
                    "period",
                    "unit",
                    "start_time",
                    "end_time",
                ],
                name="uniq_energy_tariff_schedule",
            ),
        ),
    ]
