# Generated by Django 5.2.4 on 2025-09-20 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_energy_tariff_2025_update"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="energytariff",
            options={
                "ordering": (
                    "-year",
                    "season",
                    "zone",
                    "contract_type",
                    "period",
                    "start_time",
                ),
                "verbose_name": "Energy Tariff",
                "verbose_name_plural": "Energy Tariffs",
            },
        ),
    ]
