# Generated by Django 5.2.4 on 2025-09-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_user_admin_profile_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="show_in_header",
            field=models.BooleanField(default=False, verbose_name="Show in Header"),
        ),
    ]
