# Generated by Django 5.2.4 on 2025-09-24 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_todo_url_normalize_loopback"),
        ("nodes", "0008_emailoutbox_is_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitelead",
            name="sent_via_outbox",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invite_leads",
                to="nodes.emailoutbox",
            ),
        ),
    ]
