# Generated by Django 5.2.4 on 2025-09-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_rename_socialprofile_verbose"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagerelease",
            name="release_on",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
