# Generated by Django 5.2.4 on 2025-10-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_rfid_origin_node"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="dependencies_path",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="package",
            name="test_command",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="package",
            name="version_path",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
