# Generated by Django 5.2.4 on 2025-10-01 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_package_dependencies_path_package_test_command_and_more"),
        ("core", "0054_package_packages"),
    ]

    operations = []
