# Generated by Django 5.2.4 on 2025-10-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_remove_package_packages"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagerelease",
            name="changelog",
            field=models.TextField(blank=True, default=""),
        ),
    ]
