# Generated by Django 5.2.4 on 2025-10-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_packagerelease_changelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfid",
            name="external_command",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional command executed during validation.",
            ),
        ),
    ]
