# Generated by Django 5.2.4 on 2025-10-03 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_rfid_external_command"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorldSimulator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "base_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional absolute path to an existing Evennia game directory.",
                        max_length=500,
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        default="127.0.0.1",
                        help_text="Hostname or IP address where the simulator should listen.",
                        max_length=255,
                    ),
                ),
                (
                    "server_port",
                    models.PositiveIntegerField(
                        default=4000,
                        help_text="Telnet port exposed by the Evennia server.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                    ),
                ),
                (
                    "webclient_port",
                    models.PositiveIntegerField(
                        default=4002,
                        help_text="Port used by the Evennia web client.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                    ),
                ),
                (
                    "watchdog_interval",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Seconds between watchdog checks that ensure Evennia stays online.",
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(3600),
                        ],
                    ),
                ),
                (
                    "watchdog_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically restart the simulator if it stops.",
                    ),
                ),
                ("last_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_watchdog_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "World simulator",
                "verbose_name_plural": "World simulators",
                "ordering": ["name"],
            },
        ),
    ]
