# Generated by Django 5.2.7 on 2025-10-08 00:29

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_remove_socialprofile_socialprofile_network_handle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="releasemanager",
            name="git_password",
            field=core.fields.SigilShortAutoField(
                blank=True,
                help_text="Password or personal access token for HTTPS Git pushes. Leave blank to use the GitHub token instead.",
                max_length=200,
                verbose_name="Git password/token",
            ),
        ),
        migrations.AddField(
            model_name="releasemanager",
            name="git_username",
            field=core.fields.SigilShortAutoField(
                blank=True,
                help_text="Username used for Git pushes (for example, your GitHub username).",
                max_length=100,
                verbose_name="Git username",
            ),
        ),
    ]
