# Generated by Django 5.2.7 on 2025-10-08 16:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_releasemanager_git_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="packages",
            field=models.JSONField(
                default=core.models.default_package_modules,
                help_text="List of Python packages to include in the distribution.",
            ),
        ),
    ]
