# Generated by Django 5.2.7 on 2025-10-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_releasemanager_git_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="description",
            field=models.CharField(
                default="Power & Energy Infrastructure", max_length=255
            ),
        ),
    ]
