# Generated by Django 5.2.7 on 2025-10-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_rfid_post_auth_command"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="generated_for_revision",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="todo",
            name="generated_for_version",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
