# Generated by Django 5.2.7 on 2025-10-15 00:00

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_todo_generated_for_revision_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="releasemanager",
            name="pypi_url",
            field=core.fields.SigilShortAutoField(
                blank=True,
                help_text=(
                    "Link to the PyPI user profile (for example, https://pypi.org/user/username/). "
                    "Use the account's user page, not a project-specific URL. "
                    "This value is informational and not used for uploads."
                ),
                max_length=200,
                verbose_name="PyPI URL",
            ),
        ),
    ]
