# Generated by Django 5.2.7 on 2025-10-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_rfid_reversed_uid"),
        ("teams", "0010_delete_assistantprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AssistantProfile",
        ),
    ]
