# Generated by Django 5.2.7 on 2025-10-28 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_delete_assistantprofile"),
        ("nodes", "0023_rename_constellation_to_watchtower"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="origin_node",
            field=models.ForeignKey(
                blank=True,
                help_text="Node where this TODO was generated.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="originated_todos",
                to="nodes.node",
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="original_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User responsible for creating this TODO.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="originated_todos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="original_user_is_authenticated",
            field=models.BooleanField(
                default=False,
                help_text="Whether the originating user was authenticated during creation.",
            ),
        ),
    ]
