# Generated by Django 5.2.7 on 2025-10-28 23:24

import core.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_todo_origin_node_todo_original_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleCalendarProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("calendar_id", core.fields.SigilShortAutoField(max_length=255)),
                ("api_key", core.fields.SigilShortAutoField(max_length=255)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                (
                    "max_events",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Number of upcoming events to display (1-20).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "timezone",
                    core.fields.SigilShortAutoField(blank=True, max_length=100),
                ),
                (
                    "group",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.securitygroup",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Calendar",
                "verbose_name_plural": "Google Calendars",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("user__isnull", False), ("group__isnull", True)),
                            models.Q(("user__isnull", True), ("group__isnull", False)),
                            _connector="OR",
                        ),
                        name="googlecalendarprofile_requires_owner",
                    )
                ],
            },
        ),
    ]
