# Generated by Django 5.2.7 on 2025-10-28 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0077_googlecalendarprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="googlecalendarprofile",
            options={
                "verbose_name": "Calendar Profile",
                "verbose_name_plural": "Calendar Profile",
            },
        ),
    ]
