# Generated by Django 5.2.7 on 2025-10-29 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0077_googlecalendarprofile"),
        ("nodes", "0024_alter_nodemanager_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="done_node",
            field=models.ForeignKey(
                blank=True,
                help_text="Node where this TODO was completed.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_todos",
                to="nodes.node",
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="done_revision",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="todo",
            name="done_username",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="todo",
            name="done_version",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
