# Generated by Django 5.2.7 on 2025-11-02 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0081_clientreport_language_clientreport_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="kilowatt_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional kilowatt capacity associated with the product.",
                max_digits=10,
                null=True,
                verbose_name="Kilowatt Value (kW)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="odoo_created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Employee profile that registered this product from Odoo.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products_created",
                to="core.odooprofile",
                verbose_name="Odoo employee",
            ),
        ),
    ]
