# Generated by Django 5.2.7 on 2025-11-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0081_clientreport_language_clientreport_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagerelease",
            name="severity",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("low", "Low"),
                    ("critical", "Critical"),
                ],
                default="normal",
                help_text="Controls the expected urgency for auto-upgrades.",
                max_length=16,
            ),
        ),
    ]
