# Generated by Django 5.2.7 on 2025-11-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0082_packagerelease_severity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="odooprofile",
            options={
                "verbose_name": "CRM Employee",
                "verbose_name_plural": "CRM Employees",
            },
        ),
        migrations.AddField(
            model_name="odooprofile",
            name="crm",
            field=models.CharField(
                choices=[("odoo", "Odoo")], default="odoo", max_length=32
            ),
        ),
    ]
