# Generated by Django 5.2.7 on 2025-11-06 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0085_remove_manualtask"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="birthday",
        ),
    ]
