# Generated by Django 5.2.4 on 2025-11-06 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_remove_user_birthday'),
        ('core', '0086_slugify_periodic_task_names'),
    ]

    operations = [
    ]
