# Generated by Django 5.2.7 on 2025-11-06 23:24

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0087_merge_20251105_2104"),
    ]

    operations = [
        migrations.AddField(
            model_name="openpayprofile",
            name="default_processor",
            field=models.CharField(
                choices=[("openpay", "OpenPay"), ("paypal", "PayPal")],
                default="openpay",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="openpayprofile",
            name="paypal_client_id",
            field=core.fields.SigilShortAutoField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="openpayprofile",
            name="paypal_client_secret",
            field=core.fields.SigilShortAutoField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="openpayprofile",
            name="paypal_is_production",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="openpayprofile",
            name="paypal_webhook_id",
            field=core.fields.SigilShortAutoField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="openpayprofile",
            name="merchant_id",
            field=core.fields.SigilShortAutoField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="openpayprofile",
            name="private_key",
            field=core.fields.SigilShortAutoField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="openpayprofile",
            name="public_key",
            field=core.fields.SigilShortAutoField(blank=True, max_length=255),
        ),
    ]
