# Generated by Django 5.2.4 on 2025-11-06 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_openpayprofile_default_processor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openpayprofile',
            options={'verbose_name': 'Payment Processor', 'verbose_name_plural': 'Payment Processors'},
        ),
    ]
