# Generated by Django 5.2.7 on 2025-11-08 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0091_todo_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="todo",
            name="stale_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
