# Generated by Django 5.2.8 on 2025-11-11 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0093_drop_existing_todos"),
        ("ocpp", "0044_delete_brand_delete_electricvehicle_delete_evmodel_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name="ElectricVehicle"),
                migrations.DeleteModel(name="EVModel"),
                migrations.DeleteModel(name="WMICode"),
                migrations.DeleteModel(name="Brand"),
            ],
        ),
    ]
