# Generated by Django 5.2.8 on 2025-11-13 00:09

import django.core.validators
from django.db import migrations, models


def _normalize_lead_fields(apps, schema_editor):
    """Replace ``NULL`` values with blank strings for existing lead data."""

    Location = apps.get_model("core", "Location")
    InviteLead = apps.get_model("core", "InviteLead")
    User = apps.get_model("core", "User")

    Location.objects.filter(contract_type__isnull=True).update(contract_type="")
    Location.objects.filter(zone__isnull=True).update(zone="")
    InviteLead.objects.filter(ip_address__isnull=True).update(ip_address="")
    User.objects.filter(last_visit_ip_address__isnull=True).update(
        last_visit_ip_address=""
    )


def _restore_lead_nulls(apps, schema_editor):
    """Restore legacy ``NULL`` values when rolling back."""

    Location = apps.get_model("core", "Location")
    InviteLead = apps.get_model("core", "InviteLead")
    User = apps.get_model("core", "User")

    Location.objects.filter(contract_type="").update(contract_type=None)
    Location.objects.filter(zone="").update(zone=None)
    InviteLead.objects.filter(ip_address="").update(ip_address=None)
    User.objects.filter(last_visit_ip_address="").update(
        last_visit_ip_address=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0099_remove_packagerelease_changelog"),
    ]

    operations = [
        migrations.RunPython(
            _normalize_lead_fields,
            _restore_lead_nulls,
        ),
        migrations.AlterField(
            model_name="location",
            name="contract_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("domestic", "Domestic service (Tarifa 1)"),
                    ("dac", "High consumption domestic (DAC)"),
                    ("pdbt", "General service low demand (PDBT)"),
                    ("gdbt", "General service high demand (GDBT)"),
                    ("gdmto", "General distribution medium tension (GDMTO)"),
                    ("gdmth", "General distribution medium tension hourly (GDMTH)"),
                ],
                help_text="CFE service contract type required to match energy tariff pricing.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="zone",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Zone 1"),
                    ("1A", "Zone 1A"),
                    ("1B", "Zone 1B"),
                    ("1C", "Zone 1C"),
                    ("1D", "Zone 1D"),
                    ("1E", "Zone 1E"),
                    ("1F", "Zone 1F"),
                ],
                help_text="CFE climate zone used to select matching energy tariffs.",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="invitelead",
            name="ip_address",
            field=models.CharField(
                blank=True,
                max_length=45,
                validators=[django.core.validators.validate_ipv46_address],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_visit_ip_address",
            field=models.CharField(
                blank=True,
                max_length=45,
                validators=[django.core.validators.validate_ipv46_address],
            ),
        ),
    ]
