# Generated by Django 5.2.8 on 2025-11-13 00:09

import django.core.validators
from django.db import migrations, models


def _fill_blank_fields(apps, schema_editor):
    InviteLead = apps.get_model("core", "InviteLead")
    Location = apps.get_model("core", "Location")
    User = apps.get_model("core", "User")

    InviteLead.objects.filter(ip_address__isnull=True).update(ip_address="")
    Location.objects.filter(contract_type__isnull=True).update(contract_type="")
    Location.objects.filter(zone__isnull=True).update(zone="")
    User.objects.filter(last_visit_ip_address__isnull=True).update(
        last_visit_ip_address=""
    )


def _noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0099_remove_packagerelease_changelog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitelead",
            name="ip_address",
            field=models.CharField(
                blank=True,
                max_length=45,
                null=True,
                validators=[django.core.validators.validate_ipv46_address],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_visit_ip_address",
            field=models.CharField(
                blank=True,
                max_length=45,
                null=True,
                validators=[django.core.validators.validate_ipv46_address],
            ),
        ),
        migrations.RunPython(_fill_blank_fields, _noop),
        migrations.AlterField(
            model_name="invitelead",
            name="ip_address",
            field=models.CharField(
                blank=True,
                max_length=45,
                validators=[django.core.validators.validate_ipv46_address],
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="contract_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("domestic", "Domestic service (Tarifa 1)"),
                    ("dac", "High consumption domestic (DAC)"),
                    ("pdbt", "General service low demand (PDBT)"),
                    ("gdbt", "General service high demand (GDBT)"),
                    ("gdmto", "General distribution medium tension (GDMTO)"),
                    ("gdmth", "General distribution medium tension hourly (GDMTH)"),
                ],
                help_text="CFE service contract type required to match energy tariff pricing.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="zone",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Zone 1"),
                    ("1A", "Zone 1A"),
                    ("1B", "Zone 1B"),
                    ("1C", "Zone 1C"),
                    ("1D", "Zone 1D"),
                    ("1E", "Zone 1E"),
                    ("1F", "Zone 1F"),
                ],
                help_text="CFE climate zone used to select matching energy tariffs.",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_visit_ip_address",
            field=models.CharField(
                blank=True,
                max_length=45,
                validators=[django.core.validators.validate_ipv46_address],
            ),
        ),
    ]
