# Generated by Django 5.2.8 on 2025-11-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0101_update_sigilroot_content_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountdownTimer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True, default="")),
                ("scheduled_for", models.DateTimeField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Countdown Timer",
                "verbose_name_plural": "Countdown Timers",
                "ordering": ("scheduled_for", "title", "pk"),
            },
        ),
    ]
