# Generated by Django 5.2.8 on 2025-11-14 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0102_countdowntimer"),
        ("pages", "0034_developerarticle"),
    ]

    operations = [
        migrations.AddField(
            model_name="countdowntimer",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="countdown_timers",
                to="pages.developerarticle",
            ),
        ),
        migrations.AddField(
            model_name="countdowntimer",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
