# Generated by Django 5.2.8 on 2025-11-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0103_countdowntimer_article_countdowntimer_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="odooprofile",
            name="partner_id",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
