# Generated by Django 5.2.8 on 2025-11-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0105_merge_20251115_1210"),
    ]

    operations = [
        migrations.AddField(
            model_name="totpdevicesettings",
            name="allow_without_password",
            field=models.BooleanField(
                default=False,
                help_text="Allow authenticator logins to skip the password step.",
            ),
        ),
    ]
