# Generated by Django 5.2.8 on 2025-11-16 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0108_merge_20251115_1815"),
    ]

    operations = [
        migrations.AddField(
            model_name="countdowntimer",
            name="package_release",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="countdown_timer",
                to="core.packagerelease",
            ),
        ),
    ]
