# Generated by Django 5.2.7 on 2025-11-24 00:00

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0109_countdowntimer_package_release"),
    ]

    operations = [
        migrations.AddField(
            model_name="openpayprofile",
            name="stripe_is_production",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="openpayprofile",
            name="stripe_publishable_key",
            field=core.fields.SigilShortAutoField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="openpayprofile",
            name="stripe_secret_key",
            field=core.fields.SigilShortAutoField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="openpayprofile",
            name="stripe_webhook_secret",
            field=core.fields.SigilShortAutoField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="openpayprofile",
            name="default_processor",
            field=models.CharField(
                choices=[
                    ("openpay", "OpenPay"),
                    ("paypal", "PayPal"),
                    ("stripe", "Stripe"),
                ],
                default="openpay",
                max_length=20,
            ),
        ),
    ]
