# Generated by Django 5.2.8 on 2025-11-20 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0112_remove_constellation_udp_periodic_task"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Todo",
        ),
    ]
