# Generated by Django 5.2.8 on 2025-11-20 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0113_delete_todo"),
        ("core", "0113_rfid_expiry_date"),
    ]

    operations = []
