# Generated by Django 5.2.8 on 2025-11-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0116_admincommandresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeraccount",
            name="odoo_customer",
            field=models.JSONField(
                blank=True,
                help_text="Selected customer from Odoo (id, name, and contact details)",
                null=True,
            ),
        ),
    ]
