# Generated by Django 5.2.8 on 2025-11-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0117_customeraccount_odoo_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="require_2fa",
            field=models.BooleanField(
                default=False,
                help_text="Require both a password and authenticator code to sign in.",
                verbose_name="require 2FA",
            ),
        ),
    ]
