# Generated by Django 5.2.8 on 2025-11-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0118_user_require_2fa"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="temporary_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Automatically deactivate this account after the selected date and time.",
                null=True,
            ),
        ),
    ]
