# Generated by Django 5.2.8 on 2025-11-29 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0122_delete_publicwifiaccess"),
        ("core", "0122_delete_socialprofile"),
    ]

    operations = []
