# Generated by Django 5.2.11 on 2026-02-24 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cards", "0007_alter_rfidattempt_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="NFT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "token_id",
                    models.CharField(
                        help_text="Unique token identifier from the NFT source.",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional human-friendly NFT name.",
                        max_length=255,
                    ),
                ),
                (
                    "payload",
                    models.BinaryField(
                        blank=True,
                        default=bytes,
                        help_text="Raw NFT payload bytes that can be written onto an RFID card.",
                    ),
                ),
                (
                    "payload_mime_type",
                    models.CharField(
                        default="application/octet-stream",
                        help_text="MIME type for the payload bytes.",
                        max_length=127,
                    ),
                ),
            ],
            options={
                "ordering": ("token_id",),
            },
        ),
        migrations.CreateModel(
            name="RFIDBoundIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "identity_key",
                    models.CharField(
                        help_text="Stable identity key independent from the physical card RFID.",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "card_payload",
                    models.BinaryField(
                        blank=True,
                        default=bytes,
                        help_text="Bytes intended to be stored directly in the target RFID card.",
                    ),
                ),
                (
                    "payload_written_to_card",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether card_payload was written to the physical card.",
                    ),
                ),
                ("last_transferred_on", models.DateTimeField(blank=True, null=True)),
                (
                    "current_rfid",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current card carrying this identity.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nft_identities",
                        to="cards.rfid",
                    ),
                ),
                (
                    "nft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bound_identities",
                        to="nfts.nft",
                    ),
                ),
            ],
            options={
                "ordering": ("identity_key",),
            },
        ),
        migrations.CreateModel(
            name="NFTTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("actor", models.CharField(blank=True, default="", max_length=255)),
                ("transferred_on", models.DateTimeField(auto_now_add=True)),
                (
                    "from_rfid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nft_transfers_from",
                        to="cards.rfid",
                    ),
                ),
                (
                    "to_rfid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nft_transfers_to",
                        to="cards.rfid",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="nfts.rfidboundidentity",
                    ),
                ),
            ],
            options={
                "ordering": ("-transferred_on",),
            },
        ),
    ]
