# Generated by Django 5.2.11 on 2026-02-24 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nfts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nft",
            options={
                "ordering": ("token_id",),
                "verbose_name": "NFT",
                "verbose_name_plural": "NFTs",
            },
        ),
        migrations.AlterModelOptions(
            name="nfttransfer",
            options={
                "ordering": ("-transferred_on",),
                "verbose_name": "NFT RFID transfer",
                "verbose_name_plural": "NFT RFID transfers",
            },
        ),
        migrations.AlterModelOptions(
            name="rfidboundidentity",
            options={
                "ordering": ("identity_key",),
                "verbose_name": "RFID-bound NFT identity",
                "verbose_name_plural": "RFID-bound NFT identities",
            },
        ),
    ]
