# Generated by Django 5.2.11 on 2026-02-24 21:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BluetoothAdapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="hci0", max_length=64, unique=True)),
                ("powered", models.BooleanField(default=False)),
                ("discoverable", models.BooleanField(default=False)),
                ("pairable", models.BooleanField(default=False)),
                ("address", models.CharField(blank=True, default="", max_length=32)),
                ("alias", models.CharField(blank=True, default="", max_length=255)),
                (
                    "last_checked_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="BluetoothDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("alias", models.CharField(blank=True, default="", max_length=255)),
                ("icon", models.CharField(blank=True, default="", max_length=100)),
                ("paired", models.BooleanField(default=False)),
                ("trusted", models.BooleanField(default=False)),
                ("blocked", models.BooleanField(default=False)),
                ("connected", models.BooleanField(default=False)),
                ("rssi", models.IntegerField(blank=True, null=True)),
                ("uuids", models.JSONField(blank=True, default=list)),
                (
                    "first_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_registered", models.BooleanField(default=False)),
                ("registered_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "adapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="bluetooth.bluetoothadapter",
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_bluetooth_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-last_seen_at", "address"),
            },
        ),
    ]
