# Generated by Django 5.2.11 on 2026-02-24 22:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bluetooth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bluetoothdevice",
            name="last_seen_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
