# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIExplorer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "base_url",
                    models.URLField(
                        help_text="Base URL for this API, such as https://api.example.com/v1.",
                        max_length=500,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "API Explorer",
                "verbose_name_plural": "API Explorers",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ResourceMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_name", models.CharField(max_length=150)),
                (
                    "resource_path",
                    models.CharField(
                        help_text="Relative path, e.g. /users/{id}.", max_length=255
                    ),
                ),
                (
                    "http_method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                        ],
                        max_length=10,
                    ),
                ),
                ("request_structure", models.JSONField(blank=True, default=dict)),
                ("response_structure", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "api",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_methods",
                        to="apis.apiexplorer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource Method",
                "verbose_name_plural": "Resource Methods",
                "ordering": (
                    "api__name",
                    "resource_path",
                    "http_method",
                    "operation_name",
                ),
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "api",
                            "resource_path",
                            "http_method",
                            "operation_name",
                        ),
                        name="apis_resource_method_unique_operation",
                    )
                ],
            },
        ),
    ]
