# Generated by Django 5.2.15 on 2026-07-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIExplorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('base_url', models.URLField(help_text='Base URL for this API, such as https://api.example.com/v1.', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Explorer',
                'verbose_name_plural': 'API Explorers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GeneralServiceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('token_prefix', models.CharField(db_index=True, max_length=40)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=16)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, default='', max_length=300)),
                ('claims', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'General Service Token',
                'verbose_name_plural': 'General Service Tokens',
                'ordering': ('-created_at',),
                'permissions': [('manage_general_service_tokens', 'Can manage general service token lifecycle'), ('reveal_general_service_token_secret', 'Can reveal newly created general service token secrets')],
            },
        ),
        migrations.CreateModel(
            name='GeneralServiceTokenEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('retired', 'Retired'), ('revealed', 'Secret Revealed'), ('revoked', 'Revoked')], max_length=24)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'General Service Token Event',
                'verbose_name_plural': 'General Service Token Events',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ResourceMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(max_length=150)),
                ('resource_path', models.CharField(help_text='Relative path, e.g. /users/{id}.', max_length=255)),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('request_structure', models.JSONField(blank=True, default=dict)),
                ('response_structure', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resource Method',
                'verbose_name_plural': 'Resource Methods',
                'ordering': ('api__name', 'resource_path', 'http_method', 'operation_name'),
            },
        ),
        migrations.CreateModel(
            name='ServiceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('token_prefix', models.CharField(db_index=True, max_length=24)),
                ('secret_hash', models.CharField(max_length=255)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('replaced', 'Replaced'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=16)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Token',
                'verbose_name_plural': 'Service Tokens',
                'ordering': ('-created_at',),
                'permissions': [('manage_service_tokens', 'Can manage service token lifecycle'), ('reveal_service_token_secret', 'Can reveal newly created service token secrets')],
            },
        ),
        migrations.CreateModel(
            name='ServiceTokenEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('revealed', 'Secret Revealed'), ('revoked', 'Revoked'), ('rotated', 'Rotated')], max_length=24)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Service Token Event',
                'verbose_name_plural': 'Service Token Events',
                'ordering': ('-created_at',),
            },
        ),
    ]
