# Generated by Django 5.2.15 on 2026-07-02 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apis', '0001_initial'),
        ('groups', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generalservicetoken',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_general_service_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalservicetoken',
            name='security_groups',
            field=models.ManyToManyField(blank=True, help_text='Optional SG filter. Empty means all SGs the user can access.', related_name='general_service_tokens', to='groups.securitygroup'),
        ),
        migrations.AddField(
            model_name='generalservicetoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='general_service_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalservicetokenevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_service_token_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalservicetokenevent',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='apis.generalservicetoken'),
        ),
        migrations.AddField(
            model_name='resourcemethod',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_methods', to='apis.apiexplorer'),
        ),
        migrations.AddField(
            model_name='servicetoken',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_service_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicetoken',
            name='rotated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotated_to', to='apis.servicetoken'),
        ),
        migrations.AddField(
            model_name='servicetokenevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_token_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicetokenevent',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='apis.servicetoken'),
        ),
        migrations.AddConstraint(
            model_name='resourcemethod',
            constraint=models.UniqueConstraint(fields=('api', 'resource_path', 'http_method', 'operation_name'), name='apis_resource_method_unique_operation'),
        ),
    ]
