# Generated by Django 5.2.12 on 2026-04-01 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("token_prefix", models.CharField(db_index=True, max_length=24)),
                ("secret_hash", models.CharField(max_length=255)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("replaced", "Replaced"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revoked_reason",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_service_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rotated_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rotated_to",
                        to="apis.servicetoken",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Token",
                "verbose_name_plural": "Service Tokens",
                "ordering": ("-created_at",),
                "permissions": [
                    ("manage_service_tokens", "Can manage service token lifecycle"),
                    (
                        "reveal_service_token_secret",
                        "Can reveal newly created service token secrets",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceTokenEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("revealed", "Secret Revealed"),
                            ("revoked", "Revoked"),
                            ("rotated", "Rotated"),
                        ],
                        max_length=24,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_token_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="apis.servicetoken",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Token Event",
                "verbose_name_plural": "Service Token Events",
                "ordering": ("-created_at",),
            },
        ),
    ]
