# Generated by Django 5.2.12 on 2026-04-23 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0002_servicetoken_servicetokenevent"),
        ("groups", "0003_seed_ap_user_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralServiceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("token_prefix", models.CharField(db_index=True, max_length=40)),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("retired", "Retired"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revoked_reason",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("claims", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_general_service_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "security_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Optional SG filter. Empty means all SGs the user can access.",
                        related_name="general_service_tokens",
                        to="groups.securitygroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="general_service_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "General Service Token",
                "verbose_name_plural": "General Service Tokens",
                "ordering": ("-created_at",),
                "permissions": [
                    (
                        "manage_general_service_tokens",
                        "Can manage general service token lifecycle",
                    ),
                    (
                        "reveal_general_service_token_secret",
                        "Can reveal newly created general service token secrets",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GeneralServiceTokenEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("retired", "Retired"),
                            ("revealed", "Secret Revealed"),
                            ("revoked", "Revoked"),
                        ],
                        max_length=24,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="general_service_token_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="apis.generalservicetoken",
                    ),
                ),
            ],
            options={
                "verbose_name": "General Service Token Event",
                "verbose_name_plural": "General Service Token Events",
                "ordering": ("-created_at",),
            },
        ),
    ]
