# Generated by Django 5.2.15 on 2026-09-02 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ResourceMethod",
        ),
        migrations.DeleteModel(
            name="APIExplorer",
        ),
    ]
