# Generated by Django 5.2.12 on 2026-04-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0004_generalservicetoken_status_and_expiry_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicetoken",
            name="expires_at",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="servicetoken",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("replaced", "Replaced"),
                    ("revoked", "Revoked"),
                ],
                db_index=True,
                default="active",
                max_length=16,
            ),
        ),
    ]
