# Generated by Django 5.2.11 on 2026-03-01 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0008_applicationmodel_smb_wiki_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShellScript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=255)),
                ("path", models.CharField(max_length=500, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("base", "Base shell script"),
                            ("app", "App shell script"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "managed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="App responsible for this script when kind is app.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shell_scripts",
                        to="app.application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shell script",
                "verbose_name_plural": "Shell scripts",
                "ordering": ("kind", "path"),
            },
        ),
    ]
