# Generated by Django 5.2.4 on 2025-08-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitebadge",
            name="login_image",
            field=models.URLField(
                blank=True, help_text="Optional URL for login page image"
            ),
        ),
    ]
