# Generated by Django 5.2.4 on 2025-08-09 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "path",
                    models.CharField(
                        help_text="Base path for the app, starting with /",
                        max_length=100,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apps",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "unique_together": {("site", "path")},
            },
        ),
    ]
