# Generated by Django 5.2.4 on 2025-08-10 01:45

import django.contrib.sites.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0001_initial"),
        ("website", "0002_site_is_seed_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteProxy",
            fields=[],
            options={
                "verbose_name": "Site",
                "verbose_name_plural": "Sites",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("sites.site",),
            managers=[
                ("objects", django.contrib.sites.models.SiteManager()),
            ],
        ),
    ]
