# Generated by Django 5.2.4 on 2025-08-10 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0003_site_is_seed_data"),
        ("website", "0005_alter_application_path"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="application",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="application",
            name="is_default",
        ),
        migrations.RemoveField(
            model_name="application",
            name="path",
        ),
        migrations.RemoveField(
            model_name="application",
            name="site",
        ),
        migrations.CreateModel(
            name="SiteApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        help_text="Base path for the app, starting with /",
                        max_length=100,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_applications",
                        to="website.application",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_applications",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "unique_together": {("site", "path")},
            },
        ),
    ]
