# Generated by Django 5.2.4 on 2025-08-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_remove_site_is_seed_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
