# Generated by Django 5.2.15 on 2026-07-02 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seed_data', models.BooleanField(default=False, editable=False)),
                ('is_user_data', models.BooleanField(default=False, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('file_name', models.CharField(help_text='Relative path inside the cookbooks/ folder', max_length=255)),
            ],
            options={
                'verbose_name': 'Cookbook',
                'verbose_name_plural': 'Cookbooks',
                'db_table': 'docs_cookbook',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='DocumentIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seed_data', models.BooleanField(default=False, editable=False)),
                ('is_user_data', models.BooleanField(default=False, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('doc_path', models.CharField(help_text='Relative documentation path (for example: docs/platform/overview.md or apps/docs/integrations/api.md).', max_length=255, unique=True)),
                ('listable', models.BooleanField(default=True, help_text='Allow display in Indexed Documents even when no course group is assigned.')),
            ],
            options={
                'verbose_name': 'Document index',
                'verbose_name_plural': 'Document index',
                'db_table': 'docs_document_index',
                'ordering': ['title', 'doc_path'],
            },
        ),
        migrations.CreateModel(
            name='ModelDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seed_data', models.BooleanField(default=False, editable=False)),
                ('is_user_data', models.BooleanField(default=False, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('doc_path', models.CharField(help_text='Relative documentation path (for example: docs/platform/overview.md or apps/docs/integrations/api.md).', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Model documentation',
                'verbose_name_plural': 'Model documentation',
                'db_table': 'docs_model_documentation',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='DocumentIndexAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seed_data', models.BooleanField(default=False, editable=False)),
                ('is_user_data', models.BooleanField(default=False, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('access', models.CharField(choices=[('available', 'Available'), ('recommended', 'Recommended'), ('required', 'Required'), ('restricted', 'Restricted')], max_length=16)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='docs.documentindex')),
            ],
            options={
                'verbose_name': 'Document index assignment',
                'verbose_name_plural': 'Document index assignments',
                'db_table': 'docs_document_index_assignment',
                'ordering': ['security_group__name', 'document__title', 'document__doc_path'],
            },
        ),
    ]
