# Generated by Django 5.2.15 on 2026-07-02 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('docs', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentindexassignment',
            name='security_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_assignments', to='groups.securitygroup'),
        ),
        migrations.AddField(
            model_name='modeldocumentation',
            name='models',
            field=models.ManyToManyField(blank=True, related_name='documentation_links', to='contenttypes.contenttype'),
        ),
        migrations.AddConstraint(
            model_name='documentindexassignment',
            constraint=models.UniqueConstraint(fields=('document', 'security_group'), name='docs_unique_document_security_group_assignment'),
        ),
    ]
