# Generated by Django 5.2.11 on 2026-03-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("docs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelDocumentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("title", models.CharField(max_length=255)),
                (
                    "doc_path",
                    models.CharField(
                        help_text="Relative documentation path (for example: docs/platform/overview.md or apps/docs/integrations/api.md).",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "models",
                    models.ManyToManyField(
                        blank=True,
                        related_name="documentation_links",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Model documentation",
                "verbose_name_plural": "Model documentation",
                "db_table": "docs_model_documentation",
                "ordering": ["title"],
            },
        ),
    ]
