# Generated by Django 5.2.12 on 2026-04-14 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0001_initial"),
        ("groups", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "doc_path",
                    models.CharField(
                        help_text="Relative documentation path (for example: docs/platform/overview.md or apps/docs/integrations/api.md).",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "listable",
                    models.BooleanField(
                        default=True,
                        help_text="Allow display in Indexed Documents even when no course group is assigned.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document index",
                "verbose_name_plural": "Document index",
                "db_table": "docs_document_index",
                "ordering": ["title", "doc_path"],
            },
        ),
        migrations.CreateModel(
            name="DocumentIndexAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "access",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("recommended", "Recommended"),
                            ("required", "Required"),
                            ("restricted", "Restricted"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="docs.documentindex",
                    ),
                ),
                (
                    "security_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_assignments",
                        to="groups.securitygroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document index assignment",
                "verbose_name_plural": "Document index assignments",
                "db_table": "docs_document_index_assignment",
                "ordering": [
                    "security_group__name",
                    "document__title",
                    "document__doc_path",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "security_group"),
                        name="docs_unique_document_security_group_assignment",
                    )
                ],
            },
        ),
    ]
