# Generated by Django 5.2.12 on 2026-08-24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cookbook",
        ),
        migrations.DeleteModel(
            name="DocumentIndexAssignment",
        ),
        migrations.DeleteModel(
            name="DocumentIndex",
        ),
        migrations.DeleteModel(
            name="ModelDocumentation",
        ),
    ]
