# Generated by Django 5.2.12 on 2026-04-17 16:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "team",
                    models.CharField(blank=True, max_length=255, verbose_name="Team"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Location"
                    ),
                ),
                ("summary", models.TextField(verbose_name="Summary")),
                (
                    "responsibilities",
                    models.TextField(blank=True, verbose_name="Responsibilities"),
                ),
                (
                    "requirements",
                    models.TextField(blank=True, verbose_name="Requirements"),
                ),
                ("is_public", models.BooleanField(default=True, verbose_name="Public")),
                (
                    "publish_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Publish at"
                    ),
                ),
                (
                    "close_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Close at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name": "Job posting",
                "verbose_name_plural": "Job postings",
                "ordering": ("title", "id"),
            },
        ),
        migrations.CreateModel(
            name="CVSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Full name"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=64, verbose_name="Phone"),
                ),
                (
                    "cv_file",
                    models.FileField(upload_to="jobs/cv/", verbose_name="CV file"),
                ),
                (
                    "cover_letter",
                    models.TextField(blank=True, verbose_name="Cover letter"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "job_posting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cv_submissions",
                        to="jobs.jobposting",
                        verbose_name="Job posting",
                    ),
                ),
            ],
            options={
                "verbose_name": "CV submission",
                "verbose_name_plural": "CV submissions",
                "ordering": ("-created_at", "-id"),
            },
        ),
    ]
