# Generated by Django 5.2.12 on 2026-04-18 17:24

import apps.jobs.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvsubmission",
            name="cv_file",
            field=models.FileField(
                upload_to="jobs/cv/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx"]
                    ),
                    apps.jobs.models.validate_cv_file_size,
                ],
                verbose_name="CV file",
            ),
        ),
    ]
