# Generated by Django 5.2.8 on 2025-12-06 15:03
from django.db import migrations, models
import django.db.models.deletion


def _add_feature_column(apps, schema_editor):
    table_name = "nodes_nodeservice"
    column_name = "feature_id"

    with schema_editor.connection.cursor() as cursor:
        columns = schema_editor.connection.introspection.get_table_description(
            cursor, table_name
        )

    if any(column.name == column_name for column in columns):
        return

    field = models.ForeignKey(
        "nodes.NodeFeature",
        on_delete=django.db.models.deletion.SET_NULL,
        null=True,
        blank=True,
    )
    field.set_attributes_from_name("feature")
    schema_editor.add_field(apps.get_model("services", "NodeService"), field)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nodes", "0011_netmessage_expires_at"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="NodeService",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("is_seed_data", models.BooleanField(default=False, editable=False)),
                        ("is_user_data", models.BooleanField(default=False, editable=False)),
                        ("is_deleted", models.BooleanField(default=False, editable=False)),
                        ("slug", models.SlugField(max_length=50, unique=True)),
                        ("display", models.CharField(max_length=100)),
                        (
                            "unit_template",
                            models.CharField(
                                help_text="Pattern for the systemd unit name (for example {service_name}.service).",
                                max_length=150,
                            ),
                        ),
                        (
                            "is_required",
                            models.BooleanField(
                                default=False,
                                help_text="Mark as required when the service should always be present.",
                            ),
                        ),
                        (
                            "template_path",
                            models.CharField(
                                blank=True,
                                help_text="Path to the service template stored in the repository.",
                                max_length=255,
                            ),
                        ),
                        (
                            "template_content",
                            models.TextField(
                                blank=True,
                                help_text="Stored copy of the service template for reference.",
                            ),
                        ),
                        (
                            "feature",
                            models.ForeignKey(
                                blank=True,
                                help_text="Limit this service to nodes with the selected feature.",
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="nodes.nodefeature",
                            ),
                        ),
                    ],
                    options={
                        "ordering": ["display"],
                        "verbose_name": "Node Service",
                        "verbose_name_plural": "Node Services",
                        "db_table": "nodes_nodeservice",
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(_add_feature_column, migrations.RunPython.noop)
            ],
        )
    ]
