# Generated by Django 5.2.15 on 2026-07-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('display', models.CharField(max_length=80)),
                ('unit_template', models.CharField(help_text='Systemd unit template, for example "celery-{service}" or "arthexis-usb-inventory.timer".', max_length=120)),
                ('unit_kind', models.CharField(choices=[('service', 'Service'), ('timer', 'Timer')], default='service', max_length=16)),
                ('pid_file', models.CharField(blank=True, max_length=120)),
                ('docs_path', models.CharField(blank=True, max_length=160)),
                ('activation', models.CharField(choices=[('always', 'Always enabled'), ('feature', 'Node feature'), ('lockfile', 'Lock file'), ('manual', 'Manual')], default='manual', max_length=16)),
                ('feature_slug', models.SlugField(blank=True, max_length=64)),
                ('lock_names', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Lifecycle Service',
                'verbose_name_plural': 'Lifecycle Services',
                'ordering': ['sort_order', 'display'],
            },
        ),
    ]
