# Generated by Django 5.2.11 on 2026-02-18 19:20
# ruff: noqa: RUF012

import encrypted_model_fields.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chats", "0004_alter_chatavatar_group_alter_chatavatar_user"),
        ("groups", "0003_site_operator_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvergoUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("evergo_email", models.EmailField(blank=True, max_length=254)),
                (
                    "evergo_password",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, max_length=255
                    ),
                ),
                (
                    "evergo_user_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("empresa_id", models.PositiveIntegerField(blank=True, null=True)),
                ("empresa_name", models.CharField(blank=True, max_length=255)),
                ("subempresa_id", models.PositiveIntegerField(blank=True, null=True)),
                ("subempresa_name", models.CharField(blank=True, max_length=255)),
                ("two_fa_enabled", models.BooleanField(default=False)),
                ("two_fa_authenticated", models.BooleanField(default=False)),
                (
                    "two_factor_secret",
                    encrypted_model_fields.fields.EncryptedTextField(blank=True),
                ),
                ("evergo_created_at", models.DateTimeField(blank=True, null=True)),
                ("evergo_updated_at", models.DateTimeField(blank=True, null=True)),
                ("last_login_test_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "avatar",
                    models.ForeignKey(
                        blank=True,
                        help_text="Avatar that owns this profile when not linked directly to a user or group.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="chats.chatavatar",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Security group that owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="groups.securitygroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User that owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evergo User",
                "verbose_name_plural": "Evergo Users",
            },
        ),
    ]
