# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvergoCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remote_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone_number", models.CharField(blank=True, max_length=64)),
                ("address", models.CharField(blank=True, max_length=512)),
                ("latest_so", models.CharField(blank=True, max_length=64)),
                (
                    "latest_order_updated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("refreshed_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Evergo Customer",
                "verbose_name_plural": "Evergo Customers",
                "ordering": ("-latest_order_updated_at", "name"),
            },
        ),
        migrations.CreateModel(
            name="EvergoOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remote_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, unique=True
                    ),
                ),
                ("order_number", models.CharField(blank=True, max_length=64)),
                ("prefix", models.CharField(blank=True, max_length=32)),
                ("suffix", models.CharField(blank=True, max_length=32)),
                ("uuid", models.PositiveIntegerField(blank=True, null=True)),
                ("status_id", models.PositiveIntegerField(blank=True, null=True)),
                ("status_name", models.CharField(blank=True, max_length=255)),
                ("site_id", models.PositiveIntegerField(blank=True, null=True)),
                ("site_name", models.CharField(blank=True, max_length=255)),
                ("client_id", models.PositiveIntegerField(blank=True, null=True)),
                ("client_name", models.CharField(blank=True, max_length=255)),
                ("phone_primary", models.CharField(blank=True, max_length=64)),
                ("phone_secondary", models.CharField(blank=True, max_length=64)),
                ("address_street", models.CharField(blank=True, max_length=255)),
                ("address_num_ext", models.CharField(blank=True, max_length=64)),
                ("address_num_int", models.CharField(blank=True, max_length=64)),
                (
                    "address_between_streets",
                    models.CharField(blank=True, max_length=255),
                ),
                ("address_neighborhood", models.CharField(blank=True, max_length=255)),
                ("address_municipality", models.CharField(blank=True, max_length=255)),
                ("address_city", models.CharField(blank=True, max_length=255)),
                ("address_state", models.CharField(blank=True, max_length=255)),
                ("address_postal_code", models.CharField(blank=True, max_length=32)),
                (
                    "assigned_engineer_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "assigned_engineer_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "assigned_coordinator_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "assigned_coordinator_name",
                    models.CharField(blank=True, max_length=255),
                ),
                ("has_charger", models.BooleanField(default=False)),
                ("has_vehicle", models.BooleanField(default=False)),
                ("charger_count", models.PositiveIntegerField(default=0)),
                (
                    "estimated_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("source_created_at", models.DateTimeField(blank=True, null=True)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                ("source_last_contact_at", models.DateTimeField(blank=True, null=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "validation_state",
                    models.CharField(
                        choices=[
                            ("validated", "Validated in Evergo"),
                            ("placeholder", "Temporary placeholder"),
                        ],
                        default="validated",
                        max_length=20,
                    ),
                ),
                ("refreshed_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Evergo Order",
                "verbose_name_plural": "Evergo Orders",
                "ordering": ("-source_updated_at", "-remote_id"),
            },
        ),
        migrations.CreateModel(
            name="EvergoArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="evergo/artifacts/")),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[("image", "Image"), ("pdf", "PDF")],
                        editable=False,
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="evergo.evergocustomer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evergo Artifact",
                "verbose_name_plural": "Evergo Artifacts",
                "ordering": ("created_at", "pk"),
            },
        ),
        migrations.AddField(
            model_name="evergocustomer",
            name="latest_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="evergo.evergoorder",
            ),
        ),
        migrations.CreateModel(
            name="EvergoOrderFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=64)),
                ("remote_id", models.PositiveIntegerField(blank=True, null=True)),
                ("remote_name", models.CharField(max_length=255)),
                ("local_label", models.CharField(blank=True, max_length=255)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Evergo Order Field Value",
                "verbose_name_plural": "Evergo Order Field Values",
                "unique_together": {("field_name", "remote_id")},
            },
        ),
        migrations.CreateModel(
            name="EvergoUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("evergo_email", models.EmailField(max_length=254)),
                (
                    "evergo_password",
                    encrypted_model_fields.fields.EncryptedCharField(blank=True),
                ),
                (
                    "dashboard_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "evergo_user_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("empresa_id", models.PositiveIntegerField(blank=True, null=True)),
                ("empresa_name", models.CharField(blank=True, max_length=255)),
                ("subempresa_id", models.PositiveIntegerField(blank=True, null=True)),
                ("subempresa_name", models.CharField(blank=True, max_length=255)),
                ("two_fa_enabled", models.BooleanField(default=False)),
                ("two_fa_authenticated", models.BooleanField(default=False)),
                (
                    "two_factor_secret",
                    encrypted_model_fields.fields.EncryptedTextField(blank=True),
                ),
                (
                    "two_factor_recovery_codes",
                    encrypted_model_fields.fields.EncryptedTextField(blank=True),
                ),
                (
                    "two_factor_confirmed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("evergo_created_at", models.DateTimeField(blank=True, null=True)),
                ("evergo_updated_at", models.DateTimeField(blank=True, null=True)),
                ("last_login_test_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "avatar",
                    models.ForeignKey(
                        blank=True,
                        help_text="Avatar that owns this profile when not linked directly to a user or group.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="chats.chatavatar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evergo Contractor",
                "verbose_name_plural": "Evergo Contractors",
            },
        ),
    ]
