# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("evergo", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evergouser",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User that owns this object.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evergoorder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="evergo.evergouser",
            ),
        ),
        migrations.AddField(
            model_name="evergocustomer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="evergo.evergouser",
            ),
        ),
        migrations.AddConstraint(
            model_name="evergouser",
            constraint=models.CheckConstraint(
                condition=models.Q(("evergo_email", ""), _negated=True),
                name="evergo_evergouser_email_non_empty",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="evergocustomer",
            unique_together={("user", "remote_id")},
        ),
    ]
