# Generated by Django 5.2.11 on 2026-02-22 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evergo", "0002_evergouser_two_factor_confirmed_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvergoOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remote_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("order_number", models.CharField(blank=True, max_length=64)),
                ("prefix", models.CharField(blank=True, max_length=32)),
                ("suffix", models.CharField(blank=True, max_length=32)),
                ("uuid", models.PositiveIntegerField(blank=True, null=True)),
                ("status_id", models.PositiveIntegerField(blank=True, null=True)),
                ("status_name", models.CharField(blank=True, max_length=255)),
                ("site_id", models.PositiveIntegerField(blank=True, null=True)),
                ("site_name", models.CharField(blank=True, max_length=255)),
                ("client_id", models.PositiveIntegerField(blank=True, null=True)),
                ("client_name", models.CharField(blank=True, max_length=255)),
                (
                    "assigned_engineer_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "assigned_engineer_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "assigned_coordinator_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "assigned_coordinator_name",
                    models.CharField(blank=True, max_length=255),
                ),
                ("has_charger", models.BooleanField(default=False)),
                ("has_vehicle", models.BooleanField(default=False)),
                ("charger_count", models.PositiveIntegerField(default=0)),
                (
                    "estimated_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("source_created_at", models.DateTimeField(blank=True, null=True)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("refreshed_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="evergo.evergouser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evergo Order",
                "verbose_name_plural": "Evergo Orders",
                "ordering": ("-source_updated_at", "-remote_id"),
            },
        ),
        migrations.CreateModel(
            name="EvergoOrderFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=64)),
                ("remote_id", models.PositiveIntegerField(blank=True, null=True)),
                ("remote_name", models.CharField(max_length=255)),
                ("local_label", models.CharField(blank=True, max_length=255)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Evergo Order Field Value",
                "verbose_name_plural": "Evergo Order Field Values",
                "unique_together": {("field_name", "remote_id")},
            },
        ),
    ]
