# Generated by Django 5.2.12 on 2026-04-20

from __future__ import annotations

import uuid

from django.db import migrations, models


def _populate_customer_public_ids(apps, schema_editor):
    EvergoCustomer = apps.get_model("evergo", "EvergoCustomer")
    for customer in EvergoCustomer.objects.filter(public_id__isnull=True).iterator():
        customer.public_id = uuid.uuid4()
        customer.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("evergo", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evergoartifact",
            name="display_order",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="evergocustomer",
            name="public_id",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(_populate_customer_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="evergocustomer",
            name="public_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterModelOptions(
            name="evergoartifact",
            options={
                "ordering": ("display_order", "created_at", "pk"),
                "verbose_name": "Evergo Artifact",
                "verbose_name_plural": "Evergo Artifacts",
            },
        ),
    ]
