# Generated by Django 5.2.11 on 2026-02-25 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evergo", "0005_evergoorder_address_between_streets_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evergouser",
            options={
                "verbose_name": "Evergo Contractor",
                "verbose_name_plural": "Evergo Contractors",
            },
        ),
    ]
