# Generated by Django 5.2.11 on 2026-03-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evergo", "0009_alter_evergouser_evergo_email"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="evergouser",
            constraint=models.CheckConstraint(
                condition=~models.Q(("evergo_email", "")),
                name="evergo_evergouser_email_non_empty",
            ),
        ),
    ]
