# Generated by Django 5.2.11 on 2026-03-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evergo", "0010_evergouser_email_non_empty_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evergoorder",
            name="remote_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
    ]
