# Generated by Django 5.2.4 on 2025-07-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("charger_id", models.CharField(max_length=100)),
                ("transaction_id", models.BigIntegerField()),
                ("meter_start", models.IntegerField(blank=True, null=True)),
                ("meter_stop", models.IntegerField(blank=True, null=True)),
                ("start_time", models.DateTimeField()),
                ("stop_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "unique_together": {("charger_id", "transaction_id")},
            },
        ),
    ]
