# Generated by Django 5.2.4 on 2025-07-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Charger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("charger_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("config", models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
