# Generated by Django 5.2.4 on 2025-08-07 17:28

from django.db import migrations


def create_default_simulators(apps, schema_editor):
    Simulator = apps.get_model("ocpp", "Simulator")
    Simulator.objects.get_or_create(
        name="CP1",
        defaults={"cp_path": "CP1", "host": "127.0.0.1", "ws_port": 9000},
    )
    Simulator.objects.get_or_create(
        name="CP2",
        defaults={"cp_path": "CP2", "host": "127.0.0.1", "ws_port": 9000},
    )


def remove_default_simulators(apps, schema_editor):
    Simulator = apps.get_model("ocpp", "Simulator")
    Simulator.objects.filter(name__in=["CP1", "CP2"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_simulators, remove_default_simulators),
    ]
