# Generated by Django 5.2.4 on 2025-08-11 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="charger",
            name="is_seed_data",
        ),
    ]
