# Generated by Django 5.2.4 on 2025-08-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0002_remove_charger_is_seed_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulator",
            name="duration",
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name="simulator",
            name="pre_charge_delay",
            field=models.FloatField(default=10.0, verbose_name="Delay"),
        ),
        migrations.AlterField(
            model_name="simulator",
            name="ws_port",
            field=models.IntegerField(default=8000, verbose_name="WS Port"),
        ),
    ]
