# Generated by Django 5.2.4 on 2025-07-29 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocpp', '0003_add_charger_status_fields'),
        ('ocpp', '0003_charger_require_rfid'),
    ]

    operations = [
    ]
