# Generated by Django 5.2.4 on 2025-08-12 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0003_simulator_duration_simulator_pre_charge_delay_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="transaction",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="meterreading",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="charger_id",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="transaction_id",
        ),
        migrations.AddField(
            model_name="meterreading",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meter_readings",
                to="ocpp.transaction",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="charger",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="ocpp.charger",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="rfid",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
