# Generated by Django 5.2.4 on 2025-09-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0003_charger_connector_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="charger",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="charger",
            name="console_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="charger",
            name="notify_on_charge",
            field=models.BooleanField(
                default=False,
                verbose_name="Notify On Charge",
                help_text="Send a net message when a charging session starts.",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="metervalue",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="simulator",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
