# Generated by Django 5.2.4 on 2025-07-29 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocpp', '0004_merge'),
        ('ocpp', '0004_merge_20250728_1832'),
    ]

    operations = [
    ]
