# Generated by Django 5.2.4 on 2025-09-14 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_delete_businesspowerlead"),
        ("ocpp", "0004_user_data_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[],
            options={
                "verbose_name": "EV Brand",
                "verbose_name_plural": "EV Brands",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.brand",),
        ),
        migrations.CreateModel(
            name="EVModel",
            fields=[],
            options={
                "verbose_name": "EV Model",
                "verbose_name_plural": "EV Models",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.evmodel",),
        ),
    ]
