# Generated by Django 5.2.4 on 2025-07-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0005_merge_0004_merge_0004_merge_20250728_1832"),
    ]

    operations = [
        migrations.CreateModel(
            name="Simulator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("cp_path", models.CharField(max_length=100)),
                ("host", models.CharField(default="127.0.0.1", max_length=100)),
                ("ws_port", models.IntegerField(default=9000)),
                ("rfid", models.CharField(default="FFFFFFFF", max_length=8)),
                ("repeat", models.BooleanField(default=False)),
                ("username", models.CharField(blank=True, max_length=100)),
                ("password", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
