# Generated by Django 5.2.4 on 2025-07-29 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_account_credits_kwh_and_more"),
        ("ocpp", "0006_simulator"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="accounts.account",
            ),
        ),
    ]
