# Generated by Django 5.2.4 on 2025-08-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0006_location_remove_charger_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulator",
            name="vin",
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name="transaction",
            name="vin",
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
