# Generated by Django 5.2.4 on 2025-07-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0008_merge_0007_charger_reference_0007_transaction_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulator",
            name="ws_port",
            field=models.IntegerField(default=8000),
        ),
    ]
