# Generated by Django 5.2.4 on 2025-08-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0009_charger_temperature_charger_temperature_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="charger",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="charger",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="location",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="location",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="meterreading",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="meterreading",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="simulator",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="simulator",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
