# Generated by Django 5.2.4 on 2025-09-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0009_remove_charger_console_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="charger",
            name="last_error_code",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="charger",
            name="last_status",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="charger",
            name="last_status_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="charger",
            name="last_status_vendor_info",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
