# Generated by Django 5.2.4 on 2025-07-29 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocpp', '0009_alter_simulator_ws_port'),
        ('ocpp', '0009_charger_latitude_charger_longitude'),
    ]

    operations = [
    ]
