# Generated by Django 5.2.4 on 2025-09-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0009_remove_charger_console_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="charger",
            name="diagnostics_location",
            field=models.CharField(
                blank=True,
                help_text="Location or URI reported for the latest diagnostics upload.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="charger",
            name="diagnostics_status",
            field=models.CharField(
                blank=True,
                help_text="Most recent diagnostics status reported by the charger.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="charger",
            name="diagnostics_timestamp",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp associated with the latest diagnostics status.",
                null=True,
            ),
        ),
    ]
