# Generated by Django 5.2.4 on 2025-09-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0009_remove_charger_console_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="charger",
            name="firmware_status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Latest firmware status reported by the charger.",
                max_length=32,
                verbose_name="Firmware Status",
            ),
        ),
        migrations.AddField(
            model_name="charger",
            name="firmware_status_info",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Additional information supplied with the firmware status.",
                max_length=255,
                verbose_name="Firmware Status Details",
            ),
        ),
        migrations.AddField(
            model_name="charger",
            name="firmware_timestamp",
            field=models.DateTimeField(
                blank=True,
                help_text="When the charger reported the current firmware status.",
                null=True,
                verbose_name="Firmware Status Timestamp",
            ),
        ),
    ]
