# Generated by Django 5.2.4 on 2025-07-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0010_merge_20250728_2203"),
    ]

    operations = [
        migrations.AddField(
            model_name="charger",
            name="last_path",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
