# Generated by Django 5.2.4 on 2025-07-29 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0011_charger_last_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeterReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("connector_id", models.IntegerField(blank=True, null=True)),
                ("transaction_id", models.BigIntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField()),
                ("measurand", models.CharField(blank=True, max_length=100)),
                ("value", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit", models.CharField(blank=True, max_length=16)),
                (
                    "charger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meter_readings",
                        to="ocpp.charger",
                    ),
                ),
            ],
        ),
    ]
