# Generated by Django 5.2.4 on 2025-07-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocpp', '0012_meterreading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charger',
            name='charger_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='charger',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Location Name'),
        ),
        migrations.AlterField(
            model_name='charger',
            name='require_rfid',
            field=models.BooleanField(default=False, verbose_name='Require RFID'),
        ),
    ]
