# Generated by Django 5.2.4 on 2025-07-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0013_alter_charger_charger_id_alter_charger_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulator",
            name="interval",
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name="simulator",
            name="kwh_max",
            field=models.FloatField(default=60.0),
        ),
    ]
