# Generated by Django 5.2.4 on 2025-09-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0013_remove_charger_charger_connector_unique_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulator",
            name="ws_port",
            field=models.IntegerField(
                blank=True, default=8000, null=True, verbose_name="WS Port"
            ),
        ),
    ]
