# Generated by Django 5.2.4 on 2025-09-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0014_alter_simulator_ws_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="charger",
            name="public_display",
            field=models.BooleanField(
                default=True,
                help_text="Display this charger on the public status dashboard.",
                verbose_name="Show on Public Dashboard",
            ),
        ),
    ]
