# Generated by Django 5.2.4 on 2025-09-27 03:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_ensure_system_user_staff"),
        ("ocpp", "0020_datatransfermessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="charger",
            name="owner_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Security groups that can view this charge point.",
                related_name="owned_chargers",
                to="core.securitygroup",
            ),
        ),
        migrations.AddField(
            model_name="charger",
            name="owner_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who can view this charge point.",
                related_name="owned_chargers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
