# Generated by Django 5.2.4 on 2025-09-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0022_alter_charger_availability_request_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulator",
            name="configuration_keys",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of configurationKey entries to return for GetConfiguration calls.",
            ),
        ),
        migrations.AddField(
            model_name="simulator",
            name="configuration_unknown_keys",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Keys to include in the GetConfiguration unknownKey response.",
            ),
        ),
    ]
