# Generated by Django 5.2.7 on 2025-10-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0024_transaction_received_start_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datatransfermessage",
            name="connector_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Connector ID"
            ),
        ),
        migrations.AlterField(
            model_name="datatransfermessage",
            name="message_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Message ID"
            ),
        ),
        migrations.AlterField(
            model_name="datatransfermessage",
            name="ocpp_message_id",
            field=models.CharField(max_length=64, verbose_name="OCPP message ID"),
        ),
        migrations.AlterField(
            model_name="datatransfermessage",
            name="vendor_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Vendor ID"
            ),
        ),
    ]
