# Generated by Django 5.2.7 on 2025-10-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0025_alter_datatransfermessage_connector_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="charger",
            name="language",
            field=models.CharField(
                choices=[
                    ("es", "Spanish"),
                    ("en", "English"),
                    ("it", "Italian"),
                    ("de", "German"),
                ],
                default="es",
                help_text="Preferred language for the public landing page.",
                max_length=12,
                verbose_name="Language",
            ),
        ),
    ]
