# Generated by Django 5.2.7 on 2025-10-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0026_charger_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charger",
            name="language",
            field=models.CharField(
                choices=[
                    ("es", "Spanish (Latin America)"),
                    ("en", "English"),
                    ("it", "Italian"),
                    ("de", "German"),
                ],
                default="es",
                help_text="Preferred language for the public landing page.",
                max_length=12,
                verbose_name="Language",
            ),
        ),
    ]
