# Generated by Django 5.2.4 on 2025-10-28 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocpp', '0030_chargerconfiguration_charger_configuration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datatransfermessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Data Message', 'verbose_name_plural': 'Data Messages'},
        ),
    ]
