# Generated by Django 5.2.7 on 2025-10-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0032_chargerconfiguration_evcs_snapshot_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="contract_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("domestic", "Domestic service (Tarifa 1)"),
                    ("dac", "High consumption domestic (DAC)"),
                    ("pdbt", "General service low demand (PDBT)"),
                    ("gdbt", "General service high demand (GDBT)"),
                    ("gdmto", "General distribution medium tension (GDMTO)"),
                    ("gdmth", "General distribution medium tension hourly (GDMTH)"),
                ],
                help_text="CFE service contract type required to match energy tariff pricing.",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="zone",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Zone 1"),
                    ("1A", "Zone 1A"),
                    ("1B", "Zone 1B"),
                    ("1C", "Zone 1C"),
                    ("1D", "Zone 1D"),
                    ("1E", "Zone 1E"),
                    ("1F", "Zone 1F"),
                ],
                help_text="CFE climate zone used to select matching energy tariffs.",
                max_length=3,
                null=True,
            ),
        ),
    ]
