# Generated by Django 5.2.7 on 2025-11-01 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0025_node_ipv4_address_node_ipv6_address_and_more"),
        ("ocpp", "0034_charger_network_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="charger",
            name="forwarded_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Remote node receiving forwarded transactions.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forwarded_chargers",
                to="nodes.node",
            ),
        ),
        migrations.AddField(
            model_name="charger",
            name="forwarding_watermark",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the last forwarded transaction.",
                null=True,
            ),
        ),
    ]
