# Generated by Django 5.2.4 on 2025-11-01 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocpp', '0035_charger_forwarded_to_charger_forwarding_watermark'),
        ('ocpp', '0035_cpreservation'),
    ]

    operations = [
    ]
