# Generated by Django 5.2.7 on 2025-11-06 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0040_remove_chargerconfiguration_configuration_keys_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cpfirmwaredeployment",
            options={
                "ordering": ["-requested_at"],
                "verbose_name": "CP Firmware Deployment",
                "verbose_name_plural": "CP Firmware Deployments",
            },
        ),
    ]
