# Generated by Django 5.2.7 on 2025-11-07 01:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0041_alter_cpfirmwaredeployment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="charger",
            name="charging_profile_pending_profile",
            field=models.JSONField(
                blank=True,
                help_text="Charging profile payload awaiting confirmation from the charge point.",
                null=True,
                verbose_name="Pending Charging Profile",
            ),
        ),
        migrations.AddField(
            model_name="charger",
            name="charging_profile_request_details",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Additional details returned with the SetChargingProfile status.",
                max_length=255,
                verbose_name="Profile Request Details",
            ),
        ),
        migrations.AddField(
            model_name="charger",
            name="charging_profile_request_status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Latest status reported by the charge point for a SetChargingProfile request.",
                max_length=32,
                verbose_name="Profile Request Status",
            ),
        ),
        migrations.AddField(
            model_name="charger",
            name="charging_profile_request_status_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the SetChargingProfile status was recorded.",
                null=True,
                verbose_name="Profile Status At",
            ),
        ),
        migrations.AddField(
            model_name="charger",
            name="charging_profile_requested_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When a SetChargingProfile request was last submitted.",
                null=True,
                verbose_name="Profile Requested At",
            ),
        ),
        migrations.CreateModel(
            name="ChargingProfileApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "connector_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Connector ID"
                    ),
                ),
                (
                    "ocpp_message_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="OCPP message ID"
                    ),
                ),
                ("profile_id", models.PositiveIntegerField(verbose_name="Profile ID")),
                (
                    "stack_level",
                    models.PositiveIntegerField(verbose_name="Stack level"),
                ),
                ("purpose", models.CharField(max_length=32, verbose_name="Purpose")),
                ("kind", models.CharField(max_length=32, verbose_name="Kind")),
                (
                    "recurrency_kind",
                    models.CharField(
                        blank=True, default="", max_length=16, verbose_name="Recurrency"
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Valid from"
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Valid to"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Transaction ID",
                    ),
                ),
                ("charging_schedules", models.JSONField(blank=True, default=list)),
                ("raw_profile", models.JSONField(blank=True, default=dict)),
                ("applied_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "charger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applied_charging_profiles",
                        to="ocpp.charger",
                    ),
                ),
            ],
            options={
                "verbose_name": "Charging Profile",
                "verbose_name_plural": "Charging Profiles",
                "ordering": ["-applied_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["charger", "connector_id"],
                        name="ocpp_cpapp_chg_conn_idx",
                    ),
                    models.Index(fields=["profile_id"], name="ocpp_cpapp_profile_idx"),
                ],
            },
        ),
    ]
