# Generated by Django 5.2.4 on 2025-11-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocpp', '0044_delete_brand_delete_electricvehicle_delete_evmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charger',
            name='allow_remote',
            field=models.BooleanField(default=False, help_text='Permit this charge point to receive remote commands from its manager or forwarding target.'),
        ),
        migrations.AlterField(
            model_name='charger',
            name='export_transactions',
            field=models.BooleanField(default=False, help_text="Enable to share this charge point's transactions with remote nodes or export tools. Required for CP forwarders."),
        ),
    ]
