# Generated by Django 5.2.7 on 2025-03-01 00:00
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0046_chargerlogrequest_last_status_payload_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="location",
            table="core_location",
        ),
    ]
