# Generated by Django 5.2.8 on 2025-11-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0048_location_to_core_app"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationkey",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="configurationkey",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="configurationkey",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
