# Generated by Django 5.2.8 on 2025-11-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0049_configurationkey_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cpfirmwarerequest",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="cpfirmwarerequest",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="cpfirmwarerequest",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
