# Generated by Django 5.2.8 on 2025-11-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0050_cpfirmwarerequest_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="charger",
            name="allow_insecure_local_ws",
            field=models.BooleanField(
                default=False,
                help_text="Permit this charge point to connect over an unencrypted ws:// connection when it comes from the local network.",
                verbose_name="Allow insecure local websocket",
            ),
        ),
    ]
