# Generated by Django 5.2.8 on 2025-11-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0056_update_charger_energy_units"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charger",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("es", "Spanish (Latin America)"),
                    ("en", "English"),
                    ("it", "Italian"),
                    ("de", "German"),
                ],
                default="",
                help_text="Preferred language for the public landing page.",
                max_length=12,
                verbose_name="Language",
            ),
        ),
    ]
