# Generated by Django 5.2.8 on 2025-11-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0058_charger_diagnostics_bucket"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulator",
            name="default",
            field=models.BooleanField(
                default=False, help_text="Mark this simulator as the default option."
            ),
        ),
        migrations.AddConstraint(
            model_name="simulator",
            constraint=models.UniqueConstraint(
                condition=models.Q(("default", True), ("is_deleted", False)),
                fields=("default",),
                name="unique_default_simulator",
            ),
        ),
    ]
