# Generated by Django 5.2.8 on 2025-11-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0061_set_default_cp2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulator",
            name="cp_path",
            field=models.CharField(max_length=100, verbose_name="Serial Number"),
        ),
    ]
