# Generated by Django 5.2.8 on 2025-11-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0063_charger_preferred_ocpp_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="ocpp_transaction_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Transaction identifier reported by the charge point or generated by OCPP.",
                max_length=128,
            ),
        ),
    ]
