# Generated by Django 5.2.8 on 2025-11-24 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0047_remove_roleconfigurationprofile_role_and_more"),
        ("ocpp", "0065_cpnetworkprofile_charger_network_profile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CPCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "name",
                    models.CharField(blank=True, max_length=200, verbose_name="Name"),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Certificate type"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Serial number"
                    ),
                ),
                (
                    "hash_algorithm",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Hash algorithm"
                    ),
                ),
                (
                    "issuer_name_hash",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Issuer name hash"
                    ),
                ),
                (
                    "subject_name_hash",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Subject name hash"
                    ),
                ),
                (
                    "public_key_hash",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Public key hash"
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Fingerprint"
                    ),
                ),
                (
                    "ocpp_hash_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw certificateHashData values reported by the charge point.",
                    ),
                ),
                (
                    "status",
                    models.CharField(blank=True, max_length=32, verbose_name="Status"),
                ),
                (
                    "status_info",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Status details"
                    ),
                ),
                (
                    "status_timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Status timestamp"
                    ),
                ),
                (
                    "installed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Installed at"
                    ),
                ),
                (
                    "removed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Removed at"
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last seen"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "charger",
                    models.ForeignKey(
                        blank=True,
                        help_text="Charge point that owns this certificate.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificates",
                        to="ocpp.charger",
                    ),
                ),
            ],
            options={
                "verbose_name": "CP Certificate",
                "verbose_name_plural": "CP Certificates",
                "ordering": ["charger", "certificate_type", "serial_number", "id"],
            },
        ),
        migrations.CreateModel(
            name="CPCertificateOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("action", models.CharField(max_length=64, verbose_name="Action")),
                (
                    "ocpp_message_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="OCPP message ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(blank=True, max_length=32, verbose_name="Status"),
                ),
                (
                    "status_info",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Status details"
                    ),
                ),
                (
                    "status_timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Status timestamp"
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Requested at"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed at"
                    ),
                ),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations",
                        to="ocpp.cpcertificate",
                    ),
                ),
                (
                    "charger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificate_operations",
                        to="ocpp.charger",
                        verbose_name="Charge point",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificate_operations",
                        to="nodes.node",
                        verbose_name="Node",
                    ),
                ),
            ],
            options={
                "verbose_name": "CP Certificate Operation",
                "verbose_name_plural": "CP Certificate Operations",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.AddIndex(
            model_name="cpcertificate",
            index=models.Index(
                fields=["charger", "certificate_type", "serial_number"],
                name="ocpp_cpcert_charger_09d465_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cpcertificateoperation",
            index=models.Index(
                fields=["ocpp_message_id"], name="ocpp_cpcert_ocpp_me_b7ccc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cpcertificateoperation",
            index=models.Index(
                fields=["charger", "action"], name="ocpp_cpcert_charger_aa4373_idx"
            ),
        ),
    ]
