# Generated by Django 5.2.8 on 2025-11-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0064_chargingprofiledispatch_chargingschedule_and_more"),
        ("ocpp", "0065_cpnetworkprofile_charger_network_profile_and_more"),
    ]

    operations = []
