# Generated by Django 5.2.8 on 2025-11-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0066_cpcertificate_cpcertificateoperation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cpcertificate",
            name="certificate_data",
            field=models.TextField(
                blank=True,
                help_text="PEM, base64, or hex-encoded certificate to send with InstallCertificate.",
                verbose_name="Certificate data",
            ),
        ),
    ]
