# Generated by Django 5.2.8 on 2025-11-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0068_alter_cpreservation_ocpp_message_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="simulator",
            old_name="kw_max",
            new_name="average_kwh",
        ),
        migrations.AddField(
            model_name="simulator",
            name="amperage",
            field=models.FloatField(default=90.0),
        ),
    ]
