# Generated by Django 5.2.8 on 2025-11-29 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("ocpp", "0069_rename_kw_max_simulator_average_kwh_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charger",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chargers",
                to="accounts.location",
            ),
        ),
        migrations.AlterField(
            model_name="cpreservation",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cp_reservations",
                to="accounts.customeraccount",
                verbose_name="Energy account",
            ),
        ),
        migrations.AlterField(
            model_name="cpreservation",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="accounts.location",
                verbose_name="Location",
            ),
        ),
        migrations.AlterField(
            model_name="electricvehicle",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicles",
                to="accounts.customeraccount",
            ),
        ),
        migrations.AlterField(
            model_name="rfidsessionattempt",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rfid_attempts",
                to="accounts.customeraccount",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="accounts.customeraccount",
            ),
        ),
    ]
