"""Deterministic pull-request oversight helpers."""

from __future__ import annotations

from .affinity import infer_work_profile, score_node_affinity
from .checks import (
    ADVISORY_CHECK_LABELS,
    BAD_CHECKS,
    BAD_MERGE_STATES,
    GOOD_CHECKS,
    PENDING_CHECKS,
    VERSION_SUFFIX_SEPARATORS,
    _author_login,
    _check_entry,
    _check_group_key,
    _check_name,
    _check_order_key,
    _looks_like_version_suffix,
    _normalize_dependency_name,
    _parse_dependency_title,
    _split_marker,
    _strip_version_suffix,
    _version_suffix,
    _version_suffix_match,
    check_rollup_state,
    dependency_duplicates,
    dependency_key,
    dependency_target_version,
    is_advisory_check,
    is_dependency_pr,
    readiness_gate,
)
from .hygiene import (
    README_RE,
    affected_install_shard,
    changed_files_to_test_plan,
    hygiene_report,
    render_test_plan_markdown,
)
from .reply import review_reply_summary
from .service import PR_FIELDS, CommandRunner, PullRequestOverseer
from .types import (
    AuthorPayload,
    CheckEntry,
    CheckPayload,
    CheckRollupState,
    CommandResult,
    JSONValue,
    PullRequestOverseeError,
    PullRequestPayload,
    ReadinessGateResult,
    ReviewCommentPayload,
    ReviewThreadPayload,
    _coerce_list,
    _coerce_mapping,
    _json_loads,
)
from .worktree import (
    PATCHWORK_ENV_VAR,
    PATCHWORK_METADATA,
    PATCHWORK_OWNED_NOISE,
    _git_worktree_missing_error,
    _is_reparse_point,
    _local_venv_link,
    _path_is_relative_to,
    _remove_owned_path,
    _slugify_path_segment,
    _status_is_patchwork_noise,
    _status_path,
    default_patchwork_dir,
    patchwork_worktree_path,
)

__all__ = [
    "AuthorPayload",
    "ADVISORY_CHECK_LABELS",
    "BAD_CHECKS",
    "BAD_MERGE_STATES",
    "CheckEntry",
    "CheckPayload",
    "CheckRollupState",
    "CommandResult",
    "CommandRunner",
    "GOOD_CHECKS",
    "JSONValue",
    "PATCHWORK_ENV_VAR",
    "PATCHWORK_METADATA",
    "PATCHWORK_OWNED_NOISE",
    "PENDING_CHECKS",
    "PR_FIELDS",
    "PullRequestOverseeError",
    "PullRequestOverseer",
    "PullRequestPayload",
    "README_RE",
    "ReadinessGateResult",
    "ReviewCommentPayload",
    "ReviewThreadPayload",
    "VERSION_SUFFIX_SEPARATORS",
    "_author_login",
    "_check_entry",
    "_check_group_key",
    "_check_name",
    "_check_order_key",
    "_coerce_list",
    "_coerce_mapping",
    "_git_worktree_missing_error",
    "_is_reparse_point",
    "_json_loads",
    "_local_venv_link",
    "_looks_like_version_suffix",
    "_normalize_dependency_name",
    "_parse_dependency_title",
    "_path_is_relative_to",
    "_remove_owned_path",
    "_slugify_path_segment",
    "_split_marker",
    "_status_is_patchwork_noise",
    "_status_path",
    "_strip_version_suffix",
    "_version_suffix",
    "_version_suffix_match",
    "affected_install_shard",
    "changed_files_to_test_plan",
    "check_rollup_state",
    "default_patchwork_dir",
    "dependency_duplicates",
    "dependency_key",
    "dependency_target_version",
    "hygiene_report",
    "infer_work_profile",
    "is_advisory_check",
    "is_dependency_pr",
    "patchwork_worktree_path",
    "readiness_gate",
    "render_test_plan_markdown",
    "review_reply_summary",
    "score_node_affinity",
]
