# Generated by Django 5.2.4 on 2025-08-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='arthexis', max_length=100)),
                ('description', models.CharField(default='Django-based MESH system', max_length=255)),
                ('author', models.CharField(default='Rafael J. Guillén-Osorio', max_length=100)),
                ('email', models.EmailField(default='tecnologia@gelectriic.com', max_length=254)),
                ('python_requires', models.CharField(default='>=3.10', max_length=20)),
                ('license', models.CharField(default='MIT', max_length=100)),
                ('repository_url', models.URLField(default='https://github.com/arthexis/arthexis')),
                ('homepage_url', models.URLField(default='https://arthexis.com')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('token', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Package Configuration',
                'verbose_name_plural': 'Package Configuration',
            },
        ),
        migrations.CreateModel(
            name='TestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=7)),
                ('output', models.TextField()),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
