# Generated by Django 5.2.4 on 2025-08-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0002_todo"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField(default=list)),
                ("auto_install", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
