# Generated by Django 5.2.4 on 2025-08-11 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0004_alter_seeddata_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SeedData",
        ),
    ]
