# Generated by Django 5.2.4 on 2025-08-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0005_delete_seeddata"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadmeSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(unique=True)),
                ("content", models.TextField()),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
