# Generated by Django 5.2.12 on 2026-03-27 20:33

import apps.sigils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GitHubApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("webhook_url", models.URLField(blank=True)),
                (
                    "webhook_slug",
                    models.SlugField(
                        blank=True,
                        help_text="Optional URL slug for the webhook endpoint. When provided, the full webhook URL is derived from the current site configuration.",
                        max_length=255,
                    ),
                ),
                (
                    "webhook_secret",
                    apps.sigils.fields.SigilShortAutoField(blank=True, max_length=255),
                ),
                ("webhook_events", models.JSONField(blank=True, default=list)),
                ("webhook_active", models.BooleanField(default=True)),
                (
                    "webhook_content_type",
                    models.CharField(
                        choices=[("json", "JSON"), ("form", "Form")],
                        default="json",
                        max_length=20,
                    ),
                ),
                ("webhook_insecure_ssl", models.BooleanField(default=False)),
                ("display_name", models.CharField(max_length=255)),
                ("app_id", models.PositiveBigIntegerField(unique=True)),
                ("app_slug", models.SlugField(blank=True, max_length=255)),
                ("app_url", models.URLField(blank=True)),
                ("homepage_url", models.URLField(blank=True)),
                ("callback_url", models.URLField(blank=True)),
                ("setup_url", models.URLField(blank=True)),
                ("redirect_url", models.URLField(blank=True)),
                (
                    "client_id",
                    apps.sigils.fields.SigilShortAutoField(blank=True, max_length=255),
                ),
                (
                    "client_secret",
                    apps.sigils.fields.SigilShortAutoField(blank=True, max_length=255),
                ),
                ("private_key", apps.sigils.fields.SigilLongAutoField(blank=True)),
                ("public_key", apps.sigils.fields.SigilLongAutoField(blank=True)),
                ("permissions", models.JSONField(blank=True, default=dict)),
                ("default_events", models.JSONField(blank=True, default=list)),
                (
                    "auth_method",
                    models.CharField(
                        choices=[
                            ("app", "GitHub App"),
                            ("user_token", "User Token"),
                            ("user_password", "User Password"),
                            ("temp_password", "Temporary Password"),
                        ],
                        default="app",
                        max_length=20,
                    ),
                ),
                (
                    "auth_token",
                    apps.sigils.fields.SigilShortAutoField(
                        blank=True,
                        help_text="Personal access token or OAuth token for the auth user.",
                        max_length=255,
                    ),
                ),
                (
                    "auth_password",
                    apps.sigils.fields.SigilShortAutoField(
                        blank=True,
                        help_text="Password for the auth user. Temporary passwords are permitted for the system account when configured.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub App",
                "verbose_name_plural": "GitHub Apps",
            },
        ),
        migrations.CreateModel(
            name="GitHubAppInstall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("installation_id", models.PositiveBigIntegerField()),
                ("account_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("account_login", models.CharField(blank=True, max_length=255)),
                ("target_type", models.CharField(blank=True, max_length=50)),
                ("repository_selection", models.CharField(blank=True, max_length=50)),
                ("permissions", models.JSONField(blank=True, default=dict)),
                ("events", models.JSONField(blank=True, default=list)),
                ("installed_at", models.DateTimeField(blank=True, null=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("app_version", models.CharField(blank=True, max_length=50)),
                ("app_revision", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "GitHub App Install",
                "verbose_name_plural": "GitHub App Installs",
            },
        ),
        migrations.CreateModel(
            name="GitHubEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("http_method", models.CharField(blank=True, max_length=10)),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("query_params", models.JSONField(blank=True, default=dict)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("raw_body", models.TextField(blank=True)),
                ("owner", models.CharField(blank=True, max_length=255)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("event_type", models.CharField(blank=True, max_length=255)),
                ("delivery_id", models.CharField(blank=True, max_length=255)),
                ("hook_id", models.CharField(blank=True, max_length=255)),
                ("signature", models.CharField(blank=True, max_length=255)),
                ("signature_256", models.CharField(blank=True, max_length=255)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "GitHub Event",
                "verbose_name_plural": "GitHub Events",
                "ordering": ("-received_at",),
            },
        ),
        migrations.CreateModel(
            name="GitHubRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("owner", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_private", models.BooleanField(default=False)),
                ("html_url", models.URLField(blank=True)),
                ("api_url", models.URLField(blank=True)),
                ("ssh_url", models.CharField(blank=True, max_length=255)),
                ("default_branch", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "GitHub Repository",
                "verbose_name_plural": "GitHub Repositories",
            },
        ),
        migrations.CreateModel(
            name="GitHubToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "token",
                    apps.sigils.fields.SigilShortAutoField(
                        help_text="Personal access token or OAuth token for GitHub operations.",
                        max_length=255,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "GitHub Token",
                "verbose_name_plural": "GitHub Tokens",
            },
        ),
        migrations.CreateModel(
            name="PackageRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("repository_url", models.URLField(blank=True, default="")),
                ("verify_availability", models.BooleanField(default=False)),
                ("extra_args", models.JSONField(blank=True, default=list)),
                ("token", models.CharField(blank=True, default="", max_length=255)),
                ("username", models.CharField(blank=True, default="", max_length=150)),
                ("password", models.CharField(blank=True, default="", max_length=150)),
            ],
            options={
                "verbose_name": "Package Repository",
                "verbose_name_plural": "Package Repositories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="RepositoryIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=500)),
                ("state", models.CharField(max_length=50)),
                ("html_url", models.URLField(blank=True)),
                ("api_url", models.URLField(blank=True)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Repository Issue",
                "verbose_name_plural": "Repository Issues",
                "ordering": ("-updated_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="RepositoryPullRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=500)),
                ("state", models.CharField(max_length=50)),
                ("html_url", models.URLField(blank=True)),
                ("api_url", models.URLField(blank=True)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("merged_at", models.DateTimeField(blank=True, null=True)),
                ("source_branch", models.CharField(blank=True, max_length=255)),
                ("target_branch", models.CharField(blank=True, max_length=255)),
                ("is_draft", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Repository Pull Request",
                "verbose_name_plural": "Repository Pull Requests",
                "ordering": ("-updated_at", "-created_at"),
            },
        ),
    ]
