# Generated by Django 5.2.8 on 2025-12-05 02:53

from django.db import migrations, models
from utils.migration_branches import BranchTagOperation


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        BranchTagOperation("rebuild-20251205025325", migration_label="repos.0001_initial", project_apps=('app', 'awg', 'cards', 'celery', 'chats', 'content', 'core', 'counters', 'dns', 'docs', 'emails', 'embeds', 'energy', 'flows', 'groups', 'links', 'locale', 'locals', 'maps', 'media', 'meta', 'nmcli', 'nodes', 'ocpp', 'odoo', 'pages', 'payments', 'protocols', 'rates', 'release', 'repos', 'screens', 'sigils', 'tasks', 'teams', 'users', 'vehicle')),
        migrations.CreateModel(
            name="GitHubRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("owner", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_private", models.BooleanField(default=False)),
                ("html_url", models.URLField(blank=True)),
                ("api_url", models.URLField(blank=True)),
                ("ssh_url", models.CharField(blank=True, max_length=255)),
                ("default_branch", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "GitHub Repository",
                "verbose_name_plural": "GitHub Repositories",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "name"),
                        name="unique_github_repository_owner_name",
                    )
                ],
            },
        ),
    ]
