# Generated by Django 5.2.8 on 2025-12-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("owner", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_private", models.BooleanField(default=False)),
                ("html_url", models.URLField(blank=True)),
                ("api_url", models.URLField(blank=True)),
                ("ssh_url", models.CharField(blank=True, max_length=255)),
                ("default_branch", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "Repository",
                "verbose_name_plural": "Repositories",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "name"), name="unique_repository_owner_name"
                    )
                ],
            },
        ),
    ]
