# Generated by Django 5.2.15 on 2026-07-02 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
        ('nodes', '0002_initial'),
        ('release', '0001_initial'),
        ('repos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='githubapp',
            name='auth_user',
            field=models.ForeignKey(blank=True, help_text='User to authenticate as for non-admin GitHub access or delegated operations.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='github_apps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='githubappinstall',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installs', to='repos.githubapp'),
        ),
        migrations.AddField(
            model_name='githubmonitoritem',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='repos.githubmonitortask'),
        ),
        migrations.AddConstraint(
            model_name='githubrepository',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_github_repository_owner_name'),
        ),
        migrations.AddField(
            model_name='githubmonitortask',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_tasks', to='repos.githubrepository'),
        ),
        migrations.AddField(
            model_name='githubevent',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='repos.githubrepository'),
        ),
        migrations.AddField(
            model_name='githubresponsetemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_response_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='githubtoken',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Security group that owns this object.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='groups.securitygroup'),
        ),
        migrations.AddField(
            model_name='githubtoken',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User that owns this object.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packagerepository',
            name='packages',
            field=models.ManyToManyField(blank=True, related_name='package_repositories', to='release.package'),
        ),
        migrations.AddField(
            model_name='repositoryissue',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='repos.githubrepository'),
        ),
        migrations.AddField(
            model_name='repositoryissuespamassessment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_spam_assessments', to='repos.githubevent'),
        ),
        migrations.AddField(
            model_name='repositoryissuespamassessment',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_spam_assessments', to='repos.githubrepository'),
        ),
        migrations.AddField(
            model_name='repositorypullrequest',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='repos.githubrepository'),
        ),
        migrations.AddField(
            model_name='repositoryworkassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repository_work_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repositoryworkassignment',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_work_assignments', to='nodes.node'),
        ),
        migrations.AddField(
            model_name='repositoryworkassignment',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_assignments', to='repos.githubrepository'),
        ),
        migrations.AddField(
            model_name='repositoryworknodesnapshot',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repository_work_snapshot', to='nodes.node'),
        ),
        migrations.AddIndex(
            model_name='githubappinstall',
            index=models.Index(fields=['installation_id'], name='github_install_id_idx'),
        ),
        migrations.AddIndex(
            model_name='githubappinstall',
            index=models.Index(fields=['account_login'], name='github_install_login_idx'),
        ),
        migrations.AddConstraint(
            model_name='githubappinstall',
            constraint=models.UniqueConstraint(fields=('app', 'installation_id'), name='unique_github_app_install'),
        ),
        migrations.AddIndex(
            model_name='githubmonitoritem',
            index=models.Index(fields=['status', 'queued_at'], name='repos_ghmon_status_idx'),
        ),
        migrations.AddIndex(
            model_name='githubmonitoritem',
            index=models.Index(fields=['task', 'issue_number'], name='repos_ghmon_issue_idx'),
        ),
        migrations.AddIndex(
            model_name='githubmonitoritem',
            index=models.Index(fields=['target_type', 'status'], name='repos_ghmon_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='githubmonitoritem',
            constraint=models.UniqueConstraint(fields=('task', 'issue_number'), name='unique_github_monitor_item_issue'),
        ),
        migrations.AddIndex(
            model_name='githubevent',
            index=models.Index(fields=['event_type'], name='github_event_type_idx'),
        ),
        migrations.AddIndex(
            model_name='githubevent',
            index=models.Index(fields=['delivery_id'], name='github_delivery_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='githubresponsetemplate',
            constraint=models.UniqueConstraint(fields=('user', 'label'), name='unique_github_response_template_label_per_user'),
        ),
        migrations.AddConstraint(
            model_name='githubtoken',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', True), ('user__isnull', False)), fields=('user',), name='unique_github_token_user'),
        ),
        migrations.AddConstraint(
            model_name='repositoryissue',
            constraint=models.UniqueConstraint(fields=('repository', 'number'), name='unique_issue_per_repository'),
        ),
        migrations.AddIndex(
            model_name='repositoryissuespamassessment',
            index=models.Index(fields=['is_spam', 'processed_at'], name='repo_issue_spam_idx'),
        ),
        migrations.AddIndex(
            model_name='repositoryissuespamassessment',
            index=models.Index(fields=['issue_author'], name='repo_issue_spam_author_idx'),
        ),
        migrations.AddConstraint(
            model_name='repositoryissuespamassessment',
            constraint=models.UniqueConstraint(fields=('repository', 'issue_number', 'delivery_id'), name='unique_issue_spam_assessment_delivery'),
        ),
        migrations.AddConstraint(
            model_name='repositorypullrequest',
            constraint=models.UniqueConstraint(fields=('repository', 'number'), name='unique_pull_request_per_repository'),
        ),
        migrations.AddConstraint(
            model_name='repositoryworkassignment',
            constraint=models.UniqueConstraint(fields=('repository', 'target_type', 'number', 'node'), name='unique_repository_work_assignment_per_node'),
        ),
    ]
