# Generated by Django 5.2.12 on 2026-04-20 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repos", "0003_githubresponsetemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepositoryIssueSpamAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("issue_number", models.PositiveIntegerField()),
                ("issue_title", models.CharField(blank=True, max_length=500)),
                ("issue_body", models.TextField(blank=True)),
                ("issue_author", models.CharField(blank=True, max_length=255)),
                ("action", models.CharField(blank=True, max_length=50)),
                (
                    "score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                ("is_spam", models.BooleanField(default=False)),
                ("reasons", models.JSONField(blank=True, default=list)),
                ("delivery_id", models.CharField(blank=True, max_length=255)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issue_spam_assessments",
                        to="repos.githubevent",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_spam_assessments",
                        to="repos.githubrepository",
                    ),
                ),
            ],
            options={
                "verbose_name": "Repository Issue Spam Assessment",
                "verbose_name_plural": "Repository Issue Spam Assessments",
                "ordering": ("-processed_at",),
                "indexes": [
                    models.Index(
                        fields=["is_spam", "processed_at"], name="repo_issue_spam_idx"
                    ),
                    models.Index(
                        fields=["issue_author"], name="repo_issue_spam_author_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("repository", "issue_number", "delivery_id"),
                        name="unique_issue_spam_assessment_delivery",
                    )
                ],
            },
        ),
    ]
