# Generated by Django 5.2.12 on 2026-05-06 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0004_repositoryissuespamassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubMonitorTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seed_data', models.BooleanField(default=False, editable=False)),
                ('is_user_data', models.BooleanField(default=False, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.SlugField(max_length=120, unique=True)),
                ('display', models.CharField(max_length=160)),
                ('enabled', models.BooleanField(default=True)),
                ('issue_title', models.CharField(max_length=255)),
                ('issue_marker', models.CharField(blank=True, help_text='Optional marker that must be present in the issue body.', max_length=255)),
                ('terminal_title', models.CharField(default='Arthexis GitHub Monitor', max_length=160)),
                ('terminal_state_key', models.SlugField(max_length=120, unique=True)),
                ('codex_command', models.CharField(default='codex', max_length=255)),
                ('prompt_template', models.TextField(blank=True)),
                ('skill_slugs', models.JSONField(blank=True, default=list)),
                ('inactivity_timeout_minutes', models.PositiveSmallIntegerField(default=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_tasks', to='repos.githubrepository')),
            ],
            options={
                'verbose_name': 'GitHub Monitor Task',
                'verbose_name_plural': 'GitHub Monitor Tasks',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GitHubMonitorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seed_data', models.BooleanField(default=False, editable=False)),
                ('is_user_data', models.BooleanField(default=False, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('issue_number', models.PositiveIntegerField()),
                ('issue_title', models.CharField(max_length=500)),
                ('issue_url', models.URLField(blank=True, max_length=500)),
                ('issue_state', models.CharField(default='open', max_length=50)),
                ('issue_body', models.TextField(blank=True)),
                ('prompt', models.TextField(blank=True)),
                ('terminal_state_key', models.SlugField(blank=True, max_length=120)),
                ('terminal_pid_file', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('active', 'Active'), ('completed', 'Completed'), ('closed', 'Closed'), ('timed_out', 'Timed out'), ('failed', 'Failed'), ('dismissed', 'Dismissed')], default='queued', max_length=32)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('launched_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_message', models.TextField(blank=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='repos.githubmonitortask')),
            ],
            options={
                'verbose_name': 'GitHub Monitor Item',
                'verbose_name_plural': 'GitHub Monitor Items',
                'ordering': ('queued_at', 'id'),
                'indexes': [models.Index(fields=['status', 'queued_at'], name='repos_ghmon_status_idx'), models.Index(fields=['task', 'issue_number'], name='repos_ghmon_issue_idx')],
                'constraints': [models.UniqueConstraint(fields=('task', 'issue_number'), name='unique_github_monitor_item_issue')],
            },
        ),
    ]
