# Generated by Django 5.2.10 on 2026-01-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repos", "0005_githubapp_githubappinstall"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubapp",
            name="webhook_slug",
            field=models.SlugField(
                blank=True,
                help_text="Optional URL slug for the webhook endpoint. When provided, the full webhook URL is derived from the current site configuration.",
                max_length=255,
            ),
        ),
    ]
