# Generated by Django 5.2.11 on 2026-02-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegisteredExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "extension",
                    models.CharField(
                        help_text="Operating system extension including dot (for example: .pdf).",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Administrative notes. Use filename sigil in command args to inject the opened file path.",
                    ),
                ),
                (
                    "django_command",
                    models.CharField(
                        help_text="Django management command to execute.",
                        max_length=128,
                    ),
                ),
                (
                    "extra_args",
                    models.TextField(
                        blank=True,
                        help_text="Optional arguments (shell-style) for the command. The filename sigil will be replaced with the opened file path.",
                    ),
                ),
                (
                    "filename_sigil",
                    models.CharField(
                        default="{filename}",
                        help_text="Sigil token replaced with the opened file path in extra args.",
                        max_length=64,
                    ),
                ),
                (
                    "filename_as_input",
                    models.BooleanField(
                        default=False,
                        help_text="Pass the opened file path as command stdin instead of replacing the filename sigil.",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Registered Extension",
                "verbose_name_plural": "Registered Extensions",
                "ordering": ("extension",),
            },
        ),
    ]
