# Generated by Django 5.2.12 on 2026-03-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DesktopShortcut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                (
                    "desktop_filename",
                    models.CharField(
                        help_text="Filename used in the desktop folder (without .desktop suffix).",
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("comment", models.CharField(blank=True, max_length=255)),
                (
                    "launch_mode",
                    models.CharField(
                        choices=[("url", "URL")],
                        default="url",
                        help_text="Desktop shortcuts always open a URL through the browser helper.",
                        max_length=16,
                    ),
                ),
                (
                    "target_url",
                    models.CharField(
                        blank=True,
                        help_text="HTTP or HTTPS URL to open. Supports the {port} placeholder.",
                        max_length=512,
                    ),
                ),
                (
                    "install_location",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop"),
                            ("applications", "Applications menu"),
                            ("both", "Desktop and Applications menu"),
                        ],
                        default="desktop",
                        help_text="Where the .desktop launcher file should be installed.",
                        max_length=16,
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        help_text="Existing OS icon name to reference (for example web-browser).",
                        max_length=128,
                    ),
                ),
                (
                    "icon_base64",
                    models.TextField(
                        blank=True,
                        help_text="Base64 encoded icon payload written to ~/.local/share/icons.",
                    ),
                ),
                (
                    "icon_extension",
                    models.CharField(
                        default="png",
                        help_text="Extension used when persisting base64 icon payloads.",
                        max_length=8,
                    ),
                ),
                (
                    "categories",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("terminal", models.BooleanField(default=False)),
                ("startup_notify", models.BooleanField(default=True)),
                (
                    "extra_entries",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional Desktop Entry key/value pairs.",
                    ),
                ),
                (
                    "condition_expression",
                    models.CharField(
                        blank=True,
                        help_text="Optional constrained boolean expression evaluated against context keys: has_desktop_ui, has_feature, is_staff, is_superuser, group_names.",
                        max_length=255,
                    ),
                ),
                ("require_desktop_ui", models.BooleanField(default=True)),
                ("only_staff", models.BooleanField(default=False)),
                ("only_superuser", models.BooleanField(default=False)),
                ("is_enabled", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=100)),
            ],
            options={
                "verbose_name": "Desktop Shortcut",
                "verbose_name_plural": "Desktop Shortcuts",
                "ordering": ("sort_order", "name", "slug"),
            },
        ),
        migrations.CreateModel(
            name="RegisteredExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "extension",
                    models.CharField(
                        help_text="Operating system extension including dot (for example: .pdf).",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Administrative notes."),
                ),
                (
                    "archived_runtime_mapping",
                    models.JSONField(blank=True, default=dict, editable=False),
                ),
                ("is_enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Registered Extension",
                "verbose_name_plural": "Registered Extensions",
                "ordering": ("extension",),
            },
        ),
    ]
