# Generated by Django 5.2.12 on 2026-03-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("desktop", "0001_initial"),
        ("nodes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="desktopshortcut",
            name="required_features",
            field=models.ManyToManyField(blank=True, to="nodes.nodefeature"),
        ),
        migrations.AddField(
            model_name="desktopshortcut",
            name="required_groups",
            field=models.ManyToManyField(blank=True, to="auth.group"),
        ),
    ]
