# Generated by Django 5.2.8 on 2025-12-05 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
        ("nodes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentsample",
            name="node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nodes.node",
            ),
        ),
    ]
