# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
import parler.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contentsample",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contentclassification",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classifications",
                to="content.contentsample",
            ),
        ),
        migrations.AddField(
            model_name="contentclassification",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classifications",
                to="content.contenttag",
            ),
        ),
        migrations.AddField(
            model_name="contenttagtranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="content.contenttag",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contentclassifiertranslation",
            unique_together={("language_code", "master")},
        ),
        migrations.AddConstraint(
            model_name="contentsample",
            constraint=models.UniqueConstraint(
                condition=models.Q(("hash", ""), _negated=True),
                fields=("hash",),
                name="nodes_contentsample_hash_unique",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contentclassification",
            unique_together={("sample", "classifier", "tag")},
        ),
        migrations.AlterUniqueTogether(
            name="contenttagtranslation",
            unique_together={("language_code", "master")},
        ),
    ]
