# Generated by Django 5.2.12 on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_cleanup_retired_web_sampler_periodic_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentsample",
            name="method",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
