# Generated by Django 5.2.10 on 2026-01-25 18:38

import django.db.models.deletion
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content",
            "0006_remove_webrequestsampler_content_webrequestsampler_owner_exclusive_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentclassifier",
            options={
                "ordering": ["translations__label"],
                "verbose_name": "Content Classifier",
                "verbose_name_plural": "Content Classifiers",
            },
        ),
        migrations.AlterModelBases(
            name="contentclassifier",
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.AlterModelOptions(
            name="contenttag",
            options={
                "ordering": ["translations__label"],
                "verbose_name": "Content Tag",
                "verbose_name_plural": "Content Tags",
            },
        ),
        migrations.AlterModelBases(
            name="contenttag",
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.AlterModelOptions(
            name="webrequestsampler",
            options={
                "ordering": ["translations__label"],
                "verbose_name": "Web Request Sampler",
                "verbose_name_plural": "Web Request Samplers",
            },
        ),
        migrations.AlterModelBases(
            name="webrequestsampler",
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.AlterModelBases(
            name="webrequeststep",
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.RemoveField(
            model_name="contentclassifier",
            name="label",
        ),
        migrations.RemoveField(
            model_name="contenttag",
            name="label",
        ),
        migrations.RemoveField(
            model_name="webrequestsampler",
            name="description",
        ),
        migrations.RemoveField(
            model_name="webrequestsampler",
            name="label",
        ),
        migrations.RemoveField(
            model_name="webrequeststep",
            name="name",
        ),
        migrations.CreateModel(
            name="ContentClassifierTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("label", models.CharField(max_length=150)),
                (
                    "master",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="content.contentclassifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Classifier Translation",
                "db_table": "content_contentclassifier_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ContentTagTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("label", models.CharField(max_length=150)),
                (
                    "master",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="content.contenttag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Tag Translation",
                "db_table": "content_contenttag_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="WebRequestSamplerTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("label", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "master",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="content.webrequestsampler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Web Request Sampler Translation",
                "db_table": "content_webrequestsampler_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="WebRequestStepTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150)),
                (
                    "master",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="content.webrequeststep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Web Request Step Translation",
                "db_table": "content_webrequeststep_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
