# Generated by Django 5.2.10 on 2026-01-25 22:25

import django.db.models.deletion
import parler.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_alter_contentclassifier_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentclassifiertranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="content.contentclassifier",
            ),
        ),
        migrations.AlterField(
            model_name="contenttagtranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="content.contenttag",
            ),
        ),
        migrations.AlterField(
            model_name="webrequestsamplertranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="content.webrequestsampler",
            ),
        ),
        migrations.AlterField(
            model_name="webrequeststeptranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="content.webrequeststep",
            ),
        ),
        migrations.AlterModelTable(
            name="contentclassifiertranslation",
            table="nodes_contentclassifier_translation",
        ),
        migrations.AlterModelTable(
            name="contenttagtranslation",
            table="nodes_contenttag_translation",
        ),
    ]
