# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QRRedirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Short, persistent slug used for QR links.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "target_url",
                    models.CharField(
                        help_text="Destination URL or absolute path.", max_length=500
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional display title for the public view.",
                        max_length=200,
                    ),
                ),
                (
                    "text_above",
                    models.TextField(
                        blank=True,
                        help_text="Optional text to show above the embedded content.",
                    ),
                ),
                (
                    "text_below",
                    models.TextField(
                        blank=True,
                        help_text="Optional text to show below the embedded content.",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Controls visibility in the public QR listing.",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "QR Redirect",
                "verbose_name_plural": "QR Redirects",
                "ordering": ("slug",),
            },
        ),
        migrations.CreateModel(
            name="QRRedirectLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("path", models.TextField(blank=True)),
                ("referer", models.TextField(blank=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "ip_address",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        validators=[django.core.validators.validate_ipv46_address],
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("assigned", "Assigned"),
                            ("closed", "Closed"),
                            ("spam", "Spam"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("target_url", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "QR Redirect Lead",
                "verbose_name_plural": "QR Redirect Leads",
            },
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "content_type",
                    models.CharField(
                        choices=[("text", "Text"), ("image", "Image")],
                        default="text",
                        max_length=5,
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(max_length=500, verbose_name="Title / Alt Text"),
                ),
                ("value", models.TextField(blank=True)),
                ("uses", models.PositiveIntegerField(default=0)),
                ("method", models.CharField(default="qr", max_length=50)),
                (
                    "validated_url_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last URL validation check.",
                        null=True,
                        verbose_name="Validated URL",
                    ),
                ),
                (
                    "validation_status",
                    models.IntegerField(
                        blank=True,
                        help_text="HTTP status code from the last URL validation attempt.",
                        null=True,
                        verbose_name="Validation Status",
                    ),
                ),
                (
                    "include_in_footer",
                    models.BooleanField(
                        default=False, verbose_name="Include in Footer"
                    ),
                ),
                (
                    "show_in_header",
                    models.BooleanField(default=False, verbose_name="Show in Header"),
                ),
                (
                    "footer_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("staff", "Staff"),
                        ],
                        default="public",
                        max_length=7,
                        verbose_name="Footer Visibility",
                    ),
                ),
                (
                    "transaction_uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name="Transaction UUID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Reference",
                "verbose_name_plural": "References",
                "db_table": "core_reference",
            },
        ),
        migrations.CreateModel(
            name="ShortURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Short, persistent slug used for shared links.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "original_url",
                    models.CharField(
                        db_index=True,
                        help_text="Original URL used when the short link was created.",
                        max_length=500,
                    ),
                ),
                (
                    "target_url",
                    models.CharField(
                        db_index=True,
                        help_text="Destination URL or absolute path.",
                        max_length=500,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Short URL",
                "verbose_name_plural": "Short URLs",
                "ordering": ("slug",),
            },
        ),
    ]
