# Generated by Django 5.2.8 on 2025-12-01 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperienceReference",
            fields=[],
            options={
                "verbose_name": "Reference",
                "verbose_name_plural": "References",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("links.reference",),
        ),
    ]
