# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0001_initial"),
        ("links", "0001_initial"),
        ("media", "0001_initial"),
        ("modules", "0002_initial"),
        ("nodes", "0001_initial"),
        ("sites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="qrredirectlead",
            name="assign_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="qrredirectlead",
            name="qr_redirect",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leads",
                to="links.qrredirect",
            ),
        ),
        migrations.AddField(
            model_name="qrredirectlead",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="application",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional application this reference belongs to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="references",
                to="app.application",
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="references",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="features",
            field=models.ManyToManyField(
                blank=True, related_name="references", to="nodes.nodefeature"
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="file_media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reference_files",
                to="media.mediafile",
                verbose_name="File",
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="footer_modules",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional module-specific footer rules. Leave blank to show in the general footer.",
                related_name="footer_references",
                to="modules.module",
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="image_media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reference_images",
                to="media.mediafile",
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="references", to="nodes.noderole"
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="sites",
            field=models.ManyToManyField(
                blank=True, related_name="references", to="sites.site"
            ),
        ),
        migrations.CreateModel(
            name="ExperienceReference",
            fields=[],
            options={
                "verbose_name": "Reference",
                "verbose_name_plural": "References",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("links.reference",),
        ),
        migrations.AddConstraint(
            model_name="reference",
            constraint=models.UniqueConstraint(
                fields=("alt_text", "value"), name="links_reference_alt_text_value_uniq"
            ),
        ),
    ]
