# Generated by Django 5.2.10 on 2026-02-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0008_shorturl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shorturl",
            name="original_url",
            field=models.CharField(
                db_index=True,
                help_text="Original URL used when the short link was created.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="shorturl",
            name="target_url",
            field=models.CharField(
                db_index=True,
                help_text="Destination URL or absolute path.",
                max_length=500,
            ),
        ),
    ]
