# Generated by Django 5.2.10 on 2026-02-02 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0008_remove_os_footer_references"),
        ("links", "0009_alter_shorturl_original_url_and_more"),
    ]

    operations = []
