# Generated by Django 5.2.10 on 2026-02-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0012_remove_sqlite_faq_reference"),
        ("modules", "0007_module_agent_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="footer_modules",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional module-specific footer rules. Leave blank to show in the general footer.",
                related_name="footer_references",
                to="modules.module",
            ),
        ),
    ]
