# Generated by Django 5.2.10 on 2026-02-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0014_remove_sqlite_faq_reference_if_exists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrredirectlead",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("assigned", "Assigned"),
                    ("closed", "Closed"),
                    ("spam", "Spam"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
