# Generated by Django 5.2.11 on 2026-02-22 23:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_applicationmodel_ocpp_wiki_url"),
        ("links", "0016_reference_application_and_seed_links"),
        ("media", "0001_initial"),
        ("modules", "0007_module_agent_notes"),
        ("nodes", "0027_update_ap_router_roles"),
        ("sites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="reference",
            constraint=models.UniqueConstraint(
                fields=("alt_text", "value"), name="links_reference_alt_text_value_uniq"
            ),
        ),
    ]
