# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("links", "0002_initial"),
        ("media", "0001_initial"),
        ("terms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationsubmission",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_registrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="registrationsubmission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registration_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="term",
            name="document_media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="term_documents",
                to="media.mediafile",
                verbose_name="Document",
            ),
        ),
        migrations.AddField(
            model_name="term",
            name="reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="terms",
                to="links.reference",
            ),
        ),
        migrations.AddField(
            model_name="term",
            name="security_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="terms",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="termacceptance",
            name="required_document_media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="term_acceptance_documents",
                to="media.mediafile",
            ),
        ),
        migrations.AddField(
            model_name="termacceptance",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="term_acceptances",
                to="terms.registrationsubmission",
            ),
        ),
        migrations.AddField(
            model_name="termacceptance",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acceptances",
                to="terms.term",
            ),
        ),
        migrations.AddField(
            model_name="termacceptance",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="term_acceptances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
