# Generated by Django 5.2.4 on 2025-09-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awg", "0002_user_data_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculatortemplate",
            name="show_in_pages",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Show in public site"
            ),
        ),
    ]
