# Generated by Django 5.2.4 on 2025-09-20 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("awg", "0003_alter_calculatortemplate_show_in_pages"),
        ("core", "0038_energytariff"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnergyTariff",
            fields=[],
            options={
                "verbose_name": "Energy Tariff",
                "verbose_name_plural": "Energy Tariffs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.energytariff",),
        ),
    ]
