# Generated by Django 5.2.4 on 2025-08-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awg', '0005_calculatortemplate_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cablesize',
            options={'verbose_name': 'Cable Size', 'verbose_name_plural': 'Cable Sizes'},
        ),
        migrations.AlterModelOptions(
            name='calculatortemplate',
            options={'verbose_name': 'Calculator Template', 'verbose_name_plural': 'Calculator Templates'},
        ),
        migrations.AlterModelOptions(
            name='conduitfill',
            options={'verbose_name': 'Conduit Fill', 'verbose_name_plural': 'Conduit Fills'},
        ),
    ]
