# Generated by Django 5.2.4 on 2025-08-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awg", "0006_alter_cablesize_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cablesize",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="cablesize",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="calculatortemplate",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="calculatortemplate",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="conduitfill",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="conduitfill",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
