# Generated by Django 5.2.8 on 2025-11-13 00:09

import django.core.validators
from django.db import migrations, models


def _fill_blank_ip(apps, schema_editor):
    PowerLead = apps.get_model("awg", "PowerLead")
    PowerLead.objects.filter(ip_address__isnull=True).update(ip_address="")


def _noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("awg", "0006_powerlead_malformed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="powerlead",
            name="ip_address",
            field=models.CharField(
                blank=True,
                max_length=45,
                validators=[django.core.validators.validate_ipv46_address],
            ),
        ),
        migrations.RunPython(_fill_blank_ip, _noop),
    ]
