# Generated by Django 5.2.12 on 2026-03-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NetworkConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("connection_id", models.CharField(max_length=255, unique=True)),
                (
                    "uuid",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "interface_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("autoconnect", models.BooleanField(default=False)),
                ("priority", models.IntegerField(blank=True, null=True)),
                ("metered", models.CharField(blank=True, default="", max_length=50)),
                (
                    "ip4_address",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("ip4_method", models.CharField(blank=True, default="", max_length=50)),
                (
                    "ip4_gateway",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("ip4_dns", models.CharField(blank=True, default="", max_length=255)),
                (
                    "ip6_address",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("ip6_method", models.CharField(blank=True, default="", max_length=50)),
                (
                    "ip6_gateway",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("ip6_dns", models.CharField(blank=True, default="", max_length=255)),
                (
                    "dhcp_client_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "dhcp_hostname",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "wireless_ssid",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "wireless_mode",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "wireless_band",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "wireless_channel",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "security_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("password", models.CharField(blank=True, default="", max_length=255)),
                (
                    "mac_address",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("last_nmcli_check", models.DateTimeField(blank=True, null=True)),
                ("last_modified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Network Connection",
                "verbose_name_plural": "Network Connections",
                "ordering": ("connection_id",),
            },
        ),
        migrations.CreateModel(
            name="APClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "connection_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "interface_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("mac_address", models.CharField(db_index=True, max_length=64)),
                ("signal_dbm", models.IntegerField(blank=True, null=True)),
                ("rx_bitrate_mbps", models.FloatField(blank=True, null=True)),
                ("tx_bitrate_mbps", models.FloatField(blank=True, null=True)),
                ("inactive_time_ms", models.IntegerField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "AP Client",
                "verbose_name_plural": "AP Clients",
                "ordering": ("-last_seen_at", "mac_address"),
                "unique_together": {("mac_address", "interface_name")},
            },
        ),
    ]
