# Generated by Django 5.2.4 on 2025-09-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_experiencereference"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="favorite",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="landing",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="module",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="sitebadge",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
