# Generated by Django 5.2.4 on 2025-09-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_sitebadge_dark_orange"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitebadge",
            name="badge_color",
            field=models.CharField(default="#28a745", max_length=7),
        ),
    ]
