# Generated by Django 5.2.4 on 2025-09-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_userstory"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstory",
            name="github_issue_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of the GitHub issue created for this feedback.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userstory",
            name="github_issue_url",
            field=models.URLField(
                blank=True,
                help_text="Link to the GitHub issue created for this feedback.",
            ),
        ),
        migrations.AddField(
            model_name="userstory",
            name="take_screenshot",
            field=models.BooleanField(
                default=True,
                help_text="Request a screenshot capture for this feedback.",
            ),
        ),
    ]
