# Generated by Django 5.2.4 on 2025-09-27 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_userstory_github_issue_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userstory",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Internal owner for this feedback.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_user_stories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
