# Generated by Django 5.2.4 on 2025-10-05 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0016_contentclassifier_contenttag_contentclassification"),
        ("pages", "0014_arthexis_badge_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleLanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "landing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_defaults",
                        to="pages.landing",
                    ),
                ),
                (
                    "node_role",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="default_landing",
                        to="nodes.noderole",
                    ),
                ),
            ],
            options={
                "verbose_name": "Default Landing",
                "verbose_name_plural": "Default Landings",
            },
        ),
    ]
