# Generated by Django 5.2.4 on 2025-10-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0018_alter_rolelanding_options_rolelanding_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermanual",
            name="pdf_orientation",
            field=models.CharField(
                choices=[("landscape", "Landscape"), ("portrait", "Portrait")],
                default="landscape",
                help_text="Orientation used when rendering the PDF download.",
                max_length=10,
            ),
        ),
    ]
