# Generated by Django 5.2.7 on 2025-10-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0022_site_managed_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="landing",
            name="track_leads",
            field=models.BooleanField(default=False),
        ),
    ]
