# Generated by Django 5.2.7 on 2025-10-28 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0023_rename_constellation_to_watchtower"),
        ("pages", "0027_update_ocpp_landing_paths"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstory",
            name="screenshot",
            field=models.ForeignKey(
                blank=True,
                help_text="Screenshot captured for this feedback.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_stories",
                to="nodes.contentsample",
            ),
        ),
    ]
