# Generated by Django 5.2.8 on 2025-11-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0033_add_future_event_calculator_landing"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeveloperArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("summary", models.TextField(blank=True, default="")),
                ("content", models.TextField()),
                ("is_published", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Developer Article",
                "verbose_name_plural": "Developer Articles",
                "ordering": ("-created_on", "title"),
            },
        ),
    ]
