# Generated by Django 5.2.8 on 2025-11-15 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0036_odoochatbridge"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siteproxy",
            options={
                "default_permissions": (),
                "permissions": [
                    ("add_siteproxy", "Can add site"),
                    ("change_siteproxy", "Can change site"),
                    ("delete_siteproxy", "Can delete site"),
                    ("view_siteproxy", "Can view site"),
                ],
                "proxy": True,
                "verbose_name": "Site",
                "verbose_name_plural": "Sites",
            },
        ),
    ]
