# Generated by Django 5.2.8 on 2025-11-28 00:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0049_seed_site_template"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="odoochatbridge",
            options={
                "ordering": ["site__domain", "pk"],
                "verbose_name": "Odoo Chat Bridge",
                "verbose_name_plural": "Odoo Chat Bridges",
            },
        ),
        migrations.AlterModelOptions(
            name="whatsappchatbridge",
            options={
                "ordering": ["site__domain", "pk"],
                "verbose_name": "WhatsApp Chat Bridge",
                "verbose_name_plural": "WhatsApp Chat Bridges",
            },
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID"
            ),
        ),
        migrations.AlterField(
            model_name="odoochatbridge",
            name="channel_id",
            field=models.PositiveIntegerField(
                help_text="Identifier of the Odoo mail.channel that should receive forwarded messages.",
                verbose_name="Channel ID",
            ),
        ),
        migrations.AlterField(
            model_name="odoochatbridge",
            name="channel_uuid",
            field=models.CharField(
                blank=True,
                help_text="Optional UUID of the Odoo mail.channel for reference.",
                max_length=64,
                verbose_name="Channel UUID",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappchatbridge",
            name="access_token",
            field=models.CharField(
                help_text="Bearer token used to authenticate against the WhatsApp API.",
                max_length=255,
                verbose_name="Access Token",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappchatbridge",
            name="api_base_url",
            field=models.URLField(
                default="https://graph.facebook.com/v18.0",
                help_text="Base URL for the WhatsApp Cloud API.",
                verbose_name="API Base URL",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappchatbridge",
            name="phone_number_id",
            field=models.CharField(
                help_text="Identifier of the WhatsApp phone number used to send messages.",
                max_length=100,
                verbose_name="Phone Number ID",
            ),
        ),
    ]
