# Generated by Django 5.2.8 on 2025-11-29 01:08

from django.db import migrations, models


APPLICATION_ORDERS = {
    "awg": 1,
    "core": 2,
    "ocpp": 3,
    "protocols": 3,
    "nodes": 4,
    "django_celery_beat": 5,
    "teams": 6,
    "pages": 7,
}


def populate_application_orders(apps, schema_editor):
    Application = apps.get_model("pages", "Application")

    for name, order in APPLICATION_ORDERS.items():
        app, _ = Application.objects.get_or_create(name=name)
        updates = {"order": order}
        if app.order != order:
            Application.objects.filter(pk=app.pk).update(**updates)


def clear_application_orders(apps, schema_editor):
    Application = apps.get_model("pages", "Application")
    Application.objects.filter(name__in=APPLICATION_ORDERS.keys()).update(order=None)


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0050_alter_odoochatbridge_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(populate_application_orders, clear_application_orders),
    ]
