# Generated by Django 5.2.12 on 2026-04-01 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nodes", "0003_node_last_mesh_heartbeat_node_mesh_capability_flags_and_more"),
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeshMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "tenant",
                    models.CharField(
                        blank=True,
                        help_text="Tenant identifier for external mesh orchestration scope.",
                        max_length=64,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="netmesh_memberships",
                        to="nodes.node",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="netmesh_memberships",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "ordering": ["tenant", "site__domain", "node__hostname", "pk"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("node", "tenant", "site"),
                        name="netmesh_unique_membership_scope",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NodeEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("endpoint", models.CharField(max_length=255)),
                (
                    "nat_type",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "Unknown"),
                            ("OPEN", "Open"),
                            ("RESTRICTED", "Restricted"),
                            ("SYMMETRIC", "Symmetric"),
                        ],
                        default="UNKNOWN",
                        max_length=16,
                    ),
                ),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="netmesh_endpoints",
                        to="nodes.node",
                    ),
                ),
            ],
            options={
                "ordering": ["node__hostname", "-last_seen", "pk"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("node", "endpoint"), name="netmesh_node_endpoint_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NodeKeyMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("public_key", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoked", models.BooleanField(default=False)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="netmesh_keys",
                        to="nodes.node",
                    ),
                ),
            ],
            options={
                "ordering": ["node__hostname", "-created_at", "pk"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("revoked", False)),
                        fields=("node",),
                        name="netmesh_node_single_active_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PeerPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "tenant",
                    models.CharField(
                        blank=True,
                        help_text="Tenant identifier that owns this policy.",
                        max_length=64,
                    ),
                ),
                (
                    "allowed_services",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allowed service identifiers or protocol names.",
                    ),
                ),
                (
                    "destination_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="netmesh_destination_policies",
                        to="nodes.noderole",
                    ),
                ),
                (
                    "destination_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="netmesh_destination_policies",
                        to="nodes.node",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="netmesh_peer_policies",
                        to="sites.site",
                    ),
                ),
                (
                    "source_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="netmesh_source_policies",
                        to="nodes.noderole",
                    ),
                ),
                (
                    "source_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="netmesh_source_policies",
                        to="nodes.node",
                    ),
                ),
            ],
            options={
                "ordering": ["tenant", "site__domain", "pk"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant", "site", "source_node"],
                        name="netmesh_policy_scope_src_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceAdvertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("service_name", models.CharField(max_length=100)),
                ("port", models.PositiveIntegerField()),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("tcp", "TCP"),
                            ("udp", "UDP"),
                            ("http", "HTTP"),
                            ("https", "HTTPS"),
                        ],
                        default="tcp",
                        max_length=8,
                    ),
                ),
                ("route_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="netmesh_service_ads",
                        to="nodes.node",
                    ),
                ),
            ],
            options={
                "ordering": ["node__hostname", "service_name", "port", "pk"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("node", "service_name", "port", "protocol"),
                        name="netmesh_service_ad_unique",
                    )
                ],
            },
        ),
    ]
