# Generated by Django 5.2.12 on 2026-04-01 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "netmesh",
            "0002_remove_meshmembership_netmesh_unique_membership_scope_and_more",
        ),
        ("nodes", "0004_nodeenrollment_nodeenrollmentevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelayRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("code", models.SlugField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("relay_endpoint", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code", "pk"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="nodeendpoint",
            name="candidate_endpoints",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Additional direct endpoints agents should try for this node.",
            ),
        ),
        migrations.AddField(
            model_name="nodeendpoint",
            name="endpoint_priority",
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="nodeendpoint",
            name="last_successful_direct_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nodeendpoint",
            name="relay_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="nodeendpoint",
            name="relay_required",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="NodeRelayConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("relay_endpoint", models.CharField(blank=True, max_length=255)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("priority", models.PositiveSmallIntegerField(default=1000)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="netmesh_relay_configs",
                        to="nodes.node",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_configs",
                        to="netmesh.relayregion",
                    ),
                ),
            ],
            options={
                "ordering": ["node__hostname", "priority", "pk"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("node", "region"),
                        name="netmesh_node_relay_region_unique",
                    )
                ],
            },
        ),
    ]
