# Generated by Django 5.2.12 on 2026-04-01 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netmesh", "0003_relayregion_nodeendpoint_candidate_endpoints_and_more"),
        ("ocpp", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="peerpolicy",
            name="netmesh_policy_source_selector_xor",
        ),
        migrations.RemoveConstraint(
            model_name="peerpolicy",
            name="netmesh_policy_destination_selector_xor",
        ),
        migrations.AddField(
            model_name="peerpolicy",
            name="denied_services",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of denied service identifiers or protocol names.",
            ),
        ),
        migrations.AddField(
            model_name="peerpolicy",
            name="destination_station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="netmesh_destination_policies",
                to="ocpp.charger",
            ),
        ),
        migrations.AddField(
            model_name="peerpolicy",
            name="destination_tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Node tags (mesh capability flags) that must be present on the destination.",
            ),
        ),
        migrations.AddField(
            model_name="peerpolicy",
            name="source_station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="netmesh_source_policies",
                to="ocpp.charger",
            ),
        ),
        migrations.AddField(
            model_name="peerpolicy",
            name="source_tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Node tags (mesh capability flags) that must be present on the source.",
            ),
        ),
    ]
