# Generated by Django 5.2.12 on 2026-04-12 01:48

from django.db import migrations, models


def _backfill_transport_key_fields(apps, schema_editor):
    node_key_material_model = apps.get_model("netmesh", "NodeKeyMaterial")
    for key_material in node_key_material_model.objects.all().only("id", "public_key", "revoked"):
        public_key = (key_material.public_key or "").strip()
        key_material.key_type = "rsa-bootstrap" if public_key.startswith("ssh-rsa ") else "x25519"
        key_material.key_state = "retired" if key_material.revoked else "active"
        key_material.save(update_fields=["key_type", "key_state"])


class Migration(migrations.Migration):

    dependencies = [
        ("netmesh", "0007_netmeshagentstatus"),
        ("nodes", "0010_cleanup_retired_node_feature_slugs"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="nodekeymaterial",
            name="netmesh_node_single_active_key",
        ),
        migrations.AddField(
            model_name="nodekeymaterial",
            name="key_state",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("retired", "Retired"),
                    ("retiring", "Retiring"),
                ],
                default="active",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="nodekeymaterial",
            name="key_type",
            field=models.CharField(
                choices=[("rsa-bootstrap", "RSA bootstrap"), ("x25519", "X25519")],
                default="x25519",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="nodekeymaterial",
            name="key_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(
            _backfill_transport_key_fields,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="nodekeymaterial",
            constraint=models.UniqueConstraint(
                condition=models.Q(("key_state", "active")),
                fields=("node",),
                name="netmesh_node_single_active_transport_key",
            ),
        ),
    ]
