# Generated by Django 5.2.12 on 2026-04-12 02:37

import ipaddress

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_overlay_leases(apps, schema_editor):
    mesh_membership = apps.get_model("netmesh", "MeshMembership")
    mesh_overlay_lease = apps.get_model("netmesh", "MeshOverlayLease")
    cidr = getattr(settings, "NETMESH_OVERLAY_IPV4_CIDR", "100.96.0.0/16")
    pool = ipaddress.IPv4Network(cidr, strict=False)
    reserved = {pool.network_address, pool.broadcast_address}

    scope_used_ips: dict[tuple[str, int | None], set[int]] = {}

    memberships = mesh_membership.objects.filter(is_enabled=True).order_by("tenant", "site_id", "pk")
    for membership in memberships:
        scope_key = (membership.tenant, membership.site_id)
        used = scope_used_ips.setdefault(scope_key, set())
        if not used:
            used.update(
                int(ipaddress.IPv4Address(value))
                for value in mesh_overlay_lease.objects.filter(
                    tenant=membership.tenant,
                    site_id=membership.site_id,
                ).values_list("overlay_ipv4", flat=True)
            )
        address = None
        for candidate in pool.hosts():
            if candidate in reserved:
                continue
            candidate_int = int(candidate)
            if candidate_int in used:
                continue
            used.add(candidate_int)
            address = str(candidate)
            break
        if address is None:
            raise RuntimeError(f"No free overlay IPv4 addresses remain in pool {pool}.")
        mesh_overlay_lease.objects.create(
            membership_id=membership.id,
            tenant=membership.tenant,
            site_id=membership.site_id,
            overlay_ipv4=address,
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "netmesh",
            "0008_remove_nodekeymaterial_netmesh_node_single_active_key_and_more",
        ),
        ("sites", "0002_remove_custom_site_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeshOverlayLease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("tenant", models.CharField(max_length=64)),
                ("overlay_ipv4", models.GenericIPAddressField(protocol="IPv4")),
                (
                    "membership",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overlay_lease",
                        to="netmesh.meshmembership",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="netmesh_overlay_leases",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "ordering": ["tenant", "site__domain", "overlay_ipv4", "pk"],
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("tenant", ""), _negated=True),
                        name="netmesh_overlaylease_tenant_non_empty",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("site__isnull", True)),
                        fields=("tenant", "overlay_ipv4"),
                        name="netmesh_overlaylease_unique_default_scope",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("site__isnull", False)),
                        fields=("tenant", "site", "overlay_ipv4"),
                        name="netmesh_overlaylease_unique_site_scope",
                    ),
                ],
            },
        ),
        migrations.RunPython(backfill_overlay_leases, migrations.RunPython.noop),
    ]
