# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("credentials", "0001_initial"),
        ("media", "0001_initial"),
        ("nodes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sshaccount",
            name="node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ssh_accounts",
                to="nodes.node",
            ),
        ),
        migrations.AddField(
            model_name="sshaccount",
            name="private_key_media",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional private key for key-based authentication.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ssh_private_keys",
                to="media.mediafile",
                verbose_name="Private key",
            ),
        ),
        migrations.AddField(
            model_name="sshaccount",
            name="public_key_media",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional public key for key-based authentication.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ssh_public_keys",
                to="media.mediafile",
                verbose_name="Public key",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sshaccount",
            unique_together={("node", "username")},
        ),
    ]
