from __future__ import annotations

from .certificates import (
    handle_certificate_signed_error,
    handle_certificate_signed_result,
    handle_delete_certificate_error,
    handle_delete_certificate_result,
    handle_get_installed_certificate_ids_error,
    handle_get_installed_certificate_ids_result,
    handle_install_certificate_error,
    handle_install_certificate_result,
)
from .charging_profiles import (
    handle_clear_charging_profile_error,
    handle_clear_charging_profile_result,
    handle_get_charging_profiles_error,
    handle_get_charging_profiles_result,
    handle_set_charging_profile_error,
    handle_set_charging_profile_result,
)
from .core import (
    handle_change_availability_error,
    handle_change_availability_result,
    handle_change_configuration_error,
    handle_change_configuration_result,
    handle_clear_cache_error,
    handle_clear_cache_result,
    handle_clear_display_message_error,
    handle_clear_display_message_result,
    handle_customer_information_error,
    handle_customer_information_result,
    handle_data_transfer_error,
    handle_data_transfer_result,
    handle_get_base_report_error,
    handle_get_base_report_result,
    handle_get_composite_schedule_error,
    handle_get_composite_schedule_result,
    handle_get_configuration_error,
    handle_get_configuration_result,
    handle_get_diagnostics_error,
    handle_get_diagnostics_result,
    handle_get_display_messages_error,
    handle_get_display_messages_result,
    handle_get_local_list_version_result,
    handle_get_log_error,
    handle_get_log_result,
    handle_get_report_error,
    handle_get_report_result,
    handle_get_transaction_status_error,
    handle_get_transaction_status_result,
    handle_remote_start_transaction_error,
    handle_remote_start_transaction_result,
    handle_remote_stop_transaction_error,
    handle_remote_stop_transaction_result,
    handle_request_start_transaction_error,
    handle_request_start_transaction_result,
    handle_request_stop_transaction_error,
    handle_request_stop_transaction_result,
    handle_reset_error,
    handle_reset_result,
    handle_send_local_list_result,
    handle_set_display_message_error,
    handle_set_display_message_result,
    handle_trigger_message_error,
    handle_trigger_message_result,
    handle_unlock_connector_error,
    handle_unlock_connector_result,
)
from .firmware import (
    handle_publish_firmware_error,
    handle_publish_firmware_result,
    handle_unpublish_firmware_error,
    handle_unpublish_firmware_result,
    handle_update_firmware_error,
    handle_update_firmware_result,
)
from .monitoring import (
    handle_clear_variable_monitoring_result,
    handle_get_monitoring_report_result,
    handle_get_variables_result,
    handle_set_monitoring_base_error,
    handle_set_monitoring_base_result,
    handle_set_monitoring_level_error,
    handle_set_monitoring_level_result,
    handle_set_variable_monitoring_result,
    handle_set_variables_result,
)
from .network import handle_set_network_profile_error, handle_set_network_profile_result
from .reservations import (
    handle_cancel_reservation_error,
    handle_cancel_reservation_result,
    handle_reserve_now_error,
    handle_reserve_now_result,
)
from .types import CallErrorContext, CallErrorHandler, CallResultContext, CallResultHandler


CALL_RESULT_HANDLERS: dict[str, CallResultHandler] = {
    "ChangeConfiguration": handle_change_configuration_result,
    "DataTransfer": handle_data_transfer_result,
    "GetCompositeSchedule": handle_get_composite_schedule_result,
    "GetLog": handle_get_log_result,
    "SendLocalList": handle_send_local_list_result,
    "GetLocalListVersion": handle_get_local_list_version_result,
    "ClearCache": handle_clear_cache_result,
    "UpdateFirmware": handle_update_firmware_result,
    "PublishFirmware": handle_publish_firmware_result,
    "UnpublishFirmware": handle_unpublish_firmware_result,
    "GetConfiguration": handle_get_configuration_result,
    "TriggerMessage": handle_trigger_message_result,
    "ReserveNow": handle_reserve_now_result,
    "CancelReservation": handle_cancel_reservation_result,
    "RemoteStartTransaction": handle_remote_start_transaction_result,
    "RemoteStopTransaction": handle_remote_stop_transaction_result,
    "GetDiagnostics": handle_get_diagnostics_result,
    "RequestStartTransaction": handle_request_start_transaction_result,
    "RequestStopTransaction": handle_request_stop_transaction_result,
    "GetTransactionStatus": handle_get_transaction_status_result,
    "Reset": handle_reset_result,
    "ChangeAvailability": handle_change_availability_result,
    "UnlockConnector": handle_unlock_connector_result,
    "SetChargingProfile": handle_set_charging_profile_result,
    "ClearChargingProfile": handle_clear_charging_profile_result,
    "ClearDisplayMessage": handle_clear_display_message_result,
    "CustomerInformation": handle_customer_information_result,
    "GetBaseReport": handle_get_base_report_result,
    "GetChargingProfiles": handle_get_charging_profiles_result,
    "GetDisplayMessages": handle_get_display_messages_result,
    "GetReport": handle_get_report_result,
    "SetDisplayMessage": handle_set_display_message_result,
    "SetMonitoringBase": handle_set_monitoring_base_result,
    "SetMonitoringLevel": handle_set_monitoring_level_result,
    "SetNetworkProfile": handle_set_network_profile_result,
    "InstallCertificate": handle_install_certificate_result,
    "DeleteCertificate": handle_delete_certificate_result,
    "CertificateSigned": handle_certificate_signed_result,
    "GetInstalledCertificateIds": handle_get_installed_certificate_ids_result,
    "GetVariables": handle_get_variables_result,
    "SetVariables": handle_set_variables_result,
    "SetVariableMonitoring": handle_set_variable_monitoring_result,
    "ClearVariableMonitoring": handle_clear_variable_monitoring_result,
    "GetMonitoringReport": handle_get_monitoring_report_result,
}

CALL_ERROR_HANDLERS: dict[str, CallErrorHandler] = {
    "GetCompositeSchedule": handle_get_composite_schedule_error,
    "ChangeConfiguration": handle_change_configuration_error,
    "GetLog": handle_get_log_error,
    "DataTransfer": handle_data_transfer_error,
    "ClearCache": handle_clear_cache_error,
    "GetConfiguration": handle_get_configuration_error,
    "TriggerMessage": handle_trigger_message_error,
    "UpdateFirmware": handle_update_firmware_error,
    "PublishFirmware": handle_publish_firmware_error,
    "UnpublishFirmware": handle_unpublish_firmware_error,
    "ReserveNow": handle_reserve_now_error,
    "CancelReservation": handle_cancel_reservation_error,
    "RemoteStartTransaction": handle_remote_start_transaction_error,
    "RemoteStopTransaction": handle_remote_stop_transaction_error,
    "GetDiagnostics": handle_get_diagnostics_error,
    "RequestStartTransaction": handle_request_start_transaction_error,
    "RequestStopTransaction": handle_request_stop_transaction_error,
    "GetTransactionStatus": handle_get_transaction_status_error,
    "Reset": handle_reset_error,
    "ChangeAvailability": handle_change_availability_error,
    "UnlockConnector": handle_unlock_connector_error,
    "SetChargingProfile": handle_set_charging_profile_error,
    "ClearChargingProfile": handle_clear_charging_profile_error,
    "ClearDisplayMessage": handle_clear_display_message_error,
    "CustomerInformation": handle_customer_information_error,
    "GetBaseReport": handle_get_base_report_error,
    "GetChargingProfiles": handle_get_charging_profiles_error,
    "GetDisplayMessages": handle_get_display_messages_error,
    "GetReport": handle_get_report_error,
    "SetDisplayMessage": handle_set_display_message_error,
    "SetMonitoringBase": handle_set_monitoring_base_error,
    "SetMonitoringLevel": handle_set_monitoring_level_error,
    "SetNetworkProfile": handle_set_network_profile_error,
    "InstallCertificate": handle_install_certificate_error,
    "DeleteCertificate": handle_delete_certificate_error,
    "CertificateSigned": handle_certificate_signed_error,
    "GetInstalledCertificateIds": handle_get_installed_certificate_ids_error,
}


async def dispatch_call_result(
    consumer: CallResultContext,
    action: str | None,
    message_id: str,
    metadata: dict,
    payload_data: dict,
    log_key: str,
) -> bool:
    if not action:
        return False
    handler = CALL_RESULT_HANDLERS.get(action)
    if not handler:
        return False
    return await handler(consumer, message_id, metadata, payload_data, log_key)


async def dispatch_call_error(
    consumer: CallErrorContext,
    action: str | None,
    message_id: str,
    metadata: dict,
    error_code: str | None,
    description: str | None,
    details: dict | None,
    log_key: str,
) -> bool:
    if not action:
        return False
    handler = CALL_ERROR_HANDLERS.get(action)
    if not handler:
        return False
    return await handler(consumer, message_id, metadata, error_code, description, details, log_key)


__all__ = [
    "CALL_ERROR_HANDLERS",
    "CALL_RESULT_HANDLERS",
    "CallErrorContext",
    "CallErrorHandler",
    "CallResultContext",
    "CallResultHandler",
    "dispatch_call_error",
    "dispatch_call_result",
    "handle_certificate_signed_error",
    "handle_certificate_signed_result",
    "handle_change_availability_error",
    "handle_change_availability_result",
    "handle_change_configuration_error",
    "handle_change_configuration_result",
    "handle_clear_cache_error",
    "handle_clear_cache_result",
    "handle_clear_charging_profile_error",
    "handle_clear_charging_profile_result",
    "handle_clear_display_message_error",
    "handle_clear_display_message_result",
    "handle_clear_variable_monitoring_result",
    "handle_cancel_reservation_error",
    "handle_cancel_reservation_result",
    "handle_customer_information_error",
    "handle_customer_information_result",
    "handle_data_transfer_error",
    "handle_data_transfer_result",
    "handle_delete_certificate_error",
    "handle_delete_certificate_result",
    "handle_get_base_report_error",
    "handle_get_base_report_result",
    "handle_get_charging_profiles_error",
    "handle_get_charging_profiles_result",
    "handle_get_composite_schedule_error",
    "handle_get_composite_schedule_result",
    "handle_get_configuration_error",
    "handle_get_configuration_result",
    "handle_get_diagnostics_error",
    "handle_get_diagnostics_result",
    "handle_get_display_messages_error",
    "handle_get_display_messages_result",
    "handle_get_installed_certificate_ids_error",
    "handle_get_installed_certificate_ids_result",
    "handle_get_local_list_version_result",
    "handle_get_log_error",
    "handle_get_log_result",
    "handle_get_monitoring_report_result",
    "handle_get_report_error",
    "handle_get_report_result",
    "handle_get_transaction_status_error",
    "handle_get_transaction_status_result",
    "handle_get_variables_result",
    "handle_install_certificate_error",
    "handle_install_certificate_result",
    "handle_publish_firmware_error",
    "handle_publish_firmware_result",
    "handle_remote_start_transaction_error",
    "handle_remote_start_transaction_result",
    "handle_remote_stop_transaction_error",
    "handle_remote_stop_transaction_result",
    "handle_request_start_transaction_error",
    "handle_request_start_transaction_result",
    "handle_request_stop_transaction_error",
    "handle_request_stop_transaction_result",
    "handle_reset_error",
    "handle_reset_result",
    "handle_reserve_now_error",
    "handle_reserve_now_result",
    "handle_send_local_list_result",
    "handle_set_charging_profile_error",
    "handle_set_charging_profile_result",
    "handle_set_display_message_error",
    "handle_set_display_message_result",
    "handle_set_monitoring_base_error",
    "handle_set_monitoring_base_result",
    "handle_set_monitoring_level_error",
    "handle_set_monitoring_level_result",
    "handle_set_network_profile_error",
    "handle_set_network_profile_result",
    "handle_set_variable_monitoring_result",
    "handle_set_variables_result",
    "handle_trigger_message_error",
    "handle_trigger_message_result",
    "handle_unpublish_firmware_error",
    "handle_unpublish_firmware_result",
    "handle_unlock_connector_error",
    "handle_unlock_connector_result",
    "handle_update_firmware_error",
    "handle_update_firmware_result",
]
