# Generated by Django 5.2.11 on 2026-02-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selenium", "0004_migrate_to_playwright"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionCookie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Optional source label (service, node, or account).",
                        max_length=100,
                    ),
                ),
                (
                    "cookies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Cookie list compatible with Playwright BrowserContext.add_cookies.",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("stale", "Stale"),
                            ("rejected", "Rejected"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("last_validated_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_count", models.PositiveIntegerField(default=0)),
                ("last_rejection_reason", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Session Cookie",
                "verbose_name_plural": "Session Cookies",
                "indexes": [
                    models.Index(fields=["state", "expires_at"], name="sel_sc_state_exp_idx"),
                ],
            },
        ),
    ]
