# Generated by Django 5.2.7 on 2025-11-08 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nodes", "0032_remove_node_nodes_node_constellation_device_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="CPForwarder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional label used when listing this forwarder.",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable to forward eligible charge points to the remote node.",
                    ),
                ),
                (
                    "is_running",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="Indicates whether an active forwarding websocket is connected.",
                    ),
                ),
                (
                    "last_forwarded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the most recent forwarding activity.",
                        null=True,
                        verbose_name="Last forwarded at",
                    ),
                ),
                (
                    "last_status",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Summary of the last forwarding synchronization.",
                        max_length=255,
                        verbose_name="Last status",
                    ),
                ),
                (
                    "last_error",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Most recent error encountered while configuring forwarding.",
                        max_length=255,
                        verbose_name="Last error",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the forwarder last attempted to apply its configuration.",
                        null=True,
                        verbose_name="Last synced at",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_node",
                    models.ForeignKey(
                        blank=True,
                        help_text="Node providing the original charge point connection.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_forwarders",
                        to="nodes.node",
                    ),
                ),
                (
                    "target_node",
                    models.ForeignKey(
                        help_text="Remote node that will receive forwarded sessions.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_forwarders",
                        to="nodes.node",
                    ),
                ),
            ],
            options={
                "verbose_name": "CP Forwarder",
                "verbose_name_plural": "CP Forwarders",
                "ordering": ["target_node__hostname", "target_node__pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_node", "target_node"),
                        name="unique_forwarder_per_target",
                    )
                ],
            },
        ),
    ]
