# Generated by Django 5.2.4 on 2025-11-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0002_cpforwarder_forwarded_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpforwarder',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Enable to forward eligible charge points to the remote node. Charge points must also have Export transactions enabled.'),
        ),
    ]
