# Generated by Django 5.2.12 on 2026-03-10 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recipes", "0003_recipeproduct"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shortcut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("display", models.CharField(max_length=120)),
                (
                    "key_combo",
                    models.CharField(help_text="Example: CTRL+SHIFT+K", max_length=120),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("server", "Server Shortcut"),
                            ("client", "Client Shortcut"),
                        ],
                        default="client",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "use_clipboard_patterns",
                    models.BooleanField(
                        default=False,
                        help_text="Evaluate clipboard patterns in ascending priority before fallback recipe.",
                    ),
                ),
                ("clipboard_output_enabled", models.BooleanField(default=False)),
                ("keyboard_output_enabled", models.BooleanField(default=False)),
                (
                    "output_template",
                    models.TextField(
                        blank=True,
                        help_text="Optional output template; supports sigils and [ARG.*] tokens.",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        blank=True,
                        help_text="Fallback recipe when no clipboard pattern matches.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shortcuts",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ("display",),
            },
        ),
        migrations.CreateModel(
            name="ClipboardPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("display", models.CharField(max_length=120)),
                (
                    "pattern",
                    models.CharField(help_text="Python regex pattern.", max_length=255),
                ),
                ("priority", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("clipboard_output_enabled", models.BooleanField(default=False)),
                ("keyboard_output_enabled", models.BooleanField(default=False)),
                ("output_template", models.TextField(blank=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clipboard_shortcut_patterns",
                        to="recipes.recipe",
                    ),
                ),
                (
                    "shortcut",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clipboard_patterns",
                        to="shortcuts.shortcut",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "pk"),
            },
        ),
        migrations.AddConstraint(
            model_name="shortcut",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("key_combo",),
                name="shortcuts_active_key_combo_unique",
            ),
        ),
    ]
