# Generated by Codex on 2026-03-21

from __future__ import annotations

import re

from django.db import migrations, models


_ACTION = "action"
_COMMAND = "command"
_WORKFLOW = "workflow"

_APPEND_SUFFIX_PATTERN = re.compile(
    r"^result\s*=\s*kwargs\.get\('(?P<source>clipboard|keyboard|shortcut_key)'\s*,\s*''\)\s*\+\s*'(?P<suffix>.*)'\s*$"
)
_PREPEND_PREFIX_PATTERN = re.compile(
    r"^result\s*=\s*'(?P<prefix>.*)'\s*\+\s*kwargs\.get\('(?P<source>clipboard|keyboard|shortcut_key)'\s*,\s*''\)\s*$"
)


def _forward_target(recipe):
    """Map a legacy recipe record to a typed shortcut target tuple."""
    if recipe is None:
        return _ACTION, "text.static", {"text": ""}

    script = (recipe.script or "").strip()
    lowered_slug = (recipe.slug or "").lower()
    body_type = getattr(recipe, "body_type", "python")

    if lowered_slug.endswith(".md"):
        return _ACTION, "text.static", {"text": recipe.script or ""}

    match = _APPEND_SUFFIX_PATTERN.match(script)
    if match:
        return _COMMAND, "text.append_suffix", match.groupdict()

    match = _PREPEND_PREFIX_PATTERN.match(script)
    if match:
        return _COMMAND, "text.prepend_prefix", match.groupdict()

    return (
        _ACTION,
        "text.static",
        {
            "text": recipe.display,
            "legacy_recipe_slug": recipe.slug,
            "legacy_recipe_format": body_type,
        },
    )


def _reverse_script(kind, identifier, payload):
    """Recreate a runnable legacy recipe script from a typed target."""
    payload = payload if isinstance(payload, dict) else {}
    if kind == _ACTION and identifier == "text.static":
        return f"result = {str(payload.get('text') or '')!r}"
    if kind == _ACTION and identifier == "clipboard.echo":
        return "result = kwargs.get('clipboard', '')"
    if kind == _ACTION and identifier == "keyboard.echo":
        return "result = kwargs.get('keyboard', '')"
    if kind == _ACTION and identifier == "shortcut_key.echo":
        return "result = kwargs.get('shortcut_key', '')"
    if kind == _COMMAND and identifier == "text.append_suffix":
        source = payload.get("source") or "clipboard"
        suffix = repr(str(payload.get("suffix") or ""))
        return f"result = kwargs.get({source!r}, '') + {suffix}"
    if kind == _COMMAND and identifier == "text.prepend_prefix":
        source = payload.get("source") or "clipboard"
        prefix = repr(str(payload.get('prefix') or ''))
        return f"result = {prefix} + kwargs.get({source!r}, '')"
    if kind == _COMMAND and identifier == "text.replace":
        source = payload.get("source") or "clipboard"
        old = repr(str(payload.get("old") or ""))
        new = repr(str(payload.get("new") or ""))
        return f"result = kwargs.get({source!r}, '').replace({old}, {new})"
    if kind == _WORKFLOW and identifier == "text.render_template":
        template = repr(str(payload.get("template") or ""))
        return f"result = {template}"
    return f"result = {repr(str(payload))}"


def forwards(apps, schema_editor):
    """Populate typed target fields from existing recipe relations."""
    Shortcut = apps.get_model("shortcuts", "Shortcut")
    ClipboardPattern = apps.get_model("shortcuts", "ClipboardPattern")

    for shortcut in Shortcut.objects.select_related("recipe"):
        kind, identifier, payload = _forward_target(getattr(shortcut, "recipe", None))
        Shortcut.objects.filter(pk=shortcut.pk).update(
            target_kind=kind,
            target_identifier=identifier,
            target_payload=payload,
        )

    for pattern in ClipboardPattern.objects.select_related("recipe"):
        kind, identifier, payload = _forward_target(getattr(pattern, "recipe", None))
        ClipboardPattern.objects.filter(pk=pattern.pk).update(
            target_kind=kind,
            target_identifier=identifier,
            target_payload=payload,
        )


def backwards(apps, schema_editor):
    """Restore legacy recipe relations from typed shortcut targets."""
    Recipe = apps.get_model("recipes", "Recipe")
    Shortcut = apps.get_model("shortcuts", "Shortcut")
    ClipboardPattern = apps.get_model("shortcuts", "ClipboardPattern")

    for shortcut in Shortcut.objects.all():
        recipe = Recipe.objects.create(
            slug=f"shortcut-{shortcut.pk}-{shortcut.target_identifier}"[:100],
            display=f"{shortcut.display} legacy recipe",
            script=_reverse_script(shortcut.target_kind, shortcut.target_identifier, shortcut.target_payload),
        )
        Shortcut.objects.filter(pk=shortcut.pk).update(recipe=recipe)

    for pattern in ClipboardPattern.objects.select_related("shortcut"):
        recipe = Recipe.objects.create(
            slug=f"clipboard-pattern-{pattern.pk}-{pattern.target_identifier}"[:100],
            display=f"{pattern.display} legacy recipe",
            script=_reverse_script(pattern.target_kind, pattern.target_identifier, pattern.target_payload),
        )
        ClipboardPattern.objects.filter(pk=pattern.pk).update(recipe=recipe)


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_recipeproduct"),
        ("shortcuts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortcut",
            name="target_identifier",
            field=models.CharField(default="text.static", help_text="Structured action, command, or workflow identifier.", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shortcut",
            name="target_kind",
            field=models.CharField(choices=[("action", "Predefined Action"), ("command", "Structured Command"), ("workflow", "Workflow")], default="action", help_text="Typed execution target used when no clipboard pattern matches.", max_length=24),
        ),
        migrations.AddField(
            model_name="shortcut",
            name="target_payload",
            field=models.JSONField(blank=True, default=dict, help_text="Validated target parameters stored as structured JSON."),
        ),
        migrations.AddField(
            model_name="clipboardpattern",
            name="target_identifier",
            field=models.CharField(default="text.static", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clipboardpattern",
            name="target_kind",
            field=models.CharField(choices=[("action", "Predefined Action"), ("command", "Structured Command"), ("workflow", "Workflow")], default="action", max_length=24),
        ),
        migrations.AddField(
            model_name="clipboardpattern",
            name="target_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(model_name="shortcut", name="recipe"),
        migrations.RemoveField(model_name="clipboardpattern", name="recipe"),
    ]
