# Generated by Django 5.2.12 on 2026-03-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortcuts", "0002_shortcut_typed_targets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortcut",
            name="use_clipboard_patterns",
            field=models.BooleanField(
                default=False,
                help_text="Evaluate clipboard patterns in ascending priority before fallback target.",
            ),
        ),
    ]
