# Generated by Django 5.2.11 on 2026-02-23 02:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0003_site_operator_group"),
        ("recipes", "0002_recipe_body_type_alter_recipe_script"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoteAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("display", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "operation_id",
                    models.CharField(
                        help_text="OpenAPI operationId for this action.",
                        max_length=120,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Security group that owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="groups.securitygroup",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        help_text="Recipe executed when this action is invoked.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="remote_actions",
                        to="recipes.recipe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User that owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote Action",
                "verbose_name_plural": "Remote Actions",
                "ordering": ("display",),
                "constraints": [
                    models.CheckConstraint(
                        condition=(
                            models.Q(user__isnull=True, group__isnull=True)
                            | models.Q(user__isnull=False, group__isnull=True)
                            | models.Q(user__isnull=True, group__isnull=False)
                        ),
                        name="actions_remoteaction_owner_exclusive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RemoteActionToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=100)),
                ("key_prefix", models.CharField(editable=False, max_length=12)),
                (
                    "key_hash",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("expires_at", models.DateTimeField()),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User that owns this bearer token.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remote_action_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote Action Token",
                "verbose_name_plural": "Remote Action Tokens",
                "ordering": ("-created_at",),
            },
        ),
    ]
