# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("actions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stafftaskpreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_task_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboardaction",
            constraint=models.UniqueConstraint(
                fields=("content_type", "slug"),
                name="actions_dashboardaction_unique_slug_per_model",
            ),
        ),
        migrations.AddConstraint(
            model_name="stafftaskpreference",
            constraint=models.UniqueConstraint(
                fields=("user", "task"),
                name="actions_stafftaskpreference_unique_user_task",
            ),
        ),
    ]
