# Generated by Django 5.2.11 on 2026-03-04 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("recipes", "0003_recipeproduct"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100)),
                ("label", models.CharField(max_length=120)),
                (
                    "http_method",
                    models.CharField(
                        choices=[("get", "GET"), ("post", "POST")],
                        default="get",
                        max_length=8,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("admin_url", "Admin URL Name"),
                            ("absolute_url", "Absolute URL"),
                            ("recipe", "Recipe"),
                        ],
                        default="admin_url",
                        max_length=24,
                    ),
                ),
                ("admin_url_name", models.CharField(blank=True, max_length=200)),
                ("absolute_url", models.CharField(blank=True, max_length=500)),
                (
                    "caller_sigil",
                    models.CharField(
                        blank=True,
                        help_text="Optional marker passed to downstream executables.",
                        max_length=120,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Model row where this action appears on the admin dashboard.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_actions",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dashboard_actions",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Action",
                "verbose_name_plural": "Dashboard Actions",
                "ordering": ("order", "label"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "slug"),
                        name="actions_dashboardaction_unique_slug_per_model",
                    )
                ],
            },
        ),
    ]
