# Generated by Django 5.2.15 on 2026-07-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboardaction",
            name="action_name",
            field=models.CharField(
                choices=[
                    ("config", "Config"),
                    ("data", "Data"),
                    ("discover", "Discover"),
                    ("environment", "Environment"),
                    ("groups", "Groups"),
                    ("imager", "Imager"),
                    ("issues", "Issues"),
                    ("logs", "Logs"),
                    ("release", "Release"),
                    ("reports", "Reports"),
                    ("rules", "Rules"),
                    ("seed", "Seed"),
                    ("sigil", "Sigil"),
                    ("system", "System"),
                    ("tasks", "Tasks"),
                    ("upgrade", "Upgrade"),
                ],
                default="config",
                help_text="Named internal action rendered for this model row.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="stafftask",
            name="action_name",
            field=models.CharField(
                choices=[
                    ("config", "Config"),
                    ("data", "Data"),
                    ("discover", "Discover"),
                    ("environment", "Environment"),
                    ("groups", "Groups"),
                    ("imager", "Imager"),
                    ("issues", "Issues"),
                    ("logs", "Logs"),
                    ("release", "Release"),
                    ("reports", "Reports"),
                    ("rules", "Rules"),
                    ("seed", "Seed"),
                    ("sigil", "Sigil"),
                    ("system", "System"),
                    ("tasks", "Tasks"),
                    ("upgrade", "Upgrade"),
                ],
                default="config",
                max_length=50,
            ),
        ),
    ]
