# Generated by Django 5.2.11 on 2026-03-07 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0002_dashboardaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("label", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("admin_url_name", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                ("default_enabled", models.BooleanField(default=True)),
                ("staff_only", models.BooleanField(default=True)),
                ("superuser_only", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Staff Task",
                "verbose_name_plural": "Staff Tasks",
                "ordering": ("order", "label"),
            },
        ),
        migrations.CreateModel(
            name="StaffTaskPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_preferences",
                        to="actions.stafftask",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_task_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Task Preference",
                "verbose_name_plural": "Staff Task Preferences",
                "ordering": ("task__order", "task__label"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "task"),
                        name="actions_stafftaskpreference_unique_user_task",
                    )
                ],
            },
        ),
    ]
