# Generated by Django 5.2.12 on 2026-03-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0005_add_system_staff_task"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stafftask",
            options={
                "ordering": ("order", "label"),
                "verbose_name": "Suite Task",
                "verbose_name_plural": "Suite Tasks",
            },
        ),
        migrations.AlterModelOptions(
            name="stafftaskpreference",
            options={
                "ordering": ("task__order", "task__label"),
                "verbose_name": "Suite Task Preference",
                "verbose_name_plural": "Suite Task Preferences",
            },
        ),
    ]
