# Generated by Django 5.2.11 on 2026-03-09 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cdn", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cdnconfiguration",
            name="base_url",
            field=models.URLField(
                help_text="Public base URL where static assets are served from.",
                validators=[django.core.validators.URLValidator(schemes=["https"])],
            ),
        ),
        migrations.AddConstraint(
            model_name="cdnconfiguration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("provider", "aws_cloudfront"),
                        models.Q(("aws_distribution_id", ""), _negated=True),
                    ),
                    models.Q(
                        models.Q(("provider", "aws_cloudfront"), _negated=True),
                        ("aws_distribution_id", ""),
                    ),
                    _connector="OR",
                ),
                name="cdn_distribution_id_matches_provider",
            ),
        ),
    ]
