name: Feature request
description: Suggest an idea or enhancement
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing an idea! The more detail you provide, the easier it is to prioritize.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: A short description of the feature request.
      placeholder: e.g. Add bulk import for charge points
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: Describe the pain point or workflow gap.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the change you'd like to see.
      placeholder: Describe the feature, UI, or API changes.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Describe any alternatives or workarounds.
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Who benefits and how often is this needed?
      placeholder: e.g. Operations team uses this daily.
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any supporting context, mockups, or references.
