# Generated by Django 5.2.8 on 2025-12-02 02:54

import apps.base.models
import apps.sigils.fields
import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("data_path", models.CharField(blank=True, max_length=255)),
                (
                    "last_visit_ip_address",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        validators=[django.core.validators.validate_ipv46_address],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting customer accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "require_2fa",
                    models.BooleanField(
                        default=False,
                        help_text="Require both a password and authenticator code to sign in.",
                        verbose_name="require 2FA",
                    ),
                ),
                (
                    "temporary_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Automatically deactivate this account after the selected date and time.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "abstract": False,
            },
            managers=[
                ("objects", apps.base.models.EntityUserManager()),
                ("all_objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AdminCommandResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("command", models.TextField()),
                ("resolved_command", models.TextField()),
                ("command_name", models.CharField(blank=True, max_length=150)),
                ("stdout", models.TextField(blank=True)),
                ("stderr", models.TextField(blank=True)),
                ("traceback", models.TextField(blank=True)),
                ("runtime", models.DurationField(default=datetime.timedelta)),
                ("exit_code", models.IntegerField(default=0)),
                ("success", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Command Result",
                "verbose_name_plural": "Command Results",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="EmailArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("subject", models.CharField(max_length=255)),
                ("sender", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True)),
                ("sigils", models.JSONField(default=dict)),
                ("fingerprint", models.CharField(max_length=32)),
            ],
            options={
                "verbose_name": "Email Artifact",
                "verbose_name_plural": "Email Artifacts",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="EmailTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        default="inbound",
                        help_text="Whether the message originated from an inbox or is being sent out.",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("collected", "Collected"),
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="collected",
                        help_text="Lifecycle stage for the stored email message.",
                        max_length=9,
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True,
                        help_text="Message-ID header for threading and deduplication.",
                        max_length=255,
                    ),
                ),
                (
                    "thread_id",
                    models.CharField(
                        blank=True,
                        help_text="Thread or conversation identifier, if provided by the provider.",
                        max_length=255,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=998)),
                (
                    "from_address",
                    models.CharField(
                        blank=True,
                        help_text="From header as provided by the email message.",
                        max_length=512,
                    ),
                ),
                (
                    "sender_address",
                    models.CharField(
                        blank=True,
                        help_text="Envelope sender address, if available.",
                        max_length=512,
                    ),
                ),
                (
                    "to_addresses",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of To recipient addresses.",
                    ),
                ),
                (
                    "cc_addresses",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of Cc recipient addresses.",
                    ),
                ),
                (
                    "bcc_addresses",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of Bcc recipient addresses.",
                    ),
                ),
                (
                    "reply_to_addresses",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of Reply-To addresses from the message headers.",
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Complete header map as parsed from the message.",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional provider-specific metadata.",
                    ),
                ),
                ("body_text", models.TextField(blank=True)),
                ("body_html", models.TextField(blank=True)),
                (
                    "raw_content",
                    models.TextField(
                        blank=True,
                        help_text="Raw RFC822 payload for the message, if stored.",
                    ),
                ),
                (
                    "message_ts",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp supplied by the email headers.",
                        null=True,
                    ),
                ),
                (
                    "queued_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the message was queued for outbound delivery.",
                        null=True,
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the message was sent or fully processed.",
                        null=True,
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        help_text="Failure details captured during processing, if any.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email Transaction",
                "verbose_name_plural": "Email Transactions",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EmailTransactionAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("filename", models.CharField(blank=True, max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=255)),
                (
                    "content_id",
                    models.CharField(
                        blank=True,
                        help_text="Identifier used for inline attachments.",
                        max_length=255,
                    ),
                ),
                (
                    "inline",
                    models.BooleanField(
                        default=False,
                        help_text="Marks whether the attachment is referenced inline in the body.",
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Size of the decoded attachment payload in bytes.",
                        null=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Base64 encoded attachment payload."
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Attachment",
                "verbose_name_plural": "Email Attachments",
            },
        ),
        migrations.CreateModel(
            name="GoogleCalendarProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "calendar_id",
                    apps.sigils.fields.SigilShortAutoField(
                        max_length=255, verbose_name="Calendar ID"
                    ),
                ),
                (
                    "api_key",
                    apps.sigils.fields.SigilShortAutoField(
                        max_length=255, verbose_name="API Key"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Display Name"
                    ),
                ),
                (
                    "max_events",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Number of upcoming events to display (1-20).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "timezone",
                    apps.sigils.fields.SigilShortAutoField(
                        blank=True, max_length=100, verbose_name="Time Zone"
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Calendar",
                "verbose_name_plural": "Google Calendars",
            },
        ),
        migrations.CreateModel(
            name="InviteLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("path", models.TextField(blank=True)),
                ("referer", models.TextField(blank=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "ip_address",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        validators=[django.core.validators.validate_ipv46_address],
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("assigned", "Assigned"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("comment", models.TextField(blank=True)),
                ("sent_on", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("mac_address", models.CharField(blank=True, max_length=17)),
            ],
            options={
                "verbose_name": "Invite Lead",
                "verbose_name_plural": "Invite Leads",
            },
        ),
        migrations.CreateModel(
            name="PasskeyCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly label shown on the security settings page.",
                        max_length=80,
                    ),
                ),
                (
                    "credential_id",
                    models.CharField(
                        help_text="Base64-encoded identifier returned by the authenticator.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("public_key", models.BinaryField()),
                ("sign_count", models.PositiveIntegerField(default=0)),
                ("user_handle", models.CharField(max_length=255)),
                ("transports", models.JSONField(blank=True, default=list)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Passkey",
                "verbose_name_plural": "Passkeys",
                "ordering": ("name", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="RFID",
            fields=[
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "label_id",
                    models.AutoField(
                        db_column="label_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "rfid",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9A-Fa-f]+$",
                                message="RFID must be hexadecimal digits",
                            )
                        ],
                        verbose_name="RFID",
                    ),
                ),
                (
                    "reversed_uid",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="UID value stored with opposite endianness for reference.",
                        max_length=255,
                        verbose_name="Reversed UID",
                    ),
                ),
                (
                    "custom_label",
                    models.CharField(
                        blank=True,
                        help_text="Optional custom label for this RFID.",
                        max_length=32,
                        verbose_name="Custom Label",
                    ),
                ),
                (
                    "key_a",
                    models.CharField(
                        default="FFFFFFFFFFFF",
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9A-Fa-f]{12}$",
                                message="Key must be 12 hexadecimal digits",
                            )
                        ],
                        verbose_name="Key A",
                    ),
                ),
                (
                    "key_b",
                    models.CharField(
                        default="FFFFFFFFFFFF",
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9A-Fa-f]{12}$",
                                message="Key must be 12 hexadecimal digits",
                            )
                        ],
                        verbose_name="Key B",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=list, help_text="Sector and block data"
                    ),
                ),
                ("key_a_verified", models.BooleanField(default=False)),
                ("key_b_verified", models.BooleanField(default=False)),
                ("allowed", models.BooleanField(default=True)),
                (
                    "external_command",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional command executed during validation.",
                    ),
                ),
                (
                    "post_auth_command",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional command executed after successful validation.",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional expiration date for this RFID card.",
                        null=True,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("B", "Black"),
                            ("W", "White"),
                            ("U", "Blue"),
                            ("R", "Red"),
                            ("G", "Green"),
                        ],
                        default="B",
                        max_length=1,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("CLASSIC", "MIFARE Classic"), ("NTAG215", "NTAG215")],
                        default="CLASSIC",
                        max_length=8,
                    ),
                ),
                (
                    "endianness",
                    models.CharField(
                        choices=[("BIG", "Big endian"), ("LITTLE", "Little endian")],
                        default="BIG",
                        max_length=6,
                    ),
                ),
                ("released", models.BooleanField(default=False)),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                ("last_seen_on", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "RFID",
                "verbose_name_plural": "RFIDs",
                "db_table": "core_rfid",
            },
        ),
        migrations.CreateModel(
            name="SecurityGroup",
            fields=[
                (
                    "group_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Group",
                "verbose_name_plural": "Security Groups",
            },
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name="TOTPDeviceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "issuer",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Label shown in authenticator apps. Leave blank to use Arthexis.",
                        max_length=64,
                    ),
                ),
                (
                    "allow_without_password",
                    models.BooleanField(
                        default=False,
                        help_text="Allow authenticator logins to skip the password step.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Authenticator Device Setting",
                "verbose_name_plural": "Authenticator Device Settings",
            },
        ),
        migrations.CreateModel(
            name="UserPhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "number",
                    models.CharField(help_text="Contact phone number", max_length=20),
                ),
                ("priority", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Phone Number",
                "verbose_name_plural": "Phone Numbers",
                "ordering": ("priority", "id"),
            },
        ),
    ]
