# Generated by Django 5.2.8 on 2025-11-30 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
        ("energy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientReport",
            fields=[],
            options={
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("energy.clientreport",),
        ),
        migrations.CreateModel(
            name="ClientReportSchedule",
            fields=[],
            options={
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("energy.clientreportschedule",),
        ),
        migrations.CreateModel(
            name="CustomerAccount",
            fields=[],
            options={
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("energy.customeraccount",),
        ),
        migrations.CreateModel(
            name="EnergyCredit",
            fields=[],
            options={
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("energy.energycredit",),
        ),
        migrations.CreateModel(
            name="EnergyTariff",
            fields=[],
            options={
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("energy.energytariff",),
        ),
        migrations.CreateModel(
            name="EnergyTransaction",
            fields=[],
            options={
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("energy.energytransaction",),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[],
            options={
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("energy.location",),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="operate_as",
            field=models.ForeignKey(
                blank=True,
                help_text="Operate using another user's permissions when additional authority is required.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operated_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="admincommandresult",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="command_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
