# Generated by Django 5.2.8 on 2025-12-02 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
        ("links", "0001_initial"),
        ("otp_totp", "0003_add_timestamps"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfid",
            name="reference",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional reference for this RFID.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rfids",
                to="links.reference",
            ),
        ),
        migrations.AddField(
            model_name="securitygroup",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="core.securitygroup",
            ),
        ),
        migrations.AddField(
            model_name="googlecalendarprofile",
            name="group",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.securitygroup",
            ),
        ),
        migrations.AddField(
            model_name="totpdevicesettings",
            name="device",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_settings",
                to="otp_totp.totpdevice",
            ),
        ),
        migrations.AddField(
            model_name="totpdevicesettings",
            name="security_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Share this authenticator with every user in the selected security group.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="totp_devices",
                to="core.securitygroup",
            ),
        ),
        migrations.AddField(
            model_name="userphonenumber",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phone_numbers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emailartifact",
            unique_together={("collector", "fingerprint")},
        ),
        migrations.AddIndex(
            model_name="emailtransaction",
            index=models.Index(fields=["message_id"], name="email_txn_msgid"),
        ),
        migrations.AddIndex(
            model_name="emailtransaction",
            index=models.Index(
                fields=["direction", "status"], name="email_txn_dir_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="passkeycredential",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="core_passkey_unique_name_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="googlecalendarprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("user__isnull", False), ("group__isnull", True)),
                    models.Q(("user__isnull", True), ("group__isnull", False)),
                    _connector="OR",
                ),
                name="googlecalendarprofile_requires_owner",
            ),
        ),
    ]
