# Generated by Django 5.2.8 on 2025-12-06 15:03

from django.db import migrations

from utils.migration_branches import SafelyDeprecatedMigration


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        SafelyDeprecatedMigration(reason="legacy branch alignment placeholder"),
    ]
