# Generated by Django 5.2.8 on 2025-11-30 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="countdowntimer",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="countdown_timers",
                to="pages.developerarticle",
            ),
        ),
    ]
