# Generated by Django 5.2.7 on 2026-04-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminnotice",
            options={
                "ordering": ["-created_at"],
                "permissions": [("can_trigger_upgrade_checks", "Can trigger upgrade checks")],
                "verbose_name": "Admin Notice",
                "verbose_name_plural": "Admin Notices",
            },
        ),
    ]
