# Generated by Django 5.2.8 on 2025-11-30 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_initial"),
        ("django_celery_beat", "0020_googlecalendarprofile_horologiacountdowntimer"),
        ("links", "0001_initial"),
        ("nodes", "0001_initial"),
        ("otp_totp", "0003_add_timestamps"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailartifact",
            name="collector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifacts",
                to="teams.emailcollector",
            ),
        ),
        migrations.AddField(
            model_name="emailtransaction",
            name="collector",
            field=models.ForeignKey(
                blank=True,
                help_text="Collector that discovered this message, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="teams.emailcollector",
            ),
        ),
        migrations.AddField(
            model_name="emailtransaction",
            name="inbox",
            field=models.ForeignKey(
                blank=True,
                help_text="Inbox account the message was read from or will use for sending.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="teams.emailinbox",
            ),
        ),
        migrations.AddField(
            model_name="emailtransaction",
            name="outbox",
            field=models.ForeignKey(
                blank=True,
                help_text="Outbox configuration used to send the message, when known.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="teams.emailoutbox",
            ),
        ),
        migrations.AddField(
            model_name="emailtransactionattachment",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="core.emailtransaction",
            ),
        ),
        migrations.AddField(
            model_name="googlecalendarprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invitelead",
            name="assign_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invitelead",
            name="sent_via_outbox",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invite_leads",
                to="teams.emailoutbox",
            ),
        ),
        migrations.AddField(
            model_name="invitelead",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="openpayprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="packagerelease",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="releases",
                to="core.package",
            ),
        ),
        migrations.AddField(
            model_name="packagerelease",
            name="scheduled_task",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="package_release_schedule",
                serialize=False,
                to="django_celery_beat.periodictask",
            ),
        ),
        migrations.AddField(
            model_name="countdowntimer",
            name="package_release",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="countdown_timer",
                to="core.packagerelease",
            ),
        ),
        migrations.AddField(
            model_name="passkeycredential",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passkeys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="releasemanager",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="packagerelease",
            name="release_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.releasemanager",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="release_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.releasemanager",
            ),
        ),
        migrations.AddField(
            model_name="rfid",
            name="origin_node",
            field=models.ForeignKey(
                blank=True,
                help_text="Node where this RFID record was created.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_rfids",
                to="nodes.node",
            ),
        ),
        migrations.AddField(
            model_name="rfid",
            name="reference",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional reference for this RFID.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rfids",
                to="links.reference",
            ),
        ),
        migrations.AddField(
            model_name="securitygroup",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="core.securitygroup",
            ),
        ),
        migrations.AddField(
            model_name="releasemanager",
            name="group",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.securitygroup",
            ),
        ),
        migrations.AddField(
            model_name="openpayprofile",
            name="group",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.securitygroup",
            ),
        ),
        migrations.AddField(
            model_name="googlecalendarprofile",
            name="group",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.securitygroup",
            ),
        ),
        migrations.AddField(
            model_name="totpdevicesettings",
            name="device",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_settings",
                to="otp_totp.totpdevice",
            ),
        ),
        migrations.AddField(
            model_name="totpdevicesettings",
            name="security_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Share this authenticator with every user in the selected security group.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="totp_devices",
                to="core.securitygroup",
            ),
        ),
        migrations.AddField(
            model_name="userphonenumber",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phone_numbers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emailartifact",
            unique_together={("collector", "fingerprint")},
        ),
        migrations.AddIndex(
            model_name="emailtransaction",
            index=models.Index(fields=["message_id"], name="email_txn_msgid"),
        ),
        migrations.AddIndex(
            model_name="emailtransaction",
            index=models.Index(
                fields=["direction", "status"], name="email_txn_dir_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="passkeycredential",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="core_passkey_unique_name_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="packagerelease",
            constraint=models.UniqueConstraint(
                fields=("package", "version"), name="unique_package_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="package",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("is_active",),
                name="unique_active_package",
            ),
        ),
        migrations.AddConstraint(
            model_name="releasemanager",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("user__isnull", False), ("group__isnull", True)),
                    models.Q(("user__isnull", True), ("group__isnull", False)),
                    _connector="OR",
                ),
                name="releasemanager_requires_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="openpayprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("user__isnull", False), ("group__isnull", True)),
                    models.Q(("user__isnull", True), ("group__isnull", False)),
                    _connector="OR",
                ),
                name="openpayprofile_requires_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="googlecalendarprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("user__isnull", False), ("group__isnull", True)),
                    models.Q(("user__isnull", True), ("group__isnull", False)),
                    _connector="OR",
                ),
                name="googlecalendarprofile_requires_owner",
            ),
        ),
    ]
