# Generated by Django 5.2.8 on 2025-12-03 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_delete_rfid"),
        ("pages", "0004_delete_rolelanding"),
    ]

    operations = [
        migrations.AddField(
            model_name="securitygroup",
            name="site_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Branding template applied to members of this group when set.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="security_groups",
                to="pages.sitetemplate",
                verbose_name="Site template",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="site_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Branding template to apply for this user when overriding the site default.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="pages.sitetemplate",
                verbose_name="Site template",
            ),
        ),
    ]
