# Generated by Django 5.2.8 on 2025-11-30 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_delete_openpayprofile"),
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailartifact",
            name="collector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifacts",
                to="emails.emailcollector",
            ),
        ),
        migrations.AlterField(
            model_name="emailtransaction",
            name="collector",
            field=models.ForeignKey(
                blank=True,
                help_text="Collector that discovered this message, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="emails.emailcollector",
            ),
        ),
        migrations.AlterField(
            model_name="emailtransaction",
            name="inbox",
            field=models.ForeignKey(
                blank=True,
                help_text="Inbox account the message was read from or will use for sending.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="emails.emailinbox",
            ),
        ),
        migrations.AlterField(
            model_name="emailtransaction",
            name="outbox",
            field=models.ForeignKey(
                blank=True,
                help_text="Outbox configuration used to send the message, when known.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="emails.emailoutbox",
            ),
        ),
        migrations.AlterField(
            model_name="invitelead",
            name="sent_via_outbox",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invite_leads",
                to="emails.emailoutbox",
            ),
        ),
    ]
