# Generated by Django 5.2.8 on 2025-12-03 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_delete_energy_proxies"),
        ("core", "0005_securitygroup_site_template_user_site_template"),
    ]

    operations = []
