# Generated by Django 5.2.8 on 2025-11-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_emailartifact_collector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admincommandresult",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="admincommandresult",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="admincommandresult",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="passkeycredential",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="passkeycredential",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="passkeycredential",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="totpdevicesettings",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="totpdevicesettings",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="totpdevicesettings",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
