# Generated by Django 5.2.8 on 2025-12-03 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_securitygroup_group_ptr_and_more"),
        ("emails", "0002_alter_emailinbox_group_alter_emailoutbox_group"),
        ("groups", "0001_initial"),
        ("nodes", "0003_alter_nodemanager_group"),
        ("ocpp", "0005_alter_charger_owner_groups_and_more"),
        ("odoo", "0003_alter_odooemployee_group"),
        ("payments", "0003_alter_openpayprocessor_group_and_more"),
        ("release", "0002_alter_releasemanager_group"),
        ("tasks", "0002_alter_manualtask_assigned_group_and_more"),
        ("teams", "0004_alter_slackbotprofile_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googlecalendarprofile",
            name="group",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="groups.securitygroup",
            ),
        ),
        migrations.AlterField(
            model_name="totpdevicesettings",
            name="security_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Share this authenticator with every user in the selected security group.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="totp_devices",
                to="groups.securitygroup",
            ),
        ),
    ]
