# Generated by Django 5.2.11 on 2026-02-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_invitelead_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatabaseConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("backend", models.CharField(default="postgres", max_length=32)),
                ("name", models.CharField(max_length=255)),
                ("user", models.CharField(max_length=255)),
                ("password", models.CharField(blank=True, default="", max_length=255)),
                ("host", models.CharField(default="localhost", max_length=255)),
                ("port", models.PositiveIntegerField(default=5432)),
                ("is_active", models.BooleanField(default=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_status_ok", models.BooleanField(default=False)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Database configuration",
                "verbose_name_plural": "Database configurations",
                "ordering": ["-updated_at"],
            },
        ),
    ]
