# Generated by Django 5.2.10 on 2026-01-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio", "0002_audiosample"),
        ("nodes", "0023_rename_rpi_camera_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordingdevice",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="recordingdevice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("node",),
                name="audio_recordingdevice_default_per_node",
            ),
        ),
    ]
