# Generated by Django 5.2.11 on 2026-02-26 00:00

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("smb", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smbserver",
            name="password",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default="", max_length=255),
        ),
    ]
