"""Diagnostics utilities for user-linked bug triage bundles."""

from __future__ import annotations

import json
from pathlib import Path

from django.core.management.base import BaseCommand, CommandError

from apps.users.diagnostics import build_bundle_for_username
from apps.users.error_report_analysis import (
    analyze_error_report_package,
    redact_analysis_payload,
    redact_sensitive_text,
)


class Command(BaseCommand):
    help = "Build user diagnostics bundles and analyze downloaded error-report packages."

    def add_arguments(self, parser):
        parser.add_argument(
            "action",
            nargs="?",
            default="build",
            choices=("build", "analyze"),
            help="Command action: build (default) or analyze.",
        )
        parser.add_argument("--username", help="Username to build the bundle for.")
        parser.add_argument(
            "--title",
            default="",
            help="Optional bundle title override.",
        )
        parser.add_argument(
            "--limit",
            type=int,
            default=50,
            help="Maximum number of recent events to include.",
        )
        parser.add_argument(
            "--package",
            help="Path to an error-report zip package generated by error-report.sh.",
        )
        parser.add_argument(
            "--format",
            choices=("text", "json"),
            default="text",
            help="Output format for package analysis.",
        )
        parser.add_argument(
            "--output",
            help="Optional path to write JSON analysis results.",
        )
        parser.add_argument(
            "--fail-on",
            choices=("low", "medium", "high", "critical"),
            help="Exit non-zero when the highest detected severity meets or exceeds this level.",
        )

    def handle(self, *args, **options):
        action = options["action"]
        if action == "analyze":
            self._handle_analyze(options)
            return
        self._handle_build(options)

    def _handle_build(self, options):
        username = (options.get("username") or "").strip()
        if not username:
            raise CommandError("Username is required for 'build'.")
        limit = max(1, int(options["limit"]))
        try:
            bundle = build_bundle_for_username(
                username=username,
                title=options.get("title") or "",
                limit=limit,
            )
        except Exception as exc:
            raise CommandError(f"Unable to build diagnostics bundle: {exc}") from exc
        self.stdout.write(
            self.style.SUCCESS(
                f"Created diagnostics bundle #{bundle.pk} for {username} with {bundle.events.count()} event(s)."
            )
        )

    def _handle_analyze(self, options):
        package_arg = (options.get("package") or "").strip()
        if not package_arg:
            raise CommandError("--package is required for 'analyze'.")
        package_path = Path(package_arg)
        try:
            result = analyze_error_report_package(package_path)
        except (FileNotFoundError, ValueError, OSError) as exc:
            safe_package = redact_sensitive_text(str(package_path))
            safe_error = redact_sensitive_text(str(exc))
            raise CommandError(
                f"Unable to analyze package '{safe_package}': {safe_error}"
            ) from exc

        safe_result = redact_analysis_payload(result)
        output_path = (options.get("output") or "").strip()
        if output_path:
            output_target = Path(output_path)
            try:
                output_target.parent.mkdir(parents=True, exist_ok=True)
                output_target.write_text(
                    # codeql[py/clear-text-storage-sensitive-data]
                    json.dumps(safe_result, indent=2, sort_keys=True),
                    encoding="utf-8",
                )
            except OSError as exc:
                safe_target = redact_sensitive_text(str(output_target))
                safe_error = redact_sensitive_text(str(exc))
                raise CommandError(
                    f"Unable to write analysis output to '{safe_target}': {safe_error}"
                ) from exc

        if options.get("format") == "json":
            self.stdout.write(json.dumps(safe_result, indent=2, sort_keys=True))
        else:
            self.stdout.write(
                self.style.SUCCESS(
                    f"Analyzed: {redact_sensitive_text(str(package_path))}"
                )
            )
            self.stdout.write(
                f"Risk score: {result['risk_score']} ({result['max_severity']})"
            )
            self.stdout.write(f"Findings: {len(result['findings'])}")
            if safe_result["warnings"]:
                self.stdout.write("Warnings:")
                for warning in safe_result["warnings"]:
                    self.stdout.write(f"- {warning}")
            for finding in safe_result["findings"]:
                self.stdout.write(
                    f"[{finding['severity'].upper()}] {finding['category']}: {finding['message']}"
                )

        fail_on = options.get("fail_on")
        if fail_on and result["max_severity_rank"] >= result["severity_order"][fail_on]:
            raise CommandError(
                f"Analysis severity threshold reached: max={result['max_severity']} threshold={fail_on}."
            )
