# Generated by Django 5.2.4 on 2025-08-24 13:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import integrate.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("refs", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("street", models.CharField(max_length=255)),
                ("number", models.CharField(max_length=20)),
                (
                    "municipality",
                    models.CharField(
                        choices=[
                            ("Abasolo", "Abasolo"),
                            ("Acuña", "Acuña"),
                            ("Allende", "Allende"),
                            ("Arteaga", "Arteaga"),
                            ("Candela", "Candela"),
                            ("Castaños", "Castaños"),
                            ("Cuatro Ciénegas", "Cuatro Ciénegas"),
                            ("Escobedo", "Escobedo"),
                            ("Francisco I. Madero", "Francisco I. Madero"),
                            ("Frontera", "Frontera"),
                            ("General Cepeda", "General Cepeda"),
                            ("Guerrero", "Guerrero"),
                            ("Hidalgo", "Hidalgo"),
                            ("Jiménez", "Jiménez"),
                            ("Juárez", "Juárez"),
                            ("Lamadrid", "Lamadrid"),
                            ("Matamoros", "Matamoros"),
                            ("Monclova", "Monclova"),
                            ("Morelos", "Morelos"),
                            ("Múzquiz", "Múzquiz"),
                            ("Nadadores", "Nadadores"),
                            ("Nava", "Nava"),
                            ("Ocampo", "Ocampo"),
                            ("Parras", "Parras"),
                            ("Piedras Negras", "Piedras Negras"),
                            ("Progreso", "Progreso"),
                            ("Ramos Arizpe", "Ramos Arizpe"),
                            ("Sabinas", "Sabinas"),
                            ("Sacramento", "Sacramento"),
                            ("Saltillo", "Saltillo"),
                            ("San Buenaventura", "San Buenaventura"),
                            ("San Juan de Sabinas", "San Juan de Sabinas"),
                            ("San Pedro", "San Pedro"),
                            ("Sierra Mojada", "Sierra Mojada"),
                            ("Torreón", "Torreón"),
                            ("Viesca", "Viesca"),
                            ("Villa Unión", "Villa Unión"),
                            ("Zaragoza", "Zaragoza"),
                            ("Abasolo", "Abasolo"),
                            ("Agualeguas", "Agualeguas"),
                            ("Los Aldamas", "Los Aldamas"),
                            ("Allende", "Allende"),
                            ("Anáhuac", "Anáhuac"),
                            ("Apodaca", "Apodaca"),
                            ("Aramberri", "Aramberri"),
                            ("Bustamante", "Bustamante"),
                            ("Cadereyta Jiménez", "Cadereyta Jiménez"),
                            ("El Carmen", "El Carmen"),
                            ("Cerralvo", "Cerralvo"),
                            ("Ciénega de Flores", "Ciénega de Flores"),
                            ("China", "China"),
                            ("Doctor Arroyo", "Doctor Arroyo"),
                            ("Doctor Coss", "Doctor Coss"),
                            ("Doctor González", "Doctor González"),
                            ("Galeana", "Galeana"),
                            ("García", "García"),
                            ("General Bravo", "General Bravo"),
                            ("General Escobedo", "General Escobedo"),
                            ("General Terán", "General Terán"),
                            ("General Treviño", "General Treviño"),
                            ("General Zaragoza", "General Zaragoza"),
                            ("General Zuazua", "General Zuazua"),
                            ("Guadalupe", "Guadalupe"),
                            ("Los Herreras", "Los Herreras"),
                            ("Higueras", "Higueras"),
                            ("Hualahuises", "Hualahuises"),
                            ("Iturbide", "Iturbide"),
                            ("Juárez", "Juárez"),
                            ("Lampazos de Naranjo", "Lampazos de Naranjo"),
                            ("Linares", "Linares"),
                            ("Marín", "Marín"),
                            ("Melchor Ocampo", "Melchor Ocampo"),
                            ("Mier y Noriega", "Mier y Noriega"),
                            ("Mina", "Mina"),
                            ("Montemorelos", "Montemorelos"),
                            ("Monterrey", "Monterrey"),
                            ("Parás", "Parás"),
                            ("Pesquería", "Pesquería"),
                            ("Los Ramones", "Los Ramones"),
                            ("Rayones", "Rayones"),
                            ("Sabinas Hidalgo", "Sabinas Hidalgo"),
                            ("Salinas Victoria", "Salinas Victoria"),
                            ("San Nicolás de los Garza", "San Nicolás de los Garza"),
                            ("San Pedro Garza García", "San Pedro Garza García"),
                            ("Santa Catarina", "Santa Catarina"),
                            ("Santiago", "Santiago"),
                            ("Vallecillo", "Vallecillo"),
                            ("Villaldama", "Villaldama"),
                            ("Hidalgo", "Hidalgo"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("CO", "Coahuila"), ("NL", "Nuevo León")], max_length=2
                    ),
                ),
                ("postal_code", models.CharField(max_length=10)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "EV Brand",
                "verbose_name_plural": "EV Brands",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "renewal_period",
                    models.PositiveIntegerField(help_text="Renewal period in days"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RFIDSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "endpoint",
                    models.SlugField(
                        help_text="Slug for the RFID batch endpoint; '/api/rfid/' is added automatically"
                    ),
                ),
                ("default_order", models.PositiveIntegerField(default=0)),
                ("proxy_url", models.URLField(blank=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "RFID source",
                "verbose_name_plural": "RFID sources",
                "ordering": ["default_order"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Optional contact phone number",
                        max_length=20,
                    ),
                ),
                ("has_charger", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.address",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", integrate.models.EntityUserManager()),
                ("all_objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "service_account",
                    models.BooleanField(
                        default=False,
                        help_text="Allow transactions even when the balance is zero or negative",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Credit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "amount_kw",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Energy (kW)"
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="accounts.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EVModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ev_models",
                        to="accounts.brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "EV Model",
                "verbose_name_plural": "EV Models",
                "unique_together": {("brand", "name")},
            },
        ),
        migrations.CreateModel(
            name="RFID",
            fields=[
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "label_id",
                    models.AutoField(
                        db_column="label_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "rfid",
                    models.CharField(
                        max_length=8,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9A-Fa-f]{8}$",
                                message="RFID must be 8 hexadecimal digits",
                            )
                        ],
                        verbose_name="RFID",
                    ),
                ),
                (
                    "key_a",
                    models.CharField(
                        default="FFFFFFFFFFFF",
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9A-Fa-f]{12}$",
                                message="Key must be 12 hexadecimal digits",
                            )
                        ],
                        verbose_name="Key A",
                    ),
                ),
                (
                    "key_b",
                    models.CharField(
                        default="FFFFFFFFFFFF",
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9A-Fa-f]{12}$",
                                message="Key must be 12 hexadecimal digits",
                            )
                        ],
                        verbose_name="Key B",
                    ),
                ),
                ("allowed", models.BooleanField(default=True)),
                (
                    "color",
                    models.CharField(
                        choices=[("black", "Black"), ("white", "White")],
                        default="black",
                        max_length=5,
                    ),
                ),
                ("released", models.BooleanField(default=False)),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                ("source", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "reference",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional reference for this RFID.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rfids",
                        to="refs.reference",
                    ),
                ),
            ],
            options={
                "verbose_name": "RFID",
                "verbose_name_plural": "RFIDs",
                "db_table": "accounts_rfid",
            },
        ),
        migrations.AddField(
            model_name="account",
            name="rfids",
            field=models.ManyToManyField(
                blank=True, related_name="accounts", to="accounts.rfid"
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("start_date", models.DateField(auto_now_add=True)),
                ("next_renewal", models.DateField(blank=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "vin",
                    models.CharField(max_length=17, unique=True, verbose_name="VIN"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="accounts.account",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicles",
                        to="accounts.brand",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicles",
                        to="accounts.evmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WMICode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("code", models.CharField(max_length=3, unique=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wmi_codes",
                        to="accounts.brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "WMI code",
                "verbose_name_plural": "WMI codes",
            },
        ),
        migrations.CreateModel(
            name="AdminHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("url", models.TextField()),
                ("visited_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-visited_at"],
                "unique_together": {("user", "url")},
            },
        ),
    ]
