# Generated by Django 5.2.4 on 2025-07-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistedRFID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=64, unique=True)),
                ("added_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
