# Generated by Django 5.2.4 on 2025-08-10 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="is_seed_data",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="EVModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_seed_data", models.BooleanField(default=False)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ev_models",
                        to="accounts.brand",
                    ),
                ),
            ],
            options={
                "unique_together": {("brand", "name")},
            },
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicles",
                to="accounts.evmodel",
            ),
        ),
    ]
