# Generated by Django 5.2.4 on 2025-08-26 21:25

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rfid_data_rfid_key_a_verified_rfid_key_b_verified"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityGroup",
            fields=[],
            options={
                "verbose_name": "Security Group",
                "verbose_name_plural": "Security Groups",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
