# Generated by Django 5.2.4 on 2025-08-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rfid_to_accounts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evmodel',
            options={'verbose_name': 'EV Model', 'verbose_name_plural': 'EV Models'},
        ),
    ]
