# Generated by Django 5.2.4 on 2025-08-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_evmodel_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"verbose_name": "EV Brand", "verbose_name_plural": "EV Brands"},
        ),
    ]
