# Generated by Django 5.2.4 on 2025-07-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_merge_0004_rfid_model_0004_vehicle"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rfid",
            old_name="uid",
            new_name="rfid",
        ),
        migrations.AlterField(
            model_name="rfid",
            name="rfid",
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
