# Generated by Django 5.2.4 on 2025-08-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_brand_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="RFIDSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("endpoint", models.URLField()),
                ("is_source", models.BooleanField(default=False)),
                ("is_target", models.BooleanField(default=False)),
            ],
        ),
    ]
