# Generated by Django 5.2.4 on 2025-07-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_rfid_options_alter_rfid_rfid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, help_text="Optional contact phone number", max_length=20
            ),
        ),
    ]
