# Generated by Django 5.2.4 on 2025-08-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_rfidsource"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rfidsource",
            options={
                "verbose_name": "RFID source",
                "verbose_name_plural": "RFID sources",
            },
        ),
        migrations.AlterField(
            model_name="rfidsource",
            name="endpoint",
            field=models.URLField(
                help_text="Full URL to the RFID batch endpoint, including '/api/rfid/'"
            ),
        ),
    ]
