# Generated by Django 5.2.4 on 2025-08-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_rfidsource_options_alter_rfidsource_endpoint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rfidsource",
            name="endpoint",
            field=models.SlugField(
                help_text="Slug for the RFID batch endpoint; '/api/rfid/' is added automatically"
            ),
        ),
    ]
