# Generated by Django 5.2.4 on 2025-08-11 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_rfidsource_endpoint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="is_seed_data",
        ),
        migrations.RemoveField(
            model_name="evmodel",
            name="is_seed_data",
        ),
        migrations.RemoveField(
            model_name="rfid",
            name="is_seed_data",
        ),
    ]
