# Generated by Django 5.2.4 on 2025-08-12 01:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_brand_is_seed_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfid",
            name="key_a",
            field=models.CharField(
                default="FFFFFFFFFFFF",
                max_length=12,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9A-Fa-f]{12}$", message="Key must be 12 hexadecimal digits"
                    )
                ],
                verbose_name="Key A",
            ),
        ),
        migrations.AddField(
            model_name="rfid",
            name="key_b",
            field=models.CharField(
                default="FFFFFFFFFFFF",
                max_length=12,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9A-Fa-f]{12}$", message="Key must be 12 hexadecimal digits"
                    )
                ],
                verbose_name="Key B",
            ),
        ),
    ]
