# Generated by Django 5.2.4 on 2025-07-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_credit_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="service_account",
            field=models.BooleanField(
                default=False,
                help_text="Allow transactions even when the balance is zero or negative",
            ),
        ),
    ]
