# Generated by Django 5.2.4 on 2025-07-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_account_service_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="has_charger",
            field=models.BooleanField(default=False),
        ),
    ]
