# Generated by Django 5.2.4 on 2025-08-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_adminhistory"),
        ("accounts", "0013_remove_rfid_id_alter_rfid_rfid"),
    ]

    operations = []
