# Generated by Django 5.2.4 on 2025-07-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_address_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='municipality',
            field=models.CharField(choices=[('Abasolo', 'Abasolo'), ('Acuña', 'Acuña'), ('Allende', 'Allende'), ('Arteaga', 'Arteaga'), ('Candela', 'Candela'), ('Castaños', 'Castaños'), ('Cuatro Ciénegas', 'Cuatro Ciénegas'), ('Escobedo', 'Escobedo'), ('Francisco I. Madero', 'Francisco I. Madero'), ('Frontera', 'Frontera'), ('General Cepeda', 'General Cepeda'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jiménez', 'Jiménez'), ('Juárez', 'Juárez'), ('Lamadrid', 'Lamadrid'), ('Matamoros', 'Matamoros'), ('Monclova', 'Monclova'), ('Morelos', 'Morelos'), ('Múzquiz', 'Múzquiz'), ('Nadadores', 'Nadadores'), ('Nava', 'Nava'), ('Ocampo', 'Ocampo'), ('Parras', 'Parras'), ('Piedras Negras', 'Piedras Negras'), ('Progreso', 'Progreso'), ('Ramos Arizpe', 'Ramos Arizpe'), ('Sabinas', 'Sabinas'), ('Sacramento', 'Sacramento'), ('Saltillo', 'Saltillo'), ('San Buenaventura', 'San Buenaventura'), ('San Juan de Sabinas', 'San Juan de Sabinas'), ('San Pedro', 'San Pedro'), ('Sierra Mojada', 'Sierra Mojada'), ('Torreón', 'Torreón'), ('Viesca', 'Viesca'), ('Villa Unión', 'Villa Unión'), ('Zaragoza', 'Zaragoza'), ('Abasolo', 'Abasolo'), ('Agualeguas', 'Agualeguas'), ('Los Aldamas', 'Los Aldamas'), ('Allende', 'Allende'), ('Anáhuac', 'Anáhuac'), ('Apodaca', 'Apodaca'), ('Aramberri', 'Aramberri'), ('Bustamante', 'Bustamante'), ('Cadereyta Jiménez', 'Cadereyta Jiménez'), ('El Carmen', 'El Carmen'), ('Cerralvo', 'Cerralvo'), ('Ciénega de Flores', 'Ciénega de Flores'), ('China', 'China'), ('Doctor Arroyo', 'Doctor Arroyo'), ('Doctor Coss', 'Doctor Coss'), ('Doctor González', 'Doctor González'), ('Galeana', 'Galeana'), ('García', 'García'), ('General Bravo', 'General Bravo'), ('General Escobedo', 'General Escobedo'), ('General Terán', 'General Terán'), ('General Treviño', 'General Treviño'), ('General Zaragoza', 'General Zaragoza'), ('General Zuazua', 'General Zuazua'), ('Guadalupe', 'Guadalupe'), ('Los Herreras', 'Los Herreras'), ('Higueras', 'Higueras'), ('Hualahuises', 'Hualahuises'), ('Iturbide', 'Iturbide'), ('Juárez', 'Juárez'), ('Lampazos de Naranjo', 'Lampazos de Naranjo'), ('Linares', 'Linares'), ('Marín', 'Marín'), ('Melchor Ocampo', 'Melchor Ocampo'), ('Mier y Noriega', 'Mier y Noriega'), ('Mina', 'Mina'), ('Montemorelos', 'Montemorelos'), ('Monterrey', 'Monterrey'), ('Parás', 'Parás'), ('Pesquería', 'Pesquería'), ('Los Ramones', 'Los Ramones'), ('Rayones', 'Rayones'), ('Sabinas Hidalgo', 'Sabinas Hidalgo'), ('Salinas Victoria', 'Salinas Victoria'), ('San Nicolás de los Garza', 'San Nicolás de los Garza'), ('San Pedro Garza García', 'San Pedro Garza García'), ('Santa Catarina', 'Santa Catarina'), ('Santiago', 'Santiago'), ('Vallecillo', 'Vallecillo'), ('Villaldama', 'Villaldama'), ('Hidalgo', 'Hidalgo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('CO', 'Coahuila'), ('NL', 'Nuevo León')], max_length=2),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(max_length=17, unique=True, verbose_name='VIN'),
        ),
        migrations.DeleteModel(
            name='RFID',
        ),
    ]
