# Generated by Django 5.2.4 on 2025-08-13 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_merge_20250812_1814"),
    ]

    operations = [
        migrations.CreateModel(
            name="WMICode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3, unique=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wmi_codes",
                        to="accounts.brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "WMI code",
                "verbose_name_plural": "WMI codes",
            },
        ),
    ]
