# Generated by Django 5.2.4 on 2025-07-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_address_municipality_alter_address_state_and_more'),
    ]

    operations = []
