# Generated by Django 5.2.4 on 2025-07-29 21:27

from django.db import migrations, models
from django.conf import settings
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_delete_rfid"),
    ]

    operations = []
