# Generated by Django 5.2.4 on 2025-07-29 21:27

from django.db import migrations, models
from django.conf import settings
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_delete_rfid"),
    ]

    operations = [
        migrations.CreateModel(
            name="RFID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rfid",
                    models.CharField(
                        max_length=8,
                        unique=True,
                        verbose_name="RFID",
                        validators=[
                            django.core.validators.RegexValidator(
                                r"^[0-9A-Fa-f]{8}$",
                                message="RFID must be 8 hexadecimal digits",
                            )
                        ],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET_NULL,
                        related_name="rfids",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("allowed", models.BooleanField(default=True)),
                ("added_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "RFID",
                "verbose_name_plural": "RFIDs",
                "db_table": "accounts_rfid",
            },
        ),
    ]
