# Generated by Django 5.2.4 on 2025-08-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_rename_amount_kwh_credit_amount_kw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credit",
            name="amount_kw",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Energy (kW)"
            ),
        ),
    ]
