# Generated by Django 5.2.4 on 2025-07-29 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_readd_rfid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RFID',
        ),
    ]
