# Generated by Django 5.2.4 on 2025-08-13 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_alter_credit_amount_kw"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="rfids",
        ),
        migrations.AddField(
            model_name="rfid",
            name="label_id",
            field=models.AutoField(
                db_column="label_id", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="rfid",
            name="rfid",
            field=models.CharField(
                max_length=8,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9A-Fa-f]{8}$", message="RFID must be 8 hexadecimal digits"
                    )
                ],
                verbose_name="RFID",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="rfids",
            field=models.ManyToManyField(
                blank=True, related_name="accounts", to="accounts.rfid"
            ),
        ),
    ]
