# Generated by Django 5.2.4 on 2025-08-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_rfid_label_id_alter_rfid_rfid"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfid",
            name="color",
            field=models.CharField(
                choices=[("black", "Black"), ("white", "White")],
                default="black",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="rfid",
            name="released",
            field=models.BooleanField(default=False),
        ),
    ]
