# Generated by Django 5.2.4 on 2025-08-23 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0201_initial"),
        ("refs", "0101_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfid",
            name="reference",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional reference for this RFID.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rfids",
                to="refs.reference",
            ),
        ),
    ]
