# Generated by Django 5.2.15 on 2026-07-02 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seed_data', models.BooleanField(default=False, editable=False)),
                ('is_user_data', models.BooleanField(default=False, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('executable', models.CharField(blank=True, help_text='Optional executable command.', max_length=255)),
                ('launch_command', models.TextField(blank=True, help_text='Command to send after launch.')),
                ('launch_prompt', models.TextField(blank=True, help_text='Prompt text to send after command.')),
                ('prompt_blocks', models.JSONField(blank=True, default=list)),
                ('auto_close_on_exit', models.BooleanField(default=False)),
                ('prompt_block_mode', models.CharField(choices=[('end', 'End'), ('loop', 'Loop')], default='end', max_length=8)),
                ('startup_maximized', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, help_text='Security group that owns this object.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='groups.securitygroup')),
                ('node_role', models.ForeignKey(blank=True, help_text='Node role this terminal definition applies to. Defaults to Terminal role.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_terminals', to='nodes.noderole')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
