from __future__ import annotations

import json
from pathlib import Path

from apps.nginx.config_utils import (
    default_reject_server,
    http_proxy_server,
    http_redirect_server,
    https_proxy_server,
    slugify,
    write_if_changed,
)

HTTP_IPV4_LISTENS = (
    "0.0.0.0:80",
    "0.0.0.0:8000",
    "0.0.0.0:8080",
    "0.0.0.0:8900",
)

HTTP_IPV6_LISTENS = (
    "[::]:80",
    "[::]:8000",
    "[::]:8080",
    "[::]:8900",
)

HTTPS_IPV4_LISTENS = ("443 ssl",)
HTTPS_IPV6_LISTENS = ("[::]:443 ssl",)


def generate_primary_config(
    mode: str,
    port: int,
    *,
    http_server_names: str | None = None,
    https_server_names: str | None = None,
    include_ipv6: bool = False,
) -> str:
    mode = mode.lower()
    if mode not in {"internal", "public"}:
        raise ValueError(f"Unsupported mode: {mode}")

    http_listens = list(HTTP_IPV4_LISTENS)
    if include_ipv6:
        http_listens.extend(HTTP_IPV6_LISTENS)

    https_listens = list(HTTPS_IPV4_LISTENS)
    if include_ipv6:
        https_listens.extend(HTTPS_IPV6_LISTENS)

    if mode == "public":
        http_names = http_server_names or "arthexis.com *.arthexis.com"
        https_names = https_server_names or "arthexis.com *.arthexis.com"
        http_block = http_redirect_server(http_names, listens=http_listens)
        https_block = https_proxy_server(
            https_names,
            port,
            listens=https_listens,
            trailing_slash=False,
        )
        http_default = default_reject_server(http_listens)
        https_default = default_reject_server(https_listens, https=True)
        return f"{http_block}\n\n{http_default}\n\n{https_block}\n\n{https_default}\n"

    http_names = http_server_names or "_"
    http_block = http_proxy_server(
        http_names,
        port,
        http_listens,
        trailing_slash=False,
    )
    return f"{http_block}\n"


def apply_site_entries(
    config_path: Path,
    mode: str,
    port: int,
    dest_path: Path,
) -> bool:
    try:
        raw = config_path.read_text(encoding="utf-8")
        sites = json.loads(raw)
    except FileNotFoundError:
        sites = []
    except json.JSONDecodeError as exc:  # pragma: no cover - invalid staging file
        raise ValueError(f"Invalid JSON in {config_path}: {exc}")

    dest_path.parent.mkdir(parents=True, exist_ok=True)

    seen_domains: set[str] = set()
    mode = mode.lower()

    site_blocks: list[str] = ["# Autogenerated by apps.nginx.renderers"]

    for entry in sites:
        domain = (entry.get("domain") or "").strip()
        if not domain:
            continue
        require_https = bool(entry.get("require_https"))
        slug = slugify(domain)
        if slug in seen_domains:
            continue
        seen_domains.add(slug)

        blocks: list[str] = [f"# Managed site for {domain}"]

        if require_https and mode == "public":
            blocks.append(http_redirect_server(domain))
        else:
            blocks.append(http_proxy_server(domain, port))

        if mode == "public":
            blocks.append(https_proxy_server(domain, port))
        elif require_https:
            blocks.append(
                "# HTTPS requested but unavailable in internal mode; update nginx_mode.lck to 'public'."
            )

        site_blocks.append("\n\n".join(blocks))

    if len(site_blocks) == 1:
        site_blocks.append("# No managed sites configured.")

    content = "\n\n".join(site_blocks)
    return write_if_changed(dest_path, content)
