# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        ("pages", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="securitygroup",
            name="site_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Branding template applied to members of this group when set.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="security_groups",
                to="pages.sitetemplate",
                verbose_name="Site template",
            ),
        ),
    ]
