# Generated by Django 5.2.11 on 2026-03-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_site_operator_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="securitygroup",
            name="app",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Owning app label for this security group.",
                max_length=100,
                verbose_name="App",
            ),
        ),
    ]
