# Generated by Django 5.2.12 on 2026-03-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClockDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("bus", models.PositiveIntegerField(default=1)),
                ("address", models.CharField(max_length=10)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("raw_info", models.TextField(blank=True)),
                ("enable_public_view", models.BooleanField(default=False)),
                (
                    "public_view_slug",
                    models.SlugField(blank=True, null=True, unique=True),
                ),
            ],
            options={
                "verbose_name": "Clock Device",
                "verbose_name_plural": "Clock Devices",
                "ordering": ["bus", "address"],
            },
        ),
    ]
