# Generated by Django 5.2.15 on 2026-07-02 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clocks', '0001_initial'),
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockdevice',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_devices', to='nodes.node'),
        ),
        migrations.AddConstraint(
            model_name='clockdevice',
            constraint=models.UniqueConstraint(fields=('node', 'bus', 'address'), name='clocks_clockdevice_unique'),
        ),
    ]
