# Generated by Django 5.2.8 on 2025-11-30 19:39

from django.db import migrations, models


def seed_device_screens(apps, schema_editor):
    DeviceScreen = apps.get_model("screens", "DeviceScreen")
    DeviceScreen.objects.update_or_create(
        slug="lcd-1602",
        defaults={
            "name": "LCD Character 16x2",
            "category": "lcd",
            "skin": "pcf8574",
            "columns": 16,
            "rows": 2,
            "resolution_width": 16,
            "resolution_height": 2,
            "is_seed_data": True,
        },
    )


def unseed_device_screens(apps, schema_editor):
    DeviceScreen = apps.get_model("screens", "DeviceScreen")
    DeviceScreen.objects.filter(slug="lcd-1602").delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceScreen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("lcd", "LCD"),
                            ("led", "LED"),
                            ("touch", "Touch"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Broad hardware category for the screen.",
                        max_length=32,
                    ),
                ),
                (
                    "skin",
                    models.CharField(
                        help_text="Skin, SKU or shell identifier for the device.",
                        max_length=100,
                    ),
                ),
                (
                    "columns",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Text columns supported by the display."
                    ),
                ),
                (
                    "rows",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Text rows supported by the display."
                    ),
                ),
                (
                    "resolution_width",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Pixel width for graphical displays.",
                        null=True,
                    ),
                ),
                (
                    "resolution_height",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Pixel height for graphical displays.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Screen",
                "verbose_name_plural": "Device Screens",
                "ordering": ["name"],
            },
        ),
        migrations.RunPython(seed_device_screens, unseed_device_screens),
    ]
