# Generated by Django 5.2.8 on 2025-12-05 22:30

from django.db import migrations


def forward(apps, schema_editor):
    SocialProfile = apps.get_model("teams", "SocialProfile")
    ChatAvatar = apps.get_model("chats", "ChatAvatar")
    BlueskyProfile = apps.get_model("socials", "BlueskyProfile")
    DiscordProfile = apps.get_model("socials", "DiscordProfile")

    for profile in SocialProfile.objects.filter(is_deleted=False):
        avatar = None
        if getattr(profile, "avatar_id", None):
            avatar = ChatAvatar.objects.filter(pk=profile.avatar_id).first()
        if avatar is None and getattr(profile, "user_id", None):
            avatar = ChatAvatar.objects.filter(user_id=profile.user_id).first()
        if avatar is None and getattr(profile, "group_id", None):
            avatar = ChatAvatar.objects.filter(group_id=profile.group_id).first()

        if avatar is None:
            base_name = (
                profile.handle
                or profile.domain
                or profile.guild_id
                or profile.application_id
                or profile.network
                or "Social Avatar"
            )
            avatar = ChatAvatar.objects.create(
                name=str(base_name)[:150],
                user_id=getattr(profile, "user_id", None),
                group_id=getattr(profile, "group_id", None),
                is_enabled=True,
                is_seed_data=profile.is_seed_data,
                is_user_data=profile.is_user_data,
            )

        if profile.network == "bluesky":
            BlueskyProfile.objects.update_or_create(
                avatar=avatar,
                defaults={
                    "handle": profile.handle,
                    "domain": profile.domain,
                    "did": profile.did,
                    "is_seed_data": profile.is_seed_data,
                    "is_user_data": profile.is_user_data,
                },
            )
        elif profile.network == "discord":
            DiscordProfile.objects.update_or_create(
                avatar=avatar,
                defaults={
                    "application_id": profile.application_id,
                    "public_key": profile.public_key,
                    "guild_id": profile.guild_id,
                    "bot_token": profile.bot_token,
                    "default_channel_id": profile.default_channel_id,
                    "is_seed_data": profile.is_seed_data,
                    "is_user_data": profile.is_user_data,
                },
            )


def backward(apps, schema_editor):
    SocialProfile = apps.get_model("teams", "SocialProfile")
    BlueskyProfile = apps.get_model("socials", "BlueskyProfile")
    DiscordProfile = apps.get_model("socials", "DiscordProfile")

    SocialProfile.objects.all().delete()

    for bluesky in BlueskyProfile.objects.filter(is_deleted=False):
        SocialProfile.objects.create(
            network="bluesky",
            handle=bluesky.handle,
            domain=bluesky.domain,
            did=bluesky.did,
            avatar_id=getattr(bluesky, "avatar_id", None),
            is_seed_data=bluesky.is_seed_data,
            is_user_data=bluesky.is_user_data,
        )

    for discord in DiscordProfile.objects.filter(is_deleted=False):
        SocialProfile.objects.create(
            network="discord",
            application_id=discord.application_id,
            public_key=discord.public_key,
            guild_id=discord.guild_id,
            bot_token=discord.bot_token,
            default_channel_id=discord.default_channel_id,
            avatar_id=getattr(discord, "avatar_id", None),
            is_seed_data=discord.is_seed_data,
            is_user_data=discord.is_user_data,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_delete_totpdevice"),
        ("socials", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
