# Generated by Django 5.2.12 on 2026-03-10 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpecialCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Singular management command name (single lowercase word).",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "plural_name",
                    models.CharField(
                        help_text="Plural command alias (single lowercase word).",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "command_path",
                    models.CharField(
                        help_text="Import path to the command class for introspection and traceability.",
                        max_length=255,
                    ),
                ),
                (
                    "keystone_model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional app_label.ModelName keystone model reference.",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Special command",
                "verbose_name_plural": "Special commands",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SpecialCommandParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "cli_name",
                    models.CharField(
                        help_text="Argument flag (e.g. --enabled) or positional name.",
                        max_length=64,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("positional", "Positional"),
                            ("option", "Option"),
                            ("flag", "Flag"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("boolean", "Boolean"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("allows_multiple", models.BooleanField(default=False)),
                ("choices", models.JSONField(blank=True, default=list)),
                ("help_text", models.TextField(blank=True, default="")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "command",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="special.specialcommand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Special command parameter",
                "verbose_name_plural": "Special command parameters",
                "ordering": ("command", "sort_order", "id"),
                "unique_together": {("command", "cli_name"), ("command", "name")},
            },
        ),
    ]
