# Generated by Django 5.2.11 on 2026-02-24 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Blog series",
                "verbose_name_plural": "Blog series",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="BlogTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("label", models.CharField(max_length=80, unique=True)),
            ],
            options={
                "ordering": ("label",),
            },
        ),
        migrations.CreateModel(
            name="BlogArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=150, unique=True)),
                ("title", models.CharField(max_length=220)),
                ("subtitle", models.CharField(blank=True, max_length=260)),
                ("excerpt", models.TextField(blank=True)),
                ("body", models.TextField()),
                (
                    "body_format",
                    models.CharField(
                        choices=[("markdown", "Markdown"), ("html", "HTML")],
                        default="markdown",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In review"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("publish_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("canonical_url", models.URLField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("allow_comments", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="review_blog_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="blog.blogseries",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="articles", to="blog.blogtag"
                    ),
                ),
            ],
            options={
                "ordering": ("-published_at", "-updated_at"),
            },
        ),
        migrations.CreateModel(
            name="BlogCodeReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=140)),
                ("repository_path", models.CharField(max_length=255)),
                ("start_line", models.PositiveIntegerField(default=1)),
                ("end_line", models.PositiveIntegerField(default=1)),
                ("language", models.CharField(blank=True, max_length=40)),
                ("highlight_lines", models.CharField(blank=True, max_length=120)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_references",
                        to="blog.blogarticle",
                    ),
                ),
            ],
            options={
                "ordering": ("repository_path", "start_line"),
            },
        ),
        migrations.CreateModel(
            name="BlogRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("body", models.TextField()),
                ("change_note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="blog.blogarticle",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="BlogSigilShortcut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=80)),
                (
                    "expansion_template",
                    models.TextField(
                        help_text="Template inserted when this token is resolved in article content."
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sigil_shortcuts",
                        to="blog.blogarticle",
                    ),
                ),
            ],
            options={
                "ordering": ("token",),
                "unique_together": {("article", "token")},
            },
        ),
    ]
