# Generated by Django 5.2.12 on 2026-03-27 20:33

import apps.sigils.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for this spreadsheet registration.",
                        max_length=255,
                    ),
                ),
                (
                    "spreadsheet_id",
                    models.CharField(
                        help_text="Spreadsheet ID from the Google Sheets URL.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "default_worksheet",
                    models.CharField(
                        default="Sheet1",
                        help_text="Default worksheet/tab to query when none is specified.",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Cached metadata fetched from Google Sheets API.",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Disable to avoid selecting this sheet in integrations.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Sheet",
                "verbose_name_plural": "Google Sheets",
            },
        ),
        migrations.CreateModel(
            name="GoogleSheetColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "worksheet",
                    models.CharField(
                        default="Sheet1",
                        help_text="Worksheet/tab name where this column was introspected.",
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Column header as seen in the worksheet.",
                        max_length=255,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Zero-based column position in the worksheet.",
                    ),
                ),
                (
                    "detected_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("boolean", "Boolean"),
                            ("datetime", "Date/Time"),
                        ],
                        default="string",
                        help_text="Best-effort type inferred from sampled data.",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Sheet column",
                "verbose_name_plural": "Google Sheet columns",
                "ordering": ["sheet", "worksheet", "position"],
            },
        ),
        migrations.CreateModel(
            name="GoogleAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Google account email used for this integration.",
                        max_length=254,
                    ),
                ),
                (
                    "client_id",
                    apps.sigils.fields.SigilShortAutoField(
                        help_text="OAuth client ID from Google Cloud.", max_length=255
                    ),
                ),
                (
                    "client_secret",
                    apps.sigils.fields.SigilShortAutoField(
                        help_text="OAuth client secret from Google Cloud.",
                        max_length=255,
                    ),
                ),
                (
                    "refresh_token",
                    apps.sigils.fields.SigilShortAutoField(
                        help_text="Refresh token granted for offline access.",
                        max_length=255,
                    ),
                ),
                (
                    "access_token",
                    apps.sigils.fields.SigilShortAutoField(
                        blank=True,
                        help_text="Cached access token used for API requests.",
                        max_length=255,
                    ),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="UTC timestamp when the cached token expires.",
                        null=True,
                    ),
                ),
                (
                    "scopes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="OAuth scopes granted to this account.",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Disable to block API usage from this account.",
                    ),
                ),
                (
                    "avatar",
                    models.ForeignKey(
                        blank=True,
                        help_text="Avatar that owns this profile when not linked directly to a user or group.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="chats.chatavatar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Google account",
                "verbose_name_plural": "Google accounts",
            },
        ),
    ]
