# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gdrive", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="googleaccount",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User that owns this object.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="googlesheet",
            name="account",
            field=models.ForeignKey(
                blank=True,
                help_text="Google account used to access this spreadsheet.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sheets",
                to="gdrive.googleaccount",
            ),
        ),
        migrations.AddField(
            model_name="googlesheetcolumn",
            name="sheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="gdrive.googlesheet",
            ),
        ),
        migrations.AddConstraint(
            model_name="googlesheetcolumn",
            constraint=models.UniqueConstraint(
                fields=("sheet", "worksheet", "name"),
                name="gdrive_unique_sheet_column_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="googlesheetcolumn",
            constraint=models.UniqueConstraint(
                fields=("sheet", "worksheet", "position"),
                name="gdrive_unique_sheet_column_position",
            ),
        ),
    ]
