# Generated by Django 5.2.8 on 2025-12-05 02:53

import django.utils.timezone
import uuid
from django.db import migrations, models
from utils.migration_branches import BranchTagOperation


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        BranchTagOperation("rebuild-20251205025325", migration_label="chats.0001_initial", project_apps=('app', 'awg', 'cards', 'celery', 'chats', 'content', 'core', 'counters', 'dns', 'docs', 'emails', 'embeds', 'energy', 'flows', 'groups', 'links', 'locale', 'locals', 'maps', 'media', 'meta', 'nmcli', 'nodes', 'ocpp', 'odoo', 'pages', 'payments', 'protocols', 'rates', 'release', 'repos', 'screens', 'sigils', 'tasks', 'teams', 'users', 'vehicle')),
        migrations.CreateModel(
            name="ChatAvatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=150)),
                ("photo", models.ImageField(blank=True, upload_to="chats/avatars/")),
                ("is_enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Chat Avatar",
                "verbose_name_plural": "Chat Avatars",
                "ordering": ["name", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("sender_display_name", models.CharField(blank=True, max_length=150)),
                ("from_staff", models.BooleanField(default=False)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "pages_chatmessage",
                "ordering": ["created_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "visitor_key",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="WhatsApp sender identifier associated with the chat session.",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("escalated", "Escalated"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_activity_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_visitor_activity_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_staff_activity_at", models.DateTimeField(blank=True, null=True)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "pages_chatsession",
                "ordering": ["-last_activity_at", "-pk"],
            },
        ),
    ]
