# Generated by Django 5.2.10 on 2026-02-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmcli", "0002_apclient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apclient",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
