"""Tests for requirements generation from pyproject dependencies."""

from __future__ import annotations

from pathlib import Path

import pytest

from scripts import generate_requirements


@pytest.fixture()
def project_files(tmp_path: Path) -> tuple[Path, Path]:
    """Create temporary pyproject and requirements file paths."""
    return tmp_path / "pyproject.toml", tmp_path / "requirements.txt"


def test_generate_requirements_writes_runtime_and_ci_dependencies_sorted(
    project_files: tuple[Path, Path],
) -> None:
    """Generator writes sorted runtime+ci dependencies and metadata comments."""
    pyproject_path, requirements_path = project_files
    pyproject_path.write_text(
        """
[project]
dependencies = [
  "websockets>=15,<17",
  "Django==5.2.11",
]

[project.optional-dependencies]
ci = ["pytest==9.0.2"]
""".strip()
        + "\n",
        encoding="utf-8",
    )

    generate_requirements.generate_requirements(pyproject_path, requirements_path)

    expected = "\n".join(
        [
            "# This file is generated from pyproject.toml project + ci dependencies.",
            "# Regenerate with: python scripts/generate_requirements.py",
            "# Do not edit this file manually.",
            "",
            "Django==5.2.11",
            "pytest==9.0.2",
            "websockets>=15,<17",
            "",
        ]
    )
    assert requirements_path.read_text(encoding="utf-8") == expected


def test_check_requirements_detects_drift(project_files: tuple[Path, Path]) -> None:
    """Check mode fails when committed requirements diverge from generated output."""
    pyproject_path, requirements_path = project_files
    pyproject_path.write_text("[project]\ndependencies = [\"a==1\"]\n", encoding="utf-8")
    requirements_path.write_text("a==2\n", encoding="utf-8")

    assert not generate_requirements.check_requirements(pyproject_path, requirements_path)


def test_load_runtime_dependencies_requires_project_section(
    project_files: tuple[Path, Path],
) -> None:
    """Loading dependencies raises a specific error when project metadata is absent."""
    pyproject_path, _ = project_files
    pyproject_path.write_text("[tool.black]\nline-length = 88\n", encoding="utf-8")

    with pytest.raises(generate_requirements.RequirementsGenerationError):
        generate_requirements._load_runtime_dependencies(pyproject_path)
