# Generated by Django 5.2.8 on 2025-12-03 16:17

import apps.sigils.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayPalProcessor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("verified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_reference",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "client_id",
                    apps.sigils.fields.SigilShortAutoField(blank=True, max_length=255),
                ),
                (
                    "client_secret",
                    apps.sigils.fields.SigilShortAutoField(blank=True, max_length=255),
                ),
                (
                    "webhook_id",
                    apps.sigils.fields.SigilShortAutoField(blank=True, max_length=255),
                ),
                ("is_production", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "PayPal Processor",
                "verbose_name_plural": "PayPal Processors",
            },
        ),
        migrations.CreateModel(
            name="StripeProcessor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("verified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_reference",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "secret_key",
                    apps.sigils.fields.SigilShortAutoField(blank=True, max_length=255),
                ),
                (
                    "publishable_key",
                    apps.sigils.fields.SigilShortAutoField(blank=True, max_length=255),
                ),
                (
                    "webhook_secret",
                    apps.sigils.fields.SigilShortAutoField(blank=True, max_length=255),
                ),
                ("is_production", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Stripe Processor",
                "verbose_name_plural": "Stripe Processors",
            },
        ),
        migrations.CreateModel(
            name="OpenPayProcessor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("verified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_reference",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "merchant_id",
                    apps.sigils.fields.SigilShortAutoField(blank=True, max_length=100),
                ),
                (
                    "private_key",
                    apps.sigils.fields.SigilShortAutoField(blank=True, max_length=255),
                ),
                (
                    "public_key",
                    apps.sigils.fields.SigilShortAutoField(blank=True, max_length=255),
                ),
                ("is_production", models.BooleanField(default=False)),
                (
                    "webhook_secret",
                    apps.sigils.fields.SigilShortAutoField(blank=True, max_length=255),
                ),
                (
                    "group",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="groups.securitygroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "OpenPay Processor",
                "verbose_name_plural": "OpenPay Processors",
            },
        ),
    ]
