# Generated by Django 5.2.8 on 2025-12-01 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from apps.migration_utils import import_callable


SigilShortAutoField = import_callable(
    "apps.sigils.fields.SigilShortAutoField", default=models.CharField
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenPayProcessor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("verified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_reference",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Use this processor first when charging.",
                    ),
                ),
                (
                    "merchant_id",
                    SigilShortAutoField(blank=True, max_length=100),
                ),
                (
                    "private_key",
                    SigilShortAutoField(blank=True, max_length=255),
                ),
                (
                    "public_key",
                    SigilShortAutoField(blank=True, max_length=255),
                ),
                ("is_production", models.BooleanField(default=False)),
                (
                    "webhook_secret",
                    SigilShortAutoField(blank=True, max_length=255),
                ),
                (
                    "group",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.securitygroup",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OpenPay Processor",
                "verbose_name_plural": "OpenPay Processors",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("user__isnull", False), ("group__isnull", True)),
                            models.Q(("user__isnull", True), ("group__isnull", False)),
                            _connector="OR",
                        ),
                        name="openpayprocessor_requires_owner",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PayPalProcessor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("verified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_reference",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Use this processor first when charging.",
                    ),
                ),
                (
                    "client_id",
                    SigilShortAutoField(blank=True, max_length=255),
                ),
                (
                    "client_secret",
                    SigilShortAutoField(blank=True, max_length=255),
                ),
                (
                    "webhook_id",
                    SigilShortAutoField(blank=True, max_length=255),
                ),
                ("is_production", models.BooleanField(default=False)),
                (
                    "group",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.securitygroup",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PayPal Processor",
                "verbose_name_plural": "PayPal Processors",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("user__isnull", False), ("group__isnull", True)),
                            models.Q(("user__isnull", True), ("group__isnull", False)),
                            _connector="OR",
                        ),
                        name="paypalprocessor_requires_owner",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StripeProcessor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("verified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_reference",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Use this processor first when charging.",
                    ),
                ),
                (
                    "secret_key",
                    SigilShortAutoField(blank=True, max_length=255),
                ),
                (
                    "publishable_key",
                    SigilShortAutoField(blank=True, max_length=255),
                ),
                (
                    "webhook_secret",
                    SigilShortAutoField(blank=True, max_length=255),
                ),
                ("is_production", models.BooleanField(default=False)),
                (
                    "group",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.securitygroup",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stripe Processor",
                "verbose_name_plural": "Stripe Processors",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("user__isnull", False), ("group__isnull", True)),
                            models.Q(("user__isnull", True), ("group__isnull", False)),
                            _connector="OR",
                        ),
                        name="stripeprocessor_requires_owner",
                    )
                ],
            },
        ),
    ]
