# Generated by Django 5.2.8 on 2025-12-03 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0002_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="openpayprocessor",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paypalprocessor",
            name="group",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="groups.securitygroup",
            ),
        ),
        migrations.AddField(
            model_name="paypalprocessor",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stripeprocessor",
            name="group",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="groups.securitygroup",
            ),
        ),
        migrations.AddField(
            model_name="stripeprocessor",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="openpayprocessor",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("user__isnull", False), ("group__isnull", True)),
                    models.Q(("user__isnull", True), ("group__isnull", False)),
                    _connector="OR",
                ),
                name="openpayprocessor_requires_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="paypalprocessor",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("user__isnull", False), ("group__isnull", True)),
                    models.Q(("user__isnull", True), ("group__isnull", False)),
                    _connector="OR",
                ),
                name="paypalprocessor_requires_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="stripeprocessor",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("user__isnull", False), ("group__isnull", True)),
                    models.Q(("user__isnull", True), ("group__isnull", False)),
                    _connector="OR",
                ),
                name="stripeprocessor_requires_owner",
            ),
        ),
    ]
