# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audio", "0002_initial"),
        ("nodes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordingdevice",
            name="node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recording_devices",
                to="nodes.node",
            ),
        ),
        migrations.AddConstraint(
            model_name="recordingdevice",
            constraint=models.UniqueConstraint(
                fields=("node", "identifier"), name="audio_recordingdevice_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="recordingdevice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("node",),
                name="audio_recordingdevice_default_per_node",
            ),
        ),
    ]
