# Generated by Django 5.2.10 on 2026-01-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0008_videodevice_default_name_base"),
    ]

    operations = [
        migrations.AddField(
            model_name="videodevice",
            name="auto_rotate",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "0°"), (90, "90°"), (180, "180°"), (270, "270°")],
                default=0,
                help_text="Rotate captured frames counterclockwise.",
            ),
        ),
    ]
