# Generated by Django 5.2.4 on 2025-08-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('text', 'file_path', 'line_number')},
            },
        ),
    ]
