# Generated by Django 5.2.4 on 2025-09-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("man", "0002_rpi_control_manual"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usermanual",
            options={
                "verbose_name": "User Manual",
                "verbose_name_plural": "User Manuals",
            },
        ),
        migrations.AddField(
            model_name="usermanual",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="usermanual",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
