# Generated by Django 5.2.11 on 2026-02-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pyxel", "0001_initial"),
        ("screens", "0003_lcdanimation"),
    ]

    operations = [
        migrations.AddField(
            model_name="pyxelviewport",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Use as the default viewport when opening from admin list actions.",
            ),
        ),
        migrations.AddConstraint(
            model_name="pyxelviewport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="pyxel_single_default_viewport",
            ),
        ),
    ]
