# Generated by Django 5.2.15 on 2026-07-02 12:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaspberryPiImageArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('target', models.CharField(default='rpi-4b', max_length=40)),
                ('base_image_uri', models.CharField(max_length=500)),
                ('output_filename', models.CharField(max_length=255)),
                ('output_path', models.CharField(max_length=500)),
                ('sha256', models.CharField(max_length=64)),
                ('size_bytes', models.BigIntegerField()),
                ('download_uri', models.URLField(blank=True, default='')),
                ('build_engine', models.CharField(default='arthexis-bootstrap', max_length=80)),
                ('build_profile', models.CharField(default='bootstrap', max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Raspberry Pi image artifact',
                'verbose_name_plural': 'Raspberry Pi image artifacts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RaspberryPiImageBurnJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('artifact_name', models.CharField(blank=True, default='', max_length=120)),
                ('image_path', models.CharField(blank=True, default='', max_length=500)),
                ('image_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('image_size_bytes', models.BigIntegerField(default=0)),
                ('device_path', models.CharField(max_length=255)),
                ('device_identity', models.JSONField(blank=True, default=dict)),
                ('backup', models.BooleanField(default=False)),
                ('backup_dir', models.CharField(blank=True, default='', max_length=500)),
                ('progress_bytes', models.BigIntegerField(default=0)),
                ('progress_total_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='queued', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('log', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='burn_jobs', to='imager.raspberrypiimageartifact')),
            ],
            options={
                'verbose_name': 'Raspberry Pi image burn job',
                'verbose_name_plural': 'Raspberry Pi image burn jobs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='imager_rasp_status_1231be_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(models.Q(('artifact_name', ''), _negated=True), ('image_path', '')), models.Q(('artifact_name', ''), models.Q(('image_path', ''), _negated=True)), _connector='OR'), name='imager_burn_job_exactly_one_source')],
            },
        ),
    ]
