# Generated by Django 5.2.12 on 2026-04-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="raspberrypiimageartifact",
            name="build_engine",
            field=models.CharField(default="arthexis-bootstrap", max_length=80),
        ),
        migrations.AddField(
            model_name="raspberrypiimageartifact",
            name="build_profile",
            field=models.CharField(default="bootstrap", max_length=80),
        ),
    ]
