# Generated by Django 5.2.8 on 2025-12-05 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django_otp.util import hex_validator


def default_key():
    from django_otp.util import random_hex

    return random_hex(20)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("groups", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TOTPDevice",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user that this device belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_totp_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The human-readable name of this device.",
                        max_length=64,
                        verbose_name="name",
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(
                        default=True, help_text="Is this device ready for use?"
                    ),
                ),
                (
                    "throttling_failure_timestamp",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text=(
                            "A timestamp of the last failed verification attempt. Null if last attempt"
                            " succeeded."
                        ),
                        null=True,
                    ),
                ),
                (
                    "throttling_failure_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of successive failed attempts."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when this device was initially created in the system.",
                        null=True,
                        blank=True,
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        help_text="The most recent date and time this device was used.",
                        null=True,
                        blank=True,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default=default_key,
                        help_text="A hex-encoded secret key of up to 40 bytes.",
                        max_length=80,
                        validators=[hex_validator()],
                    ),
                ),
                ("step", models.PositiveSmallIntegerField(default=30, help_text="The time step in seconds.")),
                (
                    "t0",
                    models.BigIntegerField(
                        default=0, help_text="The Unix time at which to begin counting steps."
                    ),
                ),
                (
                    "digits",
                    models.PositiveSmallIntegerField(
                        choices=[(6, 6), (8, 8)],
                        default=6,
                        help_text="The number of digits to expect in a token.",
                    ),
                ),
                (
                    "tolerance",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="The number of time steps in the past or future to allow."
                    ),
                ),
                (
                    "drift",
                    models.SmallIntegerField(
                        default=0,
                        help_text="The number of time steps the prover is known to deviate from our clock.",
                    ),
                ),
                (
                    "last_t",
                    models.BigIntegerField(
                        default=-1,
                        help_text="The t value of the latest verified token. The next token must be at a higher time step.",
                    ),
                ),
            ],
            options={"verbose_name": "TOTP device", "db_table": "otp_totp_totpdevice"},
        ),
        migrations.CreateModel(
            name="TOTPDeviceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "issuer",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Label shown in authenticator apps. Leave blank to use Arthexis.",
                        max_length=64,
                    ),
                ),
                (
                    "allow_without_password",
                    models.BooleanField(
                        default=False,
                        help_text="Allow authenticator logins to skip the password step.",
                    ),
                ),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_settings",
                        to="users.totpdevice",
                    ),
                ),
                (
                    "security_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Share this authenticator with every user in the selected security group.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="totp_devices",
                        to="groups.securitygroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Authenticator Device Setting",
                "verbose_name_plural": "Authenticator Device Settings",
                "db_table": "core_totpdevicesettings",
            },
        ),
    ]
