# Generated by Django 5.2.8 on 2025-12-06 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TOTPDevice",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("django_otp.totpdevice",),
        ),
        migrations.CreateModel(
            name="TOTPDeviceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "issuer",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Label shown in authenticator apps. Leave blank to use Arthexis.",
                        max_length=64,
                    ),
                ),
                (
                    "allow_without_password",
                    models.BooleanField(
                        default=False,
                        help_text="Allow authenticator logins to skip the password step.",
                    ),
                ),
                (
                    "security_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Share this authenticator with every user in the selected security group.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="totp_devices",
                        to="groups.securitygroup",
                    ),
                ),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_settings",
                        to="users.totpdevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Authenticator Device Setting",
                "verbose_name_plural": "Authenticator Device Settings",
                "db_table": "core_totpdevicesettings",
            },
        ),
    ]
