# Generated by Django 5.2.12 on 2026-04-04 13:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_initial"),
        ("groups", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDiagnosticsProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_default=True,
                        default=True,
                        help_text="Disable this profile without deleting saved preferences.",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "collect_diagnostics",
                    models.BooleanField(
                        db_default=False,
                        default=False,
                        help_text="Allow Arthexis to collect request error context for bug fixing and development.",
                        verbose_name="Collect diagnostics",
                    ),
                ),
                (
                    "allow_manual_feedback",
                    models.BooleanField(
                        db_default=True,
                        default=True,
                        help_text="Allow staff to attach manual feedback notes to diagnostics logs.",
                        verbose_name="Allow manual feedback",
                    ),
                ),
                (
                    "avatar",
                    models.ForeignKey(
                        blank=True,
                        help_text="Avatar that owns this profile when not linked directly to a user or group.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="chats.chatavatar",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Security group that owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="groups.securitygroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User that owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Diagnostics Profile",
                "verbose_name_plural": "User Diagnostics Profiles",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserDiagnosticEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "source",
                    models.CharField(
                        choices=[("error", "Error"), ("feedback", "Manual feedback")],
                        default="error",
                        max_length=20,
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                ("details", models.TextField(blank=True)),
                ("request_method", models.CharField(blank=True, max_length=16)),
                ("request_path", models.CharField(blank=True, max_length=500)),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("fingerprint", models.CharField(db_index=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnostic_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="users.userdiagnosticsprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Diagnostic Event",
                "verbose_name_plural": "User Diagnostic Events",
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="UserDiagnosticBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("title", models.CharField(max_length=200)),
                (
                    "report",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable report bundle text to copy into a patch request.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnostic_bundles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "events",
                    models.ManyToManyField(
                        blank=True,
                        related_name="bundles",
                        to="users.userdiagnosticevent",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bundles",
                        to="users.userdiagnosticsprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Diagnostic Bundle",
                "verbose_name_plural": "User Diagnostic Bundles",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="userdiagnosticsprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("avatar__isnull", True),
                        ("group__isnull", True),
                        ("user__isnull", False),
                    ),
                    models.Q(
                        ("avatar__isnull", True),
                        ("group__isnull", False),
                        ("user__isnull", True),
                    ),
                    models.Q(
                        ("avatar__isnull", False),
                        ("group__isnull", True),
                        ("user__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="users_diag_profile_exactly_one_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="userdiagnosticsprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user",),
                name="users_diag_profile_unique_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="userdiagnosticsprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("group__isnull", False)),
                fields=("group",),
                name="users_diag_profile_unique_group",
            ),
        ),
        migrations.AddConstraint(
            model_name="userdiagnosticsprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("avatar__isnull", False)),
                fields=("avatar",),
                name="users_diag_profile_unique_avatar",
            ),
        ),
    ]
