# Generated by Django 5.2.8 on 2025-12-05 23:27

from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models


def _otp_totp_installed():
    installed_apps = set(settings.INSTALLED_APPS)
    return "otp_totp" in installed_apps or "django_otp.plugins.otp_totp" in installed_apps


class Migration(migrations.Migration):

    if _otp_totp_installed():
        dependencies = [
            ("otp_totp", "0003_add_timestamps"),
            ("users", "0002_totpdevicesettings"),
        ]

        operations = [
            migrations.CreateModel(
                name="TOTPDevice",
                fields=[],
                options={
                    "proxy": True,
                    "indexes": [],
                    "constraints": [],
                },
                bases=("otp_totp.totpdevice",),
            ),
            migrations.AlterField(
                model_name="totpdevicesettings",
                name="device",
                field=models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="custom_settings",
                    to="users.totpdevice",
                ),
            ),
        ]
    else:
        dependencies = [("users", "0002_totpdevicesettings")]
        operations = []
