# Generated by Django 5.2.8 on 2025-12-06 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_totpdevice_id_alter_totpdevice_key_and_more"),
        ("users", "0003_totpdevice_alter_totpdevicesettings_device"),
    ]

    operations = []
