# Generated by Django 5.2.12 on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_userdiagnosticbundle_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allow_local_network_passwordless_login",
            field=models.BooleanField(
                default=False,
                help_text="Allow this non-staff user to sign in from local IPv4 /16 peers without a password check.",
                verbose_name="allow local network passwordless login",
            ),
        ),
    ]
