# Generated by Django 5.2.11 on 2026-03-01 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0002_initial"),
        ("groups", "0003_site_operator_group"),
        ("users", "0003_user_login_rfid_user_login_rfid_block_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_default=True,
                        default=True,
                        help_text="Disable this profile without deleting the saved preference.",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "contact_via_chat",
                    models.BooleanField(
                        db_default=False,
                        default=False,
                        help_text="Allow support staff to contact this owner using the chat channel.",
                        verbose_name="I would like to be contacted via chat",
                    ),
                ),
                (
                    "avatar",
                    models.ForeignKey(
                        blank=True,
                        help_text="Avatar that owns this profile when not linked directly to a user or group.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="chats.chatavatar",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Security group that owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="groups.securitygroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User that owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Profile",
                "verbose_name_plural": "Chat Profiles",
            },
        ),
    ]
