# Generated by Django 5.2.11 on 2026-03-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0004_alter_chatavatar_group_alter_chatavatar_user"),
        ("groups", "0003_site_operator_group"),
        ("users", "0004_chatprofile"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="chatprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("avatar__isnull", True),
                        ("group__isnull", True),
                        ("user__isnull", False),
                    ),
                    models.Q(
                        ("avatar__isnull", True),
                        ("group__isnull", False),
                        ("user__isnull", True),
                    ),
                    models.Q(
                        ("avatar__isnull", False),
                        ("group__isnull", True),
                        ("user__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="chat_profile_exactly_one_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user",),
                name="chat_profile_unique_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("group__isnull", False)),
                fields=("group",),
                name="chat_profile_unique_group",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("avatar__isnull", False)),
                fields=("avatar",),
                name="chat_profile_unique_avatar",
            ),
        ),
    ]
