# Generated by Django 5.2.8 on 2025-12-06 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_otp", "0001_initial"),
        ("users", "0004_merge_20251205_1922"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TOTPDevice",
        ),
        migrations.CreateModel(
            name="TOTPDevice",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("django_otp.totpdevice",),
        ),
    ]
