# Generated by Django 5.2.12 on 2026-03-10 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_force_password_change"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique key for this user-level configuration flag.",
                        max_length=100,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_default=True,
                        default=True,
                        help_text="Whether the flag is currently active.",
                    ),
                ),
                (
                    "value",
                    models.JSONField(
                        blank=True,
                        help_text="Optional JSON value attached to this flag.",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Flag",
                "verbose_name_plural": "User Flags",
                "ordering": ["user__username", "key", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "key"),
                        name="users_userflag_unique_key_per_user",
                    )
                ],
            },
        ),
    ]
