# Generated by Django 5.2.12 on 2026-03-27 20:33

import apps.locals.caches
import apps.sigils.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "implementation",
                    models.CharField(
                        choices=[
                            ("condition", "SQL + Sigil comparison"),
                            ("python", "Python callable"),
                        ],
                        default="python",
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    apps.sigils.fields.ConditionTextField(blank=True, default=""),
                ),
                (
                    "condition_operator",
                    models.CharField(
                        choices=[
                            ("=", "Equals"),
                            (">", "Greater than"),
                            (">=", "Greater than or equal"),
                            ("<", "Less than"),
                            ("<=", "Less than or equal"),
                            ("!=", "Not equal"),
                        ],
                        default="=",
                        max_length=4,
                    ),
                ),
                (
                    "condition_source",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "condition_expected_boolean",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "condition_expected_number",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "condition_expected_text",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("condition_requires_triage", models.BooleanField(default=False)),
                (
                    "condition_triage_note",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("function_name", models.CharField(blank=True, max_length=255)),
                (
                    "success_message",
                    models.CharField(default="All rules met.", max_length=200),
                ),
                ("failure_message", models.CharField(blank=True, max_length=500)),
                (
                    "content_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_rule",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Rule",
                "verbose_name_plural": "Dashboard Rules",
                "ordering": ["name"],
            },
            bases=(apps.locals.caches.CacheStoreMixin, models.Model),
        ),
    ]
