# Generated by Django 5.2.8 on 2025-11-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="badgecounter",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="badgecounter",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="badgecounter",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
