# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0001_initial"),
        ("features", "0001_initial"),
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Security group that owns this object.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="groups.securitygroup",
            ),
        ),
        migrations.AddField(
            model_name="feature",
            name="main_app",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary application that owns most of the implementation for this feature.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="features",
                to="app.application",
            ),
        ),
    ]
