# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("features", "0002_initial"),
        ("nodes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="node_feature",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional node feature that must be enabled for this feature to unlock.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suite_features",
                to="nodes.nodefeature",
            ),
        ),
    ]
