# Generated by Django 5.2.10 on 2026-02-06 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0005_update_standard_charge_point"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feature",
            options={
                "ordering": ["display"],
                "verbose_name": "Suite Feature",
                "verbose_name_plural": "Suite Features",
            },
        ),
    ]
