# Generated by Django 5.2.10 on 2026-02-06 22:02

from typing import ClassVar

from django.db import migrations


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("features", "0005_update_standard_charge_point"),
    ]

    operations: ClassVar[list[migrations.AlterModelOptions]] = [
        migrations.AlterModelOptions(
            name="feature",
            options={
                "ordering": ["display"],
                "verbose_name": "Suite Feature",
                "verbose_name_plural": "Suite Features",
            },
        ),
    ]
