# Generated by Django 5.2.11 on 2026-02-24 19:24

from django.db import migrations, models


def set_seed_features_mainstream(apps, schema_editor):
    """Mark seeded suite features as mainstream and local rows as custom."""

    del schema_editor
    Feature = apps.get_model("features", "Feature")
    feature_manager = getattr(Feature, "all_objects", Feature._base_manager)
    feature_manager.filter(is_seed_data=True).update(source="mainstream")
    feature_manager.filter(is_seed_data=False).update(source="custom")


def unset_feature_source(apps, schema_editor):
    """Restore source values to custom during migration rollback."""

    del schema_editor
    Feature = apps.get_model("features", "Feature")
    feature_manager = getattr(Feature, "all_objects", Feature._base_manager)
    feature_manager.update(source="custom")


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0011_rework_evergo_api_client_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="source",
            field=models.CharField(
                choices=[("mainstream", "Mainstream"), ("custom", "Custom")],
                default="custom",
                editable=False,
                help_text="Feature origin. Mainstream features come from development fixtures; custom features are local.",
                max_length=20,
            ),
        ),
        migrations.RunPython(set_seed_features_mainstream, unset_feature_source),
    ]
