# Generated by Django 5.2.11 on 2026-02-24 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0011_rebrand_ocpp_ftp_server"),
        ("features", "0011_rework_evergo_api_client_feature"),
    ]

    operations = []
