# Generated by Django 5.2.11 on 2026-02-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0012_feature_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="source",
            field=models.CharField(
                choices=[("mainstream", "Main"), ("custom", "Custom")],
                default="custom",
                editable=False,
                help_text="Feature origin. Main features come from development fixtures; custom features are local.",
                max_length=20,
            ),
        ),
    ]
