# Generated by Django 5.2.11 on 2026-02-24 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0012_merge_20260224_0001"),
        ("features", "0012_merge_20260224_1507"),
        ("features", "0012_seed_development_blog_suite_feature"),
        ("features", "0013_alter_feature_source"),
    ]

    operations = []
