# Generated by Django 5.2.11 on 2026-02-25 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0016_merge_20260224_2038"),
        ("features", "0016_merge_20260225_0001"),
    ]

    operations = []
