# Generated by Django 5.2.11 on 2026-02-26 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0018_rename_development_blog_feature"),
        ("features", "0018_seed_operator_site_interface"),
    ]

    operations = []
