# Generated by Django 5.2.11 on 2026-02-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0020_remove_ftp_reports_node_feature_dependency"),
        ("features", "0020_seed_staff_chat_bridge_feature"),
    ]

    operations = []
