# Generated by Django 5.2.11 on 2026-03-01 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0020_seed_screenshot_capture_feature"),
        ("features", "0024_merge_20260228_1838"),
    ]

    operations = []
