# Generated by Django 5.2.11 on 2026-03-08 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0034_move_odoo_sync_integrations_to_parameters"),
        ("features", "0034_seed_celery_workers_suite_feature"),
    ]

    operations = []
