# Generated by Django 5.2.11 on 2026-03-09 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0038_merge_20260308_1856"),
        ("features", "0038_seed_llm_summary_suite_feature"),
    ]

    operations = []
