# Generated by Django 5.2.11 on 2026-03-09 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0041_merge_20260309_0000"),
        ("features", "0042_seed_release_management_suite_feature"),
    ]

    operations = []
