# Generated by Django 5.2.11 on 2026-03-10 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0043_merge_20260309_1458"),
        ("features", "0043_merge_and_seed_ocpp_simulator_backend_defaults"),
    ]

    operations = []
