# Generated by Django 5.2.15 on 2026-07-02 12:13

import apps.sites.models.user_story
import django.contrib.sites.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seed_data', models.BooleanField(default=False, editable=False)),
                ('is_user_data', models.BooleanField(default=False, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('path', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('agent_notes', models.TextField(blank=True, help_text='Hidden, agent-facing guidance about what this landing is best used for.')),
                ('validation_status', models.IntegerField(blank=True, help_text='HTTP status code from the last landing validation attempt.', null=True, verbose_name='Validation Status')),
                ('validated_url_at', models.DateTimeField(blank=True, help_text='Timestamp of the last landing validation check.', null=True, verbose_name='Validated URL')),
            ],
            options={
                'verbose_name': 'Landing',
                'verbose_name_plural': 'Landings',
            },
        ),
        migrations.CreateModel(
            name='ReferrerLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seed_data', models.BooleanField(default=False, editable=False)),
                ('is_user_data', models.BooleanField(default=False, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('referrer_domain', models.CharField(help_text='Referrer domain to match, such as example.com', max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Referrer Landing',
                'verbose_name_plural': 'Referrer Landings',
            },
        ),
        migrations.CreateModel(
            name='SiteBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seed_data', models.BooleanField(default=False, editable=False)),
                ('is_user_data', models.BooleanField(default=False, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('badge_color', models.CharField(default='#28a745', max_length=7)),
            ],
            options={
                'verbose_name': 'Site Badge',
                'verbose_name_plural': 'Site Badges',
            },
        ),
        migrations.CreateModel(
            name='SiteHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('highlight_date', models.DateField(help_text='Date shown with this highlight.')),
                ('story', models.TextField(help_text='Short highlight story. URLs are auto-linked on the public site.')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this highlight is eligible to appear on the public site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Highlight',
                'verbose_name_plural': 'Site Highlights',
                'ordering': ('-highlight_date', '-updated_at', '-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='SiteModuleVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seed_data', models.BooleanField(default=False, editable=False)),
                ('is_user_data', models.BooleanField(default=False, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('visibility', models.CharField(choices=[('show', 'Show'), ('hide', 'Hide')], db_index=True, default='show', max_length=10)),
                ('audience', models.CharField(choices=[('all', 'All visitors'), ('anonymous', 'Anonymous visitors'), ('authenticated', 'Authenticated users')], db_index=True, default='all', max_length=20)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Site module visibility',
                'verbose_name_plural': 'Site module visibility rules',
                'ordering': ('site__domain', 'module__priority', 'module__path', 'audience'),
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_public_chat', models.BooleanField(db_default=False, default=False, help_text='Allow the chat button for all visitors on this site, including guests.', verbose_name='Enable public chat')),
                ('managed', models.BooleanField(db_default=False, default=False, help_text='Include this site when staging the local NGINX configuration.', verbose_name='Managed by local NGINX')),
                ('require_https', models.BooleanField(db_default=False, default=False, help_text='Redirect HTTP traffic to HTTPS when the staged NGINX configuration is applied.', verbose_name='Require HTTPS')),
            ],
            options={
                'verbose_name': 'Site profile',
                'verbose_name_plural': 'Site profiles',
            },
        ),
        migrations.CreateModel(
            name='SiteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seed_data', models.BooleanField(default=False, editable=False)),
                ('is_user_data', models.BooleanField(default=False, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('primary_color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g. #0d6efd).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('primary_color_emphasis', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g. #0d6efd).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('accent_color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g. #0d6efd).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('accent_color_emphasis', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g. #0d6efd).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('support_color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g. #0d6efd).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('support_color_emphasis', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g. #0d6efd).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('support_text_color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g. #0d6efd).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
            ],
            options={
                'verbose_name': 'Site Branding',
                'verbose_name_plural': 'Site Brandings',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seed_data', models.BooleanField(default=False, editable=False)),
                ('is_user_data', models.BooleanField(default=False, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('referer', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, validators=[django.core.validators.validate_ipv46_address])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('closed', 'Closed'), ('spam', 'Spam')], default='open', max_length=20)),
                ('path', models.CharField(max_length=500)),
                ('name', models.CharField(blank=True, max_length=40)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rate your experience from 1 (lowest) to 5 (highest).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(help_text='Share more about your experience.')),
                ('messages', models.TextField(blank=True, help_text='Messages displayed to the user when the feedback was submitted.', validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('contact_via_chat', models.BooleanField(db_default=False, default=False, help_text='Whether the submitter opted into chat follow-up during feedback.')),
                ('javascript_enabled', models.BooleanField(db_default=False, default=False, help_text='Whether JavaScript was enabled when feedback was submitted.')),
                ('screenshot', models.ImageField(blank=True, help_text='Optional screenshot captured while submitting feedback.', upload_to='sites/user_story_screenshots/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('github_issue_number', models.PositiveIntegerField(blank=True, help_text='Number of the GitHub issue created for this feedback.', null=True)),
                ('github_issue_url', models.URLField(blank=True, help_text='Link to the GitHub issue created for this feedback.')),
                ('language_code', models.CharField(blank=True, help_text='Language selected when the feedback was submitted.', max_length=15)),
                ('feedback_tags', models.JSONField(blank=True, default=list, help_text="Hash tags parsed from feedback text, normalized without '#'.")),
                ('allow_feedback_issue_label_tags', models.BooleanField(db_default=False, default=False, help_text='Whether parsed feedback hashtags may add matching existing GitHub labels when an issue is created.')),
                ('issue_destination', models.CharField(choices=[('github', 'GitHub'), ('local', 'Local queue')], db_index=True, default='github', help_text='Where this feedback should be triaged. #local keeps it in the local queue.', max_length=16)),
            ],
            options={
                'verbose_name': 'User Story',
                'verbose_name_plural': 'User Stories',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStoryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.sites.models.user_story.user_story_attachment_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Story Attachment',
                'verbose_name_plural': 'User Story Attachments',
                'ordering': ['uploaded_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seed_data', models.BooleanField(default=False, editable=False)),
                ('is_user_data', models.BooleanField(default=False, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('kind', models.CharField(choices=[('site', 'Site'), ('admin', 'Admin')], db_index=True, default='site', max_length=20)),
                ('path', models.CharField(max_length=2048)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('status_text', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('exception_name', models.CharField(blank=True, max_length=200)),
                ('view_name', models.CharField(blank=True, max_length=200)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'View History',
                'verbose_name_plural': 'View Histories',
                'ordering': ['-visited_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkgroupPlayPanelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('link', 'Link')], default='text', max_length=10)),
                ('body', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('link_url', models.URLField(blank=True)),
                ('link_label', models.CharField(blank=True, max_length=120)),
                ('is_enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workgroup Play Panel Item',
                'verbose_name_plural': 'Workgroup Play Panel Items',
                'ordering': ('priority', '-updated_at', '-created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SiteProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'permissions': [('add_siteproxy', 'Can add site'), ('change_siteproxy', 'Can change site'), ('delete_siteproxy', 'Can delete site'), ('view_siteproxy', 'Can view site')],
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('sites.site',),
            managers=[
                ('objects', django.contrib.sites.models.SiteManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seed_data', models.BooleanField(default=False, editable=False)),
                ('is_user_data', models.BooleanField(default=False, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('label', models.CharField(max_length=32)),
                ('provider_key', models.CharField(choices=[('site', 'Site'), ('node', 'Node'), ('role', 'Role')], default='site', max_length=20)),
                ('value_query_path', models.CharField(blank=True, default='', help_text='Deprecated: provider source is configured via Provider key.', max_length=255)),
                ('first_part', models.CharField(choices=[('label', 'Label'), ('value', 'Value')], default='label', max_length=10)),
                ('second_part', models.CharField(choices=[('label', 'Label'), ('value', 'Value')], default='value', max_length=10)),
                ('filled_color', models.CharField(default='#28a745', max_length=7)),
                ('missing_color', models.CharField(default='#6c757d', max_length=7)),
                ('is_enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('group', models.ForeignKey(blank=True, help_text='Security group that owns this object.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='groups.securitygroup')),
            ],
            options={
                'verbose_name': 'Admin Badge',
                'verbose_name_plural': 'Admin Badges',
                'ordering': ('priority', 'pk'),
            },
        ),
    ]
