# Generated by Django 5.2.12 on 2026-03-27 20:33

import apps.sites.models.user_story
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("label", models.CharField(max_length=32)),
                (
                    "provider_key",
                    models.CharField(
                        choices=[("site", "Site"), ("node", "Node"), ("role", "Role")],
                        default="site",
                        max_length=20,
                    ),
                ),
                (
                    "value_query_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Deprecated: provider source is configured via Provider key.",
                        max_length=255,
                    ),
                ),
                (
                    "first_part",
                    models.CharField(
                        choices=[("label", "Label"), ("value", "Value")],
                        default="label",
                        max_length=10,
                    ),
                ),
                (
                    "second_part",
                    models.CharField(
                        choices=[("label", "Label"), ("value", "Value")],
                        default="value",
                        max_length=10,
                    ),
                ),
                ("filled_color", models.CharField(default="#28a745", max_length=7)),
                ("missing_color", models.CharField(default="#6c757d", max_length=7)),
                ("is_enabled", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Admin Badge",
                "verbose_name_plural": "Admin Badges",
                "ordering": ("priority", "pk"),
            },
        ),
        migrations.CreateModel(
            name="Landing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("path", models.CharField(max_length=200)),
                ("label", models.CharField(max_length=100)),
                ("enabled", models.BooleanField(default=True)),
                ("track_leads", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                (
                    "agent_notes",
                    models.TextField(
                        blank=True,
                        help_text="Hidden, agent-facing guidance about what this landing is best used for.",
                    ),
                ),
                (
                    "validation_status",
                    models.IntegerField(
                        blank=True,
                        help_text="HTTP status code from the last landing validation attempt.",
                        null=True,
                        verbose_name="Validation Status",
                    ),
                ),
                (
                    "validated_url_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last landing validation check.",
                        null=True,
                        verbose_name="Validated URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "Landing",
                "verbose_name_plural": "Landings",
            },
        ),
        migrations.CreateModel(
            name="LandingLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("path", models.TextField(blank=True)),
                ("referer", models.TextField(blank=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "ip_address",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        validators=[django.core.validators.validate_ipv46_address],
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("assigned", "Assigned"),
                            ("closed", "Closed"),
                            ("spam", "Spam"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Landing Lead",
                "verbose_name_plural": "Landing Leads",
            },
        ),
        migrations.CreateModel(
            name="ReferrerLanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "referrer_domain",
                    models.CharField(
                        help_text="Referrer domain to match, such as example.com",
                        max_length=255,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Referrer Landing",
                "verbose_name_plural": "Referrer Landings",
            },
        ),
        migrations.CreateModel(
            name="SiteBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("badge_color", models.CharField(default="#28a745", max_length=7)),
            ],
            options={
                "verbose_name": "Site Badge",
                "verbose_name_plural": "Site Badges",
            },
        ),
        migrations.CreateModel(
            name="SiteTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "primary_color",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color code (e.g. #0d6efd).",
                                regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                            )
                        ],
                    ),
                ),
                (
                    "primary_color_emphasis",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color code (e.g. #0d6efd).",
                                regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                            )
                        ],
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color code (e.g. #0d6efd).",
                                regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                            )
                        ],
                    ),
                ),
                (
                    "accent_color_emphasis",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color code (e.g. #0d6efd).",
                                regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                            )
                        ],
                    ),
                ),
                (
                    "support_color",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color code (e.g. #0d6efd).",
                                regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                            )
                        ],
                    ),
                ),
                (
                    "support_color_emphasis",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color code (e.g. #0d6efd).",
                                regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                            )
                        ],
                    ),
                ),
                (
                    "support_text_color",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color code (e.g. #0d6efd).",
                                regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Branding",
                "verbose_name_plural": "Site Brandings",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="UserStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("referer", models.TextField(blank=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "ip_address",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        validators=[django.core.validators.validate_ipv46_address],
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("assigned", "Assigned"),
                            ("closed", "Closed"),
                            ("spam", "Spam"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("path", models.CharField(max_length=500)),
                ("name", models.CharField(blank=True, max_length=40)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="Rate your experience from 1 (lowest) to 5 (highest).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "comments",
                    models.TextField(help_text="Share more about your experience."),
                ),
                (
                    "messages",
                    models.TextField(
                        blank=True,
                        help_text="Messages displayed to the user when the feedback was submitted.",
                        validators=[django.core.validators.MaxLengthValidator(2000)],
                    ),
                ),
                (
                    "contact_via_chat",
                    models.BooleanField(
                        db_default=False,
                        default=False,
                        help_text="Whether the submitter opted into chat follow-up during feedback.",
                    ),
                ),
                (
                    "javascript_enabled",
                    models.BooleanField(
                        db_default=False,
                        default=False,
                        help_text="Whether JavaScript was enabled when feedback was submitted.",
                    ),
                ),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True,
                        help_text="Optional screenshot captured while submitting feedback.",
                        upload_to="sites/user_story_screenshots/",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "github_issue_number",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of the GitHub issue created for this feedback.",
                        null=True,
                    ),
                ),
                (
                    "github_issue_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the GitHub issue created for this feedback.",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        blank=True,
                        help_text="Language selected when the feedback was submitted.",
                        max_length=15,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Story",
                "verbose_name_plural": "User Stories",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="UserStoryAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.sites.models.user_story.user_story_attachment_upload_to
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "User Story Attachment",
                "verbose_name_plural": "User Story Attachments",
                "ordering": ["uploaded_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ViewHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[("site", "Site"), ("admin", "Admin")],
                        db_index=True,
                        default="site",
                        max_length=20,
                    ),
                ),
                ("path", models.CharField(max_length=2048)),
                ("method", models.CharField(max_length=10)),
                ("status_code", models.PositiveSmallIntegerField()),
                ("status_text", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("exception_name", models.CharField(blank=True, max_length=200)),
                ("view_name", models.CharField(blank=True, max_length=200)),
                ("visited_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "View History",
                "verbose_name_plural": "View Histories",
                "ordering": ["-visited_at"],
            },
        ),
    ]
