# Generated by Django 5.2.15 on 2026-07-02 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('modules', '0002_initial'),
        ('pages', '0001_initial'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminbadge',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User that owns this object.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landing',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landings', to='modules.module'),
        ),
        migrations.AddField(
            model_name='referrerlanding',
            name='landing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrer_landings', to='pages.landing'),
        ),
        migrations.AddField(
            model_name='referrerlanding',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer_landings', to='sites.site'),
        ),
        migrations.AddField(
            model_name='sitebadge',
            name='favicon_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_badge_favicons', to='media.mediafile', verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='sitebadge',
            name='landing_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.landing'),
        ),
        migrations.AddField(
            model_name='sitebadge',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='badge', to='sites.site'),
        ),
        migrations.AddField(
            model_name='sitemodulevisibility',
            name='module',
            field=models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, related_name='site_visibility_rules', to='modules.module', verbose_name='Module'),
        ),
        migrations.AddField(
            model_name='sitemodulevisibility',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_visibility_rules', to='sites.site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='default_landing',
            field=models.ForeignKey(blank=True, help_text='Landing visitors should be redirected to by default.', limit_choices_to={'enabled': True, 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_site_profiles', to='pages.landing', verbose_name='Default landing'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='interface_landing',
            field=models.ForeignKey(blank=True, help_text='Landing visitors should be redirected to when the Operator Site Interface suite feature is disabled.', limit_choices_to={'enabled': True, 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interface_for_site_profiles', to='pages.landing', verbose_name='Interface landing'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='sites.site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_profiles', to='pages.sitetemplate', verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userstory',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Internal owner for this feedback.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_user_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userstory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userstoryattachment',
            name='user_story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='pages.userstory'),
        ),
        migrations.AddField(
            model_name='viewhistory',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='view_history', to='sites.site'),
        ),
        migrations.AlterUniqueTogether(
            name='landing',
            unique_together={('module', 'path')},
        ),
        migrations.AlterUniqueTogether(
            name='referrerlanding',
            unique_together={('site', 'referrer_domain')},
        ),
        migrations.AddConstraint(
            model_name='sitemodulevisibility',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('site', 'module', 'audience'), name='unique_site_module_visibility_audience'),
        ),
        migrations.AddIndex(
            model_name='viewhistory',
            index=models.Index(fields=['kind', 'visited_at'], name='pages_viewh_kind_8155b6_idx'),
        ),
        migrations.AddIndex(
            model_name='viewhistory',
            index=models.Index(fields=['site', 'visited_at'], name='pages_viewh_site_id_ad75aa_idx'),
        ),
    ]
