# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
        ("modules", "0002_initial"),
        ("pages", "0003_initial"),
        ("sites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="adminbadge",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User that owns this object.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="landing",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landings",
                to="modules.module",
            ),
        ),
        migrations.AddField(
            model_name="landinglead",
            name="assign_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="landinglead",
            name="landing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leads",
                to="pages.landing",
            ),
        ),
        migrations.AddField(
            model_name="landinglead",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referrerlanding",
            name="landing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrer_landings",
                to="pages.landing",
            ),
        ),
        migrations.AddField(
            model_name="referrerlanding",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrer_landings",
                to="sites.site",
            ),
        ),
        migrations.AddField(
            model_name="sitebadge",
            name="favicon_media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="site_badge_favicons",
                to="media.mediafile",
                verbose_name="Favicon",
            ),
        ),
        migrations.AddField(
            model_name="sitebadge",
            name="landing_override",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pages.landing",
            ),
        ),
        migrations.AddField(
            model_name="sitebadge",
            name="site",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="badge",
                to="sites.site",
            ),
        ),
        migrations.AddField(
            model_name="userstory",
            name="assign_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userstory",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Internal owner for this feedback.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_user_stories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userstory",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_stories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userstoryattachment",
            name="user_story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="pages.userstory",
            ),
        ),
        migrations.AddField(
            model_name="viewhistory",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="view_history",
                to="sites.site",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="landing",
            unique_together={("module", "path")},
        ),
        migrations.AlterUniqueTogether(
            name="referrerlanding",
            unique_together={("site", "referrer_domain")},
        ),
        migrations.AddIndex(
            model_name="viewhistory",
            index=models.Index(
                fields=["kind", "visited_at"], name="pages_viewh_kind_8155b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="viewhistory",
            index=models.Index(
                fields=["site", "visited_at"], name="pages_viewh_site_id_ad75aa_idx"
            ),
        ),
    ]
