# Generated by Django 5.2.12 on 2026-08-24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_drop_stale_landing_track_leads"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WorkgroupPlayPanelItem",
        ),
    ]
