# Generated by Django 5.2.12 on 2026-04-02

import django.db.models.deletion
from django.db import migrations, models


LEGACY_COLUMNS = {
    "default_landing_id",
    "enable_public_chat",
    "interface_landing_id",
    "managed",
    "require_https",
    "template_id",
}


def backfill_site_profiles(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    SiteProfile = apps.get_model("pages", "SiteProfile")

    connection = schema_editor.connection
    site_table = Site._meta.db_table

    with connection.cursor() as cursor:
        table_names = set(connection.introspection.table_names(cursor))
    if site_table not in table_names:
        return

    with connection.cursor() as cursor:
        description = connection.introspection.get_table_description(cursor, site_table)
    site_columns = {column.name for column in description}

    has_legacy_columns = bool(LEGACY_COLUMNS & site_columns)

    existing_profile_site_ids = set(
        SiteProfile.objects.using(schema_editor.connection.alias).values_list(
            "site_id", flat=True
        )
    )

    legacy_rows_by_site_id = {}
    if has_legacy_columns:
        with connection.cursor() as cursor:
            cursor.execute(
                f"""
                SELECT id, default_landing_id, enable_public_chat, interface_landing_id,
                       managed, require_https, template_id
                FROM {site_table}
                """
            )
            legacy_rows_by_site_id = {row[0]: row[1:] for row in cursor.fetchall()}

    sites = Site.objects.using(schema_editor.connection.alias).all().only("id")
    for site in sites.iterator():
        if site.pk in existing_profile_site_ids:
            continue

        values = {
            "site_id": site.pk,
            "enable_public_chat": False,
            "managed": False,
            "require_https": False,
        }
        row = legacy_rows_by_site_id.get(site.pk)
        if row:
            (
                values["default_landing_id"],
                values["enable_public_chat"],
                values["interface_landing_id"],
                values["managed"],
                values["require_https"],
                values["template_id"],
            ) = row

        SiteProfile.objects.using(schema_editor.connection.alias).create(**values)


def reverse_backfill_site_profiles(apps, schema_editor):
    SiteProfile = apps.get_model("pages", "SiteProfile")
    SiteProfile.objects.using(schema_editor.connection.alias).all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_initial"),
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enable_public_chat",
                    models.BooleanField(
                        db_default=False,
                        default=False,
                        help_text="Allow the chat button for all visitors on this site, including guests.",
                        verbose_name="Enable public chat",
                    ),
                ),
                (
                    "managed",
                    models.BooleanField(
                        db_default=False,
                        default=False,
                        help_text="Include this site when staging the local NGINX configuration.",
                        verbose_name="Managed by local NGINX",
                    ),
                ),
                (
                    "require_https",
                    models.BooleanField(
                        db_default=False,
                        default=False,
                        help_text="Redirect HTTP traffic to HTTPS when the staged NGINX configuration is applied.",
                        verbose_name="Require HTTPS",
                    ),
                ),
                (
                    "default_landing",
                    models.ForeignKey(
                        blank=True,
                        help_text="Landing visitors should be redirected to by default.",
                        limit_choices_to={"enabled": True, "is_deleted": False},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_site_profiles",
                        to="pages.landing",
                        verbose_name="Default landing",
                    ),
                ),
                (
                    "interface_landing",
                    models.ForeignKey(
                        blank=True,
                        help_text="Landing visitors should be redirected to when the Operator Site Interface suite feature is disabled.",
                        limit_choices_to={"enabled": True, "is_deleted": False},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interface_for_site_profiles",
                        to="pages.landing",
                        verbose_name="Interface landing",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="sites.site",
                        verbose_name="Site",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_profiles",
                        to="pages.sitetemplate",
                        verbose_name="Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site profile",
                "verbose_name_plural": "Site profiles",
            },
        ),
        migrations.RunPython(backfill_site_profiles, reverse_backfill_site_profiles),
    ]
