# Generated by Django 5.2.10 on 2026-01-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0006_sitebadge_favicon_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstory",
            name="contact_me",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Requester asked to be contacted about this feedback.",
            ),
        ),
        migrations.AddField(
            model_name="userstory",
            name="feedback_for_page",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Feedback indicates this report is for the current page.",
            ),
        ),
    ]
