# Generated by Django 5.2.10 on 2026-01-27 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_add_rfid_validator_landing"),
        ("pages", "0007_referrerlanding"),
    ]

    operations = []
