# Generated by Django 5.2.12 on 2026-04-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_sync_ocpp_terminal_landings"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "highlight_date",
                    models.DateField(help_text="Date shown with this highlight."),
                ),
                (
                    "story",
                    models.TextField(
                        help_text="Short highlight story. URLs are auto-linked on the public site."
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this highlight is eligible to appear on the public site.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Site Highlight",
                "verbose_name_plural": "Site Highlights",
                "ordering": ("-highlight_date", "-created_at", "-pk"),
            },
        ),
    ]
