# Generated by Django 5.2.10 on 2026-01-27 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_merge_20260127_1312"),
        ("pages", "0008_merge_20260127_1315"),
    ]

    operations = []
