# Generated by Django 5.2.10 on 2026-02-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_merge_20260127_1721"),
    ]

    operations = [
        migrations.AddField(
            model_name="landing",
            name="agent_notes",
            field=models.TextField(
                blank=True,
                help_text="Hidden, agent-facing guidance about what this landing is best used for.",
            ),
        ),
    ]
