# Generated by Django 5.2.10 on 2026-02-06 14:25

from django.core.validators import MaxLengthValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_landing_agent_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstory",
            name="messages",
            field=models.TextField(
                blank=True,
                help_text="Messages displayed to the user when the feedback was submitted.",
                validators=[MaxLengthValidator(2000)],
            ),
        ),
    ]
