# Generated by Django 5.2.11 on 2026-03-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0014_adminbadge"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstory",
            name="contact_via_chat",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Whether the submitter opted into chat follow-up during feedback.",
            ),
        ),
    ]
