# Generated by Django 5.2.12 on 2026-03-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0015_chat_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstory",
            name="javascript_enabled",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Whether JavaScript was enabled when feedback was submitted.",
            ),
        ),
        migrations.AddField(
            model_name="userstory",
            name="screenshot",
            field=models.FileField(
                blank=True,
                help_text="Optional screenshot captured while submitting feedback.",
                upload_to="sites/user_story_screenshots/",
            ),
        ),
    ]
