# Generated by Django 5.2.12 on 2026-03-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0016_userstory_javascript_enabled_userstory_screenshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstory",
            name="screenshot",
            field=models.ImageField(
                blank=True,
                help_text="Optional screenshot captured while submitting feedback.",
                upload_to="sites/user_story_screenshots/",
            ),
        ),
    ]
