# Generated by Django 5.2.11 on 2026-03-01 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nodes", "0037_add_x_display_server_feature"),
    ]

    operations = [
        migrations.CreateModel(
            name="XDisplayInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("display_name", models.CharField(max_length=64)),
                ("host", models.CharField(blank=True, max_length=255)),
                (
                    "runtime_scope",
                    models.CharField(
                        choices=[("local", "Local"), ("remote", "Remote")],
                        default="local",
                        max_length=10,
                    ),
                ),
                (
                    "server_type",
                    models.CharField(
                        choices=[
                            ("x11", "X11"),
                            ("xorg", "Xorg"),
                            ("xwayland", "Xwayland"),
                            ("xephyr", "Xephyr"),
                            ("xvfb", "Xvfb"),
                        ],
                        default="x11",
                        max_length=16,
                    ),
                ),
                ("process_name", models.CharField(blank=True, max_length=64)),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("detected_at", models.DateTimeField(auto_now=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="x_display_instances",
                        to="nodes.node",
                    ),
                ),
            ],
            options={
                "verbose_name": "X Display Instance",
                "verbose_name_plural": "X Display Instances",
                "ordering": ["display_name", "host"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("node", "display_name"),
                        name="xserver_display_instance_unique",
                    )
                ],
            },
        ),
    ]
