# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CertificateBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("domain", models.CharField(max_length=253)),
                ("certificate_path", models.CharField(max_length=500)),
                ("certificate_key_path", models.CharField(max_length=500)),
                ("last_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expiration_date", models.DateTimeField(blank=True, null=True)),
                ("auto_renew", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Certificate",
                "verbose_name_plural": "Certificates",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="CertbotCertificate",
            fields=[
                (
                    "certificatebase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="certs.certificatebase",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("last_requested_at", models.DateTimeField(blank=True, null=True)),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("nginx", "Nginx (HTTP-01)"),
                            ("godaddy", "GoDaddy (DNS-01)"),
                        ],
                        default="nginx",
                        max_length=20,
                    ),
                ),
                ("dns_propagation_seconds", models.PositiveIntegerField(default=120)),
            ],
            options={
                "verbose_name": "Certbot certificate",
                "verbose_name_plural": "Certbot certificates",
            },
            bases=("certs.certificatebase",),
        ),
        migrations.CreateModel(
            name="SelfSignedCertificate",
            fields=[
                (
                    "certificatebase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="certs.certificatebase",
                    ),
                ),
                ("valid_days", models.PositiveIntegerField(default=365)),
                ("key_length", models.PositiveIntegerField(default=2048)),
                ("last_generated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Self-signed certificate",
                "verbose_name_plural": "Self-signed certificates",
            },
            bases=("certs.certificatebase",),
        ),
    ]
