# Generated by Django 5.2.15 on 2026-07-02 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certs', '0001_initial'),
        ('dns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certbotcertificate',
            name='dns_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certbot_certificates', to='dns.dnsprovidercredential'),
        ),
    ]
