# Generated by Django 5.2.12 on 2026-04-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("netmesh", "0009_remove_network_surface_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="netmeshagentstatus",
            name="relay_count",
        ),
        migrations.RemoveField(
            model_name="netmeshagentstatus",
            name="session_count",
        ),
    ]
