# Generated by Django 5.2.12 on 2026-04-24 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("netmesh", "0010_remove_netmeshagentstatus_relay_count_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="meshmembership",
            name="netmesh_unique_membership_default_scope",
        ),
        migrations.RemoveConstraint(
            model_name="meshmembership",
            name="netmesh_unique_membership_site_scope",
        ),
        migrations.RemoveField(
            model_name="meshmembership",
            name="node",
        ),
        migrations.RemoveField(
            model_name="meshmembership",
            name="site",
        ),
        migrations.DeleteModel(
            name="NetmeshAgentStatus",
        ),
        migrations.RemoveConstraint(
            model_name="nodekeymaterial",
            name="netmesh_node_single_active_transport_key",
        ),
        migrations.RemoveField(
            model_name="nodekeymaterial",
            name="node",
        ),
        migrations.RemoveIndex(
            model_name="peerpolicy",
            name="netmesh_policy_scope_src_idx",
        ),
        migrations.RemoveField(
            model_name="peerpolicy",
            name="destination_group",
        ),
        migrations.RemoveField(
            model_name="peerpolicy",
            name="destination_node",
        ),
        migrations.RemoveField(
            model_name="peerpolicy",
            name="destination_station",
        ),
        migrations.RemoveField(
            model_name="peerpolicy",
            name="site",
        ),
        migrations.RemoveField(
            model_name="peerpolicy",
            name="source_group",
        ),
        migrations.RemoveField(
            model_name="peerpolicy",
            name="source_node",
        ),
        migrations.RemoveField(
            model_name="peerpolicy",
            name="source_station",
        ),
        migrations.DeleteModel(
            name="MeshMembership",
        ),
        migrations.DeleteModel(
            name="NodeKeyMaterial",
        ),
        migrations.DeleteModel(
            name="PeerPolicy",
        ),
    ]
