# Generated by Django 5.2.12 on 2026-03-27 20:33

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("energy", "0001_initial"),
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[],
            options={
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("maps.location",),
        ),
    ]
