# Generated by Django 5.2.12 on 2026-09-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='ocpp_id_tag',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
