# Generated by Django 5.2.15 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeraccount",
            name="ocpp_id_tag",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Optional OCPP idTag used to attribute non-RFID charging sessions.",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
