# Generated by Django 5.2.8 on 2025-12-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0004_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="energycredit",
            name="account",
        ),
        migrations.RemoveField(
            model_name="energycredit",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="energytransaction",
            name="purchased_kw",
        ),
        migrations.AddField(
            model_name="energytransaction",
            name="delta_kw",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Signed kW impact on the account balance (credits positive).",
                max_digits=12,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="energytransaction",
            name="direction",
            field=models.CharField(
                choices=[("credit", "Credit"), ("debit", "Debit")],
                default="credit",
                help_text="Whether this ledger entry is a credit or debit.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="energytransaction",
            name="reference",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional reference identifier for reconciliation.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="energytransaction",
            name="source",
            field=models.CharField(
                choices=[
                    ("card_topup", "Card top-up"),
                    ("subscription", "Subscription"),
                    ("session_close", "Session close"),
                    ("manual_adjustment", "Manual adjustment"),
                ],
                default="manual_adjustment",
                help_text="Originating flow for this ledger entry.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="energytransaction",
            name="charged_amount_mxn",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Currency amount for the transaction when applicable.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="energytransaction",
            name="conversion_factor",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Conversion factor (kW per MXN) applied at purchase time.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="energytransaction",
            index=models.Index(
                fields=["account", "created_on", "direction"],
                name="energy_txn_acct_dir_idx",
            ),
        ),
        migrations.DeleteModel(
            name="EnergyCredit",
        ),
    ]
