# Generated by Django 5.2.12 on 2026-04-11 01:17

import apps.locale.language
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientreport",
            name="language",
            field=models.CharField(
                choices=[("en", "English")],
                default=apps.locale.language.default_report_language,
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="clientreportschedule",
            name="language",
            field=models.CharField(
                choices=[("en", "English")],
                default=apps.locale.language.default_report_language,
                max_length=12,
            ),
        ),
    ]
