# Generated by Django 5.2.12 on 2026-04-11 01:17

import apps.locale.language
from django.db import migrations, models


def backfill_report_languages(apps, schema_editor):
    ClientReport = apps.get_model("energy", "ClientReport")
    ClientReportSchedule = apps.get_model("energy", "ClientReportSchedule")

    ClientReport.objects.filter(language__in=["de", "es", "it"]).update(language="en")
    ClientReportSchedule.objects.filter(language__in=["de", "es", "it"]).update(language="en")


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0004_initial"),
    ]

    operations = [
        migrations.RunPython(backfill_report_languages, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="clientreport",
            name="language",
            field=models.CharField(
                choices=[("en", "English")],
                default=apps.locale.language.default_report_language,
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="clientreportschedule",
            name="language",
            field=models.CharField(
                choices=[("en", "English")],
                default=apps.locale.language.default_report_language,
                max_length=12,
            ),
        ),
    ]
