# Generated by Django 5.2.12 on 2026-03-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FTPFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=100)),
                ("path", models.CharField(max_length=500)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "owner_permission",
                    models.CharField(
                        choices=[
                            ("read", "Read-only"),
                            ("write", "Read and write"),
                            ("admin", "Full control"),
                        ],
                        default="admin",
                        help_text="Permission granted to the owner for this folder.",
                        max_length=10,
                    ),
                ),
                (
                    "group_permission",
                    models.CharField(
                        choices=[
                            ("read", "Read-only"),
                            ("write", "Read and write"),
                            ("admin", "Full control"),
                        ],
                        default="read",
                        help_text="Permission granted to members of the security group.",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "FTP Folder",
                "verbose_name_plural": "FTP Folders",
            },
        ),
        migrations.CreateModel(
            name="FTPServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "bind_address",
                    models.GenericIPAddressField(
                        default="0.0.0.0",
                        help_text="Interface to bind when starting the FTP server.",
                        unpack_ipv4=True,
                    ),
                ),
                (
                    "port",
                    models.PositiveIntegerField(
                        default=2121, help_text="TCP port where the FTP server listens."
                    ),
                ),
                (
                    "passive_ports",
                    models.CharField(
                        blank=True,
                        help_text="Optional passive port range, e.g. 60000-60010.",
                        max_length=50,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Toggle whether the FTP server should start.",
                    ),
                ),
            ],
            options={
                "verbose_name": "FTP Server",
                "verbose_name_plural": "FTP Servers",
            },
        ),
    ]
