# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ftp", "0002_initial"),
        ("nodes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ftpfolder",
            name="node",
            field=models.ForeignKey(
                blank=True,
                help_text="Node that owns this folder. Leave blank to share globally.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ftp_folders",
                to="nodes.node",
            ),
        ),
    ]
