# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ftp", "0003_initial"),
        ("nodes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ftpfolder",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User that owns this object.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ftpserver",
            name="node",
            field=models.ForeignKey(
                blank=True,
                help_text="Node that should expose this FTP server configuration.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ftp_servers",
                to="nodes.node",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ftpfolder",
            unique_together={("node", "name")},
        ),
        migrations.AddConstraint(
            model_name="ftpserver",
            constraint=models.UniqueConstraint(
                condition=models.Q(("node__isnull", False)),
                fields=("node",),
                name="ftpserver_unique_node",
            ),
        ),
        migrations.AddConstraint(
            model_name="ftpserver",
            constraint=models.UniqueConstraint(
                condition=models.Q(("node__isnull", True)),
                fields=("node",),
                name="ftpserver_unique_global",
            ),
        ),
    ]
