# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "importance",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("baseline", "Baseline"),
                            ("prototype", "Prototype"),
                        ],
                        default="baseline",
                        max_length=20,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
                "db_table": "pages_application",
            },
        ),
        migrations.CreateModel(
            name="ApplicationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("model_name", models.CharField(max_length=100)),
                ("verbose_name", models.CharField(blank=True, max_length=255)),
                ("wiki_url", models.URLField(blank=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="app.application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application model",
                "verbose_name_plural": "Application models",
                "db_table": "pages_applicationmodel",
                "ordering": ("label",),
                "unique_together": {("application", "label")},
            },
        ),
    ]
