# Generated by Django 5.2.8 on 2025-12-07 16:33

from django.db import migrations


WIKI_URL = "https://en.wikipedia.org/wiki/Open_Charge_Point_Protocol"


def set_ocpp_wiki_url(apps, schema_editor):
    Application = apps.get_model("app", "Application")
    ApplicationModel = apps.get_model("app", "ApplicationModel")

    try:
        application = Application.objects.get(name="ocpp")
    except Application.DoesNotExist:
        return

    ApplicationModel.objects.filter(
        application=application, label__iexact="ocpp.Charger"
    ).update(wiki_url=WIKI_URL)


def unset_ocpp_wiki_url(apps, schema_editor):
    Application = apps.get_model("app", "Application")
    ApplicationModel = apps.get_model("app", "ApplicationModel")

    try:
        application = Application.objects.get(name="ocpp")
    except Application.DoesNotExist:
        return

    ApplicationModel.objects.filter(
        application=application, label__iexact="ocpp.Charger", wiki_url=WIKI_URL
    ).update(wiki_url="")


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_mark_cards_critical"),
    ]

    operations = [
        migrations.RunPython(set_ocpp_wiki_url, reverse_code=unset_ocpp_wiki_url),
    ]
