# Generated by Django 5.2.11 on 2026-03-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_applicationmodel_smb_wiki_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
