# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, default="", max_length=32)),
                ("language", models.CharField(blank=True, default="", max_length=32)),
                ("game", models.CharField(blank=True, default="", max_length=255)),
                ("style", models.CharField(blank=True, default="", max_length=255)),
                ("set_info", models.JSONField(blank=True, default=dict)),
                ("style_settings", models.JSONField(blank=True, default=dict)),
                ("raw_set_text", models.TextField(blank=True, default="")),
                (
                    "source_filename",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Card Set",
                "verbose_name_plural": "Card Sets",
                "ordering": ("-created_on", "name"),
            },
        ),
        migrations.CreateModel(
            name="RFIDAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "rfid",
                    models.CharField(blank=True, max_length=255, verbose_name="RFID"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scanned", "Scanned"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="scanned",
                        max_length=16,
                    ),
                ),
                ("authenticated", models.BooleanField(blank=True, null=True)),
                ("allowed", models.BooleanField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("service", "Scanner service"),
                            ("browser", "Browser submission"),
                            ("camera", "Camera scan"),
                            ("on-demand", "On-demand scan"),
                            ("ocpp", "OCPP"),
                            ("auth", "Authentication"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "RFID Attempt",
                "verbose_name_plural": "RFID Attempts",
                "ordering": ["-attempted_at"],
            },
        ),
        migrations.CreateModel(
            name="CardFace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=128)),
                (
                    "overlay_one_text",
                    models.TextField(
                        blank=True, default="", help_text="Primary overlay text."
                    ),
                ),
                (
                    "overlay_one_font",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("overlay_one_font_size", models.PositiveIntegerField(default=28)),
                ("overlay_one_x", models.IntegerField(default=0)),
                ("overlay_one_y", models.IntegerField(default=0)),
                (
                    "overlay_two_text",
                    models.TextField(
                        blank=True, default="", help_text="Secondary overlay text."
                    ),
                ),
                (
                    "overlay_two_font",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("overlay_two_font_size", models.PositiveIntegerField(default=24)),
                ("overlay_two_x", models.IntegerField(default=0)),
                ("overlay_two_y", models.IntegerField(default=0)),
                (
                    "background_media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cardface_backgrounds",
                        to="media.mediafile",
                        verbose_name="Background",
                    ),
                ),
                (
                    "fixed_back",
                    models.OneToOneField(
                        blank=True,
                        help_text="Optional fixed back for this card face.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fixed_front",
                        to="cards.cardface",
                    ),
                ),
            ],
            options={
                "verbose_name": "Card Face",
                "verbose_name_plural": "Card Faces",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="CardDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("sequence", models.PositiveIntegerField(default=0)),
                ("fields", models.JSONField(blank=True, default=dict)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "card_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_designs",
                        to="cards.cardset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Card Design",
                "verbose_name_plural": "Card Designs",
                "ordering": ("card_set", "sequence", "name"),
            },
        ),
        migrations.CreateModel(
            name="RFID",
            fields=[
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "label_id",
                    models.AutoField(
                        db_column="label_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "rfid",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9A-Fa-f]+$",
                                message="RFID must be hexadecimal digits",
                            )
                        ],
                        verbose_name="RFID",
                    ),
                ),
                (
                    "reversed_uid",
                    models.CharField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="UID value stored with opposite endianness for reference.",
                        max_length=255,
                        verbose_name="Reversed UID",
                    ),
                ),
                (
                    "custom_label",
                    models.CharField(
                        blank=True,
                        help_text="Optional custom label for this RFID.",
                        max_length=32,
                        verbose_name="Custom Label",
                    ),
                ),
                (
                    "key_a",
                    models.CharField(
                        default="FFFFFFFFFFFF",
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9A-Fa-f]{12}$",
                                message="Key must be 12 hexadecimal digits",
                            )
                        ],
                        verbose_name="Key A",
                    ),
                ),
                (
                    "key_b",
                    models.CharField(
                        default="FFFFFFFFFFFF",
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9A-Fa-f]{12}$",
                                message="Key must be 12 hexadecimal digits",
                            )
                        ],
                        verbose_name="Key B",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=list, help_text="Sector and block data"
                    ),
                ),
                ("key_a_verified", models.BooleanField(default=False)),
                ("key_b_verified", models.BooleanField(default=False)),
                ("allowed", models.BooleanField(default=True)),
                (
                    "external_command",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Deprecated: legacy raw command text. No longer executed.",
                    ),
                ),
                (
                    "post_auth_command",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Deprecated: legacy post-auth raw command text. No longer executed.",
                    ),
                ),
                (
                    "validation_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No action"),
                            ("LOG", "Log event"),
                            ("NOOP", "No-op marker"),
                            ("REJECT", "Force reject"),
                        ],
                        default="",
                        help_text="Allowlisted internal action to run during RFID validation.",
                        max_length=32,
                    ),
                ),
                (
                    "post_auth_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No action"),
                            ("LOG", "Log event"),
                            ("NOOP", "No-op marker"),
                            ("REJECT", "Force reject"),
                        ],
                        default="",
                        help_text="Allowlisted internal action to run after successful authentication.",
                        max_length=32,
                    ),
                ),
                (
                    "legacy_command_archive",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Archived legacy command text retained for audit history.",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional expiration date for this RFID card.",
                        null=True,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("B", "Black"),
                            ("W", "White"),
                            ("U", "Blue"),
                            ("R", "Red"),
                            ("G", "Green"),
                        ],
                        default="B",
                        max_length=1,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("CLASSIC", "MIFARE Classic"), ("NTAG215", "NTAG215")],
                        default="CLASSIC",
                        max_length=20,
                        verbose_name="Kind",
                    ),
                ),
                (
                    "endianness",
                    models.CharField(
                        choices=[("BIG", "Big endian"), ("LITTLE", "Little endian")],
                        default="BIG",
                        max_length=6,
                    ),
                ),
                ("released", models.BooleanField(default=False)),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                ("last_seen_on", models.DateTimeField(blank=True, null=True)),
                (
                    "card_designs",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Card designs linked to this RFID.",
                        related_name="rfids",
                        to="cards.carddesign",
                    ),
                ),
            ],
            options={
                "verbose_name": "RFID",
                "verbose_name_plural": "RFIDs",
                "db_table": "core_rfid",
            },
        ),
    ]
