# Generated by Django 5.2.15 on 2026-07-02 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfid',
            name='origin_node',
            field=models.ForeignKey(blank=True, help_text='Node where this RFID record was created.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rfids', to='nodes.node'),
        ),
    ]
