# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cards", "0001_initial"),
        ("energy", "0002_initial"),
        ("links", "0001_initial"),
        ("nodes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfid",
            name="origin_node",
            field=models.ForeignKey(
                blank=True,
                help_text="Node where this RFID record was created.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_rfids",
                to="nodes.node",
            ),
        ),
        migrations.AddField(
            model_name="rfid",
            name="reference",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional reference for this RFID.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rfids",
                to="links.reference",
            ),
        ),
        migrations.AddField(
            model_name="rfidattempt",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rfid_attempts",
                to="energy.customeraccount",
            ),
        ),
    ]
