# Generated by Django 5.2.15 on 2026-07-02 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    replaces = [
        ('cards', '0003_cardface'),
        ('cards', '0004_offeringsoul'),
        ('cards', '0005_alter_offeringsoul_options'),
        ('cards', '0006_rfid_discovered_via_ocpp'),
        (
            'cards',
            '0007_rfid_initialized_on_rfid_lcd_label_rfid_sector_keys_and_more',
        ),
        ('cards', '0008_rfid_name_key_rfid_generated_label'),
        ('cards', '0009_rfid_command_card_metadata_rfid_command_card_name_and_more'),
        ('cards', '0010_rfid_command_payload_digest'),
        ('cards', '0011_rfid_command_template_library'),
        ('cards', '0012_seed_rfid_command_templates'),
        ('cards', '0013_rfidcommandtemplate_cover_image'),
        ('cards', '0014_rfidcommandtemplate_qr_target_path_and_gway_burn'),
        ('cards', '0015_seed_rfid_command_card_burn_template'),
        ('cards', '0016_rfidcommandtemplate_lifecycle_mode'),
        ('cards', '0017_rfid_watchlists'),
        ('cards', '0018_rfid_public_usage_token'),
    ]

    dependencies = [
        ('cards', '0002_initial'),
        ('energy', '0003_initial'),
        ('ocpp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rfid',
            name='owner_user',
            field=models.ForeignKey(blank=True, help_text='User whose permissions should be used when this RFID command card runs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_rfids', to=settings.AUTH_USER_MODEL, verbose_name='Owner user'),
        ),
        migrations.AddField(
            model_name='rfidattempt',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_attempts', to='energy.customeraccount'),
        ),
        migrations.AddField(
            model_name='rfidattempt',
            name='charger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfid_attempts', to='ocpp.charger'),
        ),
        migrations.AddField(
            model_name='rfidattempt',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='cards.rfid'),
        ),
        migrations.AddField(
            model_name='rfidattempt',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_attempts', to='ocpp.transaction'),
        ),
        migrations.AddField(
            model_name='rfidcommandexecution',
            name='attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_executions', to='cards.rfidattempt'),
        ),
        migrations.AddField(
            model_name='rfidcommandexecution',
            name='rfid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_executions', to='cards.rfid'),
        ),
        migrations.AddField(
            model_name='rfidcommandexecution',
            name='run_as_user',
            field=models.ForeignKey(blank=True, help_text='User whose permissions were used for this command.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_command_executions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rfidcommandexecution',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_executions', to='cards.rfidcommandtemplate'),
        ),
        migrations.AddField(
            model_name='rfid',
            name='command_template',
            field=models.ForeignKey(blank=True, help_text='Template used to write this command card.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfids', to='cards.rfidcommandtemplate'),
        ),
        migrations.AddField(
            model_name='rfidwatchlistentry',
            name='label',
            field=models.ForeignKey(blank=True, help_text='Optional RFID row to match. The normalized RFID value is also supported.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchlist_entries', to='cards.rfid'),
        ),
        migrations.AddField(
            model_name='rfidwatchlistevent',
            name='attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchlist_events', to='cards.rfidattempt'),
        ),
        migrations.AddField(
            model_name='rfidwatchlistevent',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cards.rfidwatchlistentry'),
        ),
        migrations.AddField(
            model_name='rfidwatchlistevent',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchlist_events', to='cards.rfid'),
        ),
        migrations.AddIndex(
            model_name='rfidwatchlistentry',
            index=models.Index(fields=['enabled', 'normalized_rfid'], name='cards_rfidw_enabled_ff4205_idx'),
        ),
        migrations.AddIndex(
            model_name='rfidwatchlistentry',
            index=models.Index(fields=['enabled', 'label'], name='cards_rfidw_enabled_3866b6_idx'),
        ),
        migrations.AddIndex(
            model_name='rfidwatchlistevent',
            index=models.Index(fields=['status', 'created_at'], name='cards_rfidw_status_5e1bf1_idx'),
        ),
        migrations.AddIndex(
            model_name='rfidwatchlistevent',
            index=models.Index(fields=['source', 'created_at'], name='cards_rfidw_source_5070a9_idx'),
        ),
    ]
