# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cards", "0002_initial"),
        ("ocpp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfidattempt",
            name="charger",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rfid_attempts",
                to="ocpp.charger",
            ),
        ),
        migrations.AddField(
            model_name="rfidattempt",
            name="label",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attempts",
                to="cards.rfid",
            ),
        ),
        migrations.AddField(
            model_name="rfidattempt",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rfid_attempts",
                to="ocpp.transaction",
            ),
        ),
    ]
