# Generated by Django 5.2.12 on 2026-04-15 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_offeringsoul"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offeringsoul",
            options={
                "ordering": ("-id",),
                "verbose_name": "Offering Soul Seed",
                "verbose_name_plural": "Offering Soul Seeds",
            },
        ),
    ]
