# Generated by Django 5.2.10 on 2026-01-31 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_cardface_media_background"),
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, default="", max_length=32)),
                ("game", models.CharField(blank=True, default="", max_length=255)),
                ("style", models.CharField(blank=True, default="", max_length=255)),
                ("language", models.CharField(blank=True, default="", max_length=64)),
                ("set_info", models.JSONField(blank=True, default=dict)),
                ("style_settings", models.JSONField(blank=True, default=dict)),
                ("raw_data", models.TextField(blank=True, default="")),
                (
                    "source_media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card_sets",
                        to="media.mediafile",
                        verbose_name="Set file",
                    ),
                ),
            ],
            options={
                "verbose_name": "Card Set",
                "verbose_name_plural": "Card Sets",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="CardDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("sequence", models.PositiveIntegerField(default=0)),
                ("fields", models.JSONField(blank=True, default=dict)),
                (
                    "card_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_designs",
                        to="cards.cardset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Card Design",
                "verbose_name_plural": "Card Designs",
                "ordering": ("card_set", "sequence"),
            },
        ),
        migrations.AddField(
            model_name="rfid",
            name="card_designs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Card designs associated with this RFID.",
                related_name="rfids",
                to="cards.carddesign",
            ),
        ),
    ]
