# Generated by Django 5.2.12 on 2026-05-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0005_alter_offeringsoul_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfid",
            name="discovered_via_ocpp",
            field=models.BooleanField(
                default=False,
                help_text="Set when the RFID was first auto-discovered through OCPP authorization.",
            ),
        ),
    ]
