# Generated by Django 5.2.15 on 2026-07-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_remove_rfidcommandtemplate_cover_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidwatchlistentry',
            name='action_type',
            field=models.CharField(choices=[('audit', 'Audit only'), ('local_notification', 'Local notification'), ('net_message', 'Net message')], default='audit', max_length=32),
        ),
    ]
