# Generated by Django 5.2.15 on 2026-08-22 00:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_rfidwatchlistentry_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfid',
            name='rfid',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9][A-Za-z0-9\\s:_-]*$', message='RFID must be an alphanumeric identifier')], verbose_name='RFID'),
        ),
    ]
