# Generated by Django 5.2.10 on 2026-02-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0006_rfid_attempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rfidattempt",
            name="source",
            field=models.CharField(
                choices=[
                    ("service", "Scanner service"),
                    ("browser", "Browser submission"),
                    ("camera", "Camera scan"),
                    ("on-demand", "On-demand scan"),
                    ("ocpp", "OCPP"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
