# Generated by Django 5.2.12 on 2026-03-26 02:47

from django.db import migrations, models


def archive_legacy_commands(apps, schema_editor):
    RFID = apps.get_model("cards", "RFID")
    for tag in RFID.objects.all().iterator():
        external = (getattr(tag, "external_command", "") or "").strip()
        post_auth = (getattr(tag, "post_auth_command", "") or "").strip()
        if not external and not post_auth:
            continue

        archive = dict(getattr(tag, "legacy_command_archive", {}) or {})
        if external:
            archive["external_command"] = external
        if post_auth:
            archive["post_auth_command"] = post_auth
        archive["archived_in_migration"] = "0009"

        tag.legacy_command_archive = archive
        tag.external_command = ""
        tag.post_auth_command = ""
        tag.save(
            update_fields=[
                "legacy_command_archive",
                "external_command",
                "post_auth_command",
            ]
        )


def restore_legacy_commands(apps, schema_editor):
    RFID = apps.get_model("cards", "RFID")
    for tag in RFID.objects.all().iterator():
        archive = dict(getattr(tag, "legacy_command_archive", {}) or {})
        external = str(archive.get("external_command") or "").strip()
        post_auth = str(archive.get("post_auth_command") or "").strip()
        if not external and not post_auth:
            continue
        tag.external_command = external
        tag.post_auth_command = post_auth
        tag.save(update_fields=["external_command", "post_auth_command"])


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0008_alter_rfidattempt_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfid",
            name="legacy_command_archive",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Archived legacy command text retained for audit history.",
            ),
        ),
        migrations.AddField(
            model_name="rfid",
            name="post_auth_action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No action"),
                    ("LOG", "Log event"),
                    ("NOOP", "No-op marker"),
                    ("REJECT", "Force reject"),
                ],
                default="",
                help_text="Allowlisted internal action to run after successful authentication.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="rfid",
            name="validation_action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No action"),
                    ("LOG", "Log event"),
                    ("NOOP", "No-op marker"),
                    ("REJECT", "Force reject"),
                ],
                default="",
                help_text="Allowlisted internal action to run during RFID validation.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="rfid",
            name="external_command",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Deprecated: legacy raw command text. No longer executed.",
            ),
        ),
        migrations.AlterField(
            model_name="rfid",
            name="post_auth_command",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Deprecated: legacy post-auth raw command text. No longer executed.",
            ),
        ),
        migrations.RunPython(archive_legacy_commands, restore_legacy_commands),
    ]
