# Generated by Django 5.2.8 on 2025-12-02 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_delete_rolelanding"),
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="default_landing",
            field=models.ForeignKey(
                blank=True,
                help_text="Landing visitors should be redirected to by default.",
                limit_choices_to={"enabled": True, "is_deleted": False},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_sites",
                to="pages.landing",
                verbose_name="Default landing",
            ),
        ),
    ]
