# Generated by Django 5.2.11 on 2026-03-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_site_interface_landing"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="enable_public_chat",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Allow the chat button for all visitors on this site, including guests.",
                verbose_name="Enable public chat",
            ),
        ),
    ]
