# Generated by Django 5.2.12 on 2026-04-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpiconnect", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectimagerelease",
            name="name",
            field=models.CharField(max_length=120),
        ),
    ]
