# Generated by Django 5.2.15 on 2026-07-02 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rpiconnect', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='connectcampaignevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connect_campaign_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connectdevice',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='rpiconnect.connectaccount'),
        ),
        migrations.AddConstraint(
            model_name='connectimagerelease',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='rpiconnect_release_unique_name_version'),
        ),
        migrations.AddField(
            model_name='connectingestionevent',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_events', to='rpiconnect.connectdevice'),
        ),
        migrations.AddField(
            model_name='connectupdatecampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connect_update_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connectupdatecampaign',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='rpiconnect.connectimagerelease'),
        ),
        migrations.AddField(
            model_name='connectingestionevent',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_events', to='rpiconnect.connectupdatecampaign'),
        ),
        migrations.AddField(
            model_name='connectcampaignevent',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='rpiconnect.connectupdatecampaign'),
        ),
        migrations.AddField(
            model_name='connectupdatedeployment',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='rpiconnect.connectupdatecampaign'),
        ),
        migrations.AddField(
            model_name='connectupdatedeployment',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_deployments', to='rpiconnect.connectdevice'),
        ),
        migrations.AddField(
            model_name='connectingestionevent',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_events', to='rpiconnect.connectupdatedeployment'),
        ),
        migrations.AddField(
            model_name='connectcampaignevent',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='rpiconnect.connectupdatedeployment'),
        ),
        migrations.AddConstraint(
            model_name='connectupdatedeployment',
            constraint=models.UniqueConstraint(fields=('campaign', 'device'), name='rpiconnect_deployment_unique_campaign_device'),
        ),
        migrations.AddConstraint(
            model_name='connectingestionevent',
            constraint=models.UniqueConstraint(fields=('event_id', 'external_device_id'), name='rpiconnect_ingestion_unique_event_device'),
        ),
    ]
