# Generated by Django 5.2.12 on 2026-04-21 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpiconnect", "0003_alter_connectupdatecampaign_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectcampaignevent",
            name="deployment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="rpiconnect.connectupdatedeployment",
            ),
        ),
    ]
