# Generated by Django 5.2.12 on 2026-04-21 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpiconnect", "0004_alter_connectcampaignevent_deployment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectcampaignevent",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="rpiconnect.connectupdatecampaign",
            ),
        ),
    ]
