# Generated by Django 5.2.8 on 2026-03-07

from django.db import migrations


def github_resolve_comments_content_script() -> str:
    """Return the historical content script for the GitHub helper extension."""
    return r"""
(function () {
  if (!/github\.com$/i.test(window.location.hostname)) {
    return;
  }

  var panelId = "arthexis-resolve-comments-panel";
  var statusId = "arthexis-resolve-comments-status";

  function qsa(root, selector) {
    return Array.prototype.slice.call(root.querySelectorAll(selector));
  }

  function sleep(ms) {
    return new Promise(function (resolve) { setTimeout(resolve, ms); });
  }

  function findResolveButtons() {
    return qsa(document, "button").filter(function (button) {
      var text = (button.textContent || "").trim().toLowerCase();
      return text === "resolve conversation" && !button.disabled && button.offsetParent;
    });
  }

  function findContainer(button) {
    return button.closest(".review-comment, .js-resolvable-thread-form, .js-comment-container, .TimelineItem, .js-timeline-item");
  }

  function findCommentTextarea(container) {
    if (!container) {
      return null;
    }

    var area = container.querySelector("textarea[name='comment[body]'], textarea.js-comment-field, textarea[aria-label='Leave a comment']");
    if (!area || area.disabled || area.readOnly) {
      return null;
    }
    return area;
  }

  function findCommentButton(container) {
    if (!container) {
      return null;
    }

    var candidates = qsa(container, "button");
    for (var i = 0; i < candidates.length; i += 1) {
      var button = candidates[i];
      var label = ((button.textContent || "") + " " + (button.getAttribute("aria-label") || "")).toLowerCase();
      if (button.disabled) {
        continue;
      }
      if (label.indexOf("comment") !== -1 && label.indexOf("cancel") === -1) {
        return button;
      }
    }
    return null;
  }

  function triggerInput(element, value) {
    element.focus();
    element.value = value;
    element.dispatchEvent(new Event("input", { bubbles: true }));
    element.dispatchEvent(new Event("change", { bubbles: true }));
  }

  async function commentThenResolve(button, message) {
    var container = findContainer(button);
    var textarea = findCommentTextarea(container);
    var commentButton = findCommentButton(container);

    if (!textarea || !commentButton) {
      button.click();
      await sleep(250);
      return;
    }

    triggerInput(textarea, message);
    commentButton.click();
    await sleep(700);
    button.click();
    await sleep(250);
  }

  function getDefaultComment() {
    return new Promise(function (resolve) {
      if (!window.chrome || !chrome.storage || !chrome.storage.sync) {
        resolve("Resolved by Arthexis helper.");
        return;
      }

      chrome.storage.sync.get({ arthexisResolveComment: "Resolved by Arthexis helper." }, function (result) {
        resolve(result.arthexisResolveComment || "Resolved by Arthexis helper.");
      });
    });
  }

  function renderStatus(text, tone) {
    var status = document.getElementById(statusId);
    if (!status) {
      return;
    }
    status.textContent = text;
    status.style.color = tone === "error" ? "#f85149" : "#8b949e";
  }

  async function resolveAll(withComment) {
    var buttons = findResolveButtons();
    if (!buttons.length) {
      renderStatus("No open review conversations found on this page.");
      return;
    }

    renderStatus("Resolving " + buttons.length + " conversation(s)...");
    var comment = "";
    if (withComment) {
      comment = await getDefaultComment();
    }

    for (var i = 0; i < buttons.length; i += 1) {
      var button = buttons[i];
      if (!button || button.disabled || !button.offsetParent) {
        continue;
      }
      if (withComment) {
        await commentThenResolve(button, comment);
      } else {
        button.click();
        await sleep(250);
      }
    }

    renderStatus("Completed resolve-all action.");
  }

  function addButtonRow(panel) {
    var row = document.createElement("div");
    row.style.display = "flex";
    row.style.gap = "8px";
    row.style.marginTop = "8px";

    var resolveButton = document.createElement("button");
    resolveButton.type = "button";
    resolveButton.textContent = "Resolve all open comments";
    resolveButton.style.cssText = "padding:6px 10px;background:#238636;color:#fff;border:1px solid rgba(240,246,252,.1);border-radius:6px;cursor:pointer;font-size:12px;";
    resolveButton.addEventListener("click", function () {
      resolveAll(false).catch(function (error) {
        renderStatus("Resolve action failed: " + error.message, "error");
      });
    });

    var resolveWithCommentButton = document.createElement("button");
    resolveWithCommentButton.type = "button";
    resolveWithCommentButton.textContent = "Resolve all with comment";
    resolveWithCommentButton.style.cssText = "padding:6px 10px;background:#1f6feb;color:#fff;border:1px solid rgba(240,246,252,.1);border-radius:6px;cursor:pointer;font-size:12px;";
    resolveWithCommentButton.addEventListener("click", function () {
      resolveAll(true).catch(function (error) {
        renderStatus("Resolve with comment failed: " + error.message, "error");
      });
    });

    row.appendChild(resolveButton);
    row.appendChild(resolveWithCommentButton);
    panel.appendChild(row);
  }

  function mountPanel() {
    if (document.getElementById(panelId)) {
      return;
    }

    var panel = document.createElement("div");
    panel.id = panelId;
    panel.style.cssText = "position:fixed;bottom:16px;right:16px;z-index:2147483647;background:#0d1117;color:#c9d1d9;border:1px solid #30363d;border-radius:8px;padding:10px;box-shadow:0 8px 24px rgba(1,4,9,.4);font:12px/1.4 -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif;max-width:360px;";

    var title = document.createElement("div");
    title.textContent = "Arthexis GitHub tools";
    title.style.fontWeight = "600";
    panel.appendChild(title);

    var subtitle = document.createElement("div");
    subtitle.textContent = "Bulk resolve open review comments on this page.";
    subtitle.style.marginTop = "4px";
    subtitle.style.color = "#8b949e";
    panel.appendChild(subtitle);

    addButtonRow(panel);

    var status = document.createElement("div");
    status.id = statusId;
    status.style.marginTop = "8px";
    status.style.color = "#8b949e";
    status.textContent = "Ready.";
    panel.appendChild(status);

    document.body.appendChild(panel);
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", mountPanel, { once: true });
  } else {
    mountPanel();
  }
})();
""".strip()


def github_resolve_comments_options_page() -> str:
    """Return the historical options page for the GitHub helper extension."""
    return """
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Arthexis GitHub Resolve Comments</title>
  </head>
  <body>
    <main>
      <h1>Resolve Comments Settings</h1>
      <label for="comment">Default comment text</label>
      <br />
      <textarea id="comment" rows="5" cols="60"></textarea>
      <br />
      <button id="save" type="button">Save</button>
      <p id="status"></p>
    </main>
    <script src="options.js"></script>
  </body>
</html>
""".strip()


def github_resolve_comments_extension_defaults() -> dict[str, str | int | bool]:
    """Return the historical seed payload for the GitHub helper extension."""

    return {
        "slug": "github-resolve-open-comments",
        "name": "GitHub Resolve Open Comments",
        "description": (
            "Adds developer tools on GitHub PRs and issues to resolve all open "
            "review conversations, with optional comment posting before resolve."
        ),
        "version": "1.0.0",
        "manifest_version": 3,
        "is_enabled": True,
        "matches": "https://github.com/*",
        "permissions": "storage",
        "host_permissions": "https://github.com/*",
        "content_script": github_resolve_comments_content_script(),
        "options_page": github_resolve_comments_options_page(),
    }


def seed_github_resolve_comments_extension(apps, schema_editor):
    """Seed the GitHub bulk resolve-comments helper extension."""
    JsExtension = apps.get_model("extensions", "JsExtension")

    defaults = github_resolve_comments_extension_defaults()
    slug = str(defaults.pop("slug"))

    JsExtension.objects.get_or_create(slug=slug, defaults=defaults)


def remove_github_resolve_comments_extension(apps, schema_editor):
    """Remove seeded GitHub helper extension only when it matches seeded defaults."""
    JsExtension = apps.get_model("extensions", "JsExtension")

    defaults = github_resolve_comments_extension_defaults()
    slug = str(defaults.pop("slug"))

    extension = JsExtension.objects.filter(slug=slug).first()
    if extension is None:
        return

    seeded_keys = (
        "name",
        "description",
        "version",
        "manifest_version",
        "matches",
        "permissions",
        "host_permissions",
        "content_script",
        "options_page",
    )
    if all(getattr(extension, key) == defaults[key] for key in seeded_keys):
        extension.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("extensions", "0002_js_extension_manifest_version_constraint"),
    ]

    operations = [
        migrations.RunPython(
            seed_github_resolve_comments_extension,
            remove_github_resolve_comments_extension,
        ),
    ]
