# Generated by Django 5.2.8 on 2026-03-07

from django.db import migrations


def github_resolve_comments_extension_defaults() -> dict[str, str | int]:
    """Return the historical seed payload for the removed GitHub helper extension."""

    return {
        "slug": "github-resolve-open-comments",
        "name": "GitHub Resolve Open Comments",
        "description": "Resolve all open GitHub review threads with one click.",
        "version": "1.0.0",
        "manifest_version": 3,
        "matches": "https://github.com/*",
        "permissions": "storage",
        "host_permissions": "https://github.com/*",
        "content_script": (
            "(() => {\n"
            "  async function clickAllOpenThreads() {\n"
            "    const buttons = Array.from(document.querySelectorAll('button'))\n"
            "      .filter((button) => /resolve conversation/i.test(button.textContent || ''));\n"
            "    for (const button of buttons) {\n"
            "      button.click();\n"
            "      await new Promise((resolve) => setTimeout(resolve, 150));\n"
            "    }\n"
            "  }\n"
            "\n"
            "  if (document.readyState === 'loading') {\n"
            "    document.addEventListener('DOMContentLoaded', clickAllOpenThreads, { once: true });\n"
            "  } else {\n"
            "    clickAllOpenThreads();\n"
            "  }\n"
            "})();"
        ),
        "options_page": (
            "<!doctype html><html><head><meta charset=\"utf-8\"><title>Resolve Comments</title></head>"
            "<body><main><h1>GitHub Resolve Open Comments</h1>"
            "<p>This legacy hosted extension was retired with the runtime extensions app.</p>"
            "</main></body></html>"
        ),
    }


def seed_github_resolve_comments_extension(apps, schema_editor):
    """Seed the GitHub bulk resolve-comments helper extension."""
    JsExtension = apps.get_model("extensions", "JsExtension")

    defaults = github_resolve_comments_extension_defaults()
    slug = str(defaults.pop("slug"))

    JsExtension.objects.get_or_create(slug=slug, defaults=defaults)



def remove_github_resolve_comments_extension(apps, schema_editor):
    """Remove seeded GitHub helper extension only when it matches seeded defaults."""
    JsExtension = apps.get_model("extensions", "JsExtension")

    defaults = github_resolve_comments_extension_defaults()
    slug = str(defaults.pop("slug"))

    extension = JsExtension.objects.filter(slug=slug).first()
    if extension is None:
        return

    seeded_keys = (
        "name",
        "description",
        "version",
        "manifest_version",
        "matches",
        "permissions",
        "host_permissions",
        "content_script",
        "options_page",
    )
    if all(getattr(extension, key) == defaults[key] for key in seeded_keys):
        extension.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("extensions", "0002_js_extension_manifest_version_constraint"),
    ]

    operations = [
        migrations.RunPython(
            seed_github_resolve_comments_extension,
            remove_github_resolve_comments_extension,
        ),
    ]
