# Generated by Django 5.2.4 on 2025-07-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NginxConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("server_name", models.CharField(max_length=255)),
                (
                    "primary_upstream",
                    models.CharField(
                        help_text="Primary upstream in host:port form", max_length=255
                    ),
                ),
                (
                    "backup_upstream",
                    models.CharField(
                        blank=True,
                        help_text="Backup upstream in host:port form",
                        max_length=255,
                    ),
                ),
                ("listen_port", models.PositiveIntegerField(default=80)),
                ("ssl_certificate", models.CharField(blank=True, max_length=255)),
                ("ssl_certificate_key", models.CharField(blank=True, max_length=255)),
                ("config_text", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Nginx configuration",
                "verbose_name_plural": "Nginx configurations",
            },
        ),
    ]
