# Generated by Django 5.2.4 on 2025-07-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nginx_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nginxconfig",
            name="backup_upstream",
            field=models.CharField(
                blank=True,
                help_text="Backup upstream in host:port form (e.g., 127.0.0.1:9000)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="nginxconfig",
            name="listen_port",
            field=models.PositiveIntegerField(
                default=80, help_text="Port nginx listens on (e.g., 80 or 443)"
            ),
        ),
        migrations.AlterField(
            model_name="nginxconfig",
            name="name",
            field=models.CharField(
                help_text="Identifier for this configuration (e.g., 'myapp')",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="nginxconfig",
            name="primary_upstream",
            field=models.CharField(
                help_text="Primary upstream in host:port form (e.g., 10.0.0.1:8000)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="nginxconfig",
            name="server_name",
            field=models.CharField(
                help_text="Host name(s) for the server block (e.g., example.com)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="nginxconfig",
            name="ssl_certificate",
            field=models.CharField(
                blank=True,
                help_text="Path to SSL certificate (e.g., /etc/ssl/certs/example.crt)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="nginxconfig",
            name="ssl_certificate_key",
            field=models.CharField(
                blank=True,
                help_text="Path to SSL certificate key (e.g., /etc/ssl/private/example.key)",
                max_length=255,
            ),
        ),
    ]
