# Generated by Django 5.2.4 on 2025-07-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nginx_app", "0002_alter_nginxconfig_backup_upstream_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nginxconfig",
            name="backup_upstream",
            field=models.CharField(
                blank=True,
                help_text="Backup upstream in host:port form",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="nginxconfig",
            name="listen_port",
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AlterField(
            model_name="nginxconfig",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="nginxconfig",
            name="primary_upstream",
            field=models.CharField(
                help_text="Primary upstream in host:port form", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="nginxconfig",
            name="server_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="nginxconfig",
            name="ssl_certificate",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="nginxconfig",
            name="ssl_certificate_key",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
