# Generated by Django 5.2.15 on 2026-07-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMSummaryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='lcd-log-summary', unique=True)),
                ('display', models.CharField(default='LCD Log Summary', max_length=120)),
                ('model_path', models.CharField(blank=True, max_length=255)),
                ('backend', models.CharField(choices=[('deterministic', 'Deterministic built-in summarizer'), ('ollama', 'Ollama local model')], default='deterministic', max_length=32)),
                ('ollama_base_url', models.URLField(default='http://127.0.0.1:11434', help_text='Local Ollama API base URL.', max_length=255)),
                ('ollama_model', models.CharField(blank=True, default='gemma4:e2b', help_text='Ollama model name, for example gemma4:e2b.', max_length=120)),
                ('ollama_request_timeout_seconds', models.PositiveSmallIntegerField(default=20, help_text='Maximum time to wait for one Ollama generation request.')),
                ('ollama_max_prompt_bytes', models.PositiveIntegerField(default=12000, help_text='Maximum UTF-8 prompt bytes sent to Ollama.')),
                ('ollama_context_tokens', models.PositiveIntegerField(default=4096, help_text='Ollama num_ctx option used to bound prompt context tokens.')),
                ('ollama_max_output_tokens', models.PositiveIntegerField(default=256, help_text='Ollama num_predict option used to bound generated tokens.')),
                ('ollama_keep_alive', models.CharField(blank=True, default='0', help_text='Ollama keep_alive value. Use 0 to unload after each request.', max_length=32)),
                ('ollama_lock_timeout_seconds', models.PositiveSmallIntegerField(default=0, help_text='Seconds to wait for another Ollama summary run before falling back or failing.')),
                ('ollama_fallback_to_deterministic', models.BooleanField(default=True, help_text='Use the built-in deterministic summarizer when Ollama is unavailable.')),
                ('output_target', models.CharField(choices=[('lcd', 'LCD'), ('file', 'File')], default='lcd', max_length=16)),
                ('output_file_path', models.CharField(blank=True, help_text='Local summary file path under logs/summary. Absolute paths and traversal are rejected.', max_length=255)),
                ('output_file_format', models.CharField(choices=[('text', 'Text'), ('json', 'JSON'), ('both', 'Text and JSON')], default='text', max_length=16)),
                ('model_command_audit', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('log_offsets', models.JSONField(blank=True, default=dict)),
                ('last_prompt', models.TextField(blank=True)),
                ('last_output', models.TextField(blank=True)),
                ('last_output_file_path', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM Summary Config',
                'verbose_name_plural': 'LLM Summary Configs',
            },
        ),
    ]
