# Generated by Django 5.2.12 on 2026-04-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmsummaryconfig",
            name="last_runtime_check_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="llmsummaryconfig",
            name="last_runtime_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="llmsummaryconfig",
            name="runtime_base_url",
            field=models.CharField(
                blank=True,
                default="http://127.0.0.1:8080/v1",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="llmsummaryconfig",
            name="runtime_is_ready",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="llmsummaryconfig",
            name="runtime_model_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="llmsummaryconfig",
            name="selected_model",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="llmsummaryconfig",
            name="backend",
            field=models.CharField(
                choices=[
                    (
                        "llama_cpp_server",
                        "llama.cpp OpenAI-compatible server",
                    ),
                    ("deterministic", "Deterministic built-in summarizer"),
                ],
                default="llama_cpp_server",
                max_length=32,
            ),
        ),
    ]
