# Generated by Django 5.2 on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("summary", "0002_remove_model_backends")]

    operations = [
        migrations.AlterField(
            model_name="llmsummaryconfig",
            name="display",
            field=models.CharField(default="Log Summary", max_length=120),
        ),
        migrations.AlterField(
            model_name="llmsummaryconfig",
            name="output_target",
            field=models.CharField(
                choices=[("file", "File")], default="file", max_length=16
            ),
        ),
        migrations.AlterField(
            model_name="llmsummaryconfig",
            name="slug",
            field=models.SlugField(default="log-summary", unique=True),
        ),
    ]
