# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("certs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="default", max_length=64, unique=True),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[("internal", "Internal"), ("public", "Public")],
                        default="internal",
                        max_length=16,
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[("http", "HTTP"), ("https", "HTTPS")],
                        default="http",
                        help_text="Include HTTPS listeners when set to HTTPS.",
                        max_length=5,
                    ),
                ),
                ("role", models.CharField(default="Terminal", max_length=64)),
                (
                    "port",
                    models.PositiveIntegerField(
                        default=8888,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                    ),
                ),
                (
                    "external_websockets",
                    models.BooleanField(
                        default=True,
                        help_text="Enable websocket proxy directives for external EVCS traffic.",
                    ),
                ),
                (
                    "managed_subdomains",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Comma-separated subdomain prefixes to include for each managed site (for example: api, admin, status).",
                    ),
                ),
                ("include_ipv6", models.BooleanField(default=False)),
                (
                    "expected_path",
                    models.CharField(
                        default="/etc/nginx/sites-enabled/arthexis.conf",
                        help_text="Filesystem path where the managed nginx configuration is applied.",
                        max_length=255,
                    ),
                ),
                (
                    "site_entries_path",
                    models.CharField(
                        default="scripts/generated/nginx-sites.json",
                        help_text="Staged site definitions to include when rendering managed servers.",
                        max_length=255,
                    ),
                ),
                (
                    "site_destination",
                    models.CharField(
                        default="/etc/nginx/sites-enabled/arthexis-sites.conf",
                        help_text="Destination for the rendered managed site server blocks.",
                        max_length=255,
                    ),
                ),
                ("last_applied_at", models.DateTimeField(blank=True, null=True)),
                ("last_validated_at", models.DateTimeField(blank=True, null=True)),
                ("last_message", models.TextField(blank=True, default="")),
                (
                    "certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nginx_configurations",
                        to="certs.certificatebase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site configuration",
                "verbose_name_plural": "Site Server Configs",
            },
        ),
    ]
