# Generated by Django 5.2.15 on 2026-09-14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nginx", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="certificate",
        ),
    ]
