# Generated by Django 5.2.11 on 2026-02-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nginx", "0006_remove_siteconfiguration_secondary_instance"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="tls_certificate_key_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Resolved TLS private key path for direct Daphne TLS mode.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="tls_certificate_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Resolved TLS certificate path for direct Daphne TLS mode.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="transport",
            field=models.CharField(
                choices=[("nginx", "nginx"), ("daphne", "daphne")],
                default="nginx",
                help_text="HTTPS orchestration transport backend.",
                max_length=16,
            ),
        ),
    ]
