# Generated by Django 5.2.11 on 2026-03-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LiboqsProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("display_name", models.CharField(max_length=128)),
                ("kem_algorithm", models.CharField(max_length=128)),
                ("signature_algorithm", models.CharField(blank=True, max_length=128)),
                ("enabled", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "liboqs profile",
                "verbose_name_plural": "liboqs profiles",
                "ordering": ("display_name",),
            },
        ),
    ]
