# Generated by Django 5.2.4 on 2025-08-16 02:19

import utils.sigils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_rename_instance_odooinstance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odooinstance",
            name="database",
            field=utils.sigils.SigilCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="odooinstance",
            name="password",
            field=utils.sigils.SigilCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="odooinstance",
            name="url",
            field=utils.sigils.SigilURLField(),
        ),
        migrations.AlterField(
            model_name="odooinstance",
            name="username",
            field=utils.sigils.SigilCharField(max_length=100),
        ),
    ]
