# Generated by Django 5.2.11 on 2026-02-25 03:51

import apps.sigils.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chats", "0004_alter_chatavatar_group_alter_chatavatar_user"),
        ("groups", "0003_site_operator_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Google account email used for this integration.",
                        max_length=254,
                    ),
                ),
                (
                    "client_id",
                    apps.sigils.fields.SigilShortAutoField(
                        help_text="OAuth client ID from Google Cloud.", max_length=255
                    ),
                ),
                (
                    "client_secret",
                    apps.sigils.fields.SigilShortAutoField(
                        help_text="OAuth client secret from Google Cloud.",
                        max_length=255,
                    ),
                ),
                (
                    "refresh_token",
                    apps.sigils.fields.SigilShortAutoField(
                        help_text="Refresh token granted for offline access.",
                        max_length=255,
                    ),
                ),
                (
                    "access_token",
                    apps.sigils.fields.SigilShortAutoField(
                        blank=True,
                        help_text="Cached access token used for API requests.",
                        max_length=255,
                    ),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="UTC timestamp when the cached token expires.",
                        null=True,
                    ),
                ),
                (
                    "scopes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="OAuth scopes granted to this account.",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Disable to block API usage from this account.",
                    ),
                ),
                (
                    "avatar",
                    models.ForeignKey(
                        blank=True,
                        help_text="Avatar that owns this profile when not linked directly to a user or group.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="chats.chatavatar",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Security group that owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="groups.securitygroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User that owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Google account",
                "verbose_name_plural": "Google accounts",
            },
        ),
        migrations.CreateModel(
            name="GoogleCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly display name for this tracked calendar.",
                        max_length=255,
                    ),
                ),
                (
                    "calendar_id",
                    models.CharField(
                        help_text="Google Calendar ID, usually an email-like identifier.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="IANA timezone returned by Google Calendar.",
                        max_length=64,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Cached metadata payload from Google Calendar API.",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Disable to stop synchronization and trigger execution.",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Google account used to access this calendar.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendars",
                        to="calendars.googleaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Calendar",
                "verbose_name_plural": "Google Calendars",
            },
        ),
        migrations.CreateModel(
            name="CalendarEventTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "task_name",
                    models.CharField(
                        help_text="Fully-qualified Celery task name to dispatch.",
                        max_length=255,
                    ),
                ),
                (
                    "lead_time_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Run this many minutes before event start."
                    ),
                ),
                (
                    "summary_contains",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional case-insensitive summary fragment required to match.",
                        max_length=255,
                    ),
                ),
                (
                    "location_contains",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional case-insensitive location fragment required to match.",
                        max_length=255,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Disable to pause this trigger without deleting it.",
                    ),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggers",
                        to="calendars.googlecalendar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar event trigger",
                "verbose_name_plural": "Calendar event triggers",
            },
        ),
        migrations.CreateModel(
            name="CalendarEventDispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("event_id", models.CharField(max_length=255)),
                (
                    "event_updated",
                    models.DateTimeField(
                        help_text="Last update timestamp from Google event payload."
                    ),
                ),
                (
                    "trigger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatches",
                        to="calendars.calendareventtrigger",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar event dispatch",
                "verbose_name_plural": "Calendar event dispatches",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trigger", "event_id", "event_updated"),
                        name="calendars_unique_dispatch_per_event_revision",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CalendarEventSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("event_id", models.CharField(max_length=255)),
                ("summary", models.CharField(blank=True, default="", max_length=500)),
                ("location", models.CharField(blank=True, default="", max_length=500)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("event_updated", models.DateTimeField()),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_snapshots",
                        to="calendars.googlecalendar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar event snapshot",
                "verbose_name_plural": "Calendar event snapshots",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("calendar", "event_id"),
                        name="calendars_unique_snapshot_per_event",
                    )
                ],
            },
        ),
    ]
