# Generated by Django 5.2.8 on 2025-12-05 15:40
from django.db import migrations


LANGUAGES = [
    (1, "en", "English", "English", True),
    (2, "es", "Spanish (Latin America)", "Español (Latinoamérica)", False),
    (3, "it", "Italian", "Italiano", False),
    (4, "de", "German", "Deutsch", False),
]


def seed_languages(apps, schema_editor):
    Language = apps.get_model("locale", "Language")

    for pk, code, english_name, native_name, is_default in LANGUAGES:
        if is_default:
            Language.objects.filter(is_default=True).exclude(code=code).update(is_default=False)

        Language.objects.update_or_create(
            pk=pk,
            defaults={
                "code": code,
                "english_name": english_name,
                "native_name": native_name,
                "is_default": is_default,
                "is_seed_data": True,
                "is_deleted": False,
            },
        )


def unseed_languages(apps, schema_editor):
    Language = apps.get_model("locale", "Language")
    Language.objects.filter(pk__in=[pk for pk, *_ in LANGUAGES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("locale", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_languages, unseed_languages),
    ]
