# Generated by Django 5.2.12 on 2026-04-21 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locale", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentationtranslation",
            name="documentation",
        ),
        migrations.AlterUniqueTogether(
            name="documentationtranslation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="documentationtranslation",
            name="language",
        ),
        migrations.DeleteModel(
            name="Documentation",
        ),
        migrations.DeleteModel(
            name="DocumentationTranslation",
        ),
    ]
