from . import (
    certificates,
    charging_profiles,
    configuration,
    core,
    display_messages,
    firmware,
    monitoring,
    network_profiles,
    reservations,
)


ACTION_HANDLERS = {
    "get_configuration": configuration._handle_get_configuration,
    "reserve_now": reservations._handle_reserve_now,
    "remote_stop": core._handle_remote_stop,
    "remote_start": core._handle_remote_start,
    "request_start_transaction": core._handle_request_start_transaction,
    "request_stop_transaction": core._handle_request_stop_transaction,
    "get_transaction_status": core._handle_get_transaction_status,
    "get_diagnostics": core._handle_get_diagnostics,
    "change_availability": core._handle_change_availability,
    "change_configuration": configuration._handle_change_configuration,
    "clear_cache": core._handle_clear_cache,
    "get_log": core._handle_get_log,
    "cancel_reservation": reservations._handle_cancel_reservation,
    "unlock_connector": core._handle_unlock_connector,
    "data_transfer": core._handle_data_transfer,
    "reset": core._handle_reset,
    "trigger_message": core._handle_trigger_message,
    "send_local_list": core._handle_send_local_list,
    "get_local_list_version": core._handle_get_local_list_version,
    "get_composite_schedule": charging_profiles._handle_get_composite_schedule,
    "update_firmware": firmware._handle_update_firmware,
    "set_charging_profile": charging_profiles._handle_set_charging_profile,
    "install_certificate": certificates._handle_install_certificate,
    "delete_certificate": certificates._handle_delete_certificate,
    "certificate_signed": certificates._handle_certificate_signed,
    "get_installed_certificate_ids": certificates._handle_get_installed_certificate_ids,
    "get_variables": configuration._handle_get_variables,
    "set_variables": configuration._handle_set_variables,
    "clear_display_message": display_messages._handle_clear_display_message,
    "customer_information": core._handle_customer_information,
    "get_base_report": configuration._handle_get_base_report,
    "get_charging_profiles": charging_profiles._handle_get_charging_profiles,
    "get_display_messages": display_messages._handle_get_display_messages,
    "get_report": configuration._handle_get_report,
    "set_display_message": display_messages._handle_set_display_message,
    "set_network_profile": network_profiles._handle_set_network_profile,
    "set_monitoring_base": monitoring._handle_set_monitoring_base,
    "set_monitoring_level": monitoring._handle_set_monitoring_level,
    "set_variable_monitoring": monitoring._handle_set_variable_monitoring,
    "clear_variable_monitoring": monitoring._handle_clear_variable_monitoring,
    "get_monitoring_report": monitoring._handle_get_monitoring_report,
}
