# Generated by Django 5.2.12 on 2026-04-24 22:27

import apps.media.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaSourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seed_data', models.BooleanField(default=False, editable=False)),
                ('is_user_data', models.BooleanField(default=False, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, default='', max_length=120, verbose_name='Name')),
                ('slug', models.SlugField(default=apps.media.models.media_source_file_slug, max_length=64, unique=True, verbose_name='Source Path')),
                ('source_type', models.CharField(choices=[('mse_set', 'Magic Set Editor set'), ('archive', 'Archive'), ('other', 'Other')], default='mse_set', max_length=30, verbose_name='Source type')),
                ('file', models.FileField(upload_to=apps.media.models.media_source_file_path, verbose_name='File')),
                ('original_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Original name')),
                ('content_type', models.CharField(blank=True, default='', max_length=255, verbose_name='Content type')),
                ('size', models.BigIntegerField(default=0, verbose_name='Size (bytes)')),
                ('checksum_sha256', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='SHA-256 checksum')),
                ('source_uri', models.CharField(blank=True, default='', help_text='Original local path, upload source, or external URI for provenance.', max_length=512, verbose_name='Source URI')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media Source File',
                'verbose_name_plural': 'Media Source Files',
                'db_table': 'protocols_mediasourcefile',
                'ordering': ('-uploaded_at', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='mediafile',
            name='source_member',
            field=models.CharField(blank=True, default='', help_text='Path or member name inside the source file, when applicable.', max_length=255, verbose_name='Source member'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='source_file',
            field=models.ForeignKey(blank=True, help_text='Archive or source package this media file was derived from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_files', to='media.mediasourcefile', verbose_name='Source file'),
        ),
    ]
