# Generated by Django 5.2.12 on 2026-04-13 23:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0002_initial"),
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Gallery Category",
                "verbose_name_plural": "Gallery Categories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="GalleryTrait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Gallery Trait",
                "verbose_name_plural": "Gallery Traits",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "slug",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("include_in_public_gallery", models.BooleanField(default=False)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="images", to="gallery.gallerycategory"
                    ),
                ),
                (
                    "media_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gallery_images",
                        to="media.mediafile",
                    ),
                ),
                (
                    "owner_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_gallery_images",
                        to="groups.securitygroup",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_gallery_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery Image",
                "verbose_name_plural": "Gallery Images",
            },
        ),
        migrations.CreateModel(
            name="GalleryCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("display_name", models.CharField(max_length=255)),
                ("artist", models.CharField(blank=True, default="", max_length=255)),
                ("series", models.CharField(blank=True, default="", max_length=255)),
                ("era", models.CharField(blank=True, default="", max_length=255)),
                ("apa_citation", models.TextField(blank=True, default="")),
                ("contributed_elements", models.TextField(blank=True, default="")),
                ("excluded_elements", models.TextField(blank=True, default="")),
                ("link_url", models.URLField(blank=True, default="")),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="gallery.galleryimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery Credit",
                "verbose_name_plural": "Gallery Credits",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="GalleryImageTrait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "qualitative_value",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("float_value", models.FloatField(default=1.0)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trait_values",
                        to="gallery.gallerycategory",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trait_values",
                        to="gallery.galleryimage",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trait_values",
                        to="gallery.gallerytrait",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery Image Trait",
                "verbose_name_plural": "Gallery Image Traits",
            },
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="traits",
            field=models.ManyToManyField(
                related_name="images",
                through="gallery.GalleryImageTrait",
                to="gallery.gallerytrait",
            ),
        ),
        migrations.AddConstraint(
            model_name="galleryimagetrait",
            constraint=models.UniqueConstraint(
                fields=("image", "category", "trait", "qualitative_value"),
                name="gallery_image_trait_unique_assignment",
            ),
        ),
        migrations.AddConstraint(
            model_name="galleryimage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("owner_user__isnull", False),
                    ("owner_group__isnull", False),
                    _negated=True,
                ),
                name="gallery_image_single_owner",
            ),
        ),
    ]
