# Generated by Django 5.2.12 on 2026-04-20 05:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_galleryimage_content_sample"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="shared_with_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_gallery_images",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
