# Generated by Django 5.2.11 on 2026-03-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="closing_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="opening_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
