# Generated by Django 5.2.11 on 2026-03-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odoo", "0008_odooemployee_avatar_null"),
        ("shop", "0002_shop_closing_time_shop_opening_time"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="shop",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("closing_time__isnull", True), ("opening_time__isnull", True)
                    ),
                    models.Q(
                        ("closing_time__isnull", False), ("opening_time__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="shop_business_hours_both_set_or_null",
            ),
        ),
    ]
