import json
from pathlib import Path
from unittest.mock import ANY, patch

import pytest
from django.core.management import call_command


def test_ocpp_coverage_201_matches_fixture(tmp_path):
    output_path = tmp_path / "ocpp201_coverage.json"
    badge_path = tmp_path / "ocpp201_coverage.svg"

    call_command(
        "ocpp",
        "coverage",
        "--version",
        "2.0.1",
        json_path=output_path,
        badge_path=badge_path,
    )

    generated = json.loads(output_path.read_text())
    fixture_path = Path(__file__).resolve().parents[1] / "coverage201.json"
    expected = json.loads(fixture_path.read_text())
    assert generated["coverage"] == expected["coverage"]


def test_ocpp_coverage_16_routes_through_unified_command(tmp_path):
    """Regression: ``ocpp coverage`` should support the 1.6 coverage workflow."""

    output_path = tmp_path / "ocpp16_coverage.json"
    badge_path = tmp_path / "ocpp16_coverage.svg"

    call_command(
        "ocpp",
        "coverage",
        "--version",
        "1.6",
        json_path=output_path,
        badge_path=badge_path,
    )

    assert output_path.exists()
    assert badge_path.exists()


@pytest.mark.parametrize(
    ("version", "json_name", "badge_name", "fixture_name"),
    [
        ("1.6J", "ocpp16_coverage.json", "ocpp16_coverage.svg", "coverage.json"),
        ("2.1", "ocpp21_coverage.json", "ocpp21_coverage.svg", "coverage21.json"),
    ],
)
def test_ocpp_coverage_matches_fixture(tmp_path, version, json_name, badge_name, fixture_name):
    """Regression: generated OCPP coverage output stays aligned with checked-in fixtures.

    Args:
        tmp_path (Path): Temporary directory where command output files are written.
        version (str): OCPP version passed to the coverage subcommand.
        json_name (str): Coverage JSON file name generated by the command.
        badge_name (str): Badge SVG file name generated by the command.
        fixture_name (str): Fixture JSON file name used for expected values.

    Returns:
        None

    Raises:
        AssertionError: If generated coverage fields do not match the fixture.
    """

    output_path = tmp_path / json_name
    badge_path = tmp_path / badge_name

    call_command(
        "ocpp",
        "coverage",
        "--version",
        version,
        json_path=output_path,
        badge_path=badge_path,
    )

    generated = json.loads(output_path.read_text())
    fixture_path = Path(__file__).resolve().parents[1] / fixture_name
    expected = json.loads(fixture_path.read_text())
    assert generated == expected
