"""Generate ``requirements.txt`` from pyproject dependency declarations."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError as exc:  # pragma: no cover
    raise RuntimeError("Python 3.11+ is required to parse pyproject.toml") from exc


PYPROJECT_PATH = Path("pyproject.toml")
REQUIREMENTS_PATH = Path("requirements.txt")
HEADER_LINES = (
    "# This file is generated from pyproject.toml project + ci dependencies.",
    "# Regenerate with: python scripts/generate_requirements.py",
    "# Do not edit this file manually.",
)


class RequirementsGenerationError(RuntimeError):
    """Raised when requirement generation cannot proceed."""


def _load_runtime_dependencies(pyproject_path: Path) -> list[str]:
    """Return runtime and CI dependency specifiers from ``pyproject.toml``."""
    if not pyproject_path.exists():
        raise FileNotFoundError(f"Missing dependency source file: {pyproject_path}")

    data = tomllib.loads(pyproject_path.read_text(encoding="utf-8"))
    project_data = data.get("project")
    if not isinstance(project_data, dict):
        raise RequirementsGenerationError("Missing [project] section in pyproject.toml")

    runtime_dependencies = project_data.get("dependencies")
    if not isinstance(runtime_dependencies, list):
        raise RequirementsGenerationError(
            "Expected [project].dependencies to be a list of requirement specifiers"
        )

    optional_dependencies = project_data.get("optional-dependencies", {})
    if not isinstance(optional_dependencies, dict):
        raise RequirementsGenerationError(
            "Expected [project.optional-dependencies] to be a table of dependency lists"
        )

    ci_dependencies = optional_dependencies.get("ci", [])
    if not isinstance(ci_dependencies, list):
        raise RequirementsGenerationError(
            "Expected [project.optional-dependencies].ci to be a list"
        )

    dependencies = [*runtime_dependencies, *ci_dependencies]

    invalid_entries = [entry for entry in dependencies if not isinstance(entry, str)]
    if invalid_entries:
        raise RequirementsGenerationError("Found non-string dependency entries in pyproject.toml")

    return dependencies


def _build_requirements_text(dependencies: list[str]) -> str:
    """Build normalized requirements content with generation metadata."""
    lines = [*HEADER_LINES, "", *sorted(set(dependencies), key=str.lower)]
    return "\n".join(lines) + "\n"


def generate_requirements(pyproject_path: Path, requirements_path: Path) -> None:
    """Write ``requirements.txt`` from runtime dependencies in ``pyproject.toml``."""
    dependencies = _load_runtime_dependencies(pyproject_path)
    requirements_path.write_text(_build_requirements_text(dependencies), encoding="utf-8")


def check_requirements(pyproject_path: Path, requirements_path: Path) -> bool:
    """Return whether committed requirements content matches generated output."""
    expected = _build_requirements_text(_load_runtime_dependencies(pyproject_path))
    current = requirements_path.read_text(encoding="utf-8") if requirements_path.exists() else ""
    return current == expected


def main() -> int:
    """Parse CLI arguments and generate or validate requirements output."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify requirements.txt matches generated output without writing files.",
    )
    args = parser.parse_args()

    if args.check:
        if check_requirements(PYPROJECT_PATH, REQUIREMENTS_PATH):
            print("requirements.txt is up to date")
            return 0
        print(
            "requirements.txt is out of date. "
            "Run: python scripts/generate_requirements.py",
            file=sys.stderr,
        )
        return 1

    generate_requirements(PYPROJECT_PATH, REQUIREMENTS_PATH)
    print("Regenerated requirements.txt from pyproject.toml")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
