# Generated by Django 5.2.12 on 2026-04-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nodes", "0010_cleanup_retired_node_feature_slugs"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=150)),
                ("markdown", models.TextField()),
                (
                    "node_roles",
                    models.ManyToManyField(
                        blank=True, related_name="agent_skills", to="nodes.noderole"
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Skill",
                "verbose_name_plural": "Agent Skills",
                "ordering": ("slug",),
            },
        ),
    ]
