# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SuiteTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node_id",
                    models.CharField(
                        help_text="Full pytest node identifier.",
                        max_length=512,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Short test name.", max_length=255),
                ),
                (
                    "module_path",
                    models.CharField(
                        blank=True,
                        help_text="Python module path that owns the test.",
                        max_length=512,
                    ),
                ),
                (
                    "app_label",
                    models.CharField(
                        blank=True,
                        help_text="Inferred app label from file path.",
                        max_length=128,
                    ),
                ),
                (
                    "class_name",
                    models.CharField(
                        blank=True,
                        help_text="Owning test class when applicable.",
                        max_length=255,
                    ),
                ),
                (
                    "marks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Pytest marks/keywords attached to the test.",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Repository-relative python file path.",
                        max_length=512,
                    ),
                ),
                (
                    "is_parameterized",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this test node includes parametrization.",
                    ),
                ),
                (
                    "discovered_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Suite test",
                "verbose_name_plural": "Suite tests",
                "ordering": [
                    "app_label",
                    "module_path",
                    "class_name",
                    "name",
                    "node_id",
                ],
            },
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node_id",
                    models.CharField(
                        help_text="Full pytest node identifier", max_length=512
                    ),
                ),
                ("name", models.CharField(help_text="Short test name", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("error", "Error"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "duration",
                    models.FloatField(
                        blank=True, help_text="Runtime in seconds", null=True
                    ),
                ),
                (
                    "log",
                    models.TextField(
                        blank=True, help_text="Captured output and failure details"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
            options={
                "verbose_name": "Test result",
                "verbose_name_plural": "Test results",
                "ordering": ["-created_at", "node_id"],
            },
        ),
    ]
