# Generated by Django 5.2.8 on 2025-12-05 02:53

import django.contrib.sites.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pages", "0001_initial"),
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteProxy",
            fields=[],
            options={
                "verbose_name": "Site",
                "verbose_name_plural": "Sites",
                "permissions": [
                    ("add_siteproxy", "Can add site"),
                    ("change_siteproxy", "Can change site"),
                    ("delete_siteproxy", "Can delete site"),
                    ("view_siteproxy", "Can view site"),
                ],
                "proxy": True,
                "default_permissions": (),
                "indexes": [],
                "constraints": [],
            },
            bases=("sites.site",),
            managers=[
                ("objects", django.contrib.sites.models.SiteManager()),
            ],
        ),
    ]
