# Generated by Django 5.2.8 on 2025-12-02 02:54

import django.contrib.sites.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0001_initial"),
        ("core", "0003_initial"),
        ("nodes", "0001_initial"),
        ("pages", "0001_initial"),
        ("sites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteProxy",
            fields=[],
            options={
                "verbose_name": "Site",
                "verbose_name_plural": "Sites",
                "permissions": [
                    ("add_siteproxy", "Can add site"),
                    ("change_siteproxy", "Can change site"),
                    ("delete_siteproxy", "Can delete site"),
                    ("view_siteproxy", "Can view site"),
                ],
                "proxy": True,
                "default_permissions": (),
                "indexes": [],
                "constraints": [],
            },
            bases=("sites.site",),
            managers=[
                ("objects", django.contrib.sites.models.SiteManager()),
            ],
        ),
        migrations.AddField(
            model_name="landinglead",
            name="assign_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="landinglead",
            name="landing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leads",
                to="pages.landing",
            ),
        ),
        migrations.AddField(
            model_name="landinglead",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="app.application",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="node_role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="nodes.noderole",
            ),
        ),
        migrations.AddField(
            model_name="landing",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landings",
                to="pages.module",
            ),
        ),
        migrations.AddField(
            model_name="rolelanding",
            name="landing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_defaults",
                to="pages.landing",
            ),
        ),
        migrations.AddField(
            model_name="rolelanding",
            name="node_role",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_landing",
                to="nodes.noderole",
            ),
        ),
        migrations.AddField(
            model_name="rolelanding",
            name="security_group",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_landing",
                to="core.securitygroup",
            ),
        ),
        migrations.AddField(
            model_name="rolelanding",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_landing",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sitebadge",
            name="landing_override",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pages.landing",
            ),
        ),
        migrations.AddField(
            model_name="sitebadge",
            name="site",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="badge",
                to="sites.site",
            ),
        ),
        migrations.AddField(
            model_name="userstory",
            name="assign_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userstory",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Internal owner for this feedback.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_user_stories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userstory",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_stories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="module",
            unique_together={("node_role", "path")},
        ),
        migrations.AlterUniqueTogether(
            name="landing",
            unique_together={("module", "path")},
        ),
        migrations.AddConstraint(
            model_name="rolelanding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("node_role__isnull", False),
                        ("security_group__isnull", True),
                        ("user__isnull", True),
                    ),
                    models.Q(
                        ("node_role__isnull", True),
                        ("security_group__isnull", False),
                        ("user__isnull", True),
                    ),
                    models.Q(
                        ("node_role__isnull", True),
                        ("security_group__isnull", True),
                        ("user__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="pages_rolelanding_single_target",
            ),
        ),
    ]
