# Generated by Django 5.2.8 on 2025-12-02 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitetemplate",
            options={
                "ordering": ("name",),
                "verbose_name": "Site Branding",
                "verbose_name_plural": "Site Brandings",
            },
        ),
    ]
