# Generated by Django 5.2.8 on 2025-12-03 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
        ("groups", "0002_initial"),
        ("pages", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="landing",
            name="validated_url_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the last landing validation check.",
                null=True,
                verbose_name="Validated URL",
            ),
        ),
        migrations.AddField(
            model_name="landing",
            name="validation_status",
            field=models.IntegerField(
                blank=True,
                help_text="HTTP status code from the last landing validation attempt.",
                null=True,
                verbose_name="Validation Status",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="security_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modules",
                to="groups.securitygroup",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="security_mode",
            field=models.CharField(
                choices=[("exclusive", "Exclusive"), ("inclusive", "Inclusive")],
                default="inclusive",
                help_text="Exclusive requires site and group match; inclusive allows either.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modules",
                to="app.application",
            ),
        ),
    ]
