# Generated by Django 5.2.8 on 2025-12-01 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_add_site_nginx_fields"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExperienceReference",
        ),
    ]
