# Generated by Django 5.2.8 on 2025-12-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_delete_usermanual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viewhistory",
            name="path",
            field=models.CharField(max_length=2048),
        ),
    ]
