# Generated by Django 5.2.11 on 2026-02-25 01:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_site_operator_group"),
        ("selenium", "0007_sessioncookie_selenium_sessioncookie_owner_exclusive"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sessioncookie",
            name="selenium_sessioncookie_owner_exclusive",
        ),
        migrations.AddConstraint(
            model_name="sessioncookie",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("user__isnull", False), ("group__isnull", True)),
                    models.Q(("user__isnull", True), ("group__isnull", False)),
                    _connector="OR",
                ),
                name="selenium_sessioncookie_owner_exclusive",
            ),
        ),
    ]
