# Generated by Django 5.2.12 on 2026-03-25 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screens", "0004_lcdanimationlegacysource_remove_lcdanimation_generator_path"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CharacterScreen",
        ),
        migrations.RemoveField(
            model_name="lcdanimationlegacysource",
            name="animation",
        ),
        migrations.DeleteModel(
            name="PixelScreen",
        ),
        migrations.DeleteModel(
            name="LCDAnimation",
        ),
        migrations.DeleteModel(
            name="LCDAnimationLegacySource",
        ),
    ]
