# Generated by Django 5.2.12 on 2026-09-17 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("energy", "0002_initial"),
        ("nodes", "0002_initial"),
        ("ocpp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Charger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identity", models.CharField(max_length=120, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chargers",
                        to="nodes.node",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Connector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                ("status", models.CharField(default="available", max_length=30)),
                (
                    "charger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connectors",
                        to="ocpp.charger",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OcppTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_tag", models.CharField(blank=True, max_length=20)),
                ("remote_id", models.CharField(max_length=80, unique=True)),
                ("started_at", models.DateTimeField()),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "meter_start",
                    models.DecimalField(decimal_places=4, max_digits=14, null=True),
                ),
                (
                    "meter_stop",
                    models.DecimalField(decimal_places=4, max_digits=14, null=True),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocpp_transactions",
                        to="energy.customeraccount",
                    ),
                ),
                (
                    "charger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="ocpp.charger",
                    ),
                ),
                (
                    "connector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="ocpp.connector",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeterValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sampled_at", models.DateTimeField()),
                ("value", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "measurand",
                    models.CharField(
                        default="Energy.Active.Import.Register", max_length=60
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meter_values",
                        to="ocpp.ocpptransaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor", models.CharField(max_length=120)),
                ("family", models.CharField(blank=True, max_length=120)),
                ("model", models.CharField(max_length=120)),
                (
                    "preferred_protocol",
                    models.CharField(default="ocpp1.6", max_length=20),
                ),
                ("integration_notes", models.TextField(blank=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("vendor", "model"), name="unique_station_model"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="charger",
            name="station_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chargers",
                to="ocpp.stationmodel",
            ),
        ),
        migrations.AddConstraint(
            model_name="connector",
            constraint=models.UniqueConstraint(
                fields=("charger", "number"), name="unique_charger_connector"
            ),
        ),
    ]
