# Generated by Django 5.2.8 on 2025-12-02 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
        ("ocpp", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="cpreservation",
                    name="rfid",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cp_reservations",
                        to="cards.rfid",
                        verbose_name="RFID",
                    ),
                ),
            ],
        )
    ]
