# Generated by Django 5.2.8 on 2025-11-30 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
        ("ocpp", "0002_vehicle_models_to_vehicle_app"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charger",
            name="diagnostics_bucket",
            field=models.ForeignKey(
                blank=True,
                help_text="Media bucket where this charge point should upload diagnostics.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chargers",
                to="media.mediabucket",
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name="MediaFile",
                ),
                migrations.DeleteModel(
                    name="MediaBucket",
                ),
            ],
        ),
    ]
