# Generated by Django 5.2.12 on 2026-09-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocpp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charger',
            name='connection_token_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
