# Generated by Django 5.2.8 on 2025-12-02 01:37

from django.db import migrations, models

from apps.migration_utils import import_callable


generate_log_request_id = import_callable(
    "apps.ocpp.migration_utils.generate_log_request_id",
    aliases={
        "apps.ocpp.models.generate_log_request_id": "apps.ocpp.migration_utils.generate_log_request_id",
    },
)

default_forwarded_messages = import_callable(
    "apps.ocpp.migration_utils.default_forwarded_messages",
    default=list,
    aliases={
        "apps.ocpp.models.default_forwarded_messages": "apps.ocpp.migration_utils.default_forwarded_messages",
    },
)


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0002_alter_chargerlogrequest_request_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargerlogrequest",
            name="request_id",
            field=models.BigIntegerField(
                default=generate_log_request_id,
                unique=True,
                verbose_name="Request Id",
            ),
        ),
        migrations.AlterField(
            model_name="cpforwarder",
            name="forwarded_messages",
            field=models.JSONField(
                blank=True,
                default=default_forwarded_messages,
                help_text="Select the OCPP messages that should be forwarded to the remote node.",
            ),
        ),
    ]
