# Generated by Django 5.2.8 on 2025-12-02 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
        ("core", "0004_delete_rfid"),
        ("ocpp", "0002_alter_cpreservation_rfid"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name="RFID"),
                migrations.CreateModel(
                    name="RFID",
                    fields=[],
                    options={
                        "verbose_name": "RFID",
                        "verbose_name_plural": "RFIDs",
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("cards.rfid",),
                ),
            ],
        ),
    ]
