# Generated by Django 5.2.8 on 2025-12-02 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0003_rebase_rfid_proxy"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datatransfermessage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "CP Data Message",
                "verbose_name_plural": "CP Data Messages",
            },
        ),
    ]
