# Generated by Django 5.2.8 on 2025-12-03 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
        ("ocpp", "0004_alter_datatransfermessage_options"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="charger",
                    name="owner_groups",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="Security groups that can view this charge point.",
                        related_name="owned_chargers",
                        to="groups.securitygroup",
                    ),
                ),
                migrations.AlterField(
                    model_name="charger",
                    name="ws_auth_group",
                    field=models.ForeignKey(
                        blank=True,
                        help_text=(
                            "Charge point connections must authenticate with HTTP Basic as a member of this security group."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ws_group_authenticated_chargers",
                        to="groups.securitygroup",
                        verbose_name="WS Auth Group",
                    ),
                ),
            ],
        )
    ]
