# Generated by Django 5.2.8 on 2025-12-01 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0002_update_location_refs"),
        ("ocpp", "0004_chargerconfiguration_is_deleted_and_more"),
    ]

    operations = []
