# Generated by Django 5.2.12 on 2026-04-10 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0004_cpforwarder_forwarding_frequency_hz"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="simulator",
            options={
                "verbose_name": "OCPP Simulator",
                "verbose_name_plural": "OCPP Simulators",
            },
        ),
    ]
