# Generated by Django 5.2.12 on 2026-09-17 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocpp', '0004_certificaterecord_operationalstatusrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metervalue',
            name='multiplier',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metervalue',
            name='unit',
            field=models.CharField(default='Wh', max_length=12),
        ),
        migrations.AddField(
            model_name='ocpptransaction',
            name='energy_kwh',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='ChargerConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255)),
                ('protocol', models.CharField(max_length=12)),
                ('connected_at', models.DateTimeField(auto_now=True)),
                ('charger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='ocpp.charger')),
            ],
        ),
    ]
