# Generated by Django 5.2.12 on 2026-09-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocpp", "0005_charger_snapshot_and_connection"),
    ]

    operations = [
        migrations.AddField(
            model_name="charger",
            name="authorization_mode",
            field=models.CharField(
                choices=[("open", "Open"), ("restricted", "Restricted")],
                default="open",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="charger",
            name="enrolled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
