# Generated by Django 5.2.15 on 2026-08-21

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocpp", "0005_charger_auto_start_id_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoStartAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reservation_scope", models.CharField(max_length=64)),
                ("id_tag", models.CharField(max_length=20)),
                (
                    "attempt_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("message_id", models.CharField(max_length=36, unique=True)),
                ("action", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("accepted", "Accepted"),
                            ("started", "Started"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                            ("timed_out", "Timed out"),
                            ("released", "Released"),
                        ],
                        default="requested",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("retry_after", models.DateTimeField(blank=True, null=True)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "charger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_start_attempts",
                        to="ocpp.charger",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auto-start attempt",
                "verbose_name_plural": "Auto-start attempts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="autostartattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state__in", ("requested", "accepted", "started"))),
                fields=("charger", "reservation_scope"),
                name="unique_active_auto_start_attempt",
            ),
        ),
    ]
