# Generated by Django 5.2.12 on 2026-09-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocpp", "0006_charger_authorization_mode_charger_enrolled_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="InboundProtocolRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        choices=[
                            ("ocpp1.6", "OCPP_16"),
                            ("ocpp2.0.1", "OCPP_201"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("charge_point_to_csms", "CHARGE_POINT_TO_CSMS"),
                            ("csms_to_charge_point", "CSMS_TO_CHARGE_POINT"),
                        ],
                        default="charge_point_to_csms",
                        max_length=24,
                    ),
                ),
                ("action", models.CharField(max_length=80)),
                ("unique_id", models.CharField(max_length=80)),
                ("fingerprint", models.CharField(max_length=64)),
                (
                    "replay_policy",
                    models.CharField(
                        choices=[
                            ("call_id_and_fingerprint", "CALL_ID_AND_FINGERPRINT"),
                            ("domain_identity", "DOMAIN_IDENTITY"),
                            ("no_cross_call_dedup", "NO_CROSS_CALL_DEDUP"),
                        ],
                        default="call_id_and_fingerprint",
                        max_length=32,
                    ),
                ),
                ("domain_identity", models.CharField(blank=True, max_length=160)),
                ("identity_key", models.CharField(max_length=64)),
                ("request_payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                        ],
                        default="processing",
                        max_length=16,
                    ),
                ),
                (
                    "response_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("result", "CallResult"),
                            ("error", "CallError"),
                        ],
                        max_length=12,
                    ),
                ),
                ("response_payload", models.JSONField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("error_description", models.CharField(blank=True, max_length=240)),
                ("error_details", models.JSONField(blank=True, null=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "charger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbound_protocol_requests",
                        to="ocpp.charger",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["charger", "status", "received_at"],
                        name="ocpp_inbound_status_idx",
                    ),
                    models.Index(
                        fields=["charger", "unique_id", "received_at"],
                        name="ocpp_inbound_call_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "charger",
                            "version",
                            "direction",
                            "action",
                            "identity_key",
                        ),
                        name="unique_ocpp_inbound_replay_identity",
                    )
                ],
            },
        ),
    ]
