# Generated by Django 5.2.12 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocpp", "0010_transaction_recovery_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="metervalue",
            name="source_fingerprint",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name="metervalue",
            constraint=models.UniqueConstraint(
                condition=~models.Q(source_fingerprint=""),
                fields=("transaction", "source_fingerprint"),
                name="unique_ocpp_meter_sample_fingerprint",
            ),
        ),
    ]
