# Generated by Django 5.2.12 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocpp", "0011_meter_sample_fingerprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalstatusrecord",
            name="source_action",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="operationalstatusrecord",
            name="reported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
