# Generated by Django 5.2.12 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocpp", "0013_notification_reported_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoringrecord",
            name="reported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
