# Generated by Django 5.2.10 on 2026-02-04 18:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
        ("ocpp", "0014_publicconnectorpage_publicscanevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="stationmodel",
            name="documents_bucket",
            field=models.ForeignKey(
                blank=True,
                help_text="Media bucket for manuals and supporting files.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="station_model_documents",
                to="media.mediabucket",
            ),
        ),
        migrations.AddField(
            model_name="stationmodel",
            name="images_bucket",
            field=models.ForeignKey(
                blank=True,
                help_text="Media bucket for charger images.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="station_model_images",
                to="media.mediabucket",
            ),
        ),
        migrations.AddField(
            model_name="stationmodel",
            name="instructions_markdown",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Special instructions in Markdown format.",
            ),
        ),
        migrations.AddField(
            model_name="stationmodel",
            name="integration_rating",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Integration quality rating from 0 (unknown) to 5.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Integration Rating",
            ),
        ),
    ]
