# Generated by Django 5.2.9 on 2026-01-06 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

SITE_OPERATOR_GROUP_NAME = "Site Operator"


def assign_site_operator_group(apps, schema_editor):
    Charger = apps.get_model("ocpp", "Charger")
    SecurityGroup = apps.get_model("groups", "SecurityGroup")

    group = (
        SecurityGroup.objects.using(schema_editor.connection.alias)
        .filter(name=SITE_OPERATOR_GROUP_NAME)
        .first()
    )
    if not group:
        return

    Charger.objects.using(schema_editor.connection.alias).filter(
        user__isnull=True,
        group__isnull=True,
    ).update(group=group)


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0016_remove_rfid_session_attempt"),
        ("groups", "0003_site_operator_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="charger",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Security group that owns this object.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="groups.securitygroup",
            ),
        ),
        migrations.AddField(
            model_name="charger",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User that owns this object.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="charger",
            name="maintenance_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Optional contact to notify when the charge point is offline.",
                max_length=254,
                verbose_name="Maintenance Email",
            ),
        ),
        migrations.AddField(
            model_name="charger",
            name="email_when_offline",
            field=models.BooleanField(
                default=False,
                help_text="Send an email notification if this charge point is offline.",
                verbose_name="Email when offline",
            ),
        ),
        migrations.AddField(
            model_name="charger",
            name="offline_notification_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time an offline notification was sent for this charge point.",
                null=True,
                verbose_name="Offline Notification Sent At",
            ),
        ),
        migrations.RunPython(assign_site_operator_group, migrations.RunPython.noop),
    ]
