# Generated by Django 5.2.12 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocpp", "0016_meter_reading_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="charger",
            name="authority_cutover_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ocpptransaction",
            name="historical",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
