# Generated by Django 5.2.12 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocpp", "0017_authority_cutover_historical_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocoloperation",
            name="attempt_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="protocoloperation",
            name="first_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="protocoloperation",
            name="last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="protocoloperation",
            name="last_delivery_error",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name="protocoloperation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("delivering", "Delivering"),
                    ("recovery_required", "Recovery required"),
                    ("completed", "Completed"),
                    ("errored", "Errored"),
                    ("timed_out", "Timed out"),
                    ("disconnected", "Disconnected"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
