# Generated by Django 5.2.10 on 2026-02-07 01:18

import apps.ocpp.models.cp_forwarder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0018_forwarder_calls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cpforwarder",
            name="forwarded_calls",
            field=models.JSONField(
                blank=True,
                default=apps.ocpp.models.cp_forwarder.default_forwarded_calls,
                help_text="Select the CSMS actions that should be accepted from the remote node.",
            ),
        ),
    ]
