# Generated by Django 5.2.12 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocpp", "0019_protocol_operation_recovery_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocoloperation",
            name="attempt_token",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="protocoloperation",
            name="delivery_owner",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
