# Generated by Django 5.2.11 on 2026-03-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0021_transaction_stop_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="authorization_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional reason reported when authorization is rejected.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="authorization_status",
            field=models.CharField(
                choices=[("accepted", "Accepted"), ("rejected", "Rejected")],
                default="accepted",
                help_text="Authorization result for the start attempt that created this transaction record.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="rejected_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the start attempt was rejected.",
                null=True,
            ),
        ),
    ]
