# Generated by Django 5.2.11 on 2026-03-02 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models




def _link_existing_charge_points(apps, schema_editor):
    """Defer charge-point linking to the checkpointed release transform pipeline."""

    del apps, schema_editor


def _unlink_existing_charge_points(apps, schema_editor):
    """Revert station links before dropping ChargingStation rows."""

    Charger = apps.get_model("ocpp", "Charger")
    Charger.objects.update(charging_station=None)


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_site_operator_group"),
        ("maps", "0002_initial"),
        ("ocpp", "0023_repair_transaction_columns"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChargingStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "station_id",
                    models.CharField(
                        help_text="Unique identifier reported by the charging station.",
                        max_length=100,
                        unique=True,
                        verbose_name="Station ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional friendly name shown in admin and public pages.",
                        max_length=200,
                        verbose_name="Display Name",
                    ),
                ),
                ("last_path", models.CharField(blank=True, max_length=255)),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Security group that owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="groups.securitygroup",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="charging_stations",
                        to="maps.location",
                    ),
                ),
                (
                    "owner_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Security groups that can view this charging station.",
                        related_name="owned_charging_stations",
                        to="groups.securitygroup",
                    ),
                ),
                (
                    "owner_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users who can view this charging station.",
                        related_name="owned_charging_stations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "station_model",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional hardware model for this charging station.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="charging_stations",
                        to="ocpp.stationmodel",
                        verbose_name="Station Model",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User that owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Charging Station",
                "verbose_name_plural": "Charging Stations",
            },
        ),
        migrations.AddField(
            model_name="charger",
            name="charging_station",
            field=models.ForeignKey(
                blank=True,
                help_text="Physical charging station that owns this charge point.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="charge_points",
                to="ocpp.chargingstation",
            ),
        ),
        migrations.RunPython(_link_existing_charge_points, _unlink_existing_charge_points),
    ]
