# Generated by Django 5.2.12 on 2026-03-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0024_chargingstation_charger_charging_station"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="vin",
            field=models.CharField(
                blank=True, help_text="Use VID instead.", max_length=17
            ),
        ),
    ]
