# Generated by Django 5.2.12 on 2026-03-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0002_initial"),
        ("ocpp", "0027_remove_charger_auto_accept_offered_certificates"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleMapsLocation",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("maps.googlemapslocation",),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("maps.location",),
        ),
    ]
