# Generated by Django 5.2.12 on 2026-03-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0029_seed_public_connector_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="charger",
            name="authorization_policy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("strict", "Strict"),
                    ("allowlist", "Allowlist"),
                    ("open", "Open (insecure compatibility mode)"),
                ],
                default="",
                help_text="How to evaluate RFID/account authorization. Leave blank to use the global default.",
                max_length=16,
                verbose_name="Authorization Policy",
            ),
        ),
    ]
