# Generated by Django 5.2.4 on 2025-08-23 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("arts", "0301_initial"),
        ("refs", "0101_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="references",
            field=models.ManyToManyField(
                blank=True, related_name="articles", to="refs.reference"
            ),
        ),
        migrations.AddField(
            model_name="authorprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="authors",
            field=models.ManyToManyField(
                blank=True, related_name="articles", to="arts.authorprofile"
            ),
        ),
        migrations.AddField(
            model_name="mediaimage",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="arts.article",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mediaimage",
            unique_together={("article", "name")},
        ),
    ]
