GALLERY_MANAGER_GROUP_NAME = "Gallery Manager"
GALLERY_BUCKET_SLUG = "gallery-images"
GALLERY_AP_GUEST_SESSION_KEY = "gallery_ap_guest_key"
GALLERY_AP_GUEST_MAX_TITLE_LENGTH = 40
GALLERY_AP_GUEST_MAX_UPLOAD_BYTES = 5 * 1024 * 1024
