GALLERY_MANAGER_GROUP_NAME = "Gallery Manager"
GALLERY_BUCKET_SLUG = "gallery-images"
GALLERY_AP_GUEST_SESSION_KEY = "gallery_ap_guest_key"
GALLERY_AP_GUEST_MAX_TITLE_LENGTH = 40
GALLERY_AP_GUEST_MAX_UPLOAD_BYTES = 5 * 1024 * 1024
GALLERY_AP_GUEST_PAGE_SIZE = 24
GALLERY_AP_GUEST_DAILY_LIMIT_MESSAGE = "You can upload one image per day."
