# Generated by Django 5.2.12 on 2026-03-27 20:33

import apps.release.models.package
import django.db.models.deletion
import utils.revision
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "name",
                    models.CharField(default="arthexis", max_length=100, unique=True),
                ),
                (
                    "description",
                    models.CharField(
                        default="Energy & Power Infrastructure", max_length=255
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        default="Rafael J. Guillén-Osorio", max_length=100
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="tecnologia@gelectriic.com", max_length=254
                    ),
                ),
                ("python_requires", models.CharField(default=">=3.10", max_length=20)),
                (
                    "license",
                    models.CharField(
                        default=apps.release.models.package.PackageLicenseDefault(),
                        max_length=100,
                    ),
                ),
                (
                    "repository_url",
                    models.URLField(default="https://github.com/arthexis/arthexis"),
                ),
                ("homepage_url", models.URLField(default="https://arthexis.com")),
                (
                    "version_path",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "dependencies_path",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("test_command", models.TextField(blank=True, default="")),
                (
                    "generate_wheels",
                    models.BooleanField(
                        default=False,
                        help_text="Build wheel distributions when creating releases",
                    ),
                ),
                (
                    "oidc_publish_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Publish releases via GitHub Actions OIDC instead of direct PyPI credentials.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Designates the active package for version comparisons",
                    ),
                ),
            ],
            options={
                "verbose_name": "Package",
                "verbose_name_plural": "Packages",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="unique_active_package",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PackageRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("version", models.CharField(default="0.0.0", max_length=20)),
                (
                    "revision",
                    models.CharField(
                        blank=True,
                        default=utils.revision.get_revision,
                        editable=False,
                        max_length=40,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("low", "Low"),
                            ("critical", "Critical"),
                        ],
                        default="normal",
                        help_text="Controls the expected urgency for auto-upgrades.",
                        max_length=16,
                    ),
                ),
                (
                    "pypi_url",
                    models.URLField(
                        blank=True, editable=False, verbose_name="PyPI URL"
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True, editable=False, verbose_name="GitHub URL"
                    ),
                ),
                (
                    "pypi_publish_log",
                    models.TextField(
                        blank=True,
                        default="",
                        editable=False,
                        verbose_name="PyPI publish log",
                    ),
                ),
                (
                    "release_on",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                ("scheduled_time", models.TimeField(blank=True, null=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releases",
                        to="release.package",
                    ),
                ),
            ],
            options={
                "verbose_name": "Package Release",
                "verbose_name_plural": "Package Releases",
                "get_latest_by": "version",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("package", "version"), name="unique_package_version"
                    )
                ],
            },
        ),
    ]
