# Generated by Django 5.2.12 on 2026-04-12 04:40

from django.db import migrations, models
from django.db.models import Q
from django.db.models import functions


def _reset_overlength_test_commands(apps, schema_editor):
    package_model = apps.get_model("release", "Package")
    (
        package_model.objects.annotate(
            test_command_length=functions.Length("test_command")
        )
        .filter(Q(test_command_length__gt=255) | ~Q(test_command=""))
        .update(test_command="")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            _reset_overlength_test_commands, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="package",
            name="test_command",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Managed default (python manage.py test)"),
                    (
                        ".venv/bin/python manage.py test run --",
                        "Managed wrapper (.venv/bin/python manage.py test run --)",
                    ),
                ],
                default="",
                help_text="Use an approved managed release test wrapper only. For new workflows, add a managed `release` subcommand instead of shell commands.",
                max_length=255,
            ),
        ),
    ]
