# Generated by Django 5.2.15 on 2026-07-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="test_command",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Managed default (current Python -m pytest)"),
                    (
                        ".venv/bin/python -m pytest",
                        "Managed pytest wrapper (.venv/bin/python -m pytest)",
                    ),
                ],
                default="",
                help_text="Use an approved managed release test wrapper only. For new workflows, add a managed `release` subcommand instead of shell commands.",
                max_length=255,
            ),
        ),
    ]
