# Generated by Django 5.2.12 on 2026-03-22 00:41

from django.db import migrations, models

import apps.release.models.package


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0007_remove_release_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="license",
            field=models.CharField(
                default=apps.release.models.package.PackageLicenseDefault(),
                max_length=100,
            ),
        ),
    ]
