# Generated by Django 5.2.10 on 2026-02-01 19:16

import apps.release.models.github_token
import apps.sigils.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_site_operator_group"),
        ("release", "0007_remove_release_manager"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GithubToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "token",
                    apps.sigils.fields.SigilShortAutoField(
                        help_text="Personal access token used for GitHub release operations.",
                        max_length=255,
                        verbose_name="GitHub token",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=apps.release.models.github_token._default_expiration,
                        help_text="When this token expires.",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Security group that owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="groups.securitygroup",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional package scope. Leave blank to apply to any package.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_tokens",
                        to="release.package",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User that owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub Token",
                "verbose_name_plural": "GitHub Tokens",
                "ordering": ["-created_on"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("user__isnull", True), ("group__isnull", True)),
                            models.Q(("user__isnull", False), ("group__isnull", True)),
                            models.Q(("user__isnull", True), ("group__isnull", False)),
                            _connector="OR",
                        ),
                        name="release_githubtoken_owner_exclusive",
                    )
                ],
            },
        ),
    ]
