# Generated by Django 5.2.12 on 2026-03-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0007_remove_release_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="license",
            field=models.CharField(
                default="Arthexis Contribution Reciprocity License 1.0", max_length=100
            ),
        ),
    ]
