# Generated by Django 5.2.8 on 2025-11-30 13:28

import apps.sigils.fields
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import re
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("awg", "0002_initial"),
        ("core", "0003_initial"),
        ("crms", "0001_initial"),
        ("energy", "0002_initial"),
        ("nodes", "0001_initial"),
        ("otp_totp", "0003_add_timestamps"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InviteLead",
            fields=[],
            options={
                "verbose_name": "Invite Lead",
                "verbose_name_plural": "Invite Leads",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.invitelead",),
        ),
        migrations.CreateModel(
            name="OdooProfile",
            fields=[],
            options={
                "verbose_name": "CRM Employee",
                "verbose_name_plural": "CRM Employees",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("crms.odooprofile",),
        ),
        migrations.CreateModel(
            name="PowerLead",
            fields=[],
            options={
                "verbose_name": "Power Lead",
                "verbose_name_plural": "Power Leads",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("awg.powerlead",),
        ),
        migrations.CreateModel(
            name="ReleaseManager",
            fields=[],
            options={
                "verbose_name": "Release Manager",
                "verbose_name_plural": "Release Managers",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.releasemanager",),
        ),
        migrations.CreateModel(
            name="SecurityGroup",
            fields=[],
            options={
                "verbose_name": "Security Group",
                "verbose_name_plural": "Security Groups",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.securitygroup",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name="TOTPDevice",
            fields=[],
            options={
                "verbose_name": "TOTP Device",
                "verbose_name_plural": "TOTP Devices",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("otp_totp.totpdevice",),
        ),
        migrations.CreateModel(
            name="EmailInbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "username",
                    apps.sigils.fields.SigilShortAutoField(
                        help_text="Login name for the mailbox", max_length=255
                    ),
                ),
                (
                    "host",
                    apps.sigils.fields.SigilShortAutoField(
                        help_text="Examples: Gmail IMAP 'imap.gmail.com', Gmail POP3 'pop.gmail.com', GoDaddy IMAP 'imap.secureserver.net', GoDaddy POP3 'pop.secureserver.net'",
                        max_length=255,
                    ),
                ),
                (
                    "port",
                    models.PositiveIntegerField(
                        default=993,
                        help_text="Common ports: Gmail IMAP 993, Gmail POP3 995, GoDaddy IMAP 993, GoDaddy POP3 995",
                    ),
                ),
                ("password", apps.sigils.fields.SigilShortAutoField(max_length=255)),
                (
                    "protocol",
                    apps.sigils.fields.SigilShortAutoField(
                        choices=[("imap", "IMAP"), ("pop3", "POP3")],
                        default="imap",
                        help_text="IMAP keeps emails on the server for access across devices; POP3 downloads messages to a single device and may remove them from the server",
                        max_length=5,
                    ),
                ),
                ("use_ssl", models.BooleanField(default=True)),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Disable to remove this inbox from automatic selection.",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Higher values are selected first when multiple inboxes are available.",
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.securitygroup",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Inbox",
                "verbose_name_plural": "Email Inboxes",
                "db_table": "core_emailinbox",
                "ordering": ["-priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="EmailCollector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional label to identify this collector.",
                        max_length=255,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("sender", models.CharField(blank=True, max_length=255)),
                ("body", models.CharField(blank=True, max_length=255)),
                (
                    "fragment",
                    models.CharField(
                        blank=True,
                        help_text="Pattern with [sigils] to extract values from the body.",
                        max_length=255,
                    ),
                ),
                (
                    "use_regular_expressions",
                    models.BooleanField(
                        default=False,
                        help_text="Treat subject, sender and body filters as regular expressions (case-insensitive).",
                    ),
                ),
                (
                    "inbox",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collectors",
                        to="teams.emailinbox",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Collector",
                "verbose_name_plural": "Email Collectors",
                "db_table": "core_emailcollector",
            },
        ),
        migrations.CreateModel(
            name="EmailOutbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "host",
                    apps.sigils.fields.SigilShortAutoField(
                        help_text="Gmail: smtp.gmail.com. GoDaddy: smtpout.secureserver.net",
                        max_length=100,
                    ),
                ),
                (
                    "port",
                    models.PositiveIntegerField(
                        default=587,
                        help_text="Gmail: 587 (TLS). GoDaddy: 587 (TLS) or 465 (SSL)",
                    ),
                ),
                (
                    "username",
                    apps.sigils.fields.SigilShortAutoField(
                        blank=True,
                        help_text="Full email address for Gmail or GoDaddy",
                        max_length=100,
                    ),
                ),
                (
                    "password",
                    apps.sigils.fields.SigilShortAutoField(
                        blank=True,
                        help_text="Email account password or app password",
                        max_length=100,
                    ),
                ),
                (
                    "use_tls",
                    models.BooleanField(
                        default=True, help_text="Check for Gmail or GoDaddy on port 587"
                    ),
                ),
                (
                    "use_ssl",
                    models.BooleanField(
                        default=False,
                        help_text="Check for GoDaddy on port 465; Gmail does not use SSL",
                    ),
                ),
                (
                    "from_email",
                    apps.sigils.fields.SigilShortAutoField(
                        blank=True,
                        help_text="Default From address; usually the same as username",
                        max_length=254,
                        verbose_name="From Email",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Disable to remove this outbox from automatic selection.",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Higher values are selected first when multiple outboxes are available.",
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.securitygroup",
                    ),
                ),
                (
                    "node",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_outbox",
                        to="nodes.node",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Outbox",
                "verbose_name_plural": "Email Outboxes",
                "db_table": "nodes_emailoutbox",
                "ordering": ["-priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="TaskCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional details supporting Markdown formatting.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="workgroup/task_categories/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated fulfillment cost in local currency.",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Cost",
                    ),
                ),
                (
                    "default_duration",
                    models.DurationField(
                        blank=True,
                        help_text="Typical time expected to complete tasks in this category.",
                        null=True,
                        verbose_name="Default duration",
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("immediate", "Immediate"),
                            ("2_3_business_days", "2-3 business days"),
                            ("2_3_weeks", "2-3 weeks"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="none",
                        help_text="Typical lead time for scheduling this work.",
                        max_length=32,
                        verbose_name="Availability",
                    ),
                ),
                (
                    "assigned_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Security group typically assigned to this work.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_categories_as_assignee",
                        to="core.securitygroup",
                        verbose_name="Assigned to group",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="User responsible for overseeing this category.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_task_categories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Manager",
                    ),
                ),
                (
                    "odoo_products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Relevant Odoo products for this category.",
                        related_name="task_categories",
                        to="crms.product",
                        verbose_name="Odoo products",
                    ),
                ),
                (
                    "requestor_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Security group authorized to request this work.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_categories_as_requestor",
                        to="core.securitygroup",
                        verbose_name="Requestor group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Category",
                "verbose_name_plural": "Task Categories",
                "db_table": "core_taskcategory",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SlackBotProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "team_id",
                    models.CharField(
                        help_text="Slack workspace team identifier (starts with T).",
                        max_length=32,
                    ),
                ),
                (
                    "bot_user_id",
                    models.CharField(
                        blank=True,
                        help_text="Slack bot user identifier (starts with U or B).",
                        max_length=32,
                    ),
                ),
                (
                    "bot_token",
                    apps.sigils.fields.SigilShortAutoField(
                        help_text="Slack bot token used for authenticated API calls.",
                        max_length=255,
                    ),
                ),
                (
                    "signing_secret",
                    apps.sigils.fields.SigilShortAutoField(
                        help_text="Slack signing secret used to verify incoming requests.",
                        max_length=255,
                    ),
                ),
                (
                    "default_channels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Channel identifiers where Net Messages should be posted. Provide a JSON array of channel IDs (for example ["C01ABCDE"]).',
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Disable to stop the bot from posting to Slack.",
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.securitygroup",
                    ),
                ),
                (
                    "node",
                    models.OneToOneField(
                        blank=True,
                        help_text="Node that owns this Slack chatbot.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slack_bot",
                        to="nodes.node",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Slack Chatbot",
                "verbose_name_plural": "Slack Chatbots",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("team_id",), name="slackbotprofile_team_id_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("user__isnull", False), ("group__isnull", True)),
                            models.Q(("user__isnull", True), ("group__isnull", False)),
                            models.Q(
                                ("user__isnull", True),
                                ("group__isnull", True),
                                ("node__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="slackbotprofile_requires_owner",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SocialProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "network",
                    models.CharField(
                        choices=[("bluesky", "Bluesky"), ("discord", "Discord")],
                        default="bluesky",
                        help_text="Select the social network you want to connect. Bluesky and Discord are supported.",
                        max_length=32,
                    ),
                ),
                (
                    "handle",
                    models.CharField(
                        blank=True,
                        help_text="Bluesky handle that should resolve to Arthexis. Use the verified domain (for example arthexis.com).",
                        max_length=253,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid",
                                message="Enter a valid domain name such as example.com.",
                                regex=re.compile(
                                    "^(?=.{1,253}\\Z)(?!-)[A-Za-z0-9-]{1,63}(?<!-)(\\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))*$"
                                ),
                            )
                        ],
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        help_text="Domain that hosts the Bluesky verification. Publish a _atproto TXT record or a /.well-known/atproto-did file with the DID below.",
                        max_length=253,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid",
                                message="Enter a valid domain name such as example.com.",
                                regex=re.compile(
                                    "^(?=.{1,253}\\Z)(?!-)[A-Za-z0-9-]{1,63}(?<!-)(\\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))*$"
                                ),
                            )
                        ],
                    ),
                ),
                (
                    "did",
                    models.CharField(
                        blank=True,
                        help_text="Optional DID that Bluesky assigns once the domain is linked (for example did:plc:1234abcd).",
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid",
                                message="Enter a valid DID such as did:plc:1234abcd.",
                                regex="^(|did:[a-z0-9]+:[A-Za-z0-9.\\-_:]+)$",
                            )
                        ],
                    ),
                ),
                (
                    "application_id",
                    models.CharField(
                        blank=True,
                        help_text="Discord application ID used to control the bot.",
                        max_length=32,
                    ),
                ),
                (
                    "public_key",
                    models.CharField(
                        blank=True,
                        help_text="Discord public key used to verify interaction requests.",
                        max_length=128,
                    ),
                ),
                (
                    "guild_id",
                    models.CharField(
                        blank=True,
                        help_text="Discord guild (server) identifier where the bot should operate.",
                        max_length=32,
                    ),
                ),
                (
                    "bot_token",
                    apps.sigils.fields.SigilShortAutoField(
                        blank=True,
                        help_text="Discord bot token required for authenticated actions.",
                        max_length=255,
                    ),
                ),
                (
                    "default_channel_id",
                    models.CharField(
                        blank=True,
                        help_text="Optional Discord channel identifier used for default messaging.",
                        max_length=32,
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.securitygroup",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Identity",
                "verbose_name_plural": "Social Identities",
                "db_table": "core_socialprofile",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("handle", ""), _negated=True),
                        fields=("network", "handle"),
                        name="socialprofile_network_handle",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("domain", ""), _negated=True),
                        fields=("network", "domain"),
                        name="socialprofile_network_domain",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("user__isnull", False), ("group__isnull", True)),
                            models.Q(("user__isnull", True), ("group__isnull", False)),
                            _connector="OR",
                        ),
                        name="socialprofile_requires_owner",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ManualTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed summary of the work to perform.",
                        verbose_name="Requestor Comments",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True,
                        help_text="Estimated time to complete the task.",
                        null=True,
                        verbose_name="Expected duration",
                    ),
                ),
                (
                    "scheduled_start",
                    models.DateTimeField(
                        help_text="Planned start time for this work.",
                        verbose_name="Scheduled start",
                    ),
                ),
                (
                    "scheduled_end",
                    models.DateTimeField(
                        help_text="Planned completion time for this work.",
                        verbose_name="Scheduled end",
                    ),
                ),
                (
                    "enable_notifications",
                    models.BooleanField(
                        default=False,
                        help_text="Send reminder emails to the assigned contacts when Celery notifications are available.",
                        verbose_name="Enable notifications",
                    ),
                ),
                (
                    "assigned_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Security group containing users who can fulfill the task.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_manual_tasks",
                        to="core.securitygroup",
                        verbose_name="Potential assignees",
                    ),
                ),
                (
                    "assigned_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional user responsible for the task.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_manual_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned user",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Location associated with this manual task.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manual_tasks",
                        to="energy.location",
                        verbose_name="Location",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="User overseeing the task.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_manual_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Manager",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        help_text="Node where this manual task should be completed.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manual_tasks",
                        to="nodes.node",
                        verbose_name="Node",
                    ),
                ),
                (
                    "odoo_products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Products associated with the requested work.",
                        related_name="manual_tasks",
                        to="crms.product",
                        verbose_name="Odoo products",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select the standardized category for this work.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manual_tasks",
                        to="teams.taskcategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manual Task",
                "verbose_name_plural": "Manual Tasks",
                "db_table": "core_manualtask",
                "ordering": ("scheduled_start", "category__name"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("node__isnull", False),
                            ("location__isnull", False),
                            _connector="OR",
                        ),
                        name="manualtask_requires_target",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("scheduled_end__gte", models.F("scheduled_start"))
                        ),
                        name="manualtask_schedule_order",
                    ),
                ],
            },
        ),
    ]
