# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="slackbotprofile",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User that owns this object.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="slackbotprofile",
            constraint=models.UniqueConstraint(
                fields=("team_id",), name="slackbotprofile_team_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="slackbotprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("user__isnull", False), ("group__isnull", True)),
                    models.Q(("user__isnull", True), ("group__isnull", False)),
                    models.Q(
                        ("user__isnull", True),
                        ("group__isnull", True),
                        ("node__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="slackbotprofile_requires_owner",
            ),
        ),
    ]
