# Generated by Django 5.2.8 on 2025-12-02 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_remove_odooemployee"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="ManualTask",
                ),
                migrations.DeleteModel(
                    name="TaskCategory",
                ),
            ],
            database_operations=[],
        )
    ]
