# Generated by Django 5.2.8 on 2025-12-04 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_remove_releasemanager_proxy"),
        ("teams", "0003_slackbotprofile_avatar_socialprofile_avatar"),
    ]

    operations = []
