# Generated by Django 5.2.8 on 2025-12-03 00:00

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
        ("teams", "0003_remove_taskcategory_assigned_group_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name="SecurityGroup"),
                migrations.CreateModel(
                    name="SecurityGroup",
                    fields=[],
                    options={
                        "verbose_name": "Security Group",
                        "verbose_name_plural": "Security Groups",
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("groups.securitygroup",),
                    managers=[
                        ("objects", django.contrib.auth.models.GroupManager()),
                    ],
                ),
                migrations.AlterField(
                    model_name="slackbotprofile",
                    name="group",
                    field=models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="groups.securitygroup",
                    ),
                ),
                migrations.AlterField(
                    model_name="socialprofile",
                    name="group",
                    field=models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="groups.securitygroup",
                    ),
                ),
            ],
        ),
    ]
