# Generated by Django 5.2.8 on 2025-12-01 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_merge_20251130_2201"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="odooemployee",
            options={
                "verbose_name": "Odoo Employee",
                "verbose_name_plural": "Odoo Employees",
            },
        ),
    ]
