# Generated by Django 5.2.8 on 2025-12-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_delete_totpdevice"),
        ("socials", "0002_migrate_social_profiles"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SocialProfile",
        ),
    ]
