# Generated by Django 5.2.11 on 2026-02-25 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0003_site_operator_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlexaAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=150)),
                ("client_id", models.CharField(max_length=255)),
                ("client_secret", models.CharField(max_length=255)),
                ("refresh_token", models.CharField(max_length=255)),
                (
                    "api_base_url",
                    models.URLField(
                        default="https://api.amazonalexa.com",
                        help_text="Base Alexa API URL used for reminder operations.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_credentials_check_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_credentials_check_message",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Security group that owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="groups.securitygroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User that owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alexa account",
                "verbose_name_plural": "Alexa accounts",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="AlexaReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=150)),
                (
                    "event_key",
                    models.CharField(
                        help_text="Stable event key used when external events update this reminder.",
                        max_length=120,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Reminder text sent to Alexa accounts."),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional explicit reminder datetime.",
                        null=True,
                    ),
                ),
                (
                    "auto_update_on_event",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically mark deliveries for update when reminder events change.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Security group that owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="groups.securitygroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User that owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alexa reminder",
                "verbose_name_plural": "Alexa reminders",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="AlexaReminderDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending send"),
                            ("sent", "Sent"),
                            ("update_pending", "Pending update"),
                            ("updated", "Updated"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("remote_reference", models.CharField(blank=True, max_length=255)),
                ("event_payload", models.JSONField(blank=True, default=dict)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="alexa.alexaaccount",
                    ),
                ),
                (
                    "reminder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="alexa.alexareminder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alexa reminder delivery",
                "verbose_name_plural": "Alexa reminder deliveries",
                "ordering": ("reminder__name", "account__name"),
            },
        ),
        migrations.AddField(
            model_name="alexareminder",
            name="target_accounts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Alexa accounts that should receive this reminder.",
                related_name="targeted_reminders",
                through="alexa.AlexaReminderDelivery",
                to="alexa.alexaaccount",
            ),
        ),
        migrations.AddConstraint(
            model_name="alexaaccount",
            constraint=models.UniqueConstraint(
                fields=("name", "user", "group"), name="alexa_account_unique_owner_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="alexareminderdelivery",
            constraint=models.UniqueConstraint(
                fields=("reminder", "account"),
                name="alexa_reminder_delivery_unique_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="alexareminder",
            constraint=models.UniqueConstraint(
                fields=("event_key", "user", "group"),
                name="alexa_reminder_unique_owner_event",
            ),
        ),
    ]
