# Generated by Django 5.2.8 on 2025-05-28 00:00
import django.db.models.deletion
from django.db import migrations, models


def update_contenttypes(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    updates = [
        ("core", "sigilroot", "sigils"),
        ("pages", "customsigil", "sigils"),
    ]
    for app_label, model, new_app_label in updates:
        try:
            content_type = ContentType.objects.get(
                app_label=app_label, model=model
            )
        except ContentType.DoesNotExist:
            continue
        content_type.app_label = new_app_label
        content_type.save(update_fields=["app_label"])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0103_delete_todo"),
        ("pages", "0002_alter_module_application_delete_application"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="SigilRoot",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("is_seed_data", models.BooleanField(default=False, editable=False)),
                        ("is_user_data", models.BooleanField(default=False, editable=False)),
                        ("is_deleted", models.BooleanField(default=False, editable=False)),
                        ("prefix", models.CharField(max_length=50, unique=True)),
                        (
                            "context_type",
                            models.CharField(
                                choices=[
                                    ("config", "Configuration"),
                                    ("entity", "Entity"),
                                ],
                                max_length=20,
                            ),
                        ),
                        (
                            "content_type",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                to="contenttypes.contenttype",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "core_sigilroot",
                        "verbose_name": "Sigil Root",
                        "verbose_name_plural": "Sigil Roots",
                    },
                ),
                migrations.CreateModel(
                    name="CustomSigil",
                    fields=[],
                    options={
                        "verbose_name": "Custom Sigil",
                        "verbose_name_plural": "Custom Sigils",
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("sigils.sigilroot",),
                ),
            ],
            database_operations=[
                migrations.RunPython(update_contenttypes, migrations.RunPython.noop)
            ],
        )
    ]
