# Generated by Django 5.2.12 on 2026-04-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sigils", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sigilroot",
            name="is_user_safe",
            field=models.BooleanField(
                default=False,
                help_text="Allow this sigil root in user-facing rendering contexts.",
            ),
        ),
    ]
