# Generated by Django 5.2.12 on 2026-09-17 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("sigils", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SigilRoot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix", models.CharField(max_length=80, unique=True)),
                ("context_type", models.CharField(max_length=120)),
                ("user_safe", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sigil_roots",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ("prefix",),
            },
        ),
    ]
