# Generated by Django 5.2.12 on 2026-04-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sigils", "0002_sigilroot_is_user_safe"),
    ]

    operations = [
        migrations.CreateModel(
            name="SigilRenderPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_key",
                    models.CharField(
                        default="default", editable=False, max_length=20, unique=True
                    ),
                ),
                (
                    "unresolved_behavior",
                    models.CharField(
                        choices=[
                            ("empty", "Empty output"),
                            ("placeholder", "Keep placeholder"),
                        ],
                        default="placeholder",
                        help_text="Controls how unresolved/disallowed user-safe sigils render in templates.",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sigil Render Policy",
                "verbose_name_plural": "Sigil Render Policy",
                "db_table": "core_sigilrenderpolicy",
            },
        ),
    ]
