# Generated by Django 5.2.15 on 2026-07-02 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SerialInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('device_path', models.CharField(max_length=255, unique=True)),
                ('interface_type', models.CharField(choices=[('uart', 'UART'), ('rs485', 'RS485')], default='uart', max_length=20)),
                ('role', models.CharField(choices=[('target', 'Target Node'), ('operator', 'Operator Node')], default='target', max_length=20)),
                ('baud_rate', models.PositiveIntegerField(default=115200)),
                ('parity', models.CharField(default='N', max_length=1)),
                ('stop_bits', models.DecimalField(decimal_places=1, default=1, max_digits=2)),
                ('is_enabled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SerialPeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=120)),
                ('protocol_version', models.CharField(default='phase1', max_length=32)),
                ('shared_key_fingerprint', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peers', to='serialbridge.serialinterface')),
            ],
            options={
                'ordering': ('node_id',),
            },
        ),
        migrations.CreateModel(
            name='SerialCommandAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(choices=[('ping', 'Health Ping'), ('diagnostics', 'Diagnostics Manifest'), ('log_tail', 'Tail Logs'), ('restart', 'Restart Service'), ('restore_network', 'Restore Network'), ('safe_mode', 'Safe Mode')], max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], max_length=20)),
                ('result_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_audits', to='serialbridge.serialinterface')),
                ('peer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_audits', to='serialbridge.serialpeer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SerialSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected')], default='disconnected', max_length=20)),
                ('rx_messages', models.PositiveIntegerField(default=0)),
                ('tx_messages', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='serialbridge.serialinterface')),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='serialbridge.serialpeer')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='serialpeer',
            constraint=models.UniqueConstraint(fields=('interface', 'node_id'), name='serialbridge_peer_unique_interface_node'),
        ),
        migrations.AddConstraint(
            model_name='serialsession',
            constraint=models.UniqueConstraint(fields=('interface', 'peer'), name='serialbridge_session_unique_interface_peer'),
        ),
    ]
