# Generated by Django 5.2.11 on 2026-02-13 02:10

import apps.google.sheets.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("google", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driveaccount",
            name="access_token",
            field=apps.google.sheets.fields.EncryptedTextField(
                blank=True, help_text="OAuth access token."
            ),
        ),
        migrations.AlterField(
            model_name="driveaccount",
            name="refresh_token",
            field=apps.google.sheets.fields.EncryptedTextField(
                blank=True, help_text="OAuth refresh token."
            ),
        ),
    ]
