# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SQLReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("report_product_activity", "Report product activity"),
                            ("scheduled_reports", "Scheduled reports overview"),
                            ("sigil_roots", "Sigil roots catalog"),
                            ("legacy_archived", "Archived legacy SQL report"),
                        ],
                        max_length=64,
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                (
                    "database_alias",
                    models.CharField(default="default", editable=False, max_length=128),
                ),
                ("query", models.TextField(blank=True, default="", editable=False)),
                (
                    "html_template_name",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=255
                    ),
                ),
                (
                    "legacy_definition",
                    models.JSONField(blank=True, editable=False, null=True),
                ),
                ("schedule_enabled", models.BooleanField(default=False)),
                ("schedule_interval_minutes", models.PositiveIntegerField(default=0)),
                ("next_scheduled_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_duration", models.DurationField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "db_table": "core_sqlreport",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SQLReportProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("report_type", models.CharField(max_length=64)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("renderer_template_name", models.CharField(max_length=255)),
                ("execution_details", models.JSONField(blank=True, default=dict)),
                (
                    "database_alias",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=128
                    ),
                ),
                (
                    "resolved_sql",
                    models.TextField(blank=True, default="", editable=False),
                ),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("duration_ms", models.FloatField(blank=True, null=True)),
                ("html_content", models.TextField()),
                ("pdf_content", models.BinaryField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="reports.sqlreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Product",
                "verbose_name_plural": "Report Products",
                "ordering": ("-created_at",),
            },
        ),
    ]
