# Generated by Django 5.2.12 on 2026-04-13 00:00

import json

import django.db.models.deletion
from django.db import migrations, models

REPORT_TASK_PATH = "apps.reports.tasks.run_scheduled_sql_reports"


def _migrate_legacy_schedules_to_beat(apps, schema_editor):
    SQLReport = apps.get_model("reports", "SQLReport")
    IntervalSchedule = apps.get_model("django_celery_beat", "IntervalSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    for report in SQLReport.objects.filter(schedule_enabled=True, schedule_interval_minutes__gt=0):
        interval, _ = IntervalSchedule.objects.get_or_create(
            every=report.schedule_interval_minutes,
            period="minutes",
        )
        task, _ = PeriodicTask.objects.update_or_create(
            name=f"scheduled-sql-report-{report.pk}",
            defaults={
                "enabled": True,
                "interval": interval,
                "kwargs": json.dumps({"report_id": report.pk}, sort_keys=True),
                "start_time": report.next_scheduled_run_at,
                "task": REPORT_TASK_PATH,
            },
        )
        SQLReport.objects.filter(pk=report.pk).update(
            schedule_interval=interval,
            schedule_periodic_task=task,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_beat", "0020_googlecalendarprofile"),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sqlreport",
            name="schedule_crontab",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduled_sql_reports",
                to="django_celery_beat.crontabschedule",
            ),
        ),
        migrations.AddField(
            model_name="sqlreport",
            name="schedule_interval",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduled_sql_reports",
                to="django_celery_beat.intervalschedule",
            ),
        ),
        migrations.AddField(
            model_name="sqlreport",
            name="schedule_periodic_task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduled_sql_report",
                to="django_celery_beat.periodictask",
            ),
        ),
        migrations.RunPython(
            _migrate_legacy_schedules_to_beat, migrations.RunPython.noop
        ),
    ]
