# Generated by Django 5.2.11 on 2026-03-08 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sqlreport",
            name="html_template_name",
            field=models.CharField(
                default="reports/sql/default_report.html",
                help_text="Template used for HTML product rendering.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sqlreport",
            name="next_scheduled_run_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sqlreport",
            name="pdf_template_name",
            field=models.CharField(
                default="reports/sql/default_report_pdf.html",
                help_text="Template used for PDF product rendering.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sqlreport",
            name="schedule_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sqlreport",
            name="schedule_interval_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="SQLReportProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("database_alias", models.CharField(max_length=128)),
                ("resolved_sql", models.TextField()),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("duration_ms", models.FloatField(blank=True, null=True)),
                ("html_content", models.TextField()),
                ("pdf_content", models.BinaryField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="reports.sqlreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "SQL Report Product",
                "verbose_name_plural": "SQL Report Products",
                "ordering": ("-created_at",),
            },
        ),
    ]
