# Generated by Django 5.2.11 on 2026-03-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_sqlreport_html_template_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sqlreport",
            name="pdf_template_name",
        ),
        migrations.AlterField(
            model_name="sqlreport",
            name="html_template_name",
            field=models.CharField(
                default="reports/sql/default_report.html",
                help_text="Template used for HTML and PDF product rendering.",
                max_length=255,
            ),
        ),
    ]
