# Generated by Django 5.2.8 on 2025-11-30 13:28

import apps.sigils.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OdooProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "renewal_period",
                    models.PositiveIntegerField(help_text="Renewal period in days"),
                ),
                (
                    "odoo_product",
                    models.JSONField(
                        blank=True,
                        help_text="Selected product from Odoo (id and name)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Odoo Product",
                "verbose_name_plural": "Odoo Products",
                "db_table": "core_odoo_product",
            },
        ),
        migrations.CreateModel(
            name="OdooProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("host", apps.sigils.fields.SigilShortAutoField(max_length=255)),
                ("database", apps.sigils.fields.SigilShortAutoField(max_length=255)),
                ("username", apps.sigils.fields.SigilShortAutoField(max_length=255)),
                ("password", apps.sigils.fields.SigilShortAutoField(max_length=255)),
                ("verified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "odoo_uid",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                ("name", models.CharField(blank=True, editable=False, max_length=255)),
                (
                    "email",
                    models.EmailField(blank=True, editable=False, max_length=254),
                ),
                (
                    "partner_id",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "group",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.securitygroup",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Odoo Profile",
                "verbose_name_plural": "Odoo Profiles",
                "db_table": "core_odooprofile",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("user__isnull", False), ("group__isnull", True)),
                            models.Q(("user__isnull", True), ("group__isnull", False)),
                            _connector="OR",
                        ),
                        name="odooprofile_requires_owner",
                    )
                ],
            },
        ),
    ]
