# Generated by Django 5.2.12 on 2026-03-27 20:33

import apps.sigils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chats", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OdooDeployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "config_path",
                    models.CharField(
                        help_text="Absolute path to the odoo configuration file.",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "base_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Directory that contains the odoo configuration file.",
                        max_length=500,
                    ),
                ),
                ("addons_path", models.TextField(blank=True)),
                ("data_dir", models.CharField(blank=True, max_length=500)),
                ("db_host", models.CharField(blank=True, max_length=255)),
                ("db_port", models.PositiveIntegerField(blank=True, null=True)),
                ("db_user", models.CharField(blank=True, max_length=255)),
                ("db_password", models.CharField(blank=True, max_length=255)),
                ("db_name", models.CharField(blank=True, max_length=255)),
                ("db_filter", models.CharField(blank=True, max_length=255)),
                (
                    "admin_password",
                    models.CharField(
                        blank=True,
                        help_text="Database operations master password.",
                        max_length=255,
                    ),
                ),
                ("http_port", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "longpolling_port",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("logfile", models.CharField(blank=True, max_length=500)),
                ("last_discovered", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Odoo Deployment",
                "verbose_name_plural": "Odoo Deployments",
                "db_table": "core_odoodeployment",
                "ordering": ("name", "config_path"),
            },
        ),
        migrations.CreateModel(
            name="OdooEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("host", apps.sigils.fields.SigilShortAutoField(max_length=255)),
                ("database", apps.sigils.fields.SigilShortAutoField(max_length=255)),
                ("username", apps.sigils.fields.SigilShortAutoField(max_length=255)),
                ("password", apps.sigils.fields.SigilShortAutoField(max_length=255)),
                ("verified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "odoo_uid",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                ("name", models.CharField(blank=True, editable=False, max_length=255)),
                (
                    "email",
                    models.EmailField(blank=True, editable=False, max_length=254),
                ),
                (
                    "partner_id",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "verbose_name": "Odoo Employee",
                "verbose_name_plural": "Odoo Employees",
                "db_table": "core_odooemployee",
            },
        ),
        migrations.CreateModel(
            name="OdooProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "renewal_period",
                    models.PositiveIntegerField(help_text="Renewal period in days"),
                ),
                (
                    "odoo_product",
                    models.JSONField(
                        blank=True,
                        help_text="Selected product from Odoo (id and name)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Odoo Product",
                "verbose_name_plural": "Odoo Products",
                "db_table": "core_odoo_product",
            },
        ),
        migrations.CreateModel(
            name="OdooQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "model_name",
                    models.CharField(
                        help_text="Target Odoo model name, e.g. sale.order.",
                        max_length=255,
                        verbose_name="Odoo Model",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        default="search_read",
                        help_text="Odoo RPC method to execute.",
                        max_length=100,
                    ),
                ),
                (
                    "kwquery",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Keyword arguments for the Odoo RPC call.",
                    ),
                ),
                ("enable_public_view", models.BooleanField(default=False)),
                (
                    "public_view_slug",
                    models.SlugField(blank=True, null=True, unique=True),
                ),
                ("public_title", models.CharField(blank=True, max_length=255)),
                ("public_description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Odoo Query",
                "verbose_name_plural": "Odoo Queries",
                "db_table": "core_odooquery",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="OdooQueryVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "key",
                    models.SlugField(help_text="Identifier used in [VAR.key] sigils."),
                ),
                ("label", models.CharField(max_length=100)),
                ("help_text", models.CharField(blank=True, max_length=255)),
                ("default_value", models.TextField(blank=True)),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("datetime", "Date & time"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Odoo Query Variable",
                "verbose_name_plural": "Odoo Query Variables",
                "db_table": "core_odooqueryvariable",
                "ordering": ("sort_order", "label"),
            },
        ),
        migrations.CreateModel(
            name="OdooChatBridge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Disable to stop forwarding chat messages to this bridge.",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Use as the fallback bridge when no site-specific configuration is defined.",
                    ),
                ),
                (
                    "channel_id",
                    models.PositiveIntegerField(
                        help_text="Identifier of the Odoo mail.channel that should receive forwarded messages.",
                        verbose_name="Channel ID",
                    ),
                ),
                (
                    "channel_uuid",
                    models.CharField(
                        blank=True,
                        help_text="Optional UUID of the Odoo mail.channel for reference.",
                        max_length=64,
                        verbose_name="Channel UUID",
                    ),
                ),
                (
                    "notify_partner_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Additional Odoo partner IDs to notify when posting messages. Provide a JSON array of integers.",
                    ),
                ),
                (
                    "avatars",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Avatars allowed to use this bridge.",
                        related_name="%(app_label)s_%(class)s_bridges",
                        to="chats.chatavatar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Odoo Chat Bridge",
                "verbose_name_plural": "Odoo Chat Bridges",
                "db_table": "pages_odoochatbridge",
                "ordering": ["site__domain", "pk"],
            },
        ),
    ]
