# Generated by Django 5.2.8 on 2025-12-01 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from apps.migration_utils import import_callable


SigilShortAutoField = import_callable(
    "apps.sigils.fields.SigilShortAutoField", default=models.CharField
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_initial"),
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OdooProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "renewal_period",
                    models.PositiveIntegerField(help_text="Renewal period in days"),
                ),
                (
                    "odoo_product",
                    models.JSONField(
                        blank=True,
                        help_text="Selected product from Odoo (id and name)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Odoo Product",
                "verbose_name_plural": "Odoo Products",
                "db_table": "core_odoo_product",
            },
        ),
        migrations.CreateModel(
            name="OdooEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("host", SigilShortAutoField(max_length=255)),
                ("database", SigilShortAutoField(max_length=255)),
                ("username", SigilShortAutoField(max_length=255)),
                ("password", SigilShortAutoField(max_length=255)),
                ("verified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "odoo_uid",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                ("name", models.CharField(blank=True, editable=False, max_length=255)),
                (
                    "email",
                    models.EmailField(blank=True, editable=False, max_length=254),
                ),
                (
                    "partner_id",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "group",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.securitygroup",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Odoo Employee",
                "verbose_name_plural": "Odoo Employees",
                "db_table": "core_odooemployee",
            },
        ),
        migrations.CreateModel(
            name="OdooChatBridge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Disable to stop forwarding chat messages to this bridge.",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Use as the fallback bridge when no site-specific configuration is defined.",
                    ),
                ),
                (
                    "channel_id",
                    models.PositiveIntegerField(
                        help_text="Identifier of the Odoo mail.channel that should receive forwarded messages.",
                        verbose_name="Channel ID",
                    ),
                ),
                (
                    "channel_uuid",
                    models.CharField(
                        blank=True,
                        help_text="Optional UUID of the Odoo mail.channel for reference.",
                        max_length=64,
                        verbose_name="Channel UUID",
                    ),
                ),
                (
                    "notify_partner_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Additional Odoo partner IDs to notify when posting messages. Provide a JSON array of integers.",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Restrict this bridge to a specific site. Leave blank to use it as a fallback.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odoo_chat_bridges",
                        to="sites.site",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        help_text="Verified Odoo employee credentials used to post chat messages.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_bridges",
                        to="odoo.odooemployee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Odoo Chat Bridge",
                "verbose_name_plural": "Odoo Chat Bridges",
                "db_table": "pages_odoochatbridge",
                "ordering": ["site__domain", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="odooemployee",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("user__isnull", False), ("group__isnull", True)),
                    models.Q(("user__isnull", True), ("group__isnull", False)),
                    _connector="OR",
                ),
                name="odooemployee_requires_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="odoochatbridge",
            constraint=models.UniqueConstraint(
                condition=models.Q(("site__isnull", False)),
                fields=("site",),
                name="unique_odoo_chat_bridge_site",
            ),
        ),
        migrations.AddConstraint(
            model_name="odoochatbridge",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="single_default_odoo_chat_bridge",
            ),
        ),
    ]
