# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chats", "0002_initial"),
        ("groups", "0002_initial"),
        ("odoo", "0001_initial"),
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="odoochatbridge",
            name="site",
            field=models.ForeignKey(
                blank=True,
                help_text="Restrict this bridge to a specific site. Leave blank to use it as a fallback.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="odoo_chat_bridges",
                to="sites.site",
            ),
        ),
        migrations.AddField(
            model_name="odooemployee",
            name="avatar",
            field=models.ForeignKey(
                blank=True,
                help_text="Chat avatar that owns these Odoo credentials.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="odoo_profiles",
                to="chats.chatavatar",
            ),
        ),
        migrations.AddField(
            model_name="odooemployee",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Security group that owns this object.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="groups.securitygroup",
            ),
        ),
    ]
