# Generated by Django 5.2.8 on 2025-12-03 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0002_initial"),
        ("odoo", "0001_initial"),
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="odoochatbridge",
            name="site",
            field=models.ForeignKey(
                blank=True,
                help_text="Restrict this bridge to a specific site. Leave blank to use it as a fallback.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="odoo_chat_bridges",
                to="sites.site",
            ),
        ),
        migrations.AddField(
            model_name="odooemployee",
            name="group",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="groups.securitygroup",
            ),
        ),
    ]
