# Generated by Django 5.2.15 on 2026-07-02 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('odoo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='odooemployee',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User that owns this object.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='odooquery',
            name='profile',
            field=models.ForeignKey(blank=True, help_text='Odoo employee profile used to execute this query.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='odoo.odooemployee'),
        ),
        migrations.AddField(
            model_name='odooqueryvariable',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='odoo.odooquery'),
        ),
        migrations.AddField(
            model_name='odoosalefactorproductrule',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rules', to='odoo.odoosalefactor'),
        ),
        migrations.AddField(
            model_name='odoosaleordertemplate',
            name='salesperson',
            field=models.ForeignKey(blank=True, help_text='Optional preset salesperson (Odoo employee) for generated orders.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_order_templates', to='odoo.odooemployee'),
        ),
        migrations.AddField(
            model_name='odoosalefactor',
            name='templates',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to apply to all templates. Select templates to restrict factor usage.', related_name='restricted_factors', to='odoo.odoosaleordertemplate'),
        ),
        migrations.AddConstraint(
            model_name='odooqueryvariable',
            constraint=models.UniqueConstraint(fields=('query', 'key'), name='odooqueryvariable_unique'),
        ),
    ]
