# Generated by Django 5.2.8 on 2025-12-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
        ("odoo", "0002_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="odooemployee",
                    name="group",
                    field=models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=models.CASCADE,
                        related_name="+",
                        to="groups.securitygroup",
                    ),
                ),
            ],
        )
    ]
