# Generated by Django 5.2.12 on 2026-04-23 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("odoo", "0004_odoosalefactor_odoosalefactorproductrule_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OdooChatBridge",
        ),
    ]
