# Generated by Django 5.2.11 on 2026-02-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="body_type",
            field=models.CharField(
                choices=[("python", "Python"), ("bash", "Bash")],
                default="python",
                help_text="Runtime used to execute this recipe body.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="script",
            field=models.TextField(
                help_text="Script contents. [SIGILS] and [ARG.*] tokens are resolved before execution."
            ),
        ),
    ]
