# Generated by Django 5.2.11 on 2026-03-01 04:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipe_body_type_alter_recipe_script"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("format_detected", models.CharField(max_length=32)),
                ("input_args", models.JSONField(default=list)),
                ("input_kwargs", models.JSONField(default=dict)),
                ("result", models.TextField(blank=True)),
                ("result_variable", models.CharField(max_length=64)),
                ("resolved_script", models.TextField()),
                (
                    "executed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe Product",
                "verbose_name_plural": "Recipe Products",
                "ordering": ("-executed_at",),
            },
        ),
    ]
