# Generated by Django 5.2.12 on 2026-04-08 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="surveyresponse",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="participant_token",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="survey_responses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyresponse",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("survey", "user"),
                name="survey_unique_authenticated_response",
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyresponse",
            constraint=models.UniqueConstraint(
                condition=models.Q(("participant_token__gt", "")),
                fields=("survey", "participant_token"),
                name="survey_unique_participant_response",
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyresponse",
            constraint=models.CheckConstraint(
                condition=(
                    (models.Q(("user__isnull", False)) & models.Q(("participant_token", "")))
                    | (
                        models.Q(("user__isnull", True))
                        & models.Q(("participant_token__gt", ""))
                    )
                ),
                name="survey_response_exactly_one_respondent",
            ),
        ),
    ]
