# Generated by Django 5.2.4 on 2025-08-15 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrate", "0002_odoo_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Instance",
            new_name="OdooInstance",
        ),
    ]
