# Generated by Django 5.2.4 on 2025-08-21 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrate", "0007_bskyaccount_is_deleted_bskyaccount_is_seed_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="request_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="integrate.requesttype",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                editable=False,
                max_length=8,
            ),
        ),
    ]
