# Generated by Django 5.2.9 on 2026-01-11 00:42

import apps.recipes.models
from django.db import migrations, models
import django.db.models.deletion


def create_steps_from_scripts(apps, schema_editor):
    Recipe = apps.get_model("recipes", "Recipe")
    RecipeStep = apps.get_model("recipes", "RecipeStep")
    for recipe in Recipe.objects.all():
        if recipe.script:
            RecipeStep.objects.create(
                recipe=recipe,
                order=1,
                command=recipe.script,
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "command",
                    models.TextField(
                        help_text="Commands to execute (1-3 lines).",
                        validators=[apps.recipes.models.validate_command_line_count],
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe step",
                "verbose_name_plural": "Recipe steps",
                "ordering": ("recipe", "order"),
                "unique_together": {("recipe", "order")},
            },
        ),
        migrations.RunPython(create_steps_from_scripts, noop_reverse),
        migrations.RemoveField(
            model_name="recipe",
            name="script",
        ),
    ]
