from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from django.conf import settings
from django.db.models import Q

from apps.features.models import Feature
from apps.nodes.feature_detection import is_feature_active_for_node
from apps.nodes.models import Node, NodeFeature
from apps.skills.models import Agent

LOCAL_AGENTS_RELATIVE_PATH = Path("work") / "codex" / "AGENTS.md"


@dataclass(frozen=True)
class AgentContextRender:
    path: Path
    text: str
    written: bool = False


def default_agents_path() -> Path:
    return Path(settings.BASE_DIR) / LOCAL_AGENTS_RELATIVE_PATH


def _local_node(node: Node | None = None) -> Node | None:
    return node if node is not None else Node.get_local()


def _enabled_suite_features(node: Node | None) -> set[int]:
    enabled = set()
    for feature in Feature.objects.filter(is_enabled=True).select_related(
        "node_feature"
    ):
        if feature.is_enabled_for_node(node):
            enabled.add(feature.pk)
    return enabled


def _enabled_node_features(node: Node | None) -> set[int]:
    if node is None:
        return set()
    active_ids = set(node.features.values_list("pk", flat=True))
    for feature in NodeFeature.objects.all():
        if feature.pk in active_ids:
            continue
        if is_feature_active_for_node(node=node, slug=feature.slug):
            active_ids.add(feature.pk)
    return active_ids


def _agent_queryset_for_node(node: Node | None):
    role_id = getattr(node, "role_id", None)
    node_feature_ids = _enabled_node_features(node)
    suite_feature_ids = _enabled_suite_features(node)
    query = Q(is_default=True)
    if role_id:
        query |= Q(node_roles__pk=role_id)
    if node_feature_ids:
        query |= Q(node_features__pk__in=node_feature_ids)
    if suite_feature_ids:
        query |= Q(suite_features__pk__in=suite_feature_ids)
    return Agent.objects.filter(query).distinct()


def _agent_tier(
    agent: Agent,
    node: Node | None,
    *,
    node_feature_ids: set[int] | None = None,
    suite_feature_ids: set[int] | None = None,
) -> tuple[int, str]:
    role_id = getattr(node, "role_id", None)
    node_feature_ids = node_feature_ids if node_feature_ids is not None else (
        _enabled_node_features(node)
    )
    suite_feature_ids = suite_feature_ids if suite_feature_ids is not None else (
        _enabled_suite_features(node)
    )
    if role_id and any(role.pk == role_id for role in agent.node_roles.all()):
        return 0, "Node Role"
    if node_feature_ids and any(
        feature.pk in node_feature_ids for feature in agent.node_features.all()
    ):
        return 1, "Node Feature"
    if suite_feature_ids and any(
        feature.pk in suite_feature_ids for feature in agent.suite_features.all()
    ):
        return 2, "Suite Feature"
    return 3, "General"


def _render_agent_block(agent: Agent) -> str:
    parts = [f"### {agent.title}"]
    if agent.description:
        parts.append(agent.description.strip())
    if agent.instructions:
        parts.append(agent.instructions.strip())
    return "\n\n".join(parts)


def render_agents_context(*, node: Node | None = None) -> str:
    node = _local_node(node)
    node_feature_ids = _enabled_node_features(node)
    suite_feature_ids = _enabled_suite_features(node)
    role_name = getattr(getattr(node, "role", None), "name", "") or "unassigned"
    hostname = getattr(node, "hostname", "") or "unregistered"
    header = [
        "# Arthexis Local AGENTS",
        "",
        "This file is generated by the Arthexis suite for the local node.",
        "It supplements the repository-level developer AGENTS.md with node-role, "
        "suite-feature, and node-feature context.",
        "",
        f"- Node: {hostname}",
        f"- Node Role: {role_name}",
        "- Priority: node-role context overrides node-feature context, which "
        "overrides suite-feature and general context.",
    ]
    agents = list(
        _agent_queryset_for_node(node).prefetch_related(
            "node_roles",
            "node_features",
            "suite_features",
        )
    )
    tiered_agents = sorted(
        (
            (
                _agent_tier(
                    agent,
                    node,
                    node_feature_ids=node_feature_ids,
                    suite_feature_ids=suite_feature_ids,
                ),
                agent,
            )
            for agent in agents
        ),
        key=lambda item: (*item[0], item[1].priority, item[1].slug),
    )
    if not tiered_agents:
        return "\n".join(
            [
                *header,
                "",
                "No dynamic Agent context records are enabled for this node.",
                "",
            ]
        )

    sections: dict[str, list[str]] = {
        "Node Role": [],
        "Node Feature": [],
        "Suite Feature": [],
        "General": [],
    }
    for (_, tier), agent in tiered_agents:
        sections[tier].append(_render_agent_block(agent))

    lines = [*header, ""]
    for title, blocks in sections.items():
        if not blocks:
            continue
        lines.append(f"## {title} Context")
        lines.append("")
        lines.extend("\n\n".join(blocks).splitlines())
        lines.append("")
    return "\n".join(lines)


def write_agents_context(
    *,
    target: Path | str | None = None,
    node: Node | None = None,
) -> AgentContextRender:
    path = Path(target) if target is not None else default_agents_path()
    text = render_agents_context(node=node)
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    changed = existing != text
    if changed:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    return AgentContextRender(path=path, text=text, written=changed)
