# Generated by Django 5.2.8 on 2025-11-29 22:27

import core.entity
import core.fields
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentClassifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("label", models.CharField(max_length=150)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("IMAGE", "Image"),
                            ("AUDIO", "Audio"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "entrypoint",
                    models.CharField(
                        help_text="Dotted path to classifier callable", max_length=255
                    ),
                ),
                ("run_by_default", models.BooleanField(default=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Content Classifier",
                "verbose_name_plural": "Content Classifiers",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="ContentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("label", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Content Tag",
                "verbose_name_plural": "Content Tags",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("hostname", models.CharField(max_length=100)),
                ("network_hostname", models.CharField(blank=True, max_length=253)),
                ("ipv4_address", models.TextField(blank=True)),
                (
                    "ipv6_address",
                    models.CharField(
                        blank=True,
                        max_length=39,
                        validators=[django.core.validators.validate_ipv6_address],
                    ),
                ),
                (
                    "constellation_ip",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        validators=[django.core.validators.validate_ipv46_address],
                    ),
                ),
                ("constellation_device", models.CharField(blank=True, max_length=16)),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        validators=[django.core.validators.validate_ipv46_address],
                    ),
                ),
                ("mac_address", models.CharField(blank=True, max_length=17)),
                ("port", models.PositiveIntegerField(default=8888)),
                (
                    "trusted",
                    models.BooleanField(
                        default=False,
                        help_text="Mark the node as trusted for network interactions.",
                    ),
                ),
                (
                    "message_queue_length",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Maximum queued NetMessages to retain for this peer.",
                    ),
                ),
                ("badge_color", models.CharField(default="#28a745", max_length=7)),
                (
                    "current_relation",
                    models.CharField(
                        choices=[
                            ("UPSTREAM", "Upstream"),
                            ("DOWNSTREAM", "Downstream"),
                            ("PEER", "Peer"),
                            ("SELF", "Self"),
                        ],
                        default="PEER",
                        max_length=10,
                    ),
                ),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("public_endpoint", models.SlugField(blank=True, unique=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("public_key", models.TextField(blank=True)),
                ("base_path", models.CharField(blank=True, max_length=255)),
                ("installed_version", models.CharField(blank=True, max_length=20)),
                ("installed_revision", models.CharField(blank=True, max_length=40)),
            ],
            options={
                "verbose_name": "Node",
                "verbose_name_plural": "Nodes",
            },
        ),
        migrations.CreateModel(
            name="NodeFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("slug", models.SlugField(unique=True)),
                ("display", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Node Feature",
                "verbose_name_plural": "Node Features",
                "ordering": ["display"],
            },
        ),
        migrations.CreateModel(
            name="NodeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Key/value pairs exported to automation tools and sigils.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Node Profile",
                "verbose_name_plural": "Node Profiles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NodeRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Node Role",
                "verbose_name_plural": "Node Roles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.user",),
            managers=[
                ("objects", core.entity.EntityUserManager()),
                ("all_objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ContentSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "name",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("IMAGE", "Image"),
                            ("AUDIO", "Audio"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("path", models.CharField(blank=True, max_length=255)),
                ("method", models.CharField(blank=True, default="", max_length=10)),
                ("hash", models.CharField(blank=True, max_length=64)),
                (
                    "transaction_uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name="transaction UUID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nodes.node",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Sample",
                "verbose_name_plural": "Content Samples",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NodeFeatureAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_assignments",
                        to="nodes.nodefeature",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_assignments",
                        to="nodes.node",
                    ),
                ),
            ],
            options={
                "verbose_name": "Node Feature Assignment",
                "verbose_name_plural": "Node Feature Assignments",
            },
        ),
        migrations.AddField(
            model_name="node",
            name="features",
            field=models.ManyToManyField(
                blank=True,
                related_name="nodes",
                through="nodes.NodeFeatureAssignment",
                to="nodes.nodefeature",
            ),
        ),
        migrations.CreateModel(
            name="NodeManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "provider",
                    models.CharField(
                        choices=[("godaddy", "GoDaddy")],
                        default="godaddy",
                        max_length=20,
                    ),
                ),
                (
                    "api_key",
                    core.fields.SigilShortAutoField(
                        help_text="API key issued by the DNS provider.",
                        max_length=255,
                        verbose_name="API key",
                    ),
                ),
                (
                    "api_secret",
                    core.fields.SigilShortAutoField(
                        help_text="API secret issued by the DNS provider.",
                        max_length=255,
                        verbose_name="API secret",
                    ),
                ),
                (
                    "customer_id",
                    core.fields.SigilShortAutoField(
                        blank=True,
                        help_text="Optional GoDaddy customer identifier for the account.",
                        max_length=100,
                        verbose_name="Customer ID",
                    ),
                ),
                (
                    "default_domain",
                    core.fields.SigilShortAutoField(
                        blank=True,
                        help_text="Fallback domain when records omit one.",
                        max_length=253,
                    ),
                ),
                (
                    "use_sandbox",
                    models.BooleanField(
                        default=False,
                        help_text="Use the GoDaddy OTE (test) environment.",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Disable to prevent deployments with this manager.",
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.securitygroup",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Node Manager",
                "verbose_name_plural": "Node Managers",
            },
        ),
        migrations.CreateModel(
            name="DNSRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "provider",
                    models.CharField(
                        choices=[("godaddy", "GoDaddy")],
                        default="godaddy",
                        max_length=20,
                    ),
                ),
                (
                    "domain",
                    core.fields.SigilShortAutoField(
                        help_text="Base domain such as example.com.", max_length=253
                    ),
                ),
                (
                    "name",
                    core.fields.SigilShortAutoField(
                        help_text="Record host. Use @ for the zone apex.",
                        max_length=253,
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("AAAA", "AAAA"),
                            ("CNAME", "CNAME"),
                            ("MX", "MX"),
                            ("NS", "NS"),
                            ("SRV", "SRV"),
                            ("TXT", "TXT"),
                        ],
                        default="A",
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "data",
                    core.fields.SigilLongAutoField(
                        help_text="Record value such as an IP address or hostname."
                    ),
                ),
                (
                    "ttl",
                    models.PositiveIntegerField(
                        default=600, help_text="Time to live in seconds."
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Priority for MX and SRV records.",
                        null=True,
                    ),
                ),
                (
                    "port",
                    models.PositiveIntegerField(
                        blank=True, help_text="Port for SRV records.", null=True
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        blank=True, help_text="Weight for SRV records.", null=True
                    ),
                ),
                (
                    "service",
                    core.fields.SigilShortAutoField(
                        blank=True,
                        help_text="Service label for SRV records (for example _sip).",
                        max_length=50,
                    ),
                ),
                (
                    "protocol",
                    core.fields.SigilShortAutoField(
                        blank=True,
                        help_text="Protocol label for SRV records (for example _tcp).",
                        max_length=10,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                (
                    "node_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dns_records",
                        to="nodes.nodemanager",
                    ),
                ),
            ],
            options={
                "verbose_name": "DNS Record",
                "verbose_name_plural": "DNS Records",
            },
        ),
        migrations.AddField(
            model_name="node",
            name="profile",
            field=models.OneToOneField(
                blank=True,
                help_text="Optional profile providing metadata for automation tasks.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="node",
                to="nodes.nodeprofile",
            ),
        ),
        migrations.AddField(
            model_name="nodefeature",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="features", to="nodes.noderole"
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nodes.noderole",
            ),
        ),
        migrations.CreateModel(
            name="NetMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=64)),
                ("body", models.CharField(blank=True, max_length=256)),
                ("attachments", models.JSONField(blank=True, null=True)),
                (
                    "filter_current_relation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UPSTREAM", "Upstream"),
                            ("DOWNSTREAM", "Downstream"),
                            ("PEER", "Peer"),
                            ("SELF", "Self"),
                        ],
                        max_length=10,
                        verbose_name="Current relation",
                    ),
                ),
                (
                    "filter_installed_version",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Installed version"
                    ),
                ),
                (
                    "filter_installed_revision",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Installed revision"
                    ),
                ),
                (
                    "target_limit",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=6,
                        help_text="Maximum number of peers to contact when propagating.",
                        null=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("complete", models.BooleanField(default=False, editable=False)),
                (
                    "filter_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filtered_net_messages",
                        to="nodes.node",
                        verbose_name="Node",
                    ),
                ),
                (
                    "node_origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="originated_net_messages",
                        to="nodes.node",
                    ),
                ),
                (
                    "propagated_to",
                    models.ManyToManyField(
                        blank=True,
                        related_name="received_net_messages",
                        to="nodes.node",
                    ),
                ),
                (
                    "filter_node_feature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nodes.nodefeature",
                        verbose_name="Node feature",
                    ),
                ),
                (
                    "filter_node_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filtered_net_messages",
                        to="nodes.noderole",
                        verbose_name="Node role",
                    ),
                ),
                (
                    "reach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nodes.noderole",
                    ),
                ),
            ],
            options={
                "verbose_name": "Net Message",
                "verbose_name_plural": "Net Messages",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="NodeService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("slug", models.SlugField(unique=True)),
                ("display", models.CharField(max_length=100)),
                (
                    "unit_template",
                    models.CharField(
                        help_text="Pattern for the systemd unit name (for example {service_name}.service).",
                        max_length=150,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as required when the service should always be present.",
                    ),
                ),
                (
                    "template_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the service template stored in the repository.",
                        max_length=255,
                    ),
                ),
                (
                    "template_content",
                    models.TextField(
                        blank=True,
                        help_text="Stored copy of the service template for reference.",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        blank=True,
                        help_text="Limit this service to nodes with the selected feature.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nodes.nodefeature",
                    ),
                ),
            ],
            options={
                "verbose_name": "Node Service",
                "verbose_name_plural": "Node Services",
                "ordering": ["display"],
            },
        ),
        migrations.CreateModel(
            name="PendingNetMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seen", models.JSONField(default=list)),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("stale_at", models.DateTimeField()),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_deliveries",
                        to="nodes.netmessage",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_net_messages",
                        to="nodes.node",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pending Net Message",
                "verbose_name_plural": "Pending Net Messages",
                "ordering": ("queued_at",),
            },
        ),
        migrations.CreateModel(
            name="PublicWifiAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("mac_address", models.CharField(max_length=17)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("revoked_on", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_wifi_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wi-Fi Lease",
                "verbose_name_plural": "Wi-Fi Leases",
                "db_table": "core_publicwifiaccess",
            },
        ),
        migrations.CreateModel(
            name="BadgeCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "label_template",
                    models.CharField(
                        blank=True,
                        help_text="Optional label template that can reference {name}, {primary}, {secondary}, and {separator}. Badge counters are intended for values that do not change often; remember to invalidate the cache after updates.",
                        max_length=255,
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower values appear first from left to right.",
                    ),
                ),
                (
                    "separator",
                    models.CharField(
                        default="/",
                        help_text="Symbol shown between counters when two values are present.",
                        max_length=8,
                    ),
                ),
                (
                    "primary_source_type",
                    models.CharField(
                        choices=[
                            ("sigil", "Sigil string"),
                            ("callable", "Python callable"),
                        ],
                        default="sigil",
                        max_length=20,
                    ),
                ),
                (
                    "primary_source",
                    models.CharField(
                        help_text="Value source expressed as [sigils] or a dotted callable path. Badge counters are intended for values that do not change often and may require manual cache invalidation.",
                        max_length=255,
                    ),
                ),
                (
                    "secondary_source_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sigil", "Sigil string"),
                            ("callable", "Python callable"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("secondary_source", models.CharField(blank=True, max_length=255)),
                (
                    "css_class",
                    models.CharField(
                        default="badge-counter",
                        help_text="Additional CSS classes applied to the badge span.",
                        max_length=100,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badge_counters",
                        to="contenttypes.contenttype",
                        verbose_name="model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Badge Counter",
                "verbose_name_plural": "Badge Counters",
                "ordering": ("priority", "pk"),
                "unique_together": {("content_type", "name")},
            },
        ),
        migrations.CreateModel(
            name="ContentClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "classifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classifications",
                        to="nodes.contentclassifier",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classifications",
                        to="nodes.contentsample",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classifications",
                        to="nodes.contenttag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Classification",
                "verbose_name_plural": "Content Classifications",
                "ordering": ["-created_at"],
                "unique_together": {("sample", "classifier", "tag")},
            },
        ),
        migrations.AddConstraint(
            model_name="contentsample",
            constraint=models.UniqueConstraint(
                condition=models.Q(("hash", ""), _negated=True),
                fields=("hash",),
                name="nodes_contentsample_hash_unique",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="nodefeatureassignment",
            unique_together={("node", "feature")},
        ),
        migrations.AlterUniqueTogether(
            name="pendingnetmessage",
            unique_together={("node", "message")},
        ),
        migrations.AlterUniqueTogether(
            name="publicwifiaccess",
            unique_together={("user", "mac_address")},
        ),
    ]
