# Generated by Django 5.2.4 on 2025-09-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0002_contentsample_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="NodeFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("slug", models.SlugField(max_length=50, unique=True)),
                ("display", models.CharField(max_length=50)),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True, related_name="features", to="nodes.noderole"
                    ),
                ),
            ],
            options={
                "ordering": ["display"],
                "verbose_name": "Node Feature",
                "verbose_name_plural": "Node Features",
            },
        ),
        migrations.AddField(
            model_name="contentsample",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="emailoutbox",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="netmessage",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="node",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="noderole",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
