# Generated by Django 5.2.4 on 2025-09-13 04:04

from django.db import migrations, models


def add_emailoutbox_is_user_data(apps, schema_editor):
    EmailOutbox = apps.get_model("nodes", "EmailOutbox")
    table = EmailOutbox._meta.db_table
    column = "is_user_data"
    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            field.name
            for field in schema_editor.connection.introspection.get_table_description(
                cursor, table
            )
        }
    if column in existing_columns:
        return

    field = models.BooleanField(default=False, editable=False)
    field.set_attributes_from_name(column)
    schema_editor.add_field(EmailOutbox, field)


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0002_contentsample_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="NodeFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("slug", models.SlugField(max_length=50, unique=True)),
                ("display", models.CharField(max_length=50)),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True, related_name="features", to="nodes.noderole"
                    ),
                ),
            ],
            options={
                "ordering": ["display"],
                "verbose_name": "Node Feature",
                "verbose_name_plural": "Node Features",
            },
        ),
        migrations.AddField(
            model_name="contentsample",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="emailoutbox",
                    name="is_user_data",
                    field=models.BooleanField(default=False, editable=False),
                )
            ],
            database_operations=[
                migrations.RunPython(
                    add_emailoutbox_is_user_data, migrations.RunPython.noop
                )
            ],
        ),
        migrations.AddField(
            model_name="netmessage",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="node",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="noderole",
            name="is_user_data",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
