# Generated by Django 5.2.4 on 2025-08-10 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0002_clipboard_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="enable_public_api",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="node",
            name="public_endpoint",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name="NodeMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=10)),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("body", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="nodes.node",
                    ),
                ),
            ],
        ),
    ]
