# Generated by Django 5.2.4 on 2025-08-01 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0003_nginxconfig"),
        ("nodes", "0003_node_badge_color"),
    ]

    operations = []
