# Generated by Django 5.2.4 on 2025-08-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0005_rename_pattern_textpattern"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="enable_screenshot_polling",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="nodescreenshot",
            name="hash",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="nodescreenshot",
            name="method",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
