# Generated by Django 5.2.4 on 2025-09-21 03:27

from django.db import migrations, models


def set_existing_nodes_verified(apps, schema_editor):
    Node = apps.get_model("nodes", "Node")
    Node.objects.filter(last_seen__isnull=False).update(is_verified=True)


def reset_nodes_verified(apps, schema_editor):
    Node = apps.get_model("nodes", "Node")
    Node.objects.all().update(is_verified=False)


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0006_emailoutbox_group_emailoutbox_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="node",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(set_existing_nodes_verified, reset_nodes_verified),
    ]
