# Generated by Django 5.2.4 on 2025-09-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0006_emailoutbox_group_emailoutbox_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="netmessage",
            name="reach",
        ),
        migrations.AddField(
            model_name="node",
            name="popularity",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
