# Generated by Django 5.2.4 on 2025-09-22 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0006_emailoutbox_group_emailoutbox_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="netmessage",
            name="node_origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="originated_net_messages",
                to="nodes.node",
            ),
        ),
    ]
