# Generated by Django 5.2.4 on 2025-09-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0007_netmessage_node_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailoutbox",
            name="is_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Disable to remove this outbox from automatic selection.",
            ),
        ),
    ]
