# Generated by Django 5.2.4 on 2025-09-23 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_todo_url_normalize_loopback"),
        ("nodes", "0007_netmessage_node_origin"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfrastructureTodo",
            fields=[],
            options={
                "verbose_name": "TODO",
                "verbose_name_plural": "TODOs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.todo",),
        ),
    ]
