# Generated by Django 5.2.4 on 2025-08-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0008_systemdunit"),
    ]

    operations = [
        migrations.CreateModel(
            name="NMCLITemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("connection_name", models.CharField(max_length=100, unique=True)),
                ("assigned_device", models.CharField(blank=True, max_length=100)),
                ("priority", models.IntegerField(default=0)),
                ("autoconnect", models.BooleanField(default=True)),
                ("static_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("static_mask", models.CharField(blank=True, max_length=15)),
                ("static_gateway", models.GenericIPAddressField(blank=True, null=True)),
                ("allow_outbound", models.BooleanField(default=True)),
                ("security_type", models.CharField(blank=True, max_length=50)),
                ("ssid", models.CharField(blank=True, max_length=100)),
                ("password", models.CharField(blank=True, max_length=100)),
                ("band", models.CharField(blank=True, max_length=10)),
                (
                    "required_nodes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="required_nmcli_templates",
                        to="nodes.node",
                    ),
                ),
            ],
            options={
                "verbose_name": "NMCLI Template",
                "verbose_name_plural": "NMCLI Templates",
            },
        ),
    ]
