# Generated by Django 5.2.4 on 2025-08-13 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0009_nmclitemplate"),
        ("nodes", "0009_noderole_node_roles"),
    ]

    operations = []
