# Generated by Django 5.2.4 on 2025-09-24 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0009_node_current_relation"),
    ]

    operations = [
        migrations.AddField(
            model_name="netmessage",
            name="directionality",
            field=models.CharField(
                choices=[
                    ("BROADCAST", "Broadcast"),
                    ("UPSTREAM", "Upstream"),
                    ("DOWNSTREAM", "Downstream"),
                    ("PEERS", "Peers"),
                ],
                default="BROADCAST",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="netmessage",
            name="reach",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nodes.noderole",
            ),
        ),
    ]
