# Generated by Django 5.2.4 on 2025-09-25 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0010_nodemanager_dnsrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="netmessage",
            name="reach",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nodes.noderole",
            ),
        ),
    ]
