# Generated by Django 5.2.4 on 2025-08-14 18:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0010_merge_0009_nmclitemplate_0009_noderole_node_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="public_key",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="node",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
