# Generated by Django 5.2.4 on 2025-08-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0011_node_public_key_node_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="nmclitemplate",
            name="dns_servers",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="nmclitemplate",
            name="ipv6_address",
            field=models.GenericIPAddressField(blank=True, null=True, protocol="IPv6"),
        ),
        migrations.AddField(
            model_name="nmclitemplate",
            name="ipv6_dns_servers",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="nmclitemplate",
            name="ipv6_gateway",
            field=models.GenericIPAddressField(blank=True, null=True, protocol="IPv6"),
        ),
        migrations.AddField(
            model_name="nmclitemplate",
            name="ipv6_prefix",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
