# Generated by Django 5.2.4 on 2025-08-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0012_nmclitemplate_dns_servers_nmclitemplate_ipv6_address_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NginxConfig",
        ),
        migrations.RemoveField(
            model_name="nmclitemplate",
            name="required_nodes",
        ),
        migrations.DeleteModel(
            name="SystemdUnit",
        ),
        migrations.DeleteModel(
            name="NMCLITemplate",
        ),
    ]
