# Generated by Django 5.2.4 on 2025-08-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0013_delete_nginxconfig_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NodeCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
