# Generated by Django 5.2.4 on 2025-10-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0014_netmessage_filter_current_relation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="netmessage",
            name="payload",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="netmessage",
            name="payload_type",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Payload MIME type"
            ),
        ),
    ]
