# Generated by Django 5.2.4 on 2025-10-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0014_netmessage_filter_current_relation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="netmessage",
            name="target_limit",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=6,
                help_text="Maximum number of peers to contact when propagating.",
                null=True,
            ),
        ),
    ]
