# Generated by Django 5.2.4 on 2025-08-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0014_nodecommand"),
    ]

    operations = [
        migrations.CreateModel(
            name="Backup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Location or link to the backup file", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "size",
                    models.BigIntegerField(help_text="Size of the backup in bytes"),
                ),
                (
                    "report",
                    models.JSONField(
                        blank=True, default=dict, help_text="Report of exported objects"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
