# Generated by Django 5.2.4 on 2025-08-18 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0015_backup"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScreenSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("SCREEN", "Screen"), ("URL", "URL")], max_length=10
                    ),
                ),
                ("parameter", models.CharField(blank=True, max_length=200)),
                ("priority", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["priority", "id"],
            },
        ),
        migrations.AddField(
            model_name="nodescreenshot",
            name="origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nodes.screensource",
            ),
        ),
    ]
