# Generated by Django 5.2.4 on 2025-10-01 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0015_netmessage_payload_netmessage_payload_type"),
        ("nodes", "0015_netmessage_target_limit"),
    ]

    operations = []
