# Generated by Django 5.2.4 on 2025-08-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0016_screensource_nodescreenshot_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="base_path",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="node",
            name="installed_revision",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="node",
            name="installed_version",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
