# Generated by Django 5.2.4 on 2025-08-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0018_node_mac_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="backup",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="backup",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="node",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="node",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="nodecommand",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="nodecommand",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="nodemessage",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="nodemessage",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="noderole",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="noderole",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="nodescreenshot",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="nodescreenshot",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="screensource",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="screensource",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="step",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="step",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="textpattern",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="textpattern",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="textsample",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="textsample",
            name="is_seed_data",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
