# Generated by Django 5.2.4 on 2025-08-21 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0019_backup_is_deleted_backup_is_seed_data_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="roles",
        ),
        migrations.DeleteModel(
            name="NodeRole",
        ),
    ]
