# Generated by Django 5.2.7 on 2025-10-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0020_alter_nodemanager_api_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="netmessage",
            name="confirmed_peers",
        ),
    ]
