# Generated by Django 5.2.7 on 2025-10-28 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0023_rename_constellation_to_watchtower"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nodemanager",
            options={
                "verbose_name": "Node Profile",
                "verbose_name_plural": "Node Profiles",
            },
        ),
    ]
