# Generated by Django 5.2.7 on 2025-11-04 20:48

from django.db import migrations, models


def _update_ports(apps, schema_editor):
    Node = apps.get_model("nodes", "Node")
    Node.objects.filter(port=8000).update(port=8888)


def _restore_ports(apps, schema_editor):
    Node = apps.get_model("nodes", "Node")
    Node.objects.filter(port=8888).update(port=8000)


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0025_node_ipv4_address_node_ipv6_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="port",
            field=models.PositiveIntegerField(default=8888),
        ),
        migrations.RunPython(_update_ports, _restore_ports),
    ]
