# Generated by Django 5.2.7 on 2025-11-06 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0028_terminal_clipboard_poll_default"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="node",
            options={"verbose_name": "Node", "verbose_name_plural": "Nodes"},
        ),
        migrations.AlterModelOptions(
            name="pendingnetmessage",
            options={
                "ordering": ("queued_at",),
                "verbose_name": "Pending Net Message",
                "verbose_name_plural": "Pending Net Messages",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
