# Generated by Django 5.2.7 on 2025-11-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0029_alter_node_options_alter_pendingnetmessage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="constellation_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
