# Generated by Django 5.2.7 on 2025-11-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0030_node_constellation_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="constellation_device",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.UniqueConstraint(
                condition=models.Q(("constellation_device__isnull", False)),
                fields=("constellation_device",),
                name="nodes_node_constellation_device_unique",
            ),
        ),
    ]
