# Generated by Django 5.2.4 on 2025-11-13 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0037_alter_contentsample_hash_alter_node_address_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='node',
            name='nodes_node_mac_address_unique',
        ),
    ]
