# Generated by Django 5.2.8 on 2025-11-14 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0039_remove_node_nodes_node_constellation_device_unique"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="enable_public_api",
        ),
    ]
