# Generated by Django 5.2.4 on 2025-11-14 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0040_remove_node_enable_public_api"),
        ("nodes", "0040_resync_node_update_task"),
    ]

    operations = []
