# Generated by Django 5.2.8 on 2025-11-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0046_remove_clipboard_poll_feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="netmessage",
            name="target_limit",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=15,
                help_text="Minimum seconds this message should remain visible before receivers rotate to the next one.",
                null=True,
            ),
        ),
    ]
