# Generated by Django 5.2.8 on 2025-11-29 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0049_publicwifiaccess"),
    ]

    operations = [
        migrations.CreateModel(
            name="NodeService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("slug", models.SlugField(unique=True)),
                ("display", models.CharField(max_length=100)),
                (
                    "unit_template",
                    models.CharField(
                        help_text="Pattern for the systemd unit name (for example {service_name}.service).",
                        max_length=150,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as required when the service should always be present.",
                    ),
                ),
                (
                    "template_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the service template stored in the repository.",
                        max_length=255,
                    ),
                ),
                (
                    "template_content",
                    models.TextField(
                        blank=True,
                        help_text="Stored copy of the service template for reference.",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        blank=True,
                        help_text="Limit this service to nodes with the selected feature.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nodes.nodefeature",
                    ),
                ),
            ],
            options={
                "verbose_name": "Node Service",
                "verbose_name_plural": "Node Services",
                "ordering": ["display"],
            },
        ),
    ]
