# Generated by Django 5.2.12 on 2026-03-25 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortcuts", "0003_alter_shortcut_use_clipboard_patterns"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClipboardPattern",
        ),
        migrations.DeleteModel(
            name="Shortcut",
        ),
    ]
