# Generated by Django 5.2.4 on 2025-08-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="include_in_footer",
            field=models.BooleanField(default=False, verbose_name="Include in Footer"),
        ),
    ]
