# Generated by Django 5.2.8 on 2025-12-03 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailinbox",
            name="group",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="groups.securitygroup",
            ),
        ),
        migrations.AlterField(
            model_name="emailoutbox",
            name="group",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="groups.securitygroup",
            ),
        ),
    ]
