# Generated by Django 5.2.12 on 2026-05-01 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0003_initial"),
        ("odoo", "0004_odoosalefactor_odoosalefactorproductrule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailcollector",
            name="odoo_customer_address",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="emailcollector",
            name="odoo_customer_checked_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="emailcollector",
            name="odoo_customer_name",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name="emailcollector",
            name="odoo_customer_name_sigil",
            field=models.CharField(
                blank=True,
                default="customer_name",
                help_text="Parsed body sigil used as the Odoo customer lookup name.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="emailcollector",
            name="odoo_customer_phone",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="emailcollector",
            name="odoo_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional Odoo account used to validate customer fields.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="email_collectors",
                to="odoo.odooemployee",
            ),
        ),
    ]
