# Generated by Django 5.2.9 on 2026-01-06 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0004_alter_emailinbox_group_alter_emailinbox_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailBridge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional label for this inbox/outbox bridge.",
                        max_length=255,
                    ),
                ),
                (
                    "inbox",
                    models.OneToOneField(
                        help_text="Inbound mailbox for this bridge.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bridge",
                        to="emails.emailinbox",
                    ),
                ),
                (
                    "outbox",
                    models.OneToOneField(
                        help_text="Outbound mailbox for this bridge.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bridge",
                        to="emails.emailoutbox",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email bridge",
                "verbose_name_plural": "Email bridges",
                "db_table": "emails_emailbridge",
                "ordering": ["name", "pk"],
            },
        ),
    ]
