# Generated by Django 5.2.9 on 2026-01-06 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0005_emailbridge"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailbridge",
            options={
                "verbose_name": "Email Bridge",
                "verbose_name_plural": "Email Bridges",
                "db_table": "emails_emailbridge",
                "ordering": ["name", "pk"],
            },
        ),
    ]
