# Generated by Django 5.2.11 on 2026-03-07 00:00

from django.db import migrations, models


def migrate_recipe_mode_to_none(apps, schema_editor):
    """Convert legacy recipe mode values to none while preserving recipe linkage."""
    EmailCollector = apps.get_model("emails", "EmailCollector")
    EmailCollector.objects.filter(notification_mode="recipe").update(notification_mode="none")


def restore_none_mode_to_recipe(apps, schema_editor):
    """Restore recipe mode for records that still point at a recipe."""
    EmailCollector = apps.get_model("emails", "EmailCollector")
    EmailCollector.objects.filter(
        notification_mode="none",
        notification_recipe__isnull=False,
    ).update(notification_mode="recipe")


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0008_emailcollector_notification_recipe"),
    ]

    operations = [
        migrations.RunPython(migrate_recipe_mode_to_none, restore_none_mode_to_recipe),
        migrations.AlterField(
            model_name="emailcollector",
            name="notification_recipe",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional recipe to execute after the selected notification action.",
                null=True,
                on_delete=models.SET_NULL,
                related_name="email_collectors",
                to="recipes.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="emailcollector",
            name="notification_mode",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("net_message", "Net message"),
                    ("none", "Nothing"),
                    ("popup", "Local popup"),
                ],
                default="none",
                help_text="Action to run after collecting a new email artifact.",
                max_length=16,
            ),
        ),
    ]
