# Generated by Django 5.2.11 on 2026-03-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0009_emailcollector_notification_mode_remove_recipe_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailcollector",
            name="is_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Disable to exclude this collector from automatic runs and admin totals.",
            ),
        ),
    ]
