# Generated by Django 5.2.11 on 2026-03-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0009_emailcollector_notification_mode_remove_recipe_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailcollector",
            name="additional_inboxes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional additional inbox accounts monitored by this collector.",
                related_name="secondary_collectors",
                to="emails.emailinbox",
            ),
        ),
    ]
