# Generated by Django 5.2.12 on 2026-03-27 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaywrightBrowser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "engine",
                    models.CharField(
                        choices=[
                            ("chromium", "Chromium"),
                            ("firefox", "Firefox"),
                            ("webkit", "WebKit"),
                        ],
                        default="chromium",
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("headed", "Headed"), ("headless", "Headless")],
                        default="headed",
                        max_length=20,
                    ),
                ),
                (
                    "binary_path",
                    models.CharField(
                        blank=True,
                        help_text="Optional browser binary override.",
                        max_length=255,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Playwright Browser",
                "verbose_name_plural": "Playwright Browsers",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("is_default",),
                        name="playwright_browser_single_default",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SessionCookie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("cookies", models.JSONField(blank=True, default=list)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("stale", "Stale"),
                            ("rejected", "Rejected"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("last_validated_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_count", models.PositiveIntegerField(default=0)),
                ("last_rejection_reason", models.TextField(blank=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Security group that owns this object.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="groups.securitygroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session Cookie",
                "verbose_name_plural": "Session Cookies",
            },
        ),
    ]
