# Generated by Django 5.2.12 on 2026-03-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playwright", "0003_remove_playwrightscript"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WebsiteScreenshotRun",
        ),
        migrations.DeleteModel(
            name="WebsiteScreenshotSchedule",
        ),
    ]
