name: Coverage

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  tests:
    name: Run tests and upload coverage
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run pytest with coverage
        env:
          DJANGO_SETTINGS_MODULE: config.settings
        run: |
          pytest \
            --cov=app \
            --cov=awg \
            --cov=config \
            --cov=core \
            --cov=nodes \
            --cov=ocpp \
            --cov=pages \
            --cov=projects \
            --cov-report=xml \
            --cov-report=term-missing

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          flags: unittests
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
