# Generated by Django 5.2.12 on 2026-03-28 23:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aws", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeployInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Identifier for this Arthexis installation on the server.",
                        max_length=100,
                    ),
                ),
                (
                    "install_dir",
                    models.CharField(
                        help_text="Absolute directory where this instance is deployed.",
                        max_length=255,
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        help_text="System service name used to run this instance.",
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use lowercase letters, numbers, dots, underscores, or hyphens (2-64 chars).",
                                regex="^[a-z0-9][a-z0-9._-]{1,63}$",
                            )
                        ],
                    ),
                ),
                (
                    "env_file",
                    models.CharField(
                        blank=True,
                        help_text="Optional absolute path to an environment file.",
                        max_length=255,
                    ),
                ),
                ("branch", models.CharField(default="main", max_length=120)),
                (
                    "ocpp_port",
                    models.PositiveIntegerField(
                        default=9000,
                        help_text="WebSocket/OCPP port served by this instance.",
                    ),
                ),
                (
                    "admin_url",
                    models.CharField(
                        blank=True,
                        help_text="Optional URL used for post-deploy health checks.",
                        max_length=255,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Deployment instance",
                "verbose_name_plural": "Deployment instances",
                "ordering": ("server__name", "name"),
            },
        ),
        migrations.CreateModel(
            name="DeployRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("version", models.CharField(max_length=80, unique=True)),
                ("git_ref", models.CharField(max_length=160)),
                ("image", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Deployment release",
                "verbose_name_plural": "Deployment releases",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="DeployRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("deploy", "Deploy"),
                            ("migrate", "Migrate"),
                            ("restart", "Restart"),
                            ("rollback", "Rollback"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_by", models.CharField(blank=True, max_length=150)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("output", models.TextField(blank=True)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="deploy.deployinstance",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="deploy.deployrelease",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deployment run",
                "verbose_name_plural": "Deployment runs",
                "ordering": ("-requested_at",),
            },
        ),
        migrations.CreateModel(
            name="DeployServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_seed_data", models.BooleanField(default=False, editable=False)),
                ("is_user_data", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Human-friendly identifier used in deployment records.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("aws_lightsail", "AWS Lightsail"),
                            ("generic", "Generic"),
                        ],
                        default="aws_lightsail",
                        max_length=20,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="Cloud region for hosted servers.",
                        max_length=50,
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        help_text="Hostname or IP address used for remote commands.",
                        max_length=255,
                    ),
                ),
                ("ssh_port", models.PositiveIntegerField(default=22)),
                ("ssh_user", models.CharField(default="ubuntu", max_length=64)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "lightsail_instance",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to discovered Lightsail instance metadata.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deploy_servers",
                        to="aws.lightsailinstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deployment server",
                "verbose_name_plural": "Deployment servers",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="deployinstance",
            name="server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="deploy.deployserver",
            ),
        ),
        migrations.AddConstraint(
            model_name="deployinstance",
            constraint=models.UniqueConstraint(
                fields=("server", "name"), name="deploy_unique_instance_name_per_server"
            ),
        ),
        migrations.AddConstraint(
            model_name="deployinstance",
            constraint=models.UniqueConstraint(
                fields=("server", "install_dir"),
                name="deploy_unique_install_dir_per_server",
            ),
        ),
        migrations.AddConstraint(
            model_name="deployinstance",
            constraint=models.UniqueConstraint(
                fields=("server", "service_name"),
                name="deploy_unique_service_name_per_server",
            ),
        ),
    ]
